### ISSUE TITLE
More intuitive Applicative laws

### ISSUE THREAD

**Issue by alexfmpe** [haskell/core-libraries-committee#102]
# Motivation
https://wiki.haskell.org/Typeclassopedia#Alternative_formulation portrays `Applicative` as a pseudo-associative binary operation with a pseudo-identity, similar to `<>`/`mempty`, and requires 3 rather than 4 laws, which makes it much easier to reason about intuitively, prove lawfulness of instances, and explain to newcomers.

# Proposal
To replace the laws specified in `Control.Applicative` with a smaller and simpler set, and relegate the current ones to corollaries alongside their proofs.

One can derive the current laws from the following pseudo-associative and pseudo-identity laws.

```haskell
  fmap (\(u', (v', w')) -> u' (v' w')) (u ⊗ (v ⊗ w))
= fmap (\((u', v'), w') -> u' (v' w')) ((u ⊗ v) ⊗ w)

  fmap f u
= fmap (f . fst) (u ⊗ unit)
= fmap (f . snd) (unit ⊗ u) 
```

In fact, the first law alongside the free theorem is sufficient for `Apply`: https://github.com/ekmett/semigroupoids/issues/43#issuecomment-1282984149, since the binary operation concerns itself only with associativity and has no notion of `pure`/`unit`.
The following is written as an extension to the `semigroupoids` comment and pretends `Apply` is declared a superclass of `Applicative` to re-use results. 

```haskell
import Data.Tuple (swap)
import Prelude hiding (Applicative(..))

class Apply f => Applicative f where
  unit :: f ()

  pure :: a -> f a
  pure a = fmap (const a) unit

infixl 4 <*>
(<*>) :: Apply f => f (a -> b) -> f a -> f b
(<*>) = (<.>)

liftA2 :: Apply f => (a -> b -> c) -> f a -> f b -> f c
liftA2 = liftF2

-- Styled comment
infixl 0 ...
(...) :: a -> String -> a
(...) = const

-- Law
lawPseudoUnit :: Applicative f => (a -> b) -> f a -> f b
lawPseudoUnit f u =
      fmap f u
  === fmap (f . fst) (u ⊗ unit)
  === fmap (f . snd) (unit ⊗ u)


-- Helper
corollaryPure :: Applicative f => (a -> b) -> f a -> f b
corollaryPure f u =
      pure f <*> u
  === liftA2 ($) (pure f) u
  === fmap (uncurry ($)) (pure f ⊗ u)
  === fmap (uncurry ($)) (fmap (const f) unit ⊗ fmap id u)
  === fmap (uncurry ($)) (fmap (const f *** id) (unit ⊗ u))
  === fmap (uncurry ($) . (const f *** id)) (unit ⊗ u)
  === fmap (\((), u') -> f u') (unit ⊗ u)
  === fmap (f . snd) (unit ⊗ u)
  ... "pseudo unit"
  === fmap f u


-- Current Applicative laws

corollaryIdentity :: Applicative f => f a -> f a
corollaryIdentity v =
      pure id <*> v
  ... "corollaryPure"      
  === fmap id v
  === v

corollaryComposition :: Applicative f => f (b -> c) -> f (a -> b) -> f a -> f c
corollaryComposition u v w =
      pure (.) <*> u <*> v <*> w
  ... "corollaryPure"
  === (.) <$> u <*> v <*> w
  ... "corollary3 from Apply"
  === u <*> (v <*> w)

corollaryHomomorphism :: Applicative f => (a -> b) -> a -> f b
corollaryHomomorphism f x =
      pure f <*> pure x
  ... "corollaryPure"      
  === fmap f (pure x)
  === fmap f (fmap (const x) unit)
  === fmap (f . const x) unit
  === fmap (const (f x)) unit
  === pure (f x)

corollaryInterchange :: Applicative f => f (a -> b) -> a -> f b
corollaryInterchange u y =
      u <*> pure y
  === liftA2 ($) u (pure y)
  === fmap (uncurry ($)) (u ⊗ pure y)
  === fmap (uncurry ($)) (fmap id u ⊗ fmap (const y) unit)
  === fmap (uncurry ($)) (fmap (id *** const y) (u ⊗ unit))
  === fmap (uncurry ($) . (id *** const y)) (u ⊗ unit)
  === fmap (\(u', ()) -> u' y) (u ⊗ unit)
  === fmap (flip ($) y . fst) (u ⊗ unit)
  ... "pseudo unit"
  === fmap (flip ($) y . snd) (unit ⊗ u)
  === fmap (\((), u') -> u' y) (unit ⊗ u)
  === fmap (uncurry ($) . (const ($ y) *** id)) (unit ⊗ u)
  === fmap (uncurry ($)) (fmap (const ($ y) *** id) (unit ⊗ u))
  === fmap (uncurry ($)) (fmap (const ($ y)) unit ⊗ fmap id u)
  === fmap (uncurry ($)) (pure ($ y) ⊗ u)
  === liftA2 ($) (pure ($ y)) u
  === pure ($ y) <*> u
```
One might think the identity law could be made stronger by using `pure`, but they're equivalent
```haskell
corollarySwap :: Applicative f => (a -> b -> c) -> f a -> b -> f c
corollarySwap f u v =
      fmap (uncurry f) (u ⊗ pure v)
  === fmap (\(u', v') -> f u' v') (u ⊗ pure v)
  === fmap (\(u', v') -> f u' v') (fmap id u ⊗ fmap (const v) unit)
  === fmap (\(u', v') -> f u' v') (fmap (id *** const v) (u ⊗ unit))
  === fmap ((\(u', v') -> f u' v') . (id *** const v)) (u ⊗ unit)
  === fmap (\(u', ()) -> f u' v ) (u ⊗ unit)
  === fmap (flip f v . fst) (u ⊗ unit)
  ... "pseudo unit"
  === fmap (flip f v . snd) (unit ⊗ u)
  === fmap (\((), u') -> f u' v ) (unit ⊗ u)
  === fmap ((\(v', u') -> f u' v') . (const v *** id)) (unit ⊗ u)
  === fmap (\(v', u') -> f u' v') (fmap (const v *** id) (unit ⊗ u))
  === fmap (\(v', u') -> f u' v') (fmap (const v) unit ⊗ fmap id u)
  === fmap (\(v', u') -> f u' v') (pure v ⊗ u)
  === fmap (uncurry f . swap) (pure v ⊗ u)

**Comment by tomjaguarpaw** [comment]
I think neither the existing formulation nor the one proposed here are particularly simple.  The simplest formulation is one [discovered by
@duplode](https://duplode.github.io/posts/applicative-archery.html) in 2015, called "Compositional" below.

The benefit of the existing formulation is that it is presented in terms of `<*>`, which is actually used in practice.  Neither `⊗` nor `<.>` are used in practice.  The benefit of the compositional formulation is that it just a literal recasting of the monoid laws, which are incredibly simple.

I'm afraid I don't see the benefit of the proposed formulation. It neither corresponds to standard practice nor is particularly much simpler than the existing formulation.

### Candidates for the `Applicative` laws

#### Existing

* identity
  ```
  pure id <*> v = v
  ```
* composition
  ```
  pure (.) <*> u <*> v <*> w = u <*> (v <*> w)
  ```
* homomorphism
  ```
  pure f <*> pure x = pure (f x)
  ```
* interchange
  ```
  u <*> pure y = pure ($ y) <*> u
  ```
[I suspect homomorphism actually follows from the other three plus
parametricity.]

#### Proposed

* identity
  ```
    fmap f u
  = fmap (f . fst) (u ⊗ unit)
  = fmap (f . snd) (unit ⊗ u)
  ```
* associativity
  ```
    fmap (\(u', (v', w')) -> u' (v' w')) (u ⊗ (v ⊗ w))
  = fmap (\((u', v'), w') -> u' (v' w')) ((u ⊗ v) ⊗ w)
  ```
where `a ⊗ b = (,) <$> a <*> b`.

#### Compositional

* identity
  ```
  pure id <.> f = f
  f <.> pure id = f
  ```
* composition
  ```
  f <.> (g <.> h) = (f <.> g) <.> h
  ```
Apparently naturality, `pure f <.> pure g = pure (f . g)` follows
by parametricity.

**Comment by nomeata** [comment]
How natural would a formulation using `liftA2` be (which I tend to think of a very suitable basic definition for Applicative)?

**Comment by tomjaguarpaw** [comment]
The "compositional" formulation is a formulation using `liftA2`. `(<.>) = liftA2 (.)`. (I omitted that from my comment, originally, oops!).

**Comment by nomeata** [comment]
But it's not really important that it is `pure id` ans `liftA2 (.)`, right? It could be equivalently be started that for any monoid instead of `id` and `(.)`? (Or do I have to say Category to allow different types?) Maybe the more concrete formulation is easier … but presumably if I want to use these equations in proofs the more general form is more convenient?

**Comment by tomjaguarpaw** [comment]
I think stating it in terms of a monoid, i.e. `pure mempty` and `liftA2 (<>)` is not strong enough because, as you say, it gives no way to allow different types. Stating it in a category is strong enough. Given the polymorphism of `(.)` and `id` in their `Category` instance definitions, what I wrote translates directly! But there's no need to go all the way to `Category`. Just use the `(->)` instance, which seems to be sufficiently representative.

**Comment by alexfmpe** [comment]
Maybe a better way to put it would be with the associative law

```haskell 
-- also used in the Arrow laws, surprisingly not on Data.Tuple unlike swap
assoc :: ((a,b),c) -> (a,(b,c))
assoc ((a,b),c) = (a,(b,c))

u ⊗ (v ⊗ w) = assoc <$> ((u ⊗ v) ⊗ w)
```

from which we can derive the earlier one
```haskell
corollaryAssoc :: Apply f => f (b -> c) -> f (a -> b) -> f a -> f c
corollaryAssoc u v w =
      fmap (\(u', (v', w')) -> u' (v' w')) (u ⊗ (v ⊗ w))
  === fmap (\(u', (v', w')) -> u' (v' w')) (fmap assoc ((u ⊗ v) ⊗ w))
  === fmap ((\(u', (v', w')) -> u' (v' w')) . assoc) ((u ⊗ v) ⊗ w)
  === fmap (\((u', v'), w') -> u' (v' w')) ((u ⊗ v) ⊗ w)
```


> [I suspect homomorphism actually follows from the other three plus parametricity.]

I do think the current, errr... "Applicative"... formulation set of current ones can be reduced. After all, the other two formulations have 1 associativity constraint and 2 identity ones, so 4 sounds like one degree-of-freedom restriction too many and thus redundant.




> The simplest formulation is one discovered by @duplode in 2015, called "Compositional" below.

Very nice. I'm definitely in favor of putting that in a more discoverable place.

I'm slightly more leaning towards basing the laws on `⊗` because it's describing how the binary operation interacts with the superclasses' `fmap`. In that sense, it's an attempt at describing what `Apply`/`Applicative` brings to the table as when formulating `Monad` laws in terms of `fmap` / `join`.

Notice `⊗` factors both `liftA2` and `pure`
```haskell
  liftA2 f a b = fmap (uncurry f) (a ⊗ b)
  pure a = fmap (const a) unit
```
whereas `liftA2` _generalizes_ `⊗`
```haskell
  a ⊗ b = liftA2 (,)
```

That is, the Monoidal formulation is an incremental viewpoint while Compositional treats `Applicative` as a whole.

It seems plausible that the `liftA2 (.)` and `liftA2 (,)` formulations come out cleaner than the `liftA2 ($)` one because they lift symmetrical operations whereas `$` has its arguments take on different roles.

@tomjaguarpaw what about putting both Monoidal and Compositional formulations on the haddocks? Given they're different valid ways to think of Applicative, that seems like the place to document them.
As a matter of preference I'd argue for `⊗` as _the_ primitive operation to define in instances, but I think that ship has sailed so not pushing for that, just the laws.

**Comment by Bodigrim** [comment]
I think it's a good idea to put several formulations of laws in Haddocks, accompanied by proofs of their equivalence.

**Comment by alexfmpe** [comment]
> [I suspect homomorphism actually follows from the other three plus parametricity.]

Seems to be the case

```haskell
homomorphism :: Applicative f => (a -> b) -> a -> f b
homomorphism f x =
      pure f <*> pure x
  === fmap (const f) unit <*> fmap (const x) unit
  === liftA2 ($) (fmap (const f) unit) (fmap (const x) unit)
  === fmap (uncurry ($)) (fmap (const f) unit ⊗ fmap (const x) unit)
  === fmap (uncurry ($)) (fmap (const f *** const x) (unit ⊗ unit))
  === fmap (uncurry ($) . (const f *** const x)) (unit ⊗ unit)
  === fmap (\((), ()) -> const f () $ const x ()) (unit ⊗ unit)

  === fmap (\((), ()) -> f x) (unit ⊗ unit)

  === fmap (\((), ()) -> const id () $ const (f x) ()) (unit ⊗ unit)
  === fmap (uncurry ($) . (const id *** const (f x))) (unit ⊗ unit)
  === fmap (uncurry ($)) (fmap (const id *** const (f x)) (unit ⊗ unit))
  === fmap (uncurry ($)) (fmap (const id) unit ⊗ fmap (const (f x)) unit)
  === fmap (uncurry ($)) (pure id ⊗ pure (f x))
  === liftA2 ($) (pure id) (pure (f x))
  === pure id <*> pure (f x)
  === pure (f x)
```

**Comment by konsumlamm** [comment]
I honestly don't think that introducing a new operator just for the laws, that isn't actually used in practice, is very helpful for beginners. Neither are proofs that laws are equivalent very helpful for beginners (rather the opposite, I'd expect it to scare people off).

**Comment by Ericson2314** [comment]
Haddock expandables for the proofs *and* the alternative laws themselves I think makes this pretty low-risk: no user should be put off, just a bit more work for `base` maintainers.

**Comment by nomeata** [comment]
> I think it's a good idea to put several formulations of laws in Haddocks, accompanied by proofs of their equivalence.

Can we use `<details>` and `<summary>` in haddocks? Adding pages of equational reasoning, or many alternative laws, might not increase the approachability of our docs to people new to all this :-)

**Comment by Ericson2314** [comment]
@nomeata I think that is basically the same as the "haddock expandables" @alexfmpe brought up?

**Comment by Bodigrim** [comment]
I don't see a strong case to replace the existing laws for `Applicative`. They are enshrined in papers, educational materials and QuickCheck libraries (e. g., https://hackage.haskell.org/package/quickcheck-classes-0.6.5.0/docs/Test-QuickCheck-Classes.html#v:applicativeLaws). 

One can include a discussion of alternative laws into `Control.Applicative`, somewhere below. I believe such documentation change would not require a formal CLC vote. 

@alexfmpe would you like to insist on your original proposal to replace the laws, or are you happy to keep the formal specification unchanged?

**Comment by Bodigrim** [comment]
@alexfmpe just a gentle reminder about the question above.

**Comment by alexfmpe** [comment]
@Bodigrim Sorry for the delay, I didn't forget about this, but was unsure how to proceed for a good while. There's two concerns:

1. the existing formulation in Control.Applicative has a _ton_ of issues
   1. Hides the monoidal-ish/categorical structure that the other two formulations expose and thus have much simpler laws that re-use existing concepts
   1. Given the free theorem, has a [redundant law](https://github.com/haskell/core-libraries-committee/issues/102#issuecomment-1317050526) - that means redundant work to prove instances valid
   1. It's hard to reason about. Consider the non-obvious redundancy above, which would be absolutely visible in the associativity-with-identities formulations. Essentially we're combining the two identities and getting the identity, and we can reduce the law to this by pulling `fmap (const _)` out to turn the `pure`s into `unit`s. Being hard to reason about discourages understanding and encourages type-tetris.
   1. Relies on `pure` for every single law, meaning we can't share the associativity law with [`Data.Functor.Apply`](https://hackage.haskell.org/package/semigroupoids/docs/Data-Functor-Apply.html) which is morally the superclass, similarly to `Semigroup`/`Monoid`
1. the other (and IMO better) formulations are not well known

At the time I started this proposal, I wasn't aware of compositional nor  expecting people to push for keeping the current ones, so in my mind having the monoidal laws made front-piece solved both concerns - that is, they were the same problem.
Trying to solve (2) by keeping the current laws front piece and tucking everything else under an expandable has a problem: since the current laws are excessivelly hard to think about, people are likely to have zero desire to dig for 'more details' which is what an expandable suggests. The compositional laws add insight so I'd like them to be better known, not continue to be found only in dark corners.
It also occurred to me that this isn't Haskell specific: Applicative is used in other languages, so only having this info in Hackage (what's more, in a collapsed by default section) seems to unnecessarily limit the audience.

Instead I was thinking of writing a little blog post or what have you about the formulations (say, what viewpoint each one, their equivalence proofs), and doing a one-time posting to the usual forums. Then the haddocks could have a link to it (though maybe that'd be a separate proposal?) so that new people getting started would still have a way to run into that.
As for whether to insist on replacing the current enshrined ones (with which?), I don't currently have a strong opinion and was thinking of seeing community reaction to the post for feedback.

> I don't see a strong case to replace the existing laws for Applicative. They are enshrined in papers, educational materials and QuickCheck libraries

I don't see precedent as a strong reason except as a tiebreaker. Enshrining it in one place because it's enshrined in another place seems a bit like 'the rich get richer' to me. I'd like to also point out the monoidal formulation was introduced in the same original paper, just not front piece.

**Comment by Bodigrim** [comment]
> Then the haddocks could have a link to it (though maybe that'd be a separate proposal?) so that new people getting started would still have a way to run into that.

FWIW you don't need a CLC proposal to update haddocks as long as there are no material changes. Linking a blog post or discussing alternative laws in situ is fine.

> As for whether to insist on replacing the current enshrined ones (with which?), I don't currently have a strong opinion and was thinking of seeing community reaction to the post for feedback.

Sounds reasonable to me.

That said, we try to maintain the list of issues actionable. If you want to keep this discussion open, please go ahead with a blog post and come back with a proposal soon.

**Comment by Bodigrim** [comment]
@alexfmpe if there is no material progress within two weeks, I'll close this is abandoned / dormant.

**Comment by alexfmpe** [comment]
Sorry for the wait, it took _forever_ to prove everything and do the write-up.
I have a [draft version](https://github.com/alexfmpe/semantic-satiation/blob/draft/src/Posts/ApplicativeLaws.md) on the proofreading stage and expect to post 'for real' this weeked or so.

**Comment by Lysxia** [comment]
It seems this will be resolved by adding the alternative laws in the haddocks with no required CLC vote.

I think the haddocks on `Applicative` could use some freshening up. But I'm not convinced that there is really one set of laws that is less confusing than the others. It's quite subjective which one speaks to you. Since there are only three candidates, I don't think it hurts to include them all as a matter of curiosity.

It doesn't seem worth including the proofs of equivalence. A link could work. I view it really as more of a good exercise for the reader, at least for those who need the proof. By the way, [your post](https://github.com/alexfmpe/semantic-satiation/blob/main/src/Posts/001-applicative-laws.md) claims it "proves these sets of laws are all equivalent", but it only proves that the monoidal laws imply the others, not the converse.

> Given the free theorem, has a [redundant law](https://github.com/haskell/core-libraries-committee/issues/102#issuecomment-1317050526) - that means redundant work to prove instances valid

The case of the redundant law can explained by the fact that in the original paper, `Applicative` was not a subclass of `Functor`, making the paper more self-contained. Without `fmap`, you cannot express the law `pure x = fmap (const x) (pure ())` which lets you derive the homomorphism law from the others.

The "archery laws" look cute, but the combinators are not really practical. The monoidal laws do at least suggest a systematic way of proving equations by separating the "sequencing of effects" from the "combination of outputs", but it's not the only way to reach that insight, and then you can easily apply it to the current `Applicative` interface.

**Comment by alexfmpe** [comment]
> Since there are only three candidates, I don't think it hurts to include them all as a matter of curiosity.

4 actually, counting the `liftA2` one

> By the way, [your post](https://github.com/alexfmpe/semantic-satiation/blob/main/src/Posts/001-applicative-laws.md) claims it "proves these sets of laws are all equivalent", but it only proves that the monoidal laws imply the others, not the converse.

Pretty sure it proves converses (main delay came from me being stuck on one of them for couple weeks). They're labeled "fooCounterpositive" (could have sworn I had renamed to "converse" at some point, oh well). Technically one of the converses reduces to `<.>`, but that one had already been proven equivalent, so, y'know, transitivity.

> The case of the redundant law can explained by the fact that in the original paper, Applicative was not a subclass of Functor. You need fmap to express the law pure x = fmap (const x) (pure ()) which lets you derive the homomorphism law from the others.

Hmm true for this particular proof. Given the same paper provided a formulation with 3 laws, there might still be another way to reduce this one to. It's probably sufficient to just note on the haddocks that it's a leftover from when Functor wasn't a superclass.

> Furthermore, free theorems are a really advanced topic, even though it doesn't seem that way when you use them as a black box. 

Agreed. Heck, I read a couple tutorials on it, fixed some issues on the package and still treat them as a black box

**Comment by Bodigrim** [comment]
> As for whether to insist on replacing the current enshrined ones (with which?), I don't currently have a strong opinion and was thinking of seeing community reaction to the post for feedback.

@alexfmpe could you please come to a conclusion now?

**Comment by alexfmpe** [comment]
Yeah, I'm withdrawing the proposal and settling for a link in the haddocks once I incorporate a bit of feedback in the post.
