### ISSUE TITLE
Add unzips to Data.Traversable

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#109]
The proposed `Data.Functor.unzip` has a potential space leak. Consider the example of lists, and let

```haskell
xys :: [(Small, Large)]
xs :: [Small]
ys :: [Large]
(xs, ys) = D.F.unzip xys
```

The large structures in `ys` will be retained in memory until not only `xys` and `ys` but also `xs` become garbage.

Traversable containers support both eager and lazy versions of `unzip` that don't leak like this. They're both based on a function in `bifunctors` with an admittedly peculiar implementation.

```haskell
traverseBia
  :: (Traversable t, Biapplicative p)
  => (a -> p b c) -> t a -> p (t b) (t c)
```

For unzipping, `p` will be some variant of the pair type.

```haskell
newtype Lazy a b = Lazy { unLazy :: (a, b)}
instance Functor Lazy where
  fmap = second
instance Bifunctor Lazy where
  bimap f g ~(Lazy (a, b)) = Lazy (f a, g b)
instance Biapplicative Lazy where
  bipure x y = Lazy (x, y)
  biliftA2 f g ~(Lazy (x1, y1)) ~(Lazy (x2, y2)) =
    Lazy (f x1 x2, g y1 y2)

newtype Strict a b = Strict {unStrict :: (a, b)}
instance Functor Strict where
  fmap = second
instance Bifunctor Strict where
  bimap f g (Strict (a, b)) = Strict (f a, g b)
instance Biapplicative Strict where
  bipure x y = Strict (x, y)
  biliftA2 f g (Strict (x1, y1)) (Strict (x2, y2)) =
    Strict (f x1 x2, g y1 y2)
```

Now we can define

```haskell
unzipWith, unzipEagerWith
  :: Traversable t
  => (a -> (b, c)) -> t a -> (t b, t c)
unzipWith f = unLazy #. traverseBia (Lazy #. f)
unzipEagerWith f = unStrict #. traverseBia (Strict #. f)
```

Where

```haskell
(#.) :: Coercible y z => q y z -> (x -> y) -> x -> z
_ #. f = coerce f
```

----

I mentioned above that the implementation of `traverseBia` is a bit odd. That's the case because (to the best of my knowledge) there's no way to implement it in standard Haskell with the expected laziness properties (i.e., so it works with things like infinite cons lists and infinite snoc lists). The version in `bifunctors` uses a GADT. I don't know of a way to implement a lazy, non-leaky `unzipWith` without such machinery. An eager one can be written like this, but I expect it to be slow.

```haskell
unzipEagerSlowlyWith f (fmap f -> xys)
  | Solo xs <- traverse (\(x, _) -> Solo x) xys
  , Solo ys <- traverse (\(_, y) -> Solo y) xys
  = (xs, ys)
```

Is lacking a Report Haskell implementation a problem?

**Comment by Bodigrim** [comment]
> Is lacking a Report Haskell implementation a problem?

Not really.

----

I'm personally reluctant to bring `traverseBia` into `base`, unless we move entire `Biapplicative` there. Otherwise we'll end up with two non-trivial implementations, which someone'd have to support eternally. 

I think a simple haddock for `Data.Functor.unzip`, mentioning `traverseBia` in `bifunctors`, can give us almost all benefits with almost no hassle.

**Comment by treeowl** [comment]
What I'd really like is to have a `Traversable` method that somehow supports `Applicative`, `Biapplicative`, `Triapplicative`, etc., all at once. Unfortunately, I don't know that that would look like, and last I asked neither did @ekmett.

It's all part of a broader general issue, that `Traversable` structures all support a variety of operations that cannot be cleanly, simply, and efficiently implemented using the `Traversable` methods. Another example is

```haskell
holesIn :: Traversable t => t a -> t (a, a -> t a)
```

`holesIn xs` produces a container whose elements are pairs. The first component of each element is the corresponding element of `xs`, while the second is a function for replacing the element at that position with another. For example,

```haskell
holesIn [1,2,3] = [(1, \x -> [x,2,3]), (2, \x -> [1,x,3]), (3, \x -> [1,2,x])]
```

It's possible to implement this using `traverseBia` with a rather tricky `Biapplicative`, but that implementation can't share any structure between its argument and its results (and I don't think it can even guarantee adequate sharing among its results, though it seems to do fairly well). Ugh!

----

I think the documentation-only approach would be okay while we wait for someone really clever to come up with a more satisfactory general solution.
