### ISSUE TITLE
Improve mtimesDefault implementation

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#11]
The current implementation of `mtimesDefault` is based on `stimes` for `WrappedMonoid`, which has the default implementation. This is quite silly now that `Semigroup` is a superclass of `Monoid`! We should instead make it use the `stimes` implementation for the underlying monoid, whatever that may be. See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6872

**Comment by cigsender** [comment]
+1

**Comment by gwils** [comment]
+1

**Comment by chessai** [comment]
+1

**Comment by Bodigrim** [comment]
+1 

4 votes out of 6 are already a majority of CLC, but I would like to give @emilypi and @cgibbard an opportunity to vote until tomorrow.

**Comment by emilypi** [comment]
+1

**Comment by Bodigrim** [comment]
The proposal is approved, thanks all.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Author**             |  @treeowl   |
| **Status**             |  merged |
| **`base` version**     | `4.17.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6872 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | missing (please, [raise an MR to `base` to update changelog][changelog])  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
