### ISSUE TITLE
Add eager indexing for arrays

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#116]
The `IArray` class has a method

```haskell
 unsafeAt :: Ix i => a i e -> Int -> e
```

That's sometimes okay. Other times it's an effective way to produce memory leaks. I propose adding one of the following methods:

```haskell
  unsafeAtA :: (Ix i, Applicative f) => a i e -> Int -> f e
  unsafeAtSolo :: Ix i => a i e -> Int -> Solo e
```

Similarly, we have a function

```haskell
(!) :: (IArray a e, Ix i) => a i e -> i -> e
```

I propose to add one of the following functions:

```haskell
atA :: (IArray a e, Ix i, Applicative f) => a i e -> i -> f e
atSolo :: (IArray a e, Ix i, Applicative f) => a i e -> i -> Solo e
```

We only really need one of each pair, because either can define the other:

```haskell
atSolo = atA

atA arr i
  | Solo x <- atSolo arr i
  = pure x
```

**Comment by tomjaguarpaw** [comment]
Can you elaborate on how `unsafeAt` can produce memory leaks?

**Comment by treeowl** [comment]
Sure. The basic problem (which has been known for a long time) is that if you store `ary ! k` in a data structure (or function closure) without forcing it, then the data structure will end up containing a thunk which, *when forced*, will extract an element from the array. That thunk will keep the *entire array* alive until it's forced. Of course, it's often okay to just force the element, but sometimes it's really not.

Suppose you want to implement

```haskell
slice :: Int -> Int -> Array Int a -> Array Int a
```

which extracts an arbitrary portion of an array. This should take time $O(|r|)$, where $r$ is the result. I don't believe there is any way to achieve that performance using the public interface without risking the leak described above. `take` can be implemented efficiently using `foldr`, and `drop` can be implemented efficiently using (lazy!) `foldl`, but `slice` looks like a no-go.

**Comment by konsumlamm** [comment]
Isn't the standard solution for that returning an unboxed tuple? At least that's what `primitive` is doing: https://hackage.haskell.org/package/primitive-0.7.4.0/docs/Data-Primitive-Array.html#v:indexArray-35--35-. That has the advantage of having less overhead and the proposed functions could be implemented on top of it.

**Comment by treeowl** [comment]
> Isn't the standard solution for that returning an unboxed tuple? At least that's what `primitive` is doing: https://hackage.haskell.org/package/primitive-0.7.4.0/docs/Data-Primitive-Array.html#v:indexArray-35--35-. That has the advantage of having less overhead and the proposed functions could be implemented on top of it.

Yeah, that would probably be a bit better for the class method; good point. I don't think regular users need to see that though.

**Comment by treeowl** [comment]
There are some places where the unlifted tuples is used simply because `Solo` didn't exist in `base` yet.

**Comment by treeowl** [comment]
I hereby amend the proposal to make the class method

```haskell
  unsafeAt# :: Ix i => a i e -> Int -> (# e #)
```

This approximately matches the unexported function by that name in `GHC.Arr`, of type

```haskell
unsafeAt# :: Array i e -> Int -> (# e #)
```

**Comment by tomjaguarpaw** [comment]
Ah, I see. You want to release the reference to the underlying container but not force the element. This problem extends to all container types, not just arrays, doesn't it?

> Of course, it's often okay to just force the element, but sometimes it's really not.

Under what circumstances is it not?

> `take` can be implemented efficiently using` foldr`, and `drop` can be implemented efficiently using (lazy!) `foldl`, but `slice` looks like a no-go.

I don't understand this. Isn't it possible to implement `slice` as a combination of `take` and `drop`?

Your ` unsafeAt...` functions will need to be implemented in terms of the underlying data type.  How would you do that? Is there actually something in the array API that supports that functionality?

**Comment by treeowl** [comment]
@tomjaguarpaw Haskell is a lazy language with lazy arrays. We need to be able to index into them without breaking laziness. I don't have a very specific example in mind off the top of my head. The underlying primops support this, and both `vector` and `primitive` use it. It's not possible to implement `slice` efficiently by combining `take` and `drop`. Consider a small slice from the middle of a large array.

**Comment by tomjaguarpaw** [comment]
> Haskell is a lazy language with lazy arrays. We need to be able to index into them without breaking laziness. I don't have a very specific example in mind off the top of my head.

OK. I think I'll need to see a compelling example before I vote in favour. That's not to say I disbelieve in the existence of such an example, I would just like to see it. I think the proposal would be stronger if it came with a stronger motivation.

> The underlying primops support this, and both `vector` and `primitive` use it.

Ah interesting. Can you point to examples?

----

> It's not possible to implement `slice` efficiently by combining `take` and `drop`. Consider a small slice from the middle of a large array.

This is rather tangential, so feel free to ignore, but I'm afraid I'm considering it and I don't see the problem. If `take` and `drop` can be implemented efficiently then so can `slice`, as `slice n m = take n . drop m` (or similar, with adjusted indices).

**Comment by tomjaguarpaw** [comment]
> @tomjaguarpaw, your slice copies n+o−m elements

Oh OK, fair enough.

**Comment by Bodigrim** [comment]
Closing as out-of-scope. 
CC @hellwolf @July541 @CarstenKoenig as new maintainers of `array`.
