### ISSUE TITLE
Add Foldable1 Solo instance

### ISSUE THREAD

**Issue by phadej** [haskell/core-libraries-committee#120]
It was probably left out as Foldable1 proposal is older than Solo addition to base.

MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9782

**Comment by treeowl** [comment]
Yes, definitely.

**Comment by phadej** [comment]
@Bodigrim I would like to trigger a committee vote. This addition is trivial and uncontroversial. And getting it in (into GHC-9.6) will save some compatibility head aches.

**Comment by mixphix** [comment]
+1

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add `instance Foldable1 Solo`. It's indeed an earlier oversight caused by `Foldable1` proposal lingering too long. 

@tomjaguarpaw @chessai @cgibbard @emilypi 

----

+1 from me.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by chessai** [comment]
+1

**Comment by cgibbard** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks, 5 votes out of 6 are anough to approve.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @phadej   |
| **Status**             |  merged |
| **`base` version**     | `4.17.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9782 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | not needed |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂  

<hr>

Comments: this change doesn't require a changelog entry. It was originally implemented for `base-4.19` but it was backported to `base-4.18` where the `Foldable1` typeclass made it first appearance.
