### ISSUE TITLE
Add Data instance to System.Exit.ExitCode

### ISSUE THREAD

**Issue by yaitskov** [haskell/core-libraries-committee#121]
It might be extended to other built in types.

In my case I had a function returning Either (NonEmpty (Foo, Maybe Bar), a) i.e. ExitCode is buried very deep.

I wanted quickly tweak the value to make error message compatible with GHC8 and 9 through a trick biplate %~ (replace "x" "y") but user defined type Bar couldn't derive Data because it contains ExitCode without Data.

https://gitlab.haskell.org/ghc/ghc/-/issues/22791

**Comment by treeowl** [comment]
Yeah, this should be added. For your application, you might consider trying `Control.Lens.Plated`.

**Comment by Bodigrim** [comment]
I think it is generally uncontroversial to add `instance Data` to any type without internal invariants. That said, we need a specific list of instances to discuss, we cannot approve a _carte blance_.

**Comment by treeowl** [comment]
@Bodigrim I disagree. I believe any type with a "publicly" exposed constructor and/or a `Generic` instance should be pre-approved for a `Data` instance.

**Comment by chessai** [comment]
> @Bodigrim I disagree. I believe any type with a "publicly" exposed constructor and/or a `Generic` instance should be pre-approved for a `Data` instance.

I agree with this.

**Comment by Bodigrim** [comment]
> I believe any type with a "publicly" exposed constructor and/or a Generic instance should be pre-approved for a Data instance.

The devil is in the details of the aptly quoted "publicly". It's not like we are flooded by this sort of proposals, so I don't see reasons to carve an ad-hoc rule right now.

@yaitskov you are very welcome to raise a specific GHC MR for CLC to vote on.

**Comment by treeowl** [comment]
@Bodigrim , `Generic` and `Data` instances are *always* public. The `System.` hierarchy is also public unless otherwise specified.

**Comment by Bodigrim** [comment]
@yaitskov if there is no progress on this proposal within two weeks, I'll close it as abandoned.

**Comment by Bodigrim** [comment]
Closing as abandoned.
