### ISSUE TITLE
Consider a new ThreadId definition

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#125]
`GHC.Conc.Sync` says

```haskell
data ThreadId = ThreadId ThreadId#
-- ToDo: data ThreadId = ThreadId (Weak ThreadId#)
-- But since ThreadId# is unlifted, the Weak type must use open
-- type variables.
{- ^
A 'ThreadId' is an abstract type representing a handle to a thread.
'ThreadId' is an instance of 'Eq', 'Ord' and 'Show', where
the 'Ord' instance implements an arbitrary total ordering over
'ThreadId's. The 'Show' instance lets you convert an arbitrary-valued
'ThreadId' to string form; showing a 'ThreadId' value is occasionally
useful when debugging or diagnosing the behaviour of a concurrent
program.

/Note/: in GHC, if you have a 'ThreadId', you essentially have
a pointer to the thread itself.  This means the thread itself can\'t be
garbage collected until you drop the 'ThreadId'.
This misfeature will hopefully be corrected at a later date.

-}
```

Guess what? We can now have weak pointers to unlifted things. Do we want to use them? I believe that to maintain the `Ord` instance, the `Show` instance, and whatever we end up calling the conversion to `Word64`, we'll need this representation:

```haskell
data ThreadId = ThreadId
  { the_id_number :: !Word64
  , the_thread :: Weak# ThreadId#
  }
```

The plus side: holding a `ThreadId` will no longer keep a thread alive. The minus side: weak pointer garbage collection is kind of pricy, which I imagine might possibly be an issue if there are many threads.

If the CLC decides *not* to make this change, then the documentation and comments should be adjusted.

**Comment by treeowl** [comment]
Another potential issue: we'll have to make sure that thread ID numbers are never reused. Otherwise, `ThreadID`s comparing equal could refer to different threads.

**Comment by treeowl** [comment]
Actually, I guess it would be possible to compare the `Weak#`s rather than the `Word64`s to implement `Eq`, but a compatible `Ord` is another story.

**Comment by treeowl** [comment]
Another option: remove the `Eq` and `Ord` instances, and explicitly document that thread ID numbers are not guaranteed to be unique.

**Comment by TeofilC** [comment]
I would love to see this change. The fact that `ThreadId`s keep threads alive is such a footgun IMO.

I think removing `Eq` and/or `Ord` would be a pretty big breaking change. I for one definitely make use of that instance to store `ThreadId`s in a `Set`/`Map`. I wouldn't be surprised if that is relatively common.

**Comment by TeofilC** [comment]
It looks like the thread id numbers are never reused. There is a global counter that is incremented each time a new thread is made. See: https://gitlab.haskell.org/ghc/ghc/-/blob/master/rts/Threads.c#L129

**Comment by treeowl** [comment]
@TeofilC, that's good. I still think it's important to recognize that making this change commits to that global approach.

**Comment by treeowl** [comment]
@TeofilC Would you like to take on the role of champion for this proposal? I don't use enough concurrency to have an opinion about whether the footgun removal is worth the weak pointer GC cost.

A conservative alternative would be to leave `ThreadID` alone (for situations where the current arrangement works well) and add a `WeakThreadId` for the rest. That seems like a bit of a confusing soup for users, but I think most people just use `async` or something anyway.

**Comment by TeofilC** [comment]
Sure. I'll try to benchmark the costs of this change. That should clear up some of the trade-offs. Though I can't guarantee how soon I'll have time to get around to it. Hopefully at some point in the next couple of weeks

**Comment by TeofilC** [comment]
I think a bit of a spanner in the works is the thread introspection API added in base-4.18. I think that gives a good example of an instance where we want to retain dead threads.

For instance `threadStatus` distinguishes between `ThreadFinished` and `ThreadDied`. But, you wouldn't be able to have that if the thread gets gc'd.

**Comment by treeowl** [comment]
@TeofilC Where exactly do we run into trouble due to dead threads being retained? I can't seem to find the documentation on that.

A slightly hacky workaround:

```haskell
data ThreadId = ThreadId
  { the_id_number :: !Word64
  , the_thread :: Weak# ThreadId#
  , final_status :: !(MVar ThreadStatus)
  }

grabIDNum :: ThreadId# -> IO Word64

-- Get the thread status from the ThreadId# itself
grabThreadStatus :: ThreadId# -> IO ThreadStatus
grabThreadStatus tid# = case threadStatus# tid# s2 of
                    (# s3, stat, _cap, _locked #) -> (# s3, mk_stat (I# stat) #)
  where
    mk_stat 0 = ThreadRunning
    mk_stat 1 = ThreadBlocked OnMVar
    ....

mkThreadId :: ThreadId# -> IO ThreadId
mkThreadId tid# = do
  the_id_number <- grabIDNum tid#
  final_status <- newEmptyMVar
  the_thread <- IO $ \s1 -> case mkWeak# tid# tid# (unIO (grabThreadStatus tid# >>= putMVar final_status)) s1 of
                             (# s2, wk# #) -> (# s2, Weak wk#)
  pure ThreadId{..}

threadStatus :: ThreadId -> IO ThreadStatus
threadStatus ThreadId {the_thread, final_status} = IO $ \s1 ->
  case deRefWeak# the_thread s1 of
    (# s2, flag, tid# #) ->
      case flag of
        -- The ThreadId# has died; once its finalizer runs, `final_status` will be filled.
        0# -> unIO (readMVar final_status) s2
        -- t
        _ -> grabThreadStatus tid#
```

When the `ThreadId#` becomes unreachable (except from the finalizer), the finalizer will run, retrieving and storing the final status. Well, hopefully. GHC explicitly doesn't guarantee that finalizers are ever run.

A cleaner approach would probably be for `fork#` and `forkOn#` (well, new primops similar to those) to take the `MVar#` to report the final thread status.

**Comment by TeofilC** [comment]
As I understand it there are two issues with `ThreadId` retaining threads:
 1. the extra space taken up by TSO, which would otherwise be gc'd.
 2. I think `ThreadId` can prevent errors like `BlockedIndefinitelyOnMVar` from triggering (though this would be good to double check).

I now think that maybe it's better to keep `ThreadId` as it is and make a new `WeakThreadId` type and encourage its use, eg, in `async`. I feel like trying to retrofit `ThreadId` adds too much complexity.

**Comment by treeowl** [comment]
That sounds reasonable. Should we start by trying to add `WeakThreadId` to `async`? Should I close the CLC request and open a GHC MR to change the documentation?

**Comment by TeofilC** [comment]
That sounds like a good plan to me. Though of course don't let me dissuade you from pursuing this!

**Comment by TeofilC** [comment]
Here's an example where `ThreadId` causes an exception not to throw:
```
import Control.Concurrent
import Control.Concurrent.MVar
import System.Mem
import Control.Exception

printError k = k `onException` print "killed"

main = do
  mvar1 <- newEmptyMVar
  mvar2 <- newEmptyMVar
  tid1 <- forkIO $ printError $ do
    readMVar mvar1
    putMVar mvar2 ()
  tid2 <- forkIO $ printError $ do
    readMVar mvar2
    putMVar mvar1 ()
  threadDelay 1000
  performMajorGC
  print [tid1, tid2]
```
If we remove the last line, we get `killed` but don't if we keep it.

**Comment by treeowl** [comment]
I've opened [a ticket for `async`](https://github.com/simonmar/async/issues/141).

**Comment by treeowl** [comment]
And now I've [opened a GHC MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10067) for the comment and documentation. I'll close this ticket for now.
