### ISSUE TITLE
Add mechanism for handling of WeakPtr finalizer exceptions

### ISSUE THREAD

**Issue by sheaf** [haskell/core-libraries-committee#126]
[GHC MR !8142](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8142) added a customisable mechanism for the handling of exceptions raised during finalization of weak pointers, which also affects Handle finalization.

However, [GHC issue #21680](https://gitlab.haskell.org/ghc/ghc/-/issues/21680) pointed out that it might be undesirable to enable the reporting of these exceptions by default, as it can cause unexpected output when piping data in the command line. So the plan for the 9.6 release of GHC is that the reporting of exceptions raised during finalization of weak pointers is off by default. However, we would like to provide a mechanism for it to be enabled by calling `setFinalizerExceptionHandler printToStderrFinalizerExceptionHandler`. The question is: where should these functions be exported from?

**Proposal:** add `setFinalizerExceptionHandler`, `setFinalizerExceptionHandler` and `printToHandleFinalizerExceptionHandler` to the export list of `System.Mem.Weak`. The first two are the main mechanism through which the user can modify the exception handling mechanism; the function `printToHandleFinalizerExceptionHandler` is merely a convenience for the user.
(**NB:** the original proposal suggested to add `printToStderrFinalizerExceptionHandler`, but it seems to be a better design to allow the user to choose the handle.)

See [GHC MR !9871](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9871) for a concrete implementation.

**Comment by sheaf** [comment]
@Bodigrim I know that the CLC is on pause currently, but I'm hoping it might be possible to get a swift resolution on this issue, as I don't see any scope for breakage. I apologise for bringing up this issue so late in the 9.6 release process, we only realised recently it was going to be important for the 9.6 release.

**Comment by bgamari** [comment]
> Why the !8142 cannot wait for GHC-9.8, can it be postponed?

!8142 was needed to address testsuite instability (specifically, we had suspected that some flaky tests were due to issues in finalizer-driven handle flushing). From the last few months of CI results, I think it's fair to say that we have falsified that hypothesis.

**Comment by sheaf** [comment]
Ben pointed out to me that it doesn't make much sense to export `printToStderrFinalizerExceptionHandler` from `GHC.TopHandler` while simultaneously arguing that `GHC.TopHandler` is an internal module. I will rewrite the proposal to address this issue.

**Comment by Bodigrim** [comment]
> **Proposal:** add `setFinalizerExceptionHandler`, `setFinalizerExceptionHandler` and `printToStderrFinalizerExceptionHandle` to the export list of `System.Mem.Weak`. See [GHC MR !9871](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9871) for details about the implementation of these functions; it's as it says on the tin really.

@sheaf I'm a bit at loss here: [GHC MR !9871](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9871) does not seem to touch `System.Mem.Weak` at all.

Is it insufficient to export these functions from [`GHC.Weak.Finalize`](https://ghc.gitlab.haskell.org/ghc/doc/libraries/base-4.18.0.0/GHC-Weak-Finalize.html)?

**Comment by sheaf** [comment]
The proposal is to export these functions from `System.Mem.Weak`, as that would be a non-internal module we can tell users to import. Currently the MR does not export `printToStderrFinalizerExceptionHandle` so as to avoid changing the export list of any module from `base`.

**Comment by Bodigrim** [comment]
I'm out of my depth here. TBH this is the first time I learned about weak pointers, so sorry for being stupid. I imagine that throwing exceptions is quite a big deal. Why are we hiding them by default? Are they usually irrelevant / harmless for some reason?

**Comment by Bodigrim** [comment]
How likely are users to set handlers to anything else than `printToStderrFinalizerExceptionHandle`?

**Comment by treeowl** [comment]
> I imagine that throwing exceptions is quite a big deal. Why are we hiding them by default? Are they usually irrelevant / harmless for some reason?

I can't say why this choice was made, but changing the default would potentially be a breaking change. Perhaps the most obvious default would be to throw an asynchronous exception to the main thread. But if the exception arises cleaning up a child thread that has died, I imagine that's not an obvious choice.

**Comment by sheaf** [comment]
> I imagine that throwing exceptions is quite a big deal. Why are we hiding them by default? Are they usually irrelevant / harmless for some reason?

Good questions! It can be quite bad to silently ignore them, I agree. In practice, users will usually encounter this behaviour when working with Handles, e.g. a Handle getting flushed and closed after getting GCed. Flushing might fail, and not reporting any error in that situation will lead to silent data loss. This is why we were initially going to report the errors by default (but not rethrow them, as that seems to be a step too far for a change in default behaviour).

However, a lot of the errors one gets are benign and often encountered when piping data in/out of Haskell programs. For example, `grep -q` closes `stdin` as soon as it finds a match, so piping into it can lead to errors of the form `<stdout>: hFlush: resource vanished (Broken pipe)`. Similar behaviour can arise for users of popular programs like `pandoc`, so it seemed more prudent to keep the behaviour as-is for now, at least until we can come up with a better migration story.

> How likely are users to set handlers to anything else than `printToStderrFinalizerExceptionHandle`?

I think there are three options users might be interested in: no handler, report the exception but don't rethrow it, and rethrow the exception.

**Comment by bgamari** [comment]
To expand on @sheaf's comment a bit...

Indeed ignoring exceptions on can be quite very bad, resulting in resource leakage or silent data loss:

 * An application with strict data consistency needs (e.g. a database backend) may rely on weak pointer finalization to flush and close its backing store file. However, with today's semantics, if the flush fails (e.g. due to file permissions, full disk, or other IO error) the program will currently nevertheless exit successfully despite having lost the user's data.
 * An application creating and destroying (via weak pointer finalization) external resources (e.g. foreign memory buffers or EC2 instances) may silently leak resources if finalization fails
 
> How likely are users to set handlers to anything else than `printToStderrFinalizerExceptionHandle`?

That very much depends upon the context. I can think of several plausible behaviors:

 * The user might choose to log the event with their own logging framework
 * They may choose to abort program execution 
 * They may choose to ignore the exception
 * They may choose to do some combination of the above, depending upon the exception type
 

> Why are we hiding them by default? Are they usually irrelevant / harmless for some reason?

We are hiding them for historical reasons. However, we are in good company; see this [blog post](https://blog.sunfishcode.online/bugs-in-hello-world/) for a characterisation of the issue and its applicability.

I am generally sympathetic to the need to change the current behavior. However, as @treeowl says, this change is breaking for users and therefore we believe that we need to consult with users (likely via the CLC) before doing so.

**Comment by Bodigrim** [comment]
Thanks for explanations, @shead and @bgamari. 

> **Proposal:** add `setFinalizerExceptionHandler`, `setFinalizerExceptionHandler` and `printToStderrFinalizerExceptionHandle` to the export list of `System.Mem.Weak`.

Could you please make a separate MR (potentially targeting non-`master` branch, if it's easier) which does exactly this?

**Comment by Bodigrim** [comment]
@sheaf unless there is an MR to vote on, I'll close this in two weeks as abandoned.

**Comment by bgamari** [comment]
I have opened [GHC!10175](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10175) implementing this.

**Comment by Bodigrim** [comment]
Labeling as awaiting MR again, until the proposer and the implementor decide on [`printToStderrFinalizerExceptionHandler`](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10175#note_488706).

**Comment by bgamari** [comment]
The MR has been brought up to date with the current state of the proposal.

**Comment by sheaf** [comment]
I've updated the proposal to change `printToStderrFinalizerExceptionHandler` to `printToHandleFinalizerExceptionHandler`. This is merely a convenience function that facilitates setting the weak pointer exception handling mechanism, but it seems like a better design to allow the `Handle` to be chosen by the user.

**Comment by bgamari** [comment]
To be clear, @sheaf's above change stemmed from a request by me. Not only is it a more general interface, but it is a bit easier to implement as it incurs fewer import cycles within `base`.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add `setFinalizerExceptionHandler`, `setFinalizerExceptionHandler` and `printToStderrFinalizerExceptionHandler` to the export list of `System.Mem.Weak` (and `GHC.Weak`). Full patch is available in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10175.

The detailed motivation can be found in https://github.com/haskell/core-libraries-committee/issues/126#issuecomment-1427666999 and https://github.com/haskell/core-libraries-committee/issues/126#issuecomment-1431972431. 

The change is not breaking and allows users to customize the behaviour of `WeakPtr` finalizer exceptions, which is a practically important concern.

@tomjaguarpaw @chshersh @hasufell @mixphix @angerman @parsonsmatt 

----

+1 from me.

**Comment by mixphix** [comment]
I’m glad to hear that you’ve opted to reduce import cycles with the minor change to the function from the original proposal. +1 from me!

**Comment by Bodigrim** [comment]
@tomjaguarpaw @chshersh @hasufell @angerman @parsonsmatt just a gentle reminder to vote.

**Comment by chshersh** [comment]
+1

<hr>

This is not my area of expertise, so I'm truly thankful for @Bodigrim summaries! 🙏🏻 
Additive change in a place I never touched in my Haskell career that also adds some customization to users sounds good to me 🆗

**Comment by hasufell** [comment]
+1

**Comment by tomjaguarpaw** [comment]
-1

----

It's not clear to me that this interface is yet sufficiently stable to warrant export from a non-`GHC.` module.

**Comment by bgamari** [comment]
For what it is worth, I am sympathetic to @tomjaguarpaw's concern here. Exceptions during finalization are something that IIRC the original paper does not address and another Haskell implementations may choose a different design. I think it would be quite reasonable for this to be only exported from `GHC.Weak` (and, in fact, this was the original plan when I added these operations).

**Comment by Bodigrim** [comment]
@bgamari I'm confused. I've been asking you to prepare an MR since February, there've been plenty of time to ponder it. And yet now, no sooner the votes have been cast, you yourself are doubtful about the choice of exports.

Could you please make it clear whether you want to pursue the design in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10175 (in which case the proposal is approved, there are 4 votes in favour) or not (in which case the proposal is withdrawn)?

**Comment by bgamari** [comment]
> And yet now, no sooner the votes have been cast, yourself are doubtful about the choice of exports.

Design decisions in library design are rarely clear-cut. Historically, my view has been similar to that of @tomjaguarpaw: the Haskell Report namespaces are for stable, implementation-agnostic interfaces while `GHC.*` is for compiler-specific, often unstable interfaces. However, with #105 this view has slightly changed as we are now committing to greater stability in the `GHC.*` namespace.

Does this mean that we should also relax the requirement that `System.Mem.Weak` should not contain GHC-specific interfaces? Doing so would give the interfaces greater visibility. On the other hand, it may muddy the waters in the event that a non-GHC Haskell implementation comes along in the future. Is this worthwhile? @sheaf, who wrote the  original proposal text thought so. Personally, I don't know; it's a value judgement. However, I am happy that we have the body you chair, a committee of library design experts, who can opine on such matters.

My earlier comment was merely affirming that I think @tomjaguarpaw raises a useful point; one that, in hindsight, perhaps I should have asked @sheaf to address in the proposal. I am happy to change the proposal and amend the implementation if the CLC agrees. If not, I am satisfied with the proposal as-is.

In general, I think that it would be appropriate and useful for the CLC to offer feedback beyond "yes, we approve" or "no, we reject". I hope the body will view itself as a partner in library design and empower itself to make concrete suggestions to improve proposals; afterall, submitted proposals are mere starting points for iteration and library design is nothing if not subjective.

**Comment by Bodigrim** [comment]
> In general, I think that it would be appropriate and useful for the CLC to offer feedback beyond "yes, we approve" or "no, we reject".

CLC does offer (non-binding) feedback to willing and proactive contributors. There've been plenty of opportunities to discuss and refine the design in the course of three months I've been asking you to finalize the MR.

It is undesirable to disrupt a vote by offering concessions once someone disagrees. CLC approves specific API, changing it means that all votes must be cast anew. We are unpaid volunteers, please be mindful of our time.

> Could you please make it clear whether you want to pursue the design in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10175 (in which case the proposal is approved, there are 4 votes in favour) or not (in which case the proposal is withdrawn)?

@bgamari yes or no?

**Comment by bgamari** [comment]
@Bodigrim, please proceed with the vote on the proposal as-written.

**Comment by Bodigrim** [comment]
In this case there are 4 votes in favour, which is enough to approve; thanks all.

----

(Changing hats to a private individual)

> Does this mean that we should also relax the requirement that `System.Mem.Weak` should not contain GHC-specific interfaces?

Well, FTP and AMP are GHC-specific (= not the report), which does not preclude them from being in `Data`. Further, `QuantifiedConstraints` and `RankNTypes` are also GHC-specific - and again featured prominently in `Control` / `Data`. We are far past the point where compliance with the report is of any significance, and we should not waste our lifes theorizing about hypothetical non-existent Haskell compilers. The only meaningful split left is stable / unstable.
