### ISSUE TITLE
Extract ToList from IsList

### ISSUE THREAD

**Issue by yaitskov** [haskell/core-libraries-committee#127]
Hi,

`GHC.IsList.IsList` requires a type to be isomorphic. It is not possible to define instance with all function total for tuples.

I would like to extract subclass ToList with just toList method then tuples could have polymorphic toList method

```
class ToList l where
  type Item l
  toList :: l -> [Item l]

class ToList l => IsList l where
  type Item2 l
  fromList :: [Item2 l] -> l

instance ToList (a,a) where
  type Item (a, a) = a
  toList (a, b) = [a, b]

instance ToList (a, a, a) where
  type Item (a, a, a) = a
  toList (a, b, c) = [a, b, c]

```

**Comment by tomjaguarpaw** [comment]
Since you probably want to use this with list syntax, shouldn't you make a [GHC proposal](https://github.com/ghc-proposals/ghc-proposals/) instead?

**Comment by tomjaguarpaw** [comment]
Having said that, using list syntax for pattern matching on tuples isn't very useful, so perhaps you could elaborate on your use case?

**Comment by Bodigrim** [comment]
Introducing a new superclass for `IsList` would be a huge breaking change. I don’t see enough justification for it. 

I’d define a newtype `HomoTuple` (or is there already a package for this?) and use `Foldable.toList`.

**Comment by chessai** [comment]
This doesn't seem generally useful enough to me to be included into `base`. In most cases where I use or see others use tuples, they aren't homogeneous. Even when they are, this seems like a weird abstraction, and if I thought about its potential existence when writing my own code, I would ask myself some questions:

- Why can't I just define a function or a newtype that does what I want?
- If I'm using enough tuples of various sizes to want a typeclass that handles all these cases (sizes), why am I not using a custom datatype? I rarely exceed 3-tuples in my own code, and if I'm returning a tuple larger than that, I usually feel like I'm doing something wrong.

Typeclasses need a lot of thought and care put into their design and hierarchies - this kind of breakage seems unjustified and not generally useful.

**Comment by treeowl** [comment]
I'd personally be much more interested in removing the hardwired connection between the `(:)` and `[]` data constructors, and the `[]` type constructor, and the list type. I'd like `base` to actually have a definition looking something like

```haskell
data [a] = [] | a : [a]
```

Let me make my own `[]` type. Let me make `[]` and `:` pattern synonyms.

**Comment by yaitskov** [comment]
> Having said that, using list syntax for pattern matching on tuples isn't very useful, so perhaps you could elaborate on your use case?

`Data.Maybe.maybeToList` fits class method `toList`. 
With current signature `maybeToList` is not applicable to First/Last/Alt types from `Data.Monoid`.

**Comment by treeowl** [comment]
> `Data.Maybe.maybeToList` fits class method `toList`. With current signature `maybeToList` is not applicable to First/Last/Alt types from `Data.Monoid`.

This is a bit of a mishmash, but ...

```haskell
myToListy :: (Foldable t, IsList c, Item c ~ a) => t a -> c
myToListy = fromList . Data.Foldable.fromList
```

All the types you mentioned are `Foldable`.

----

Frankly, I'm sympathetic to your cause, but `IsList` was never intended to be a decent standalone class, and it isn't one. It really just (barely) supports the `OverloadedLists` extension. If you want something more normal, there's stuff for that in the `mono-traversable` package. I personally don't agree with many of its design decisions, but it's ... okay.

**Comment by phadej** [comment]
Using `toListOf each` from `lens` or `optics` is another design point.

**Comment by yaitskov** [comment]
Thanks for explanations.
