### ISSUE TITLE
Is it OK if time depends on template-haskell?

### ISSUE THREAD

**Issue by AshleyYakeley** [haskell/core-libraries-committee#128]
To add `Lift` instance to types in the `time` package  (haskell/time#233), I would have to make `time` depend on `template-haskell`. Does that cause any problems for the core libraries? I'm guessing no but I thought I'd check.

**Comment by thielema** [comment]
On Tue, 7 Feb 2023, Ashley Yakeley wrote:

> To add Lift instance to types in the time package (haskell/time#233), I 
> would have to make time depend on template-haskell. Does that cause any 
> problems for the core libraries? I'm guessing no but I thought I'd 
> check.

This would couple each version of time to a specific version of GHC, 
right? It will become harder to use time and stay compatible with many 
versions of GHC, then.

**Comment by tomjaguarpaw** [comment]
> This would couple each version of time to a specific version of GHC, right?

I don't think so, why? Any given `time` version could depend on a range of `template-haskell` versions, thus being compatible with a range of GHC versions.

**Comment by treeowl** [comment]
The only issue that came up doing the same thing for `containers` is that it was necessary to add some odd imports to get things working for the GHC build process. See [the note by @mpickering](https://github.com/haskell/containers/blob/master/containers/note-template-haskell-deps.md). This is only an issue for GHC boot packages, I believe; is `time` one of those?

**Comment by phadej** [comment]
@treeowl @mpickering 

```haskell
-- Therefore the modules add an import on Language.Haskell.TH.Syntax (in order to import Lift)
-- but no dependency is recorded between the module and
-- Language.Haskell.TH.Lib.Internal. 
```

Can't there be a dependency between `Language.Haskell.TH.Lib.Internal` and `Language.Haskell.TH.Syntax `, e.g. adding

```haskell
import Language.Haskell.TH.Syntax.Internal ()
```

to `Language.Haskell.TH.Syntax`?

**Comment by phadej** [comment]
Side-comment: that node should probably be `.txt` file, Language.Haskell.TH.Syntax.Internal is probably Language.Haskell.TH.Lib.Internal (Syntax -> Lib) and Haskell2021 is GHC2021. Maybe there are more mistakes.

**Comment by AshleyYakeley** [comment]
OK, sounds like there's no problem for core libraries. Also, I can build GHC with this dependency, no problem.
Thanks.
