### ISSUE TITLE
Add INLINABLE pragmas to `generic*` functions in Data.OldList

### ISSUE THREAD

**Issue by mpickering** [haskell/core-libraries-committee#129]
These functions are

* recursive
* overloaded

So it's important to add an `INLINABLE` pragma to each so that they can be specialised at the use site when the specific numeric type is known. Adding these pragmas improves the LazyText replicate benchmark (see https://gitlab.haskell.org/ghc/ghc/-/issues/22886#note_481020)

GHC MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9952

**Comment by phadej** [comment]
Or should they be SPECIALIZABLE https://github.com/ghc-proposals/ghc-proposals/pull/568 / https://github.com/ghc-proposals/ghc-proposals/pull/357

**Comment by Bodigrim** [comment]
@phadej neither of GHC proposals is approved or implemented. If/when it happens, it would constitute a material change, allowing us to review the question again.

---- 

Dear CLC members, let's vote on the proposal to mark `Data.List.generic{Length,Take,Drop,SplitAt,Index,Replicate}` as `{-# INLINABLE  #-}`, see https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9952. This would allow GHC to generate efficient code, when these functions are instantiated with, say, `Word`, `Integer` or `Natural`, reducing performance gap between them and `Int`-typed `length`, `take`, `drop`, etc. 

@angerman @chshersh @hasufell @mixphix @tomjaguarpaw @parsonsmatt

----

+1 from me, I'd love to use `genericLength` returning `Word` or `Natural` without incurring severe performance penalties.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by chshersh** [comment]
+1

<hr>

Giving the ability to specialize such functions would be a nice performance boost to people, using those functions heavily! I never used them and mostly due to performance considerations, so it's a nice move toward making flexible API more efficient.

@Bodigrim I believe, to make `genericLength` efficient with `Word` and `Natural`, one should change the following lines as well. Other `generic*` functions should be strict already as they are.

```haskell
{-# RULES
  "genericLengthInt"     genericLength = (strictGenericLength :: [a] -> Int);
  "genericLengthInteger" genericLength = (strictGenericLength :: [a] -> Integer);
 #-}
```

**Comment by mixphix** [comment]
+1

**Comment by Bodigrim** [comment]
@angerman @hasufell @parsonsmatt just a gentle reminder to vote.

**Comment by angerman** [comment]
+1

Should not break existing code. Not sure how I missed the first ping, sorry.

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, approved unanimously.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @mpickering   |
| **Status**             |  merged |
| **`base` version**     | `4.19.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9952 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | present  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
