### ISSUE TITLE
Add StrictEndo to Data.Semigroup

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#13]
The appropriate implementation of `stimes` for `Endo` depends on whether the wrapped function is lazy or strict. History has chosen to optimize the lazy case. I propose a new newtype to optimize the strict case:

```haskell
newtype StrictEndo a = StrictEndo
  { appStrictEndo :: a -> a }

instance Semigroup (StrictEndo a) where
  StrictEndo f <> StrictEndo g = StrictEndo (\x -> f $! g $! x)
  stimes n0 (StrictEndo f) = StrictEndo $ \a0 ->
    case n0 of
      _ | n0 < 0 -> errorWithoutStackTrace "You messed up! Go to your room!"
      0 -> a0
      1 -> f $! a0
      _ -> go n0 a0
    where
      go 0 !a = a
      go n !a = go (n - 1) (f a)
```

**Comment by cgibbard** [comment]
A tiny nitpick: I wonder if that should be `f $! g $! x` as written or just `f $! g x`. If g is strict, it can already cause the evaluation of x when g x is evaluated, but I think we might as well leave that up to g. It's the first `$!` which is important and which we can't emulate with `Endo`.

**Comment by treeowl** [comment]
@cgibbard, I think you're right. I believe we still want to make `stimes` explicitly strict in the initial value even though that's very slightly unlawful if someone passes it a lazy function for some strange reason.

**Comment by treeowl** [comment]
@cgibbard, is that first `$!` really necessary? We can write `Endo (f $!) <> q`. Another option is to make `<>` just compose, and make `stimes` only lawful for strict functions. There's a lot of space in here and I'm not sure exactly where the sweet spot is.

**Comment by Bodigrim** [comment]
I'm not sure how justified is to add a new data type just to provide a special instance. Is there a popular demand?

**Comment by gwils** [comment]
I don't see much benefit in adding this data type to base right now. Things are lazy by default in Haskell, so it seems a good case to default to. Adding it would also be confusing, as users would have to make an extra choice about which one to use.
I don't write performance-critical Haskell, but my suspicion is that folks doing so wouldn't really use a gadget like `Endo` in their inner loop, hence I'm not sure we need to worry about offering a separate version that's better optimised for strictness. 
Perhaps you could publish this as its own package and we could see whether it gains usage in the community, then consider moving it into base.

**Comment by Bodigrim** [comment]
I agree with @gwils

Adding a new type to `base` is a serious business: one have to define all possible instances, plus update `template-haskell` to provide `instance Lift`, plus update `deepseq` for `NFData` and so on. Doing all of this just to override a single function in a single instance looks an overkill to me. 

Such function could be declared separately `stimesStrictEndo` if needed, but I do not see a strong user demand to justify such addition to `base` at the moment.

**Comment by Bodigrim** [comment]
@treeowl would you like to put this for a formal vote?

**Comment by treeowl** [comment]
Since the design isn't even settled yet, I don't think that would be appropriate. And it sounds like most if not all CLC members are leaning against anyway.
