### ISSUE TITLE
Make quotRem and quot for Int more defined

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#142]
Currently, `quotRem (minBound :: Int) (-1)` raises an arithmetic overflow exception in the quotient:

```haskell
    a `quotRem` b
     | b == 0                     = divZeroError
       -- Note [Order of tests] in GHC.Int
     | b == (-1) && a == minBound = (overflowError, 0)
     | otherwise                  =  a `quotRemInt` b
```

 I don't see any reason for that. As long as we need that special case anyway (to avoid an unchecked floating point exception), why don't we use this?

```haskell
    | b == (-1) && a == minBound = (minBound, 0)
```

That would still satisfy the relevant law,

```haskell
x = y * quot x y + rem x y with rem x y = fromInteger 0 or g (rem x y) < g y
```

**Comment by Bodigrim** [comment]
Earlier discussion: https://gitlab.haskell.org/ghc/ghc/-/issues/8695

**Comment by treeowl** [comment]
Looks like a can of worms I don't want to get into right now.
