### ISSUE TITLE
Define `Eq` and `Ord` instances for `SSymbol`, `SChar`, and `SNat`

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/core-libraries-committee#148]
There are four singleton types currently defined in `base`:

1. [`TypeRep`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Type-Reflection.html#t:TypeRep), defined in `Type.Reflection`
2. [`SSymbol`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-TypeLits.html#t:SSymbol), defined in `GHC.TypeLits`
3. [`SChar`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-TypeLits.html#t:SChar), defined in `GHC.TypeLits`
4. [`SNat`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-TypeLits.html#t:SNat), defined in `GHC.TypeNats`

`SSymbol`, `SChar`, and `SNat` were introduced as part of proposal #85, and their APIs were designed to mimic that of `TypeRep`. Unfortunately, #85 forgot to carry over one aspect of the `TypeRep` API: the `Eq` and `Ord` instances:

```hs
instance Eq (TypeRep a) where
  _ == _  = True

instance Ord (TypeRep a) where
  compare _ _ = EQ
```

I propose that we define similar `Eq` and `Ord` instances for `SSymbol`, `SChar`, and `SNat`.

## How?

How can we know that the `Eq` and `Ord` instances for `TypeRep` always return `True`/`EQ`? This is because `TypeRep` is a singleton type. That is, given a fixed type `a`, there is only ever a single unique value¹ that can inhabit type `TypeRep a`. Therefore, the equality checks that `(==)` and `compare` perform will always succeed by virtue of the typing discipline involved.

The same reasoning applies to all other singleton types, including `SSymbol`, `SChar`, and `SNat`.

## Why?

Why bother defining these instances in the first place? On their own, they aren't terribly useful, as `(==)`/`compare` will always compute the same answer. They are more useful for the purpose of satisfying superclasses of other instances. For instance, the [`EqP`](https://hackage.haskell.org/package/some-1.0.5/docs/Data-EqP.html#t:EqP) class in the `some` library requires a quantified `Eq` superclass, so it would not be possible to define an `EqP` instance for `TypeRep` (or any other singleton type) without first giving it an `Eq` instance.

## Prior art

`TypeRep` is the most notable singleton type to define `Eq`/`Ord` instances in this fashion. Besides `TypeRep`, I have also found other occurrences of these sort of `Eq`/`Ord` instances in the wild:

1. [`SNat`](https://github.com/AndrasKovacs/singleton-nats/blob/8d10be3dd00dd3de2a931e5550b65a95e3dbeef0/Data/Nat.hs#L94-L98), defined in `singleton-nats`
2. [`SBool`](https://github.com/phadej/singleton-bool/blob/4d405690d7e44876e88459cbad259f51d6c7b8de/src/Data/Singletons/Bool.hs#L66-L72), defined in `singleton-bool`
3. [`BoolRepr`](https://github.com/GaloisInc/parameterized-utils/blob/b2e9cc34a58e5931cf14beca2c5bc28f343cf966/src/Data/Parameterized/BoolRepr.hs#L74-L75), [`NatRepr`](https://github.com/GaloisInc/parameterized-utils/blob/a58128337e2a795dd06dd3968b6a7e98dc1b27bf/src/Data/Parameterized/NatRepr/Internal.hs#L48-L49), and [`SymbolRepr`](https://github.com/GaloisInc/parameterized-utils/blob/a58128337e2a795dd06dd3968b6a7e98dc1b27bf/src/Data/Parameterized/SymbolRepr.hs#L93-L99), defined in `parameterized-utils`

-----

¹ Besides `⊥`, but [it is fine to reason modulo `⊥`](https://www.cs.ox.ac.uk/jeremy.gibbons/publications/fast+loose.pdf).

**Comment by treeowl** [comment]
Another reason is to support derived instances.

```haskell
data Foo n = Foo !(SNat n) String
  deriving (Eq, Ord)
```

I'm in favor.

**Comment by RyanGlScott** [comment]
See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10166.

**Comment by mixphix** [comment]
+1

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add `Eq` and `Ord` instances to [`SSymbol`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-TypeLits.html#t:SSymbol), [`SChar`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-TypeLits.html#t:SChar) and [`SNat`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-TypeNats.html#t:SNat) as detailed in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10166.

@tomjaguarpaw @chshersh @hasufell @angerman @parsonsmatt 

----

+1 from me.

**Comment by parsonsmatt** [comment]
+1

**Comment by chshersh** [comment]
+1

<hr>

If only every proposal was as easy to vote for as this one 🥺

**Comment by hasufell** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, 6 votes out of 7 possible are enough for approval.
