### ISSUE TITLE
Give `COMPLETE` pragmas to `TypeRep`, `SSymbol`, `SChar`, and `SNat` pattern synonyms

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/core-libraries-committee#149]
## Background

The [`TypeRep`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Type-Reflection.html#t:TypeRep) data type in `Type.Reflection` has a [pattern synonym of the same name](https://hackage.haskell.org/package/base-4.18.0.0/docs/Type-Reflection.html#v:TypeRep) that allows pattern-matching on it to bring a `Typeable` constraint into scope:

```hs
pattern TypeRep :: forall a. () => Typeable a => TypeRep a 
```

This pattern synonym was introduced in GHC 9.4 as a part of [GHC#19691](https://gitlab.haskell.org/ghc/ghc/-/issues/19691). Later, GHC 9.6 implemented CLC proposal #85, which introduced the `SSymbol`, `SChar`, and `SNat` data types alongside pattern synonyms of the same names:

```hs
pattern SSymbol :: forall s. () => KnownSymbol s => SSymbol s
pattern SChar   :: forall c. () => KnownChar c   => SChar c
pattern SNat    :: forall n. () => KnownNat n    => SNat n
```

These pattern synonyms were designed to mimic the `TypeRep` pattern synonym above.

## The problem

Currently, all of these pattern synonyms lack `COMPLETE` pragmas. This means that if you do any sort of pattern-matching on these pattern synonyms, then GHC will emit an `-Wincomplete-patterns` warning when `-Wall` is enabled. Consider this example, which is adapted from [the example in the Haddocks for `TypeRep`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Type-Reflection.html#v:TypeRep):

```hs
f :: TypeRep a -> (Typeable a => r) -> r
f TypeRep k = k {- Typeable a in scope -}
```

GHC will emit the following warning when compiling this example:

```
warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for `f':
        Patterns of type `TypeRep a', `Typeable a => r' not matched:
            (App _ _) _
            (Con _) _
   |
   | f TypeRep k = k {- Typeable a in scope -}
   | ^^^^^^^^^^^^^^^
```

This is rather silly, however. Because `TypeRep` is a singleton type, then for any given `a`, there is exactly one way to convert an explicit `TypeRep a` value to an implicit `Typeable a` constraint. That is to say: matching on `TypeRep` alone should constitute an exhaustive pattern match.

In order to silence the warning on `f` above, you would have to write code like this:

```hs
f :: TypeRep a -> (Typeable a => r) -> r
f TypeRep k = k
f x k = withTypeable x k
```

But `TypeRep` is implemented in terms of [`withTypeable`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Type-Reflection.html#v:withTypeable), so both equations are doing the exact same thing! It would be far preferable to declare the `TypeRep` pattern synonym as `COMPLETE` so that we do not have to resort to ugly workarounds like this one.

A similar problem arises for `SSymbol`, `SChar`, and `SNat`, which are also singleton types.

## The proposal

I propose that we give `COMPLETE` pragmas to each of the `TypeRep`, `SSymbol`, `SChar`, and `SNat` pattern synonyms:

```hs
pattern TypeRep :: forall a. () => Typeable a => TypeRep a
pattern TypeRep = ...
{-# COMPLETE TypeRep #-}

pattern SSymbol :: forall s. () => KnownSymbol s => SSymbol s
pattern SSymbol = ...
{-# COMPLETE SSymbol #-}

pattern SChar :: forall c. () => KnownChar c => SChar c
pattern SChar = ...
{-# COMPLETE SChar #-}

pattern SNat :: forall n. () => KnownNat n => SNat n
pattern SNat = ...
{-# COMPLETE SNat #-}
```

## Effects of the proposal

This proposal doesn't change the API of these pattern synonyms _per se_, as it only affects how they interact with GHC's pattern-match coverage checker. As such, it is unlikely that most user code will be impacted by this proposal. The only sort of code that would be affected are examples that include fall-through cases to silence GHC's pattern-match coverage checker, such as in the example above:

```hs
f :: TypeRep a -> (Typeable a => r) -> r
f TypeRep k = k
f x k = withTypeable x k
```

In today's GHC, this would be marked as exhaustive. If we added a `COMPLETE` pragma to the `TypeRep` pattern synonym, however, then GHC would (rightfully) warn that `f`'s second equation is redundant:

```
warning: [-Woverlapping-patterns]
    Pattern match is redundant
    In an equation for `f': f x = ...
   |
   | f x k = withTypeable x k
   | ^^^^^^^^^^^^^^^^^^^^^^^^
```

Since it is unlikely that anyone would _aspire_ to write this sort of code, I argue that this is acceptable.

**Comment by treeowl** [comment]
I'm utterly in favor.

**Comment by parsonsmatt** [comment]
Clear improvement, +1

**Comment by Bodigrim** [comment]
@RyanGlScott could you please prepare an MR which we can vote on?

**Comment by RyanGlScott** [comment]
See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10188.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to give `COMPLETE` pgragmas to `TypeRep`, `SSymbol`, `SChar` and `SNat` pattern synonyms as detailed in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10188.

@tomjaguarpaw @parsonsmatt @angerman @hasufell @chshersh @mixphix 

----

+1 from me, a clear improvement indeed.

**Comment by hasufell** [comment]
+1

**Comment by chshersh** [comment]
+1

**Comment by mixphix** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, 5 votes out of 7 are enough to approve.

**Comment by konsumlamm** [comment]
I honestly don't see why the CLC even votes on adding `COMPLETE` pragmas (at least when the patterns are actually complete) or why anyone would ever vote against that.
