### ISSUE TITLE
Fix `Ord1` instance for `Down`

### ISSUE THREAD

**Issue by vaibhavsagar** [haskell/core-libraries-committee#15]
As detailed in [#17472](https://gitlab.haskell.org/ghc/ghc/-/issues/17472), this is [ready to go](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2158) pending CLC approval.

**Comment by cigsender** [comment]
+1

**Comment by Bodigrim** [comment]
For the sake of a permanent reference, here is a diff in question:
```diff
-    liftCompare comp (Down x) (Down y) = comp x y
+    liftCompare comp (Down x) (Down y) = case comp x y of
+        LT -> GT
+        EQ -> EQ
+        GT -> LT
```

I would suggest a more concise implementation ``liftCompare comp (Down x) (Down y) = EQ `compare` comp x y``, but both ways it is +1 from me.

**Comment by gwils** [comment]
+1

**Comment by emilypi** [comment]
+1 i don't know how this got missed thanks @vaibhavsagar

**Comment by Bodigrim** [comment]
4 votes in favor out of 6 are already a majority, but I would like to wait for @chessai and @cgibbard until tomorrow.

**Comment by cgibbard** [comment]
+1

**Comment by tomjaguarpaw** [comment]
> I would suggest a more concise implementation ...

Tangentially, I'm quite surprised to infer from this that nothing like [`flipOrder`](https://www.stackage.org/haddock/lts-18.16/regex-tdfa-1.3.1.1/src/Text.Regex.TDFA.Common.html#flipOrder) is in `base`.

**Comment by Bodigrim** [comment]
The proposal is approved, thanks @vaibhavsagar.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Author**             |  @vaibhavsagar   |
| **Status**             |  merged  |
| **`base` version**     | `4.17.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2158 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | present  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
