### ISSUE TITLE
Generalize the type of keepAlive#, touch#

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#152]
Up until now the types of `keepAlive#` and `touch#` have precluded their use in `ST`:
```haskell
touch#
    :: forall (lev :: Levity) (v :: TYPE (BoxedRep lev)).
       v -> State# RealWorld -> State# RealWorld

keepAlive#
    :: forall (lev :: Levity) (v :: TYPE (BoxedRep lev))
              (rep :: RuntimeRep) (p :: TYPE rep).
       v -> State# RealWorld -> (State# RealWorld -> p) -> p

```
In [GHC #23163](https://gitlab.haskell.org/ghc/ghc/-/issues/23163) it was proposed that we generalize this:
```haskell
touch#
    :: forall (lev :: Levity) (v :: TYPE (BoxedRep lev)) s.
       v -> State# s -> State# s

keepAlive#
    :: forall (lev :: Levity) (v :: TYPE (BoxedRep lev))
              (rep :: RuntimeRep) (p :: TYPE rep) s.
       v -> State# s -> (State# s -> p) -> p
```
As this is re-exported from `GHC.Exts` in `base`, we believe this may require a CLC proposal

**Comment by treeowl** [comment]
Yes, please!

**Comment by chessai** [comment]
This would be very useful

**Comment by phadej** [comment]
This feels silly that this change needs CLC proposal, but apparently doesn't need GHC proposal...

**Comment by chshersh** [comment]
I have no idea what those two functions do. 

* `keepAlive#` docs don't really help
* `touch#` doesn't have documentation at all

I think this is the case of something that is supposed to be internal but somehow got leaked via reexports from `ghc-prim` to `base`.

Even though these two functions look like a really internal thing, I see that they have usages across multiple popular packages:

* [touch# usages](https://hackage-search.serokell.io/?q=touch%23)
* [keepAlive# usages](https://hackage-search.serokell.io/?q=keepAlive%23)

This looks like a change that could break things. So [impact assessment](https://github.com/haskell/core-libraries-committee/blob/main/PROPOSALS.md#impact-assessments) is required.

**Comment by bgamari** [comment]
@chshersh [this blog post](https://www.haskell.org/ghc/blog/20210607-the-keepAlive-story.html) may shed some light on the intended usage of these operations.

For what it's worth, I generally agree with @chshersh that primops aren't necessarily intended to be widely consumed. There are many primops which are present only to implement bits of GHC (e.g. `unpackClosure#`), others which are intended to be exposed only via their friendlier lifted wrappers (e.g. `indexInt16OffAddr#`), and others that are hard enough to use correctly that a user should expect to review their usage with every new GHC release (e.g. `addrToAny#`).

That being said, I think `keepAlive#` and `touch#` are examples of primops that do have legitimate uses in low-level library code. However, I cannot see any way in which this generalization would break an existing well-typed program. The only way that such a generalization would break is a failure of type inference; however, all uses of `keepAlive#` and `touch#` are already specialised to `RealWorld`.

**Comment by Bodigrim** [comment]
> I think this is the case of something that is supposed to be internal but somehow got leaked via reexports from `ghc-prim` to `base`.

FWIW entire `ghc-prim` is re-exported from `base`, usually from `GHC.Exts`, that's a proper operation. 

The idea is that users should never export `ghc-prim` themselves: this package is deeply magical in its structure and can (and does) change rapidly without any deprecation period or warning. Using its entities through `base:GHC.Exts` allows us (at least in theory) to provide some compatibility shims and wrappers.

> I have no idea what those two functions do.
> 
>     * `keepAlive#` docs don't really help
> 
>     * `touch#` doesn't have documentation at all

I must admit that this is a stumbling block for me as well, despite a non-zero experience in low-level guts of Haskell. It would be immensely helpful, if someone volunteered to improve the documentation.

@bgamari @andrewthad @chessai @treeowl is there a good reason to touch `touch#`? My understanding of https://www.haskell.org/ghc/blog/20210607-the-keepAlive-story.html is that all new development should use `keepAlive#`.

**Comment by cartazio** [comment]
For those who aren’t familiar with them: both operations are to ensure some data structure stays reachable on the heap.  

As for why touch still exists: there exists code out there that largely uses touch correctly in a way that won’t be miscompiled, and there’s no good reason to break it.  Otoh its use for new code should absolutely be discouraged.

**Comment by treeowl** [comment]
@cartazio there are also situations where `keepAlive#` has performance issues, or (at least potentially) where object lifetimes are supposed to be staggered.

**Comment by Bodigrim** [comment]
@cartazio There've been no suggestions to **remove** `touch#`.

@treeowl could you please elaborate on performance issues with `keepAlive#` with a specific example?

**Comment by treeowl** [comment]
@Bodigrim See `Lost optimisation: CPR unboxing` in `compiler/GHC/CoreToStg/Prep.hs`. I may have been wrong about the staggering bit; sorry.

**Comment by bgamari** [comment]
> @bgamari @andrewthad @chessai @treeowl is there a good reason to touch `touch#`? My understanding of https://www.haskell.org/ghc/blog/20210607-the-keepAlive-story.html is that all new development should use `keepAlive#`.

While we do strongly recommend that people use `keepAlive#` whenever possible, sometimes this is simply not the case. Specifically, some programs use `ByteArray#`s which whose lifetime does not follow the lexical scoping of the program. In these cases one must use `touch#` (and be extremely careful while doing so).

While the original ticket only addressed `keepAlive#`, I would argue that it makes sense to treat these operations symmetrically.

**Comment by Kleidukos** [comment]
(@bgamari you don't have to answer right away, but I have a question: Do these programs use `ByteaArray#`s in such a way because there is no other way, or could this usage be modified as not to require `touch#`?)

**Comment by bgamari** [comment]
> (@bgamari you don't have to answer right away, but I have a question: Do these programs use `ByteaArray#`s in such a way because there is no other way, or could this usage be modified as not to require `touch#`?)

I can certainly envision cases where the structure of a foreign library essentially precludes lexical scoping of a buffer.

**Comment by Bodigrim** [comment]
Thanks for the explanations @bgamari. 

Dear CLC members, any non-binding opinions on this?

**Comment by Bodigrim** [comment]
Dear CLC members, given that there are no more comments, let's vote on the proposal to generalize `keepAlive#` and `touch#` to accept any state token, not only `RealWorld`, as detailed in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10171/diffs. See https://gitlab.haskell.org/ghc/ghc/-/issues/23163 and https://github.com/haskell/primitive/pull/375 for related discussion.

@tomjaguarpaw @chshersh @mixphix @hasufell @parsonsmatt @angerman 

----

+1 from me.

**Comment by mixphix** [comment]
I'm in favour!

**Comment by chshersh** [comment]
+1 from me

**Comment by parsonsmatt** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, 4 votes are enough to approve.
