### ISSUE TITLE
Variants of {new,with}CStringLen which NUL-terminate their output

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#153]
Currently, `GHC.Foreign.{new,with}CStringLen` do not NUL-terminate their output (unlike `{new,with}CString`).

However, in #144 we encountered need for variants which do add a final NUL terminator. We propose to introduce:
```haskell
GHC.Foreign.newCStringLen0 :: TextEncoding -> String -> IO CStringLen
GHC.Foreign.withCStringLen0 :: TextEncoding -> String -> (CStringLen -> IO a) -> IO a
```

**Comment by bgamari** [comment]
> I think you meant to name second one withCStringLen0, not newCString0?

Sigh, yes.

> The documentation for `CStringLen` says that it explicitly stores the length instead of a terminating NUL and that it allows NUL in the middle of the string.

Yes, so it does.

> So why exactly are these functions needed?

Frankly, I don't have any particular interest in exposing these functions for public consumption. I merely need them as a means of implementing the internal-NUL check of #144 in a reasonably efficient manner. However, until progress has been made on #146 a proposal like this one is the only way by which this can be achieved.

**Comment by Bodigrim** [comment]
> Frankly, I don't have any particular interest in exposing these functions for public consumption. I merely need them as a means of implementing the internal-NUL check of #144 in a reasonably efficient manner.

Then why expose them? You can define them in the same module which uses them or somewhere under `other-modules`.

**Comment by bgamari** [comment]
> Then why expose them? You can define them in the same module which uses them or somewhere under `other-modules`.

Fair enough; I have moved the implementation to a module in `other-modules`, eliminating the need for this proposal.
