### ISSUE TITLE
Support for unaligned reads/writes

### ISSUE THREAD

**Issue by clyring** [haskell/core-libraries-committee#154]
Today, for reading and writing basic values like `Int32`s to locations in memory we have:

* The `Storable` class from `base`
* The `Prim` class from `primitive`
* Primops like `readInt32OffAddr#` and `writeInt32OffAddr#`

All of these have in common that they may only work for sufficiently aligned addresses. (...though for the primops this is not currently documented anywhere obvious.) This leads library authors to writing embarrassing workarounds like [this one](https://github.com/haskell/bytestring/blob/da6ea8f6f403a72f96f4d6b7184f4bf4281156b8/Data/ByteString/Builder/Prim/Internal.hs#L200-L214) when there is a need to read from or write to a potentially un-aligned memory location. The code this workaround produces on non-whitelisted architectures is correct but very poor.

It's clear to me that GHC should provide a family of primops like `readInt32OffUnalignedAddr#` and `writeInt32OffUnalignedAddr#`. (This should be easy to implement.)

What's less clear to me is whether and how more polite wrappers should be provided. For example, adding a `pokeUnaligned :: Ptr a -> a -> IO ()` method to `Storable a` might be convenient, but this operation is not very commonly needed and a default implementation will probably be both necessary to avoid pointless breakage and a performance foot-gun. (The instances in `base` would use efficient non-default implementations via new primops, of course.) What do others think?

**Comment by Bodigrim** [comment]
Isn't `readWord8ArrayAsWord64#` etc. for unaligned access?

**Comment by clyring** [comment]
> Isn't `readWord8ArrayAsWord64#` etc. for unaligned access?

Yes, but these are only available when working with `ByteArray#` and no `Addr#` counterparts exist at the moment.

**Comment by Bodigrim** [comment]
@clyring I'm afraid I have to ask you to come up with a specific proposal to discuss, or mark the issue as abandoned / withdrawn.

I'd personally start with small steps, introducing primops first.

**Comment by clyring** [comment]
Introducing such primops is in my todo list, but I have enough open ghc branches at the moment. Feel free to mark this as dormant.

**Comment by Bodigrim** [comment]
Thanks, closing as dormant. Feel free to reopen, once active again.

**Comment by oberblastmeister** [comment]
@Bodigrim I implemented these primops in ghc https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10614. Please reopen.

**Comment by cartazio** [comment]
I’m a little confused about the chosen names for the primops. But to be clear: we are talking about byte aligned reads and writes even when we say unaligned? 

Also this doesn’t need clc feedback because it’s not in base.

**Comment by bgamari** [comment]
While these primops are defined in `ghc-prim`, we want to ensure they will be available via `base:GHC.Exts`. Consequently, this does require a proposal.

The concrete proposal is something like the following:

`GHC.Exts` exposes a set of new functions:

```haskell
indexWord8OffAddrAs<ty> :: Addr# -> Int# -> <ty>#
readWord8OffAddrAs<ty> :: Addr# -> Int# -> State# s -> (# State# s, <ty># #)
writeWord8OffAddrAs<ty> :: Addr# -> Int# -> {rep_ty} -> State# s -> State# s
```
where `<ty>` is one of:
 * `Word`
 * `Word{8,16,32,64}`
 * `Int`
 * `Int{8,16,32,64,}`
 * `Char`
 * `WideChar`
 * `Addr`
 * `Float`
 * `Double`
 * `StablePtr`

**Comment by cartazio** [comment]
Yeah it sounds pretty reasonable.

**Comment by hasufell** [comment]
+1

**Comment by chshersh** [comment]
> we want to ensure they will be available via base:GHC.Exts

Just curious, why do we want this? I had an impression that `GHC.Exts` is a kitchen sink, and it might not be a good idea to expose everything from it. And we might prefer to avoid exporting more stuff from this module to make future clean-up of this module easier.

Could this be implemented in `ghc-prim` and then every potential user can just use `ghc-prim` directly?

In that case, it won't require a CLC proposal.

**Comment by bgamari** [comment]
> Could this be implemented in `ghc-prim` and then every potential user can just use `ghc-prim` directly?

As we've discussed in the past, `ghc-prim` is considered to be non-user-facing by both the CLC and GHC developers; it is an implementation detail of GHC which should not be used directly. `GHC.Exts` is the user-facing home for prim-ops.

However, I do agree that the current design of `GHC.Exts` leaves much to be desired; the module's documentation is both sparse and far too large to easily consume. I have long felt that we should split it up into a set of topical modules.

**Comment by hasufell** [comment]
+1

**Comment by chshersh** [comment]
+1

**Comment by angerman** [comment]
So we are going to have primops that claim to do unaligned memory access. And emulate that architectures that do not have unaligned access?

I'm +1 on this, **iif** these primops _explixity_ call out that unaligned access is not available on all systems (and on which systems these primops will be availabe natively, and on which it will be emulated) and explain the performance implications of using these primops.

**Comment by cartazio** [comment]
I agree with moritz. Unaligned reads are highly platform dependent.

**Comment by mixphix** [comment]
+1
