### ISSUE TITLE
Automatic conversion of fixed-point representations in `Data.Fixed`

### ISSUE THREAD

**Issue by VictorCMiraldo** [haskell/core-libraries-committee#159]
The `Fixed :: k -> Type` datatype from [`Data.Fixed`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Fixed.html#t:Fixed) is great to keep a unit explicit, but it would be much better if we could convert between different fixed-point resolutions, making it impossible to forget a zero when converting between different fixed point representations. I think something like `convert` below could work:

```haskell
-- | Convert between different fixed-point resolutions. If @n > m@ this function will
-- truncate the number, losing information. 
convert :: forall n m . (HasResolution n, HasResolution m) => Fixed n -> Fixed m
convert (MkFixed xn) = 
  let rN = resolution @_ @n (Proxy :: Proxy n)
      rM = resolution @_ @m (Proxy :: Proxy m)
   in case compare rN rM of
        LT -> MkFixed (xn * (rM `div` rN))
        EQ -> MkFixed xn
        GT -> MkFixed (xn `quot` (rN `div` rM))
```

```
ghci> convert (42.123456789 :: Pico) :: Micro
42.123456

ghci> convert (42.123456 :: Micro) :: Pico
42.123456000000
```

**Comment by mixphix** [comment]
This is clever. Do you have performance benchmarks?

**Comment by mixphix** [comment]
I hesitate to add things I've written in five minutes to my journal. Let's do some rigorous testing before we add something written in five minutes to the `base` library, yeah?

**Comment by mixphix** [comment]
Benchmarks for converting between different sizes would be a great start, and maybe testing the magnitude of the numbers as well.

I also foresee naming clashes, `convert` is a fairly highly-valued name IMO. Perhaps something like `respecify` or `toPrecision`.

**Comment by Bodigrim** [comment]
The problem with the proposed definition is that `convert @2 @3 = id`. Even if this is fixed, I'm uneasy with losing precision when `m` is not a multiple of `n`. I'd be more content with something like 

```haskell
upscale :: forall (m :: Nat) (n :: Nat). (KnownNat m, KnownNat n, Mod m n ~ 0) => Fixed n -> Fixed m
```

**Comment by VictorCMiraldo** [comment]
> Benchmarks for converting between different sizes would be a great start, and maybe testing the magnitude of the numbers as well.

I don't understand this. Wouldn't benchmarks only make sense if we had something to compare it against?

> I also foresee naming clashes, `convert` is a fairly highly-valued name IMO. Perhaps something like `respecify` or `toPrecision`.

Very fair; I'm happy to rename it. I like `toPrecision`!
 
@Bodigrim that's a great catch, thanks! While having values other than powers of 10 in resolution is not intuitive to me, it seems like the implementation of `Data.Fixed` was really intended this way from some comments I found in there ([`convertFixed`](https://hackage.haskell.org/package/base-4.18.0.0/docs/src/Data.Fixed.html#convertFixed), for instance). 

I don't think your suggestion would work for the majority of use cases. I imagine we'd want this to go from `Fixed EX` to `Fixed EY`, where `EX` and `EY` are one of `Milli`, `Micro`, `Pico`, ...

A potential compromise could be:
```haskell
data E (n :: k)
instance (KnownNat n) => HasResolution (E n) where ...

toPrecision :: (KnownNat n, KnownNat m) => Fixed (E n) -> Fixed (E m)
```

Now we restrict ourselves to powers of 10. We could even split this in two functions to make the loss of precision explicit:
```haskell
upscale :: (KnownNat n, KnownNat m, n <= m) => Fixed (E n) -> Fixed (E m)

unsafeDownscale :: (KnownNat n, KnownNat m, n <= m) => Fixed (E m) -> Fixed (E n)
```

**Comment by Bodigrim** [comment]
I'd rather make `type E0 = 1`, `type E1 = 10`, etc., because this is how one would design such API from the scratch in 2023. Otherwise the current interface is quite confusing, and I'm not really sure I want to extend it further.

**Comment by mixphix** [comment]
Benchmarks provide useful statistics even when they aren't used as comparison. I'd be disappointed if I tried to use this on a big (> 10^10) number and found that it was much slower than on small (< 10^3) numbers. I can't imagine this would be the case but I'd still like to be sure.

I think the `E` type family is a good idea. Currently `Data.Fixed` has independent data types `E0`, `E1`, `E2`, `E3`, `E6`, `E9`, `E12` such that the SI prefix is defined as `Fixed En` (e.g. `type Milli = Fixed E3`). With the data family we could have these and users could even define their own named precisions, e.g. `type Myrio = Fixed (E 4)`. I'm excited to see your design for this!

**Comment by phadej** [comment]
@Bodigrim 

> I'd rather make type E0 = 1, type E1 = 10

`Fixed` is polykinded, and there is `KnownNat n => HasResolution (n :: Nat)` instance though. So you can `Fixed 1000` today

**Comment by chshersh** [comment]
As a person, who wrote two libraries with units tracked on the type level with completely different approaches, I can confidently say that the design space for this problem is **HUGE** (and the CLC issue tracker might not be the best place to discuss this topic).

I see `Data.Fixed` as a good pioneering attempt but its interface is quite confusing and error-prone. So, I wouldn't want to invest a bit into making it usable. For example, if we add this lossy `convert` function that doesn't satisfy the _roundtrip_ property, people will use it nevertheless (because there's no alternative), they'll write software with bugs, and nobody is winning.

It's a mystery to me how something like `Data.Fixed` appeared in `base` in the first place. Type-level units is such a weird thing to standardize before considering different options and carefully discussing their trade-offs.

I'd rather see people explore different approaches as external libraries and let the public discourse decide what is the best solution.

**Comment by VictorCMiraldo** [comment]
@phadej I think that without `Exp10` and `Log10` (or `DivMod` as suggested by @Bodigrim), we'd remain in the problematic space where `toPrecision @2 @3` would be equivalent to `id`. I personally find it pretty unintuitve how non powers of 10 work in `Data.Fixed`. Is there any use for it?

> It's a mystery to me how something like `Data.Fixed` appeared in `base` in the first place. Type-level units is such a weird thing to standardize before considering different options and carefully discussing their trade-offs.

That makes two of us. I do agree with the sentiment of not fixing something that isn't great anyway. Maybe the best course of action is to remove `Data.Fixed` and let people explore the different approaches through libraries. My only interaction with `Data.Fixed` stems from `Data.Time`, and I've converted to and from `Pico` wrongly a few too many times by hand, hence the desire of something automatic.

All in all, it seems like my proposed `convert` is less nice than I originally thought and the design space seems to be pretty large. I'm happy to close the issue and continue the discussion somewhere else if we think this is something that should eventually be ironed out from `base`.

**Comment by mixphix** [comment]
I'd be alright with deprecating `Data.Fixed` along an appropriate time scale, provided we move the existing code to a new package. It may have to be a boot package since `time` depends on `Pico`, as you mentioned. This is rather unfortunate. @AshleyYakeley what are your thoughts on this?

**Comment by AshleyYakeley** [comment]
There shouldn't be anything special about powers of 10? `n` is the denominator, it can be any positive integer.

`Data.Fixed` originally ended up in `base` because `time` needs it, and at the time it seemed simpler than creating a new core package. But my current opinion is that `Data.Fixed`, `Data.Ratio`, and `Data.Complex` might be better off in a new core package.

**Comment by hasufell** [comment]
> I'd be alright with deprecating Data.Fixed along an appropriate time scale

Me too, but do note that some CLC members seem to carry the opinion that introducing deprecation warnings is a breaking change.

**Comment by AshleyYakeley** [comment]
Possible idea, something along the lines of:

`upscale :: forall (s :: Nat) (n :: Nat). (KnownNat s, KnownNat n, KnownNat (s * n)) => Fixed n -> Fixed (s * n)`

then use `upscale @1000` etc.

**Comment by mixphix** [comment]
> > I'd be alright with deprecating Data.Fixed along an appropriate time scale
> 
> Me too, but do note that some CLC members seem to carry the opinion that introducing deprecation warnings is a breaking change. 

Oh `-Werror`, oh `-Werror` has my little dog gone? 🎶

**Comment by mixphix** [comment]
@VictorCMiraldo shall we close this issue?

**Comment by AshleyYakeley** [comment]
> It's a mystery to me how something like Data.Fixed appeared in base in the first place. Type-level units is such a weird thing to standardize before considering different options and carefully discussing their trade-offs.

I'm a little confused by this. `Fixed` has nothing to do with type-level units. It's simply fixed-point arithmetic, as opposed to floating-point arithimetic (`Single` and `Double`).

**Comment by VictorCMiraldo** [comment]
@AshleyYakeley that's a great point. I think the names (`Milli`, `Micro`, `Pico`, etc...) might lead people to think of *grams*, *liters*, *meters*. But the names make sense; naming things is difficult.

@mixphix the discussion certainly spread and we don't seem to be reaching any consensus on whether to add something like `convert` and, if so, in which flavour. Maybe it is better to close this indeed.

**Comment by nomeata** [comment]
The existing code for conversion (where you don't have to count digits manually) is `realToFrac`, is it? Is that not good enough? If it's not for performance reasons, can it be improved using rewrite rules?

**Comment by VictorCMiraldo** [comment]
Thank you @nomeata! I wasn't looking hard enough; that is what I was looking for! We can certainly close the issue now! :)
