### ISSUE TITLE
Derive instance {Enum, Bounded, Num, Real, Integral} Compose f g a

### ISSUE THREAD

**Issue by Bodigrim** [haskell/core-libraries-committee#160]
Let's add
```haskell
deriving instance Enum (f (g a)) => Enum (Compose f g a)
deriving instance Bounded (f (g a)) => Bounded (Compose f g a)
deriving instance Num (f (g a)) => Num (Compose f g a)
deriving instance Real (f (g a)) => Real (Compose f g a)
deriving instance Integral (f (g a)) => Integral (Compose f g a)
```

I'd argue that the absense of such instances is just an omission, but if anyone is curious, my particular use case deals with things like `Compose Odd Positive Integer`, where `newtype Odd a` and `newtype Positive a` are wrappers with desired `Arbitrary` instances.

**Comment by mixphix** [comment]
Are there other `Data.Functor.*` types that are missing instances?

**Comment by mixphix** [comment]
This permits the literal `1 :: Compose Odd Positive Int`. I'm not sure this is desired behaviour.

**Comment by Bodigrim** [comment]
> This permits the literal `1 :: Compose Odd Positive Int`. I'm not sure this is desired behaviour.

As long as one is fine with `1 :: Odd Int` and `1 :: Positive Int` (which might be somewhat questionable, I agree), I don't see an issue with `1 :: Compose Odd Positive Int`. 

Basically the proposal is just to use `{-# LANGUAGE GeneralizedNewtypeDeriving #-}` for `newtype Compose f g a = Compose (f (g a))`. If for some reason there is already `instance Foo (f (g a))`, there is very little to win from not providing `instance Foo (Compose f g a)`, it's just `coerce`-away anyways. We already have this kind of instances for `Eq`, `Ord`, `Show`, and I'd like to extend to other standard type classes as well.

**Comment by Bodigrim** [comment]
> Are there other `Data.Functor.*` types that are missing instances?

Other `newtype`s under `Data.Functor` (which are `Identity` and `Const`) already have full set of instances. 

----

I've raised a draft MR with the proposed changes: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10419

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add `instance {Enum, Bounded, Num, Real, Integral} (Compose f g a)` as detailed in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10419/diffs.

@tomjaguarpaw @chshersh @hasufell @angerman @parsonsmatt @mixphix 

----

+1 from me, obviously.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by angerman** [comment]
We do not have an impact assessment for this, do we? Primarily for completeness. Every change should have an impact assessment.

As I believe this is purely additive and a fail to see how this can break existing code (someone enlighten me please, if I'm wrong). +1.

**Comment by mixphix** [comment]
+1

**Comment by chshersh** [comment]
+1

**Comment by Bodigrim** [comment]
@angerman yes, this is a purely additive change. 

Thanks all, approved.
