### ISSUE TITLE
Add foldl' to Prelude

### ISSUE THREAD

**Issue by Bodigrim** [haskell/core-libraries-committee#167]
Currently `Prelude` exports `foldl` (which is an anti-pattern most of the time, especially for lists), but does not export `foldl'`. This is silly and harmful, especially for newcomers, who easily fall into the trap and get space leaks even in the simplest programs. 

`foldl'` is a better default choice than `foldl`, and `Prelude` should not discriminate the former in favor of the latter.

**Comment by treeowl** [comment]
Generally in favor. Not a fan of the CPP I'll need to avoid warnings.

**Comment by Bodigrim** [comment]
One can avoid CPP with 
```haskell
import Prelude hiding (Foldable(..))
import Data.Foldable
```

**Comment by googleson78** [comment]
Big +1, I can't wait to stop telling students "yeah you should almost always use this other thing, but you need to \<discussion derails into explaining modules and imports\>"

> Generally in favor. Not a fan of the CPP I'll need to avoid warnings.

I am in the process of writing a proposal to address this concern regarding `-Wunused-imports`

**Comment by tomjaguarpaw** [comment]
Strongly in favour. This has been a long time coming.

**Comment by tomjaguarpaw** [comment]
[This is probably a good place to get on my high horse about `Foldable` not being a good abstraction, and `foldl'` not meaning what one might think it does for many instances, but nonetheless, I'm in support of this proposal.]

**Comment by mixphix** [comment]
+1

**Comment by jbolden1517** [comment]
Totally agree.  This is a legacy problem by putting it into prelude at least both become obvious and so we can encourage people to use the right one.

**Comment by axman6** [comment]
For some indication of how much I want to see this change, when I saw the headline on Reddit, my immediate thought was _What? It is already, isn’t it? Oh wow, it really isn’t already there, still!_. 

What would also be interesting (and beyond the scope of this specific issue) would be if GHC could offer warnings, only in the cases where `foldl` would behave differently to `foldl’` and suggest replacing a potentially leaky usage.

**Comment by stephen-smith** [comment]
> For an arbitrary `Foldable` (and not the specific case of lists), I don't see a strong reason to assume that `foldl'` is preferable to `foldr'` and it seems strange to not have symmetry here

Take that up with the `Foldable` documentation:

> Strict left-associative folds are a good fit for space-efficient reduction, while lazy right-associative folds are a good fit for corecursive iteration, or for folds that short-circuit after processing an initial subsequence of the structure's elements.

The default implementations, and the non-member functions defined in base assume `foldr` and `foldl'` are the good ones, and `foldr'` and `foldl` are the bad ones -- `Foldable` isn't truly symmetric in practice.

**Comment by treeowl** [comment]
@stephen-smith should we have these methods?

```haskell
    foldUnordered :: (a -> b -> b) -> b -> t a -> b
    foldUnordered' :: (b -> a -> b) -> b -> t a -> b
    foldUnordered' f b0 xs =
      foldUnordered (\ a r !acc -> r (f acc a)) id xs b0
```

I have been wondering for a while what `foldMap'` is supposed to be for, and whether it's useful for something.

**Comment by hasufell** [comment]
`foldr'` is not part of this proposal and I see no reason why it should be. Someone else can create a separate proposal about it.

**Comment by stephen-smith** [comment]
> @stephen-smith should we have these methods?

This discussion is better pursued outside the comments on this particular proposal.

While it might be unfortunate that the generic "Foldable" name is taken by something asymmetric, I don't think the right fix is to try to make `Foldable` symmetric.  If we really need a type class for symmetric folding, or "backward" (from the way `Foldable` prefers) folding, it should probably "simply" be under a different name.

**Comment by ocramz** [comment]
+1

**Comment by harendra-kumar** [comment]
+1 , foldl' is indeed a better choice most of the time.

**Comment by Bodigrim** [comment]
The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10489. Disregard performance test failures, they are caused by submodule bumps.

As for impact assessment, I've raised PRs to resolve name clashes to all affected Stackage packages (see links above) except [`storablevector`](https://hackage.haskell.org/package/storablevector), which does not seem to have a public issue tracker. The patch for the latter is trivial: just add `Foldable(..)` to `import Prelude hiding ...` in `Data.StorableVector.Lazy.Pattern`.

**Comment by hasufell** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by chshersh** [comment]
+1

**Comment by chreekat** [comment]
@Bodigrim do you know to what degree your upstream patches that future-proof against this change have been released? Based on the breakage on head.hackage, this could still turn into quite the fiasco once 9.8 is released. Could the CLC make some more noise about it on all the usual channels?

**Comment by tomjaguarpaw** [comment]
Thanks for raising this @chreekat. Teo posted [a list of broken packages](https://gitlab.haskell.org/ghc/ghc/-/issues/23929#note_524000) on the GHC GitLab. @Bodigrim, do you have a suggestion about how to deal with this? I'm happy to volunteer to do something, if I know what it is that's best to do.

**Comment by TeofilC** [comment]
Note that afaict this change won't be coming until GHC 9.10.1, so there's a bit more time to get things fixed.
Eg, the changelog entry is in the base-4.20 section:
https://gitlab.haskell.org/ghc/ghc/-/commit/f1ec362817baa5d440a9f2b3a8b17e5513538119#392e9dfd3417e267d708c5ab16536f2994d43745_3_3

**Comment by chreekat** [comment]
Ah! That makes a lot of sense and reduces my concerns.

**Comment by chreekat** [comment]
> As for impact assessment, I've raised PRs to resolve name clashes to all affected Stackage packages (see links above) except [storablevector](https://hackage.haskell.org/package/storablevector), which does not seem to have a public issue tracker.

FYI I emailed Henning, and there is now a candidate release 0.2.13.2 of storablevector with a future-proofing patch.
