### ISSUE TITLE
Add role annotations to SNat, SChar and SSymbol

### ISSUE THREAD

**Issue by mpickering** [haskell/core-libraries-committee#170]
SNat, SChar and SSymbol were introduced to base by https://github.com/haskell/core-libraries-committee/issues/85 but are missing role annotations. This makes it possible to implement `unsafeCoerce` using this interface.

Adam Gundry provided this example on [#23454](https://gitlab.haskell.org/ghc/ghc/-/issues/23454) which demonstrates the problem:

```
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeFamilies #-}

module SNatBroken where

import Data.Coerce (coerce)
import Data.Kind (Type)
import Data.Type.Equality
import GHC.TypeNats

bogus :: forall a b . KnownNat a => a :~: b
bogus = case testEquality (SNat @a) (coerce (SNat @a) :: SNat b) of
          Just r  -> r
          Nothing -> error "bug fixed"

type G :: Nat -> Type -> Type -> Type
type family G n s t where
  G 0 s _ = s
  G _ _ t = t

newtype N n s t = MkN { unN :: G n s t }

oops :: forall b s t . N 0 s t -> N b s t
oops x = gcastWith (bogus @0 @b) x

unsafeCoerce :: s -> t
unsafeCoerce x = unN (oops @1 (MkN x))
```

Proposal: Add `type role SNat nominal` to prevent the unsafe coercion from `SNat a` to SNat b`.

Patch: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10583

**Comment by treeowl** [comment]
This is an obvious (and serious) bug. Does it even need a ticket here?

**Comment by treeowl** [comment]
Should `base` turn on the warning for missing role annotations? Or would it be possible to make a lint rule to complain about missing role annotations in modules importing `Unsafe.Coerce`?

**Comment by tomjaguarpaw** [comment]
Yikes. [The definition for `SNat`](https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/GHC/TypeNats.hs#L346) is

```.hs
newtype SNat (n :: Nat) = UnsafeSNat Natural
```

I'm not a user of `RoleAnnotations` but [it looks like](https://downloads.haskell.org/~ghc/8.4.3/docs/html/users_guide/glasgow_exts.html#role-annotations) GHC infers `n`'s role to be `phantom`  because it doesn't appear on the RHS (I'm not sure that inference is such a great idea). With the `phantom` role the [`unsafeCoerce` in `decNat`](https://gitlab.haskell.org/ghc/ghc/-/blob/b2c745db6a817993dcef03551243a2fd2b3ea756/libraries/base/GHC/TypeNats.hs#L257) is not safely encapsulated.

**Comment by simonpj** [comment]
> This is an obvious (and serious) bug. Does it even need a ticket here?

Yes it does.  It's a change to the API of `base`, and as such falls squarely in the CLC's remit

**Comment by Bodigrim** [comment]
This seems fairly unambiguous to me. Let's wait until tomorrow just in case and then vote.

**Comment by phadej** [comment]
> Should base turn on the warning for missing role annotations? 

There isn't such warning in released GHC.  I remember that hadrian didn't GHC conditionals well, but maybe it does now (https://gitlab.haskell.org/ghc/ghc/-/issues/17821 is closed, but the comments are not super convincing).

> Or would it be possible to make a lint rule to complain about missing role annotations in modules importing Unsafe.Coerce?

Did you mean `Data.Coerce`? Well, one could argue is that it what current Safe Haskell does. `Data.Coerce` is unsafe if someone forgets to annotate roles...

**Comment by treeowl** [comment]
@phadej 
> Did you mean `Data.Coerce`? Well, one could argue is that it what current Safe Haskell does. `Data.Coerce` is unsafe if someone forgets to annotate roles...

No, I meant `Unsafe.Coerce`. It wouldn't catch everything, but it's very common for a single module to define both a "fake GADT" that encodes type information in an efficient way and also functions and/or patterns that use it (with `unsafeCoerce` or similar). So if a module imports `Unsafe.Coerce` and also is missing a role annotation, that's more suspicious than usual.

**Comment by phadej** [comment]
@treeowl I see.

I guess something like that could make sense as GHC-build-system (i.e. its CI / testsuite) specific lint rule, but not as warning I'd like to see in GHC emit. If I do something suspicious in a library, I should be careful myself (and rely on compiler *guessing* when I'm going to do something like that.

In particular, `SNat` could be defined in a hidden module, and `decSNat` (which uses `unsafeCoerce`) only in another module, so an ad-hoc lint rule like you propose won't catch that.

IMO `-Wmissing-role-annotations` should make it way into `-Wall`, and `-XRoleAnnotations` into `-XGHC20xx`, as without role annotations it's hard to write correct code.

**Comment by treeowl** [comment]
@phadej I agree; it's a lint idea and not a warning one, as I suggested above. I don't know how big the impact of adding `-Wmissing-role-annotations` to `-Wall` might be. The vast majority of roles are inferred to be (at least) as conservative as desired.

**Comment by tomjaguarpaw** [comment]
> I'd argue if there were a new language with similar system, it should pick `nominal` roles as defaults, to error on the safest side.

Agreed. To me it makes sense to choose the safe default. Anyone who wants more power will soon be prompted to add the role, so not much would be lost.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add `type role {SNat,SChar,SSymbol} nominal` to prevent `coerce` from being able, for instance, to convert any `SNat a` to any `SNat b` and thus be used to implement a version of `unsafeCoerce` in a seemingly `Safe` code. The MR can be found at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10583.

@tomjaguarpaw @chshersh @mixphix @angerman @parsonsmatt @hasufell 

----

+1 from me. It seems to be an obvious oversight from the past: we absolutely do not want singletons to be automatically coercible to each another.

**Comment by chshersh** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, 6 votes out of 7 are enough to approve.
