### ISSUE TITLE
Improve documentation about opening discussions (non-proposals)

### ISSUE THREAD

**Issue by hasufell** [haskell/core-libraries-committee#173]
@adamgundry also indicated that it's not entirely clear that this issue tracker can also serve to discuss things and visions more generally, without a concrete proposal.

We should make clear in the README that these types of issues and discussions are welcome, but will not lead to an approval of any sort.

E.g.:

- user wants input on a general idea of base
- core/boot library maintainers want input regarding their package

**Comment by hasufell** [comment]
> Perhaps this is better suited for another medium, e.g. a CLC tag on Discourse?

I don't think we should require CLC members to monitor two platforms.

**Comment by adamgundry** [comment]
Thanks for filing this @hasufell. Another case I was wondering about is that of bugs/issues with `base` that are not expected to turn into a proposal in short order (e.g. general feature requests, or infelicities in the current code where the best way forward is not necessarily clear).  I'm not sure if it is appropriate to report such issues here and leave them open, or should the GHC issue tracker be used for such cases?

**Comment by hasufell** [comment]
> There're plenty of places where people can discuss abstract ideas without making concrete proposals

Sure, ideas can also start on the GHC issue tracker, but it sounds like a really bad contribution experience if the only time you get feedback from CLC is after you created a proper proposal with all bells and whistles.

It's not just the CLC that is volunteers. Potential base contributors are too.

**Comment by hasufell** [comment]
> It cannot possibly be that difficult to create a tag on the Discourse and have us members "subscribe" to it via RSS or some other means.

Also can't be difficult to use a tag on this repository.

**Comment by adamgundry** [comment]
@Bodigrim 

> If you know upfront that you do not actually have interest/bandwidth to work on a solution and just want file-and-forget, please use GHC bug tracker. This is documented in the template:

Thank you! This answers my question precisely. I hadn't seen it because it appears only after one decides to open a proposal issue. So I'd suggest adding this text or something like it to `README.md`.

**Comment by simonpj** [comment]
> I can get behind the sentiment that @Bodigrim expressed.
> ...

That sounds sensible to me.  Maybe a tag in the issue can distinguish *concrete proposals* (on which the CLC will ultimately vote) from "pre-proposal discussions".

I think it woudl be *really* helpful to turn the outcome of this thread (once agreed) into explicit guidance on the CLC home page.

**Comment by Bodigrim** [comment]
@hasufell is there anything left to do here? Would you like to make a PR?

**Comment by hasufell** [comment]
Yeah. I'm sick at the moment, so don't know when I get around it.

**Comment by tomjaguarpaw** [comment]
Hope you feel better soon @hasufell

**Comment by Bodigrim** [comment]
@hasufell let me close the issue just to get more breathing space, feel free to fire PR when you get time.
