### ISSUE TITLE
Make `read` accept binary integer notation

### ISSUE THREAD

**Issue by damhiya** [haskell/core-libraries-committee#177]
The `BinaryLiterals` extension, included in `GHC2021`, enables binary integer notation (a binary sequence prefixed by `0b` or `0B`), but the current implementation of `read` function rejects such input. I propose modifying the `read` function, along with `readEither` and `readMaybe`, to accept binary integer notation in order to maintain consistency with the `GHC2021` syntax.

related issue : https://gitlab.haskell.org/ghc/ghc/-/issues/23518
merge request : https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10680

**Comment by hasufell** [comment]
So you want `read` to accept this expression: `read @Integer "0b11001001"`.

Right now it seems the workaround is `read @Integer . show $ 0b11001001`.

What about octal or hexadecimal notation? It seems not accepted either.

**Comment by damhiya** [comment]
> So you want `read` to accept this expression: `read @Integer "0b11001001"`.
> 
> Right now it seems the workaround is `read @Integer . show $ 0b11001001`.
> 
> What about octal or hexadecimal notation? It seems not accepted either.

Octal and hexadecimal notations are accepted. Try this:
```hs
read "0x10" :: Int
```

**Comment by hasufell** [comment]
> > So you want `read` to accept this expression: `read @Integer "0b11001001"`.
> > 
> > Right now it seems the workaround is `read @Integer . show $ 0b11001001`.
> > 
> > What about octal or hexadecimal notation? It seems not accepted either.
> 
> Octal and hexadecimal notations are accepted. Try this:
> ```hs
> read "0x10" :: Int
> ```

You're right. I'm not sure why it didn't work the first time I tried.

In that case it seems an addition that makes things more consistent.

**Comment by damhiya** [comment]
Maybe you missed type annotation. `read "0x10"` gives no parse exception in ghci.

**Comment by tomjaguarpaw** [comment]
> Does GHCi use GHC2021 by default these days?

Yes, since 9.2:

```
% ghci-9.2
GHCi, version 9.2.4: https://www.haskell.org/ghc/  :? for help
ghci> 0b1
1
```

**Comment by damhiya** [comment]
Here is the fix : https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10680

**Comment by damhiya** [comment]
https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10680#note_505297
Oleg Grenrus informed me that `NumericUnderscores` and `HexFloatLiterals` are also included in `GHC2021`, and the current implementation of `read` does not support for these notational extensions.

Here, I am proposing a principle rather than a specific implementation change: to make the `Read` class consider every language extension related to literal syntax that is included in `GHC2021`. Following this principle, I suggest adding support for `BinaryIntegerLiterals`, `NumericUnderscores`, and `HexFloatLiterals` to `read`.

We have to modify definition of `Text.Read.Lex.Number` type to support 16-base if we accept `HexFloatLiterals`, but fortunately `Text.Read.Lex` does not export constructors of `Number` type so I think there is no problem.

**Comment by damhiya** [comment]
> > Here, I am proposing a principle rather than a specific implementation change: to make the `Read` class consider every language extension related to literal syntax that is included in `GHC2021`. Following this principle, I suggest adding support for `BinaryIntegerLiterals`, `NumericUnderscores`, and `HexFloatLiterals` to `read`.
> 
> Is it possible to actually reuse a parser used by GHC itself? Technically it's more likely to be vice versa: a parser in `ghc` package can reuse a parser from `base`. It would be nice to avoid accidental bugs.

I agree that this is ideal, but GHC's lexer is written in alex. I guess it will be hard to integrate them.

**Comment by damhiya** [comment]
> @damhiya I like the suggested principle, but I'm somewhat worried about arising complexity and an element of surprise. Current state of [`GHC.Read`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-Read.html#v:readNumber) is already underspecified. For instance, there is no documented semantics of `readNumber` at all.
> 
> Could you possibly provide a complete MR with improved documentation and added tests?

Sure! I'll work on it.

**Comment by damhiya** [comment]
Sorry for inactivity! I updated MR while it is still WIP.

**Comment by damhiya** [comment]
> @damhiya could you please add some tests to your MR? It's somewhat challenging to review without them.

I modified some test files.

**Comment by Bodigrim** [comment]
Dear CLC members, could you please share your (non-binding) opinions? Do you agree with the proposed principle in https://github.com/haskell/core-libraries-committee/issues/177#issuecomment-1595720774?
@hasufell @tomjaguarpaw @mixphix @chshersh @angerman @parsonsmatt

**Comment by hasufell** [comment]
The report doesn't seem to demand a specific implementation, so it seems ok.

I can imagine that additional accepted input can in fact lead to bugs (for people misusing read in parser code). So I'm not too excited, but will not block this proposal.

**Comment by tomjaguarpaw** [comment]
I'm cautiously supportive of the principle, but I wonder about "all" extensions. Theoretically there could be an extension that implies an absurd literal format. I think we'd want to reserve the right to not extend `Read` in that case.

**Comment by mixphix** [comment]
I'd certainly prefer to have all the `GHC2021` extensions' functionality supported, and to have that fact documented, than to depend runtime behaviour on the compile-time activation of extensions.

**Comment by parsonsmatt** [comment]
hmmm

`Read`, alone, has little to go on. The informal guidance that `Show` should produce valid Haskell code, and that `Read` should work on the output of `Show` is great. But this takes it a little farther - that `Read` should work on any literal means of constructing a value in question. I am hesitant about this new understanding of `Read`.

Let's consider a record datatype:

```haskell
data X = X { x :: Int, y :: Char }
    deriving (Show, Read)
```

There are many ways of constructing this with valid Haskell syntax.

```haskell
x0 = X { x = 1, y = 'c' }
x1 = X { y = 'c', x = 1 }
x2 = X 1 'c'
```

`x0` is what you get if you call `show` on any of those values. `read` will accept `x0`, and also `x0` with whitespace added anywhere in the string - so it is already slightly more lax than "`Read` only accepts the output of `Show`." However, it will accept neither `x1` nor `x2`. So there is some prior art to not accepting valid Haskell syntax *that isn't the output of `Show`*.

Consider `Map Int Char`. If you `show` one, you'll get `"fromList [(1, 'c')]"`. And you can `read "fromList [(1, 'c')]" :: Map Int Char` which parses successfully. You can also construct a `Map Int Char` with `singleton 1 'c'`, which will fail to `Read`.

If we make this change to `Read`, does it imply further changes to other datatypes and instance? If so, what are they? If not, what's the guiding principle that we can use to know?

**Comment by mixphix** [comment]
The docs for `GHC.Read` only make assumptions for *derived* instances:

```hs

-- | Parsing of 'String's, producing values.
--
-- Derived instances of 'Read' make the following assumptions, which
-- derived instances of 'Text.Show.Show' obey:
--
-- * If the constructor is defined to be an infix operator, then the
--   derived 'Read' instance will parse only infix applications of
--   the constructor (not the prefix form).
--
-- * Associativity is not used to reduce the occurrence of parentheses,
--   although precedence may be.
--
-- * If the constructor is defined using record syntax, the derived 'Read'
--   will parse only the record-syntax form, and furthermore, the fields
--   must be given in the same order as the original declaration.
--
-- * The derived 'Read' instance allows arbitrary Haskell whitespace
--   between tokens of the input string.  Extra parentheses are also
--   allowed.
```

Since `Int`'s instance of `Read` is [not derived](https://hackage.haskell.org/package/base-4.18.0.0/docs/src/GHC.Read.html#line-586), I think it's a fairly localized change that need not affect the typical interpretation of `Read`.

**Comment by damhiya** [comment]
> If we make this change to Read, does it imply further changes to other datatypes and instance? If so, what are they? If not, what's the guiding principle that we can use to know?

If we accept this proposal, then the set of accepted inputs will change even for non-numeric types. e.g. `fromList [(1_0, 'a')] :: Map Int Char`. However, it only affects the lexical level and does not change the set of accepted parse trees (If we does not distinguish different kinds of numeric literals at the token level).

I believe this could serve as a guideline for determining whether to accept a new syntactic extension or not. If an extension only impacts the lexical level, then I think it generally acceptable. Conversely, if an extension alters the set of accepted parse trees, I believe further discussion is required.

**Comment by chshersh** [comment]
The code in the MR is a bit difficult to review with lots of changes. But I trust the exhaustive test suite.

However, looks like the MR also changes `read` to support `NumericUnderscores` while this proposal talks only about binary literals. I believe, it would be fair to change the title of this CLC proposal and the title of MR to reflect this important implementation detail.

<hr/>

Generally, I don't mind, I value consistency. But I'd rather see a more efficient parsing mechanism to be developed instead of encouraging more usages of `Read`.

**Comment by Bodigrim** [comment]
@damhiya first of all, I'm terribly sorry for dropping the ball for so long.

The existing semantics of `read :: String -> Int` is not arbitary, it was designed to match [`strtol`](https://cplusplus.com/reference/cstdlib/strtol/) (for `base = 0`). Is extending it to cover binary numbers a good idea? At least several other languages do so, including [OCaml](https://v2.ocaml.org/api/Stdlib.html#VALint_of_string_opt) and JavaScript:

```js
> Number("0x123")
291
> Number("0o123")
83
> Number("0b101")
5 
```

Given that GHC2021 accepts numeric literals in all three forms (thus we improve consistency), I'm in favor of such change.

----

I'm however negative on the rest of the proposal, which suggests to extend accepted syntaxes of `read :: String -> Int` any further. Semantic changes are the worst. 

It's easy to imagine an ~~Comma~~ Underscore Separated Value format, whose parsing is completely broken by ignoring underscores between digits, as `{-# LANGUAGE NumericUnderscores #-}` demands. If in future `{-# LANGUAGE NumDecimals #-}` becomes a part of GHC20XX and `read :: String -> Int` is made to support it, we'll get into a huge trouble breaking a ton of parsers for `Double`. And we also open a way to DDoS attack by supplying arbitrarily huge exponents, as discussed recently.

In my opinion going anywhere beyond supporting binary numbers a) violates the principle of least astonishment, b) exposes us to semantic breakage and vulnerabilities. 

If other CLC members are in favor of the extended proposal, I strongly encourage them to conduct a technical review of changes in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10680/diffs and report back that there are no vulnerabilities / bugs / loops **before** we go for a vote.

**Comment by damhiya** [comment]
@Bodigrim's point out about numeric underscores seems appropriate to me. In that case, I agree that we should not accept `NumericUnderscores` while I have no opinion about `HexFloatLiterals` on my own because I know nothing about security.

I'll remove changes related to these extensions if we have a consensus about it.

**Comment by Bodigrim** [comment]
@damhiya I suggest we vote first on extending `read` to binary literals only. It would be nice if you can prepare a comparison of `read` semantics with other languages: which of them parse binary notation in a standard `string -> int` function?

If it passes and you have an appetite for further extensions, they can be voted separately.

**Comment by Bodigrim** [comment]
> I'll remove changes related to these extensions if we have a consensus about it.

@damhiya did you get a change to update the proposal and the MR? If there is no progress by the end of January, I'll close as abandoned.

**Comment by damhiya** [comment]
> > I'll remove changes related to these extensions if we have a consensus about it.
> 
> @damhiya did you get a change to update the proposal and the MR? If there is no progress by the end of January, I'll close as abandoned.

I'm sorry for being late. I updated the MR based on feedbacks.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to make `read` accept not only decimal, hexadecimal and octal notations, but also a binary one. Currently
```haskell
> map read ["123", "0x123", "0o123"] :: [Int]
[123,291,83]
```
but 
```haskell
> read "0b101" :: Int
*** Exception: Prelude.read: no parse
```

The motivation is to increase consistency with Haskell integer literal syntax, which starting from `GHC2021` allows all four forms:
```haskell
> [123, 0x123, 0o123, 0b101] :: [Int]
[123,291,83,5]
```

The implementation is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10680/diffs

@tomjaguarpaw @hasufell @parsonsmatt @angerman @velveteer @mixphix

**Comment by parsonsmatt** [comment]
+1

**Comment by hasufell** [comment]
It doesn't look like there's an impact assessment or a possible migration path (as demanded by @angerman )?

How is this change deployed?

**Comment by Bodigrim** [comment]
I'm confused. How would one imagine an impact assessment or a migration path here?

**Comment by hasufell** [comment]
> I'm confused. How would one imagine an impact assessment or a migration path here?

Impact assessment: Running test suites. 

Migration path: a generic compiler warning (with our new warning classes that can be disabled) when using read with e.g. `Int` and a way to opt out of the behavior through e.g. a language pragma.

**Comment by damhiya** [comment]
@hasufell I thought that I ran required test suites (https://gitlab.haskell.org/damhiya/ghc/-/pipelines/88881). Do you mean impact assessment for the real world code base e.g. the Hackage?

For migration path, I think providing a way to opt out of the behavior is not appropriate, since the change is made on the `base` library rather than the language. I agree that giving a compiler warning might be good, but is there a way to enable warning for every instances that affected by this change? For example, I think we need to enable warnings for `Read Int`, `Read [Int]`, `Read [[Int]]`, `Read (Maybe Int)`, ... etc

**Comment by hasufell** [comment]
> Do you mean impact assessment for the real world code base e.g. the Hackage?

Yes, a selection of packages.

> For migration path, I think providing a way to opt out of the behavior is not appropriate

Well, changing behavior of instances is generally a difficult thing. If we emit an unconditional warning, the `-Werror` fraction will hunt us down (should warnings be used for informing about upcoming semantic changes? This is a debate on principles of warnings). If we just change it, the stability fraction will be pissed off. Opting out isn't particularly elegant. 

So what does that leave us with?

It probably means I will vote Nay, I guess.

**Comment by tomjaguarpaw** [comment]
In general changing the behaviour of instances is risky, but I don't see the risk in this particular case. Could users currently be relying on the failure of attempts to parse binary literals?

**Comment by hasufell** [comment]
> Could users currently be relying on the failure of attempts to parse binary literals?

In backtracking parsers, this is very well possible.

**Comment by tomjaguarpaw** [comment]
OK, can we flesh that out with more details? Perhaps there is a case where someone is writing a parser including a numeric literal format, and they want it to be *exactly* the same format that `read` currently accepts, but by coincidence rather than because they want to accept new literals that GHC accepts when it changes to accept them?

**Comment by hasufell** [comment]
Yes, if you accept more input, you're potentially breaking `try parser1 <|> parser2`

**Comment by tomjaguarpaw** [comment]
Agreed, I'm just struggling to think of a real world use case where that change in behaviour is actually undesirable.

**Comment by tomjaguarpaw** [comment]
+1

----

Oh, and here's my vote ^

**Comment by VitWW** [comment]
Alternative is not to change default behavior of `Read`, but to create several modules for each primitive type with newtypes with different `Read`/`Show` strategies:
```haskell
module Data.Read.Int (...) where

  -- read digits only in base-10 without sign
  newtype IntDecUnsgn = MkIntDecUnsgn {fromIntDecUnsgn :: Int} deriving ...
  instance Read IntDecUnsgn where ...
  instance Show IntDecUnsgn where ...

  newtype IntDecOneSgn =  ...  -- read digits only in base-10 and maybe "-"
  newtype IntDecBothSgn =  ... -- read digits only in base-10 and maybe "-", "+"

  newtype IntDecUnsgnUndersc = ...  -- read digits only in base-10 and underscore

  newtype IntDecOct =  ...        -- read in base-10 and base-8
  newtype IntHex =  ...           -- read in base-16
  newtype IntHexDecOct =  ...     -- read in base-16, base-10 and base-8
  newtype IntHexDecOctBin =  ...  -- read in base-16, base-10, base-8 and base-2
  ...
```

This is verbose, but this give a huge freedom to use

**Comment by damhiya** [comment]
> Alternative is not to change default behavior of Read, but to create several modules for each primitive type with newtypes with different Read/Show strategies:

The purpose of this proposal was improving the consistency between GHC's literal syntax and the behavior of `Read` class, rather than providing more freedom/flexibility. When such advanced functionalities are needed, we can just use custom lexer/parser libraries such as parsec, alex, happy, ... etc.

**Comment by hasufell** [comment]
> When such advanced functionalities are needed, we can just use custom lexer/parser libraries such as parsec, alex, happy

You're making assumptions about how people use the Read class. That's not a good strategy to develop an intuition about how much code you might break.

**Comment by damhiya** [comment]
@hasufell Thanks for pointing out. Of course, someone may use `Read` class for customized parsing. But I think the current agenda is a trade-off between consistency and backward compatibility, rather than functionality. Please interpret that comment as a caution against expanding the discourse further. Maybe I should rephrase my comment as: "When such advanced functionalities are needed, users can add their custom `Read` instances, or use community lexer/parser libraries such as parsec, alex, happy, ... etc"

**Comment by angerman** [comment]
Don't we have CLC Stackage? Has this change been run against CLC Stackage? is there any fall out when running the tests?
There must be some way to smoke test this change?

**Comment by damhiya** [comment]
@angerman I haven't heard about CLC Stackage, and this change has never been tested against such a real-world codebase yet.

How can I run such test?

**Comment by Bodigrim** [comment]
`clc-stackage` does not allow to run tests, only build packages. If anyone knows an ergonomic, relatively straightforward way to execute tests, it would be most welcome. But last time we enquired there was none.

**Comment by Bodigrim** [comment]
> Perhaps there is a case where someone is writing a parser including a numeric literal format, and they want it to be _exactly_ the same format that `read` currently accepts, but by coincidence rather than because they want to accept new literals that GHC accepts when it changes to accept them?

For starters, very few clients use `class Read` to implement parsers. And `instance Read Int` never specified which formats are acceptable. So presumably a client does not use `parsec` / `attoparsec` / `megaparsec` and somehow consciously uses a fact that `read` parses decimal, hexadecimal and octal, but not binary numbers, and relies on it to a degree that such relaxation would cause ambiguous parsing. I find such scenario rather implausible.

**Comment by Bodigrim** [comment]
@mixphix @velveteer just a gentle reminder to vote.

**Comment by velveteer** [comment]
I'm in favor of consistency, but I also agree the principle here is a slippery slope. I cautiously support this change, if only because GHC2021 is thrust upon us in GHCi.

+1

**Comment by hasufell** [comment]
> For starters, very few clients use class Read to implement parsers. 

optparse-applicative does, which is rather widely used: https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative.html#v:auto

> I find such scenario rather implausible.

I agree, but I also find that proposals need to do more proper work to evaluate ecosystem impact. This is not enough. It's the standard library and typeclass changes have proven to be delicate in the past.

I don't trust anyone's intuition on this one.

**Comment by angerman** [comment]
Without any evidence that this does not lead to surprising behavior I do not feel like I can support this proposal. If such evidence is furnished, I'm happy to support this change. Until then I am against it out of caution.

**Comment by tomjaguarpaw** [comment]
I don't see how any test for this, in principle, breaking change could be carried out. Surely no test suite *specifically* tests that `read`ing binary literals fails? Surely no production code depends upon `read`ing of binary literals failing?

**Comment by VitWW** [comment]
> For starters, very few clients use `class Read` to implement parsers

Just for clarification: sure, to extract data from (usually) complicated an (usually) compacted data (like JSON, serialized, ...) parsers are used. 
But for just extracting data from **inputs**, yes, `Read` is used.
```
> How old are you?
0x2D

> How many siblings do you have?
0b11
```

P.S. Since `Read Int` is already support Hex-format and Oct-format, supporting Bin-format sounds good

**Comment by tomjaguarpaw** [comment]
Perhaps it would help if I explained in more detail my rationale for voting in favour of this change.

The benefit of the change is that it moves the behaviour of `read` closer to one conventionally-accepted meaning of the `Read` class: that it parses Haskell literal and constructor syntax. Admittedly, this benefit is complicated by the fact that parsing of binary literals is behind an extension, albeit one that will likely be enabled in all `Haskell...` or `GHC...` `default-language` sets going forward.

So, it seems like a pleasant benefit although not a critical one. It's also a breaking change. Is the cost of the breakage worth paying to obtain this pleasant benefit?

My estimate is that, yes, it is. I've made this estimate based on my personal judgement, not by running a test suite. Indeed, I don't recall that the CLC has ever insisted a test suite be run on a proposal before. Has it? The CLC recently approved [a proposal that changes an error message](https://github.com/haskell/core-libraries-committee/issues/237#issue-2067786992). That was also technically a breaking change, but we didn't run a test suite before approving it, nor did we anticipate any real world problems being caused by that change. I don't yet see why this proposal should be treated differently.

Furthermore, a passing test suite would not increase my confidence that this change would not cause problems in practice. The only way a test suite could pick up this change is if it _specifically_ has a test that binary literals fail to parse. I strongly doubt there is such a test in the Haskell ecosystem.

So, given that I doubt there is any failing test to trigger, and I wouldn't trust a passing test suite, what options do I have? Only to use my judgement about the kind of code that is written using `read` in practice. I find it hard to imagine any use case where decimal, hex and octal integer literals are to be accepted but binary literals must be rejected. I think that use of judgement is the best I can do, for the reasons explained above.

On the other hand, if we can find a convenient way of running CLC proposals against a representative test suite, I would be in favour of that.

I hope that helps.

**Comment by Abastro** [comment]
Wouldn't this add inconsistencies between whether `BinaryLiterals` extension is enabled or not?
What if one with it enabled depends on the other with it disabled, and the inconsistency causes footguns?
This does not seems like simple breakage issues to me, it can stick around indefinitely as long as there is someone not using `BinaryLiterals` extension - which, I think, should be pretty likely.

**Comment by Bodigrim** [comment]
> I'm sympathetic to this change. I find it hard to judge the risk of breaking existing code with such a change. Do we have any guidance on this? Was a smoke test done?

I tested all boot libraries + `optparse-applicative`, there are no regressions. 

> > For starters, very few clients use class Read to implement parsers.
> 
> optparse-applicative does, which is rather widely used: https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative.html#v:auto

Not quite, `optparse-applicative` uses `read`, but does not construct parsers by combining `reads` / `ReadP`. The effect of the proposal on `read` itself is benign: parsing becomes more permissive. 

> I don't see how any test for this, in principle, breaking change could be carried out. Surely no test suite _specifically_ tests that `read`ing binary literals fails? Surely no production code depends upon `read`ing of binary literals failing?

A problematic case would be parsing a regular language `[0-9]+b[0-9]+` using `reads`: 

```haskell
do 
  (x, xs') <- reads xs 
  ('b', xs'') <- reads xs' 
  (y, xs''') <- reads xs''
  pure (x, y)
```

Now if `reads` accepts binary notation as well, parsing might get ambiguous. But one can argue that this code is broken to begin with: `reads :: String -> [(String, Int)]` parses not `[0-9]+` but a much more complex and - more importantly - unspecified regular language. Accounting for the fact that using `reads` in such way is quite rare in practice and the fact that `[0-9]+b[0-9]+` is a weird regexp to parse, I'd say that potential consequences are negligible. 

----

I realised that I did not post my own vote. I'm +1 on the proposal, which means that there are enough votes to approve. Thanks all and sorry that it took so long. 

@damhiya could you please rebase the MR, add changelog, link the proposal from commit message and ping me once ready?
