### ISSUE TITLE
Change derived Show for unlifted fields

### ISSUE THREAD

**Issue by monoidal** [haskell/core-libraries-committee#183]
I would like to change the behavior of `deriving Show` behavior for datatypes containing a field of one of the types `{Int,Word}{8,16,32}#`.

I have submitted this as a GHC proposal https://github.com/ghc-proposals/ghc-proposals/pull/596, which contains more details.

This does not change any existing instances in `base`. I'm not sure whether this is within CLC's scope, but I'm submitting this here as suggested on the GHC proposal.

**Comment by nomeata** [comment]
Thanks for raising this. We weren't sure about whether this is in scope, but thought we'd better ask than guess. If you think it is, we can turn it into a proper proposal to vote on.

**Comment by mixphix** [comment]
These are indeed exported from `base:GHC.Exts`, so they are part of the `base` API. In fact @chessai had raised the (now abandoned) proposal #156 to export these types from the Prelude.

That being said, here is my initial assessment: This does not require the language extension `-XExtendedLiterals` (available in GHC 9.8 and later), as it only affects the output string. In my view the new output is clearer, but my concern lies in re-`Read`ing such strings in light of [moving toward a reinstallable `base`](https://github.com/haskellfoundation/tech-proposals/pull/51).

**Comment by nomeata** [comment]
The types are part of base, but the `Show` instances that would change are not: These types are unboxed, so they don’t have a `Show` instance themselves. The change only affects data types that have a `Word8#` etc. _field_ and derive a show instance.

So unless you consider “the semantics of `deriving Show`” part of `base`, there is indeed no change to `base`.

Also worth noting: GHC doesn’t support `deriving Read` for such data types.

**Comment by mixphix** [comment]
> The change only affects data types that have a Word8# etc. field and derive a show instance.

You mean to say that the behaviour of types that rely on data provided from `base` will change? Sounds like an API change to me. 🤔

> GHC doesn’t support deriving Read for such data types.

Thank you, this settles my worry.

**Comment by nomeata** [comment]
> You mean to say that the behaviour of types that rely on data provided from base will change? Sounds like an API change to me. 

Well, that’s the question we put forward to the CLC: Do you consider the behavior of `deriving Show` to be part of the `base` API or it a GHC feature outside the CLC’s scope?

(In a very technical sense, `base`-the-library certainly doesn't change; its `.hs`, `.so` and `.hi` files file is identical with or without this change. But that shouldn’t stop us from consulting the CLC.)

**Comment by mixphix** [comment]
It's a curious case. My personal opinion, given that `base` is the conduit through which the vast majority of developers access these machine types GHC uses to compile their own programs, is that all aspects of their *user-observable* behaviour should be considered as part of the "`base` API". But then, is performance "user-observable" in that sense? I would argue that it is not: this change made to `deriving Show` is one that breaks the extensional equivalence of the function-prior-to-the-change and the function-after-the-change, but one that simply made it slower would still be "extensionally equal".

**Comment by simonpj** [comment]
I'm not sure we need a definitive boundary here.  The principle is that if in doubt we should consult CLC, who will (and do) respond in a timely and constructive way, possibly saying "none of our business", possibly expressing an opinion, etc.  

(FWIW my sense is that this particular one is out of scope, but I recommended consultation with CLC.)

Returning to the particular case, this issue is only one day old.  In due course it'd be great to have a consensus CLC opinion about wether you are happy with the change.

**Comment by nomeata** [comment]
Thanks for the swift feedback! (I think this can be closed then.)

**Comment by monoidal** [comment]
Unless there are objections, I will close this in 3 days.
