### ISSUE TITLE
MonadFix :+: instance for GHC Generics

### ISSUE THREAD

**Issue by Mathnerd314** [haskell/core-libraries-committee#185]
## Motivation

I was reading Control.Monad.Fix in base and noticed that there was no instance for `:+:`. But there are instances for several concrete sum types like Maybe, Either, and [], so there doesn't seem to be a reason to omit it. 

## Proposal

As noted in [Erkok's thesis](https://leventerkok.github.io/papers/erkok-thesis.pdf), Remark 2.6.4, for any monad based on a sum type, f of bottom determines the top level structure of `mfix f`. Erkok in fact provides an alternative `MonadFix Maybe` instance based on pattern-matching `f undefined` (eqn 4.3). My proposed instance for :+: is thus along the same lines:
```Haskell
instance (MonadFix f, MonadFix g) => MonadFix (f :+: g) where 
  mfix f = case f undefined of
   L1 _ -> L1 $ mfix (\x -> case f x of L1 y -> y)
   R1 _ -> R1 $ mfix (\x -> case f x of R1 y -> y)
```

There doesn't seem to be a testsuite for MonadFix but a few examples show that my instance works similarly to the existing instances:
```Haskell
f, f2, f3 :: [Integer] -> Maybe [Integer]
f = const Nothing
f2 = \x -> Just (take 100 (1:x))
f3 = Just
test f = mfix f == to1 (mfix (from1 . f))
main = print [test f, test f2, test f3] -- [True,True,<infinite loop>]
```

It was a little tricky to test it due to the `Monad` constraint on MonadFix and the lack of a `Monad (f :+: g)` instance. Perhaps the difficulty arises from deciding how to implement `pure` for `f :+: g`? I think most people would be happy with an instance that was right-biased like Either, `pure = R1 . pure`. Or the instance could have a constraint `instance (MonadFix f, MonadFix g, Monad (f :+: g)) => MonadFix (f :+: g)` with `UndecidableInstances` and leave it to the user to write an instance.

**Comment by Mathnerd314** [comment]
I think first I'll expand the proposal a little to be more thorough, before I set up a MR. I'd rather do one proposal that gets all the instances than have to file more proposals. 

So, currently in GHC.Generics in [base-4.18](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-Generics.html), it looks like there are 11 types that implement Functor: `V1, U1, Par1, Rec1, K1, M1, :+:, :*:, :.:, URec, Generically1`. Of these, the types that currently have MonadFix instances are `Par1, Rec1, M1, :*:`. Of the remaining:

* `:+:` has been discussed so far, it seems the `pure = R1 . pure` Monad instance is fine and there's no issue with my MonadFix instance either.
* `V1` can't have a non-bottom `pure` implementation, probably it should remain without Applicative/Monad/MonadFix instances.
* `U1` seems like it can be implemented easily along the lines of `everything = U1`. Such an instance being useful along with `:+:` and `:*:`.
* `K1` has an Applicative instance `pure _ = K1 mempty`, this should be extendable to a monad instance `(K1 c) >>= f = K1 c`, and similarly a MonadFix instance `mfix f = f undefined`.  I think these are the only valid instances since for example `(K1 c :: K1 Void) >>= \(_ -> absurd)` cannot really do anything else.
* URec is basically K1, seems like it can be instanced similarly.
* `:.:` has an Applicative instance but there is no obvious way to implement `join : f (g (f (g x))) -> f (g x)`, seems fine to skip it
* `Generically1 = forall {k} f a. f a -> Generically1 @k f a`  is a weird type, I am not familiar with it, I guess it was only added recently, but looking at the existing instances it seems like the instances just convert with `to1/from1`. This Monad instance typechecks:
```Haskell
instance (Generic1 f, Monad (Rep1 f)) => Monad (Generically1 f) where
  (Generically1 a) >>= f = Generically1 . to1 $ from1 a >>= (\x -> case f x of Generically1 a -> from1 a)
```
There is a similar MonadFix instance. I guess all typeclasses in base should have wrapping Generically / Generically1 instances like that?

**Comment by phadej** [comment]
`K1` is `Const` which cannot have valid `Monad` instance. 

I'm also sceptical that `:+:` can have lawful `Monad` instance (otherwise `Data.Functor.Sum` would had it). Please show `>>=` implementation and lawfulness if you think the instance exists.

`:.:` is `Compose`, and `Monad`s don't compose, so there isn't `Monad` instance either.

**Comment by Mathnerd314** [comment]
Well I was thinking something like this:
```Haskell
instance (Monad f, Monad g) => Monad (f :+: g) where
  L1 l >>= f = L1 $ l >>= (\x -> case f x of L1 y -> y)
  R1 r >>= f = R1 $ r >>= (\x -> case f x of R1 y -> y)
```
But I guess it fails for the same reason as K1, if `f` returns L1 then `return a >>= f` is undefined rather than being `f a`. I guess we would have to rely on the UndecidableInstances method then and require instances for specific types. But it is probably not worth it.

**Comment by Bodigrim** [comment]
@Mathnerd314 what are the next steps? Are you interested to proceed with the proposal further?

**Comment by Mathnerd314** [comment]
I guess :+: is not a monad, so there's no MonadFix instance either. I guess U1 has a valid instance but it's not much use. So the proposal can be closed.
