### ISSUE TITLE
Use native operations for `Enum Int64` and `Enum Word64` on 32-bit platforms

### ISSUE THREAD

**Issue by noughtmare** [haskell/core-libraries-committee#187]
### Situation

Currently, the instances `Enum Int64` and `Enum Word64` conditionally compile like this:

```haskell
#if WORD_SIZE_IN_BITS < 64
    -- See Note [Stable Unfolding for list producers] in GHC.Enum
    {-# INLINE enumFrom #-}
    enumFrom            = integralEnumFrom
    -- See Note [Stable Unfolding for list producers] in GHC.Enum
    {-# INLINE enumFromThen #-}
    enumFromThen        = integralEnumFromThen
    -- See Note [Stable Unfolding for list producers] in GHC.Enum
    {-# INLINE enumFromTo #-}
    enumFromTo          = integralEnumFromTo
    -- See Note [Stable Unfolding for list producers] in GHC.Enum
    {-# INLINE enumFromThenTo #-}
    enumFromThenTo      = integralEnumFromThenTo
#else
    -- See Note [Stable Unfolding for list producers] in GHC.Enum
    {-# INLINE enumFrom #-}
    enumFrom            = boundedEnumFrom
    -- See Note [Stable Unfolding for list producers] in GHC.Enum
    {-# INLINE enumFromThen #-}
    enumFromThen        = boundedEnumFromThen
#endif
```

So, it uses a slow `Integer`-based fallback on 32-bit platforms.

### Motivation

Now two things have happened that might make use reevaluate this decision:

* GHC is getting a JavaScript back end which uses 32-bit words.
* I have recently implemented code generation for 64-bit operations in the i386 back end ([!10771](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10771)).

So 32-bit platforms will become more common and there is now more performance to gain on i386.

### Concrete Changes

I propose to write custom `Enum Int64` and `Enum Word64` instances that use native operations instead of falling back to `Integer`-based operations. Essentially, this means copying the implementation of `Enum Int` and `Enum Word` and replacing all occurrences of `Int` with `Int64` and the same for `Word`.

### Implementation

I've already implemented the required changes in [!10825](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10825).

### Impact

This is purely a performance change. I expect it will almost always have a positive impact on performance, but it might cause things to inline differently. I have done benchmarks for [i386 which shows a 1.5x performance improvement](https://github.com/haskell/core-libraries-committee/issues/187#issuecomment-1628895010) and also for [JS which shows a 5.6x performance improvement](https://github.com/haskell/core-libraries-committee/issues/187#issuecomment-1637560782).

One other impact is that this adds a bit of maintenance burden on the GHC developers. [But this part of the code has been very stable, so we don't expect this to be a problem.](https://github.com/haskell/core-libraries-committee/issues/187#issuecomment-1628869472)

### Alternatives

1. Keep status quo. This means bad performance.

2. Reduce duplication using `CPP` trickery. This makes it harder to navigate the source code.

**Comment by hasufell** [comment]
> I have done no benchmarks yet.

Please do. It sounds exciting. 

> One other impact is that this adds maintenance burden on the GHC developers.

Do GHC devs have concerns?

**Comment by noughtmare** [comment]
> Please do. It sounds exciting.

@hsyl20 can you run some benchmarks with the JS back end? I can run benchmarks for i386.

> Do GHC devs have concerns?

I'll ask.

**Comment by bgamari** [comment]
> Do GHC devs have concerns?

No, these instances are extremely stable. The maintenance burden should be negligible. In my opinion this change is long overdue.

**Comment by noughtmare** [comment]
Rough benchmark results on i386:

```haskell
-- Bench.hs
import Data.Word

main = print (sum [1..123456789 :: Word64])
```

Compiled with:

```
$ _build/stage1/bin/ghc -O2 Bench.hs
```

Before:

```
$ /usr/bin/time -v ./Bench
7620789436823655
	Command being timed: "./Bench"
	User time (seconds): 0.51
	System time (seconds): 0.00
	Percent of CPU this job got: 100%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.51
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 7376
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 1191
	Voluntary context switches: 54
	Involuntary context switches: 20
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

After:

```
$ /usr/bin/time -v ./Bench
7620789436823655
	Command being timed: "./Bench"
	User time (seconds): 0.34
	System time (seconds): 0.00
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.34
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 3376
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 158
	Voluntary context switches: 36
	Involuntary context switches: 17
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

So about 1.5x faster, or 33% less running time if you prefer.

**Comment by noughtmare** [comment]
I've tried benchmarking the JS backend myself, but I'm actually seeing a regression:

```haskell
-- Bench.hs
import Data.Word

main = print (sum [1..12345678 :: Word64])
```

Before:

```
$ hyperfine ./Bench_before
Benchmark 1: ./Bench_before
  Time (mean ± σ):      4.809 s ±  0.038 s    [User: 4.819 s, System: 0.019 s]
  Range (min … max):    4.738 s …  4.854 s    10 runs
```

```
$ hyperfine ./Bench
Benchmark 1: ./Bench
  Time (mean ± σ):      6.432 s ±  0.938 s    [User: 6.454 s, System: 0.034 s]
  Range (min … max):    5.773 s …  8.986 s    10 runs
```

@hsyl20 can you help figuring out what's going on here?

**Comment by noughtmare** [comment]
@hsyl20 has written improved code generation for 64 bit addition and now we get much better times:

```
$ hyperfine ./Bench
Benchmark 1: ./Bench
  Time (mean ± σ):     243.9 ms ±   0.7 ms    [User: 231.9 ms, System: 18.8 ms]
  Range (min … max):   243.0 ms … 245.3 ms    12 runs
```

**Comment by hsyl20** [comment]
Thanks for the benchmarks (and the patch!) @noughtmare!

**Comment by noughtmare** [comment]
@hasufell I think this is ready for review by the committee.

**Comment by noughtmare** [comment]
@Bodigrim I don't know actually; I'll check. However, the code in my MR is a pretty direct copy of the Enum instance of Word [1] and Int respectively. Diffing against that would make the review easier.

[1] https://gitlab.haskell.org/ghc/ghc/-/blob/a7349217fb9a992ad1c0e0d6ce1ab78e29dbe144/libraries/base/GHC/Enum.hs#L736

**Comment by noughtmare** [comment]
@Bodigrim I think there is sufficient test coverage:

* Int64: https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/tests/enum02.hs#L194
* Word64: https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/tests/enum03.hs#L197

In fact, I just remembered these test caught an issue with the `Enum Int64` instance, which I have now fixed.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to implement `instance Enum Int64` and `instance Enum Word64` that use native operations on all platforms instead of falling back to `Integer`-based ones. This has positive performance impact: 1.5x faster for `i386` backend and 5.6x faster for JavaScript backend. The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10825. The change is somewhat technically involved, but is closely derived from existing `instance Enum {Int,Word}` and covered with tests. 

@tomjaguarpaw @chshersh @hasufell @angerman @parsonsmatt @mixphix 

----

+1 from me.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by mixphix** [comment]
+1

**Comment by chshersh** [comment]
+1

<hr/>

Always happy to see performance improvements!

**Comment by parsonsmatt** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, 5 votes are enough to approve.
