### ISSUE TITLE
Proposal: rename Data.ByteArray to Data.Array.ByteArray

### ISSUE THREAD

**Issue by Bodigrim** [haskell/core-libraries-committee#19]
MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6742

Currently unreleased `base` HEAD contains a new `Data.ByteArray` module. It's been [noticed](https://gitlab.haskell.org/ghc/ghc/-/issues/20044#note_372506) that this is an unfortunate naming, because it clashes with [`memory`](https://hackage.haskell.org/package/memory-0.16.0/docs/Data-ByteArray.html) and thus has a potential to break any of its [203](https://packdeps.haskellers.com/reverse/memory) downstream dependencies. 

The proposal is to rename it to `Data.Array.ByteArray`: `Data.Array` is a well-attested namespace (e. g., in [`array`](https://hackage.haskell.org/package/array)), and `Data.Array.ByteArray` is currently [unused](https://hackage-search.serokell.io/?q=Data.Array.ByteArray).

Additionally, the MR adds `{-# LANGUAGE Trustworthy #-}`, because otherwise `deepseq` has to resort to pretty [nasty hacks](https://github.com/haskell/deepseq/pull/65/files) to provide `instance NFData`.

This is unfortunately a rather pressing matter, because `deepseq`, `bytestring` and `text` need to adopt asap. Since the impact on ecosystem is positive (less packages will be broken than with status quo) and GHC MR was open for a long time, I hope this does not require prolonged deliberations.

**Comment by chessai** [comment]
Based on the breakage, I say we change the name. I don't like the proposed name, but I don't dislike it either. I don't think we should put _too much_ thought into the name, though.

So I'm +1

**Comment by konsumlamm** [comment]
What if we eventually want to add other kinds of arrays to `base`, like normal `Array`s (cf [`Data.Primitive.Array`](https://hackage.haskell.org/package/primitive/docs/Data-Primitive-Array.html))? Would that module be called `Data.Array.Array` then (`Data.Array` is already used by `array`)? That would sound pretty silly imo. Or will that just never happen?

If `PrimMonad` should eventually be moved to `base`, stealing `Data.Primitive._` from `primitive` might work...

**Comment by Bodigrim** [comment]
@konsumlamm there are currently no plans to move more parts of `primitive` to `base`, and I see little incentive to do so. Note that while `Data.ByteArray` was derived from `Data.Primitive.ByteArray`, it could have been also based on `Data.ByteString.Short` or `Data.Text.Array`. There is nothing `primitive`-specific, it is just a boxed `ByteArray#`.

**Comment by gwils** [comment]
+1, let's avoid that breakage and keep things moving. I find the name to be ugly, but acceptable, and not out of place among `base` or `array`.
Consider instead `Data.Array.Byte`? the `-Array` suffix is redundant, no?

**Comment by Bodigrim** [comment]
`Data.Array.Byte` is also fine with me. 
@emilypi @cigsender @cgibbard what do you think? Do you prefer `Data.Array.ByteArray` or `Data.Array.Byte`?

**Comment by emilypi** [comment]
That's quite the name clash. Approved.

**Comment by cigsender** [comment]
I'm not a fan of the whole `Data.*`/`Control.*` naming scheme in the first place but that's a huge can of worms. I think `Data.Array.Byte` is a happy medium here.

**Comment by cgibbard** [comment]
I'm okay with either name, and approve of avoiding the breakage situation. Normally I would slightly lean in the direction of Data.Array.ByteArray, since the module having the type's name in its name helps users identify where the type is coming from in cases where it has been imported unqualified. However, the 'array' package is full of modules like Data.Array.IO which exports IOArray. So Data.Array.Byte would be consistent with that.

**Comment by Bodigrim** [comment]
@chessai Are you comfortable with `Data.Array.Byte`?

**Comment by chessai** [comment]
I'm fine with it

**Comment by Bodigrim** [comment]
Cool, seems everyone is on board with `Data.Array.Byte`. I've updated https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6742. Closing as approved, thanks everyone.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Author**             |  @Bodigrim   |
| **Status**             |  merged |
| **`base` version**     | `4.17.0.0` |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6742 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | present |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
