### ISSUE TITLE
`HasField` for `Maybe`

### ISSUE THREAD

**Issue by googleson78** [haskell/core-libraries-committee#191]
I would like to add the following instance to `Maybe`:

```haskell
instance forall x r a. HasField x r a => HasField x (Maybe r) (Maybe a) where
  getField = fmap (getField @x)
```

Example:
```haskell
> :set -XOverloadedRecordDot
> data Foo = MkFoo {bar :: Int}
> mx = Just $ MkFoo 5
> mx.bar
Just 5
```

This instance would be very convenient when working with records inside `Maybe` values, which happens all the time in app code, e.g. working with a database where you're fetching a record using a key, and the key may not be present.

This instance nicely chains with itself for nested fields:
```haskell
> data Inner = MkInner {innerField :: Int}
> data Outer = MkOuter {outerField :: Inner}
> mx = Just $ MkOuter $ MkInner 5
> mx.outerField.innerField
Just 5
```
As well as for nested `Maybe`s:
```haskell
> data Inner = MkInner {innerField :: Int}
> data Outer = MkOuter {outerMaybeField :: Maybe Inner}
> mx = Just $ MkOuter $ Just $ MkInner 5
> mx.outerMaybeField.innerField
Just (Just 5)
```

Additionally, I'm hoping that this is a rather uncontroversial instance, as I currently can't think of other possible `HasField x (Maybe r) (Maybe a)` instance heads which would clash with this one.

Another point in favour is that this is a relatively standard practice in languages that have `Maybe`-like constructs or that have `null`s. They usually have a way of accessing a value only if it's not `Nothing`/`null`, often by means of an operator. For example:
* Rust's `?` - https://doc.rust-lang.org/rust-by-example/error/option_unwrap/question_mark.html
* JavaScript's optional chaining - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
* Ruby's "safe navigation operator" - https://ruby-doc.org/core-2.6/doc/syntax/calling_methods_rdoc.html#label-Safe+navigation+operator

I have a patch ready for ghc, and it seems relatively straightforward:
```diff
diff --git a/libraries/base/GHC/Base.hs b/libraries/base/GHC/Base.hs
index 52a247ffae..04f41262aa 100644
--- a/libraries/base/GHC/Base.hs
+++ b/libraries/base/GHC/Base.hs
@@ -72,6 +72,9 @@ Other Prelude modules are much easier with fewer complex dependencies.
 {-# LANGUAGE RankNTypes #-}
 {-# LANGUAGE UnboxedTuples #-}
 {-# LANGUAGE Unsafe #-}
+{-# LANGUAGE ScopedTypeVariables #-}
+{-# LANGUAGE TypeApplications #-}
+{-# LANGUAGE UndecidableInstances #-}
 
 -- -Wno-orphans is needed for things like:
 -- Orphan rule: "x# -# x#" ALWAYS forall x# :: Int# -# x# x# = 0
@@ -120,6 +123,7 @@ import GHC.Prim.Ext
 import GHC.Prim.PtrEq
 import GHC.Err
 import GHC.Maybe
+import GHC.Records
 import {-# SOURCE #-} GHC.IO (mkUserError, mplusIO)
 
 import GHC.Tuple (Solo (..))     -- Note [Depend on GHC.Tuple]
@@ -1062,6 +1066,9 @@ instance  Monad Maybe  where
 
     (>>) = (*>)
 
+instance forall x r a. HasField x r a => HasField x (Maybe r) (Maybe a) where
+  getField = fmap (getField @x)
+
 -- -----------------------------------------------------------------------------
 -- The Alternative class definition
 
diff --git a/libraries/base/GHC/Records.hs b/libraries/base/GHC/Records.hs
index b3f02e46c4..a05f3352fd 100644
--- a/libraries/base/GHC/Records.hs
+++ b/libraries/base/GHC/Records.hs
@@ -1,6 +1,7 @@
 {-# LANGUAGE AllowAmbiguousTypes #-}
 {-# LANGUAGE FunctionalDependencies #-}
 {-# LANGUAGE PolyKinds #-}
+{-# LANGUAGE NoImplicitPrelude #-}
 
 -----------------------------------------------------------------------------
 -- |
```
However, I'm not sure whether adding a dependency from `GHC.Base` to `GHC.Records` is something that GHC HQ and CLC would be happy with, given I'm not sure what the stability of `GHC.Records` is.
 
I'm willing to do an impact assessment as soon as [I can get `clc-stackage` working for me](https://github.com/Bodigrim/clc-stackage/issues/14)

**Comment by ocharles** [comment]
> Additionally, I'm hoping that this is a rather uncontroversial instance, as I currently can't think of other possible HasField x (Maybe r) (Maybe a) instance heads which would clash with this one.

That's true, if you take the stance that all possible instances should exist. There is another option which "clashes", which is to simply have no instances at all. Personally, I don't mind:

```haskell
mx <&> (.bar)
```

That said, this instance isn't quite at the level of confusing as `Foldable` for tuples.

**Comment by googleson78** [comment]
> That's true, if you take the stance that all possible instances should exist.

I'm not of the camp that we should add all theoretically canonical instances to Haskell, but I am of the stance that I much prefer `mx.bar` to `mx <&> (.bar)`.

While I agree that, in isolation, the latter is not much nosier than the former, when you start using `mx <&> (.bar)` as a subexpression elsewhere it (imo) gets much clunkier - you often have to use parens and/or you increase operator soupiness.

**Comment by googleson78** [comment]
Something I also forgot to mention(but will now) in my original proposal that this is a relatively standard practice in languages that have `Maybe`-like constructs or that have `null`s have a way (usually by means of operator) of accessing a value only if it's not `Nothing`/`null`. For example:
* Rust's `?` - https://doc.rust-lang.org/rust-by-example/error/option_unwrap/question_mark.html
* JavaScript's optional chaining - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by phadej** [comment]
This is specialization of `HasField` for `Functor`: https://github.com/ghc-proposals/ghc-proposals/issues/600

---

(Neither) instance allows convenient accessing of nested `Maybe` fields (i.e. true optional chaining).

Example:

```haskell
data Foo = Foo { bar :: Maybe Bar }
data Bar = Bar { who :: Maybe Who }
data Who = Who { int :: Maybe Int }
```

With `optics`, I can write

```haskell
val :: Foo
val = Foo (Just (Bar (Just (Who (Just 42)))))

ex :: Maybe Int
ex = val ^? #bar %? #who %? #int % _Just
```

In this case it's actually important to decouple "accessor" (in this case affine folds) composition (`%` or `%?`) and actual accessing (`^?`). 

With `OverloadedRecordDot` and the proposed instance:

```haskell
val.bar         :: Maybe Bar          -- using HasField Foo "bar" Bar
val.bar.who     :: Maybe (Maybe Who)  -- using HasField Bar "int" Who => HasField (Maybe Bar) "who" (Maybe Who)
val.bar.who.int :: Maybe (Maybe (Maybe Int))
```

the `Maybe`s are not squashed, so it's different from optional chaining in other languages.

I'm not entirely sure what we need for true optional chaining. (In `optics` the trailing `% _Just` is not elegant, so `%?` is probably not the best solution, but I honestly haven't given the problem any proper though).

---

```haskell
-- Full example
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedLabels #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE UndecidableInstances #-}
import Optics.Core
import GHC.Generics (Generic)
import GHC.Records

data Foo = Foo { bar :: Maybe Bar } deriving (Show, Generic)
data Bar = Bar { who :: Maybe Who } deriving (Show, Generic)
data Who = Who { int :: Maybe Int } deriving (Show, Generic)

val :: Foo
val = Foo (Just (Bar (Just (Who (Just 42)))))

ex :: Maybe Int
ex = val ^? #bar %? #who %? #int % _Just

ex' :: Maybe Int
ex' = val ^? #bar % _Just % #who % _Just % #int % _Just

instance forall x r a. HasField x r a => HasField x (Maybe r) (Maybe a) where
  getField = fmap (getField @x)

ex2 :: Maybe (Maybe Who)
ex2 = val.bar.who

ex3 :: Maybe (Maybe (Maybe Int))
ex3 = val.bar.who.int
```

**Comment by parsonsmatt** [comment]
I like the first proposed one. I don't care for the "squashing" variant, since that loses information.

**Comment by mixphix** [comment]
`data Maybe a = Nothing | Just a`

There’s no field name here.

---

I’ll paraphrase what I replied in the GHC proposal for the general Functor instance:

> This is the kind of "a functor is a box for values" thinking that leads to misunderstandings.

```hs
data Foo = Foo { bar :: Maybe Bar } deriving (Show, Generic)
data Bar = Bar { who :: Maybe Who } deriving (Show, Generic)
data Who = Who { int :: Maybe Int } deriving (Show, Generic)

val :: Foo
val = Foo (Just (Bar (Just (Who (Just 42)))))

totalUnwrap :: Maybe Int
totalUnwrap = val.bar >>= (.who) >>= (.int)
```

Operators in Haskell aren’t “soupy”. They have types that can be stated or inferred. The above is straightforward to anyone who has a grasp on the `Maybe` monad. I don’t think packing special cases into `HasField` will not make your code much easier to read, especially when combining regular fields and `Maybe` “fields”. Is it really so painful to be precise?

**Comment by ocharles** [comment]
On @mixphix's point, the examples of other languages having null chaining all have a special operator for null chaining, they _don't_ overload `.`. so I think if we did go down this path Haskell would be diverging

**Comment by adamgundry** [comment]
`HasField` should not be considered stable. There is an accepted ghc-proposal to change its design, although I'm proposing to roll back some of the accepted-but-not-implemented changes in https://github.com/ghc-proposals/ghc-proposals/pull/583. (Input into the design proposed there would be very welcome!)

All of this predates our current consensus about the roles of the CLC vs GHC SC. If we had a `ghc-experimental` package when `HasField` was introduced, it would have made sense to expose `HasField` from there rather than from `base`. Perhaps we should consider moving `GHC.Records` out of `base` into `ghc-experimental`?

Regarding this particular ticket, my feeling is that `HasField` instances should correspond pretty closely to actual fields, and that special cases such as `Maybe` are better handled using distinct operators (or optics). In particular, the proposed instance doesn't nicely extend to support setters AFAICS.

**Comment by googleson78** [comment]
Given @adamgundry's+@chshersh feedback on the topic, I'm closing this issue for the time being and only testing this particular instance in private/work codebases, perhaps coming back after I have some demonstrable positive results.

> Regarding this particular ticket, my feeling is that HasField instances should correspond pretty closely to actual fields

Is there a particular reason for this? Ignoring this `Maybe` instance, there have also been some other quite nice "virtual field" usages. The one that comes to mind immediately is @parsonsmatt's usage in `esqueleto` (see the source docs on [these instances](https://hackage.haskell.org/package/esqueleto-3.5.10.0/docs/src/Database.Esqueleto.Internal.Internal.html#line-2351), hard to link to instance docs in haddock), where he defines virtual fields which desugar into accessing a particular column in an sql query. I also know of another DB library in the works which does something very similar, and in both cases, it is quite convenient.

> In particular, the proposed instance doesn't nicely extend to support setters AFAICS.

It is entirely incidental that I phrased this using `HasField`, but I only meant to suggest implement `getField` in this particular case. Although I'm also curious - why is it not possible to support `SetField x r a => SetField x (Maybe r) (Maybe a)` (`SetField` as seen in 583)?

**Comment by adamgundry** [comment]
Thanks @googleson78 for driving this discussion forward and experimenting with how `HasField` can be improved!

> > Regarding this particular ticket, my feeling is that HasField instances should correspond pretty closely to actual fields
> 
> Is there a particular reason for this? Ignoring this `Maybe` instance, there have also been some other quite nice "virtual field" usages. The one that comes to mind immediately is @parsonsmatt's usage in `esqueleto` (see the source docs on [these instances](https://hackage.haskell.org/package/esqueleto-3.5.10.0/docs/src/Database.Esqueleto.Internal.Internal.html#line-2351), hard to link to instance docs in haddock), where he defines virtual fields which desugar into accessing a particular column in an sql query. I also know of another DB library in the works which does something very similar, and in both cases, it is quite convenient.

One reason is that I'd like `HasField`/`SetField` to provide a convenient mechanism for getting GHC to generate optics, and reasoning about how such "virtual field" usages generalise from `OverloadedRecordDot` to the optics case tends to wreck my head. :grin:

But the `esqueleto` code gives an interesting case I haven't really explored. It's plausible that DSLs can reasonably bend the rules a bit.

> > In particular, the proposed instance doesn't nicely extend to support setters AFAICS.
> 
> It is entirely incidental that I phrased this using `HasField`, but I only meant to suggest implement `getField` in this particular case. Although I'm also curious - why is it not possible to support `SetField x r a => SetField x (Maybe r) (Maybe a)` (`SetField` as seen in 583)?

The problem is in satisfying the lens laws. As per [the proposal](https://github.com/adamgundry/ghc-proposals/blob/hasfield-redesign/proposals/0000-hasfield-redesign.rst#laws), (I claim) instances should satisfy
```hs
getField @x (setField @x v r) === v  -- PutGet
```
but if you have the `Maybe` instance and take `v = Just _, r = Nothing` then the LHS is necessarily `Nothing`.

**Comment by parsonsmatt** [comment]
We use virtual fields *a lot* in the work codebase. We've got a hook in our persistent model definitions to create `HasField` instances that drop the type prefix - so a persistent model definition like:

```
OrganizationUserMembership
    organizationId OrganizationId
    userId UserId
```

which generates a Haskell type:

```haskell
data OrganizationUserMembership = OrganizationUserMembership
  { organizationUserMembershipOrganizationId :: OrganizationId
  , organizationUserMembershipUserId :: UserId
  }

-- and these extra HasFields:

instance HasField "organizationId" OrganizationUserMembership OrganizationId where
    getField = getField @"organizationUserMembershipOrganizationId"

instance HasField "userId" OrganizationUserMembership OrganizationId where
    getField = getField @"organizationUserMembershipUserId"
```

which *really* helps with code verbosity - writing `organizationUserMembership.userId` instead of `organizationUserMembershipUserId organizationUserMembership`, or (more probably) `organizationUserMembershipUserId oum`.

I'm also going to (eventually) prototype out my "qualified re-export" hack of:

```haskell
module MapTrick where

import qualified Data.Map as Map

data IMap = IMap

instance HasField "lookup" Map (k -> Map.Map k v -> Maybe v) where
    getField IMap = Map.lookup
```

allowing you to re-export `IMap` from your project prelude and then you'd get:

```haskell
import SickPrelude (IMap(..), Map)

lmao :: Map String Int -> IO ()
lmao args = do
  userRequest <- getLine
  case IMap.lookup userRequest args of
    Nothing -> print (0, "asdf")
    Just i -> print (i, "cool")
```

I think virtual fields are a *really* important and cool idea that make Haskell programming significantly nicer. Restricting the record dot to mere sugar around function accessor and record update would be a big loss.

**Comment by mixphix** [comment]
Unfortunately, simulation doesn't work if we also want to abstract the methods into a class:

```hs
import Relude.Extra.DynamicMap

class (DynamicMap m) => HasField "insert" m (Key m -> Val m -> m) where
  getField m = \k v -> insert k v m
```

The instances must be written for each data type individually.

**Comment by phadej** [comment]
@mixphix yes, that is too general, because what you wrote is adding `insert` to everything (`m`). The class resolution will only later try to resolve `DynamicMap`. So even if the intance you wrote were accepted, it would be a bad idea.
