### ISSUE TITLE
`numberToRangedRational`: fix edge cases for exp ≈ `(maxBound :: Int)`

### ISSUE THREAD

**Issue by frasertweedale** [haskell/core-libraries-committee#192]
# Motivation

numberToRangedRational: fix edge cases for exp ≈ (maxBound :: Int)  
                                                                    
Currently a negative exponent less than `minBound :: Int` results in
Infinity, which is very surprising and obviously wrong.             
                                                                    
```                                                                 
λ> read "1e-9223372036854775808" :: Double                          
0.0                                                                 
λ> read "1e-9223372036854775809" :: Double                          
Infinity                                                            
```                                                                 
                                                                    
There is a further edge case where the exponent can overflow when   
increased by the number of tens places in the integer part, or      
underflow when decreased by the number of leading zeros in the      
fractional part if the integer part is zero:                        
                                                                    
```                                                                 
λ> read "10e9223372036854775807" :: Double                          
0.0                                                                 
λ> read "0.01e-9223372036854775808" :: Double                       
Infinity                                                            
```                                                                 

# Proposal

Fix these bugs.  The exponent should not wrap and return `Infinity` (in case of underflow) or `0` (in case of overflow).
There is a [merge request](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10933).

# Impact

This improves the accuracy of floating point parsing on some *extreme* cases.  Most ordinary programs or use cases are not likely to be affected.  Users that are affected would presumably be pleased with this change.

**Comment by tomjaguarpaw** [comment]
Wow, the existing behaviour is absurd!

**Comment by frasertweedale** [comment]
> Wow, the existing behaviour is absurd!

To be fair, the inputs triggering this behaviour are also absurd :)

**Comment by frasertweedale** [comment]
Some additional exponent over/underflow cases were identified.  CLC proposal and merge request were both updated.

**Comment by mixphix** [comment]
Thanks for catching those cases! It would be generous of you to add test cases, but I'll still approve this proposal if they're elided.

**Comment by Bodigrim** [comment]
I'd strongly suggest writing tests, otherwise it's difficult to review and verify.

**Comment by frasertweedale** [comment]
I'll add some tests, in the next few days when I find some spare time :)

**Comment by mixphix** [comment]
Should `1e`anything ever be unequal to 1?

**Comment by Bodigrim** [comment]
I agree with the patch provided. There are two changes:
* The function used to compare a sum of two `Int`s (namely, `firstDigit` and `fromInteger exp`) to an `Int`. This is wrong, because a sum of two `Int`s may overflow, changing the result of the comparison. The proposed patch does the right thing: it casts all arguments to `Integer` and performs comparison on them. 
* The aforementioned change further allowed to simplify the function, completely eliminating a check (and a bug in it) for `exp :: Integer` overflowing `minBound, maxBound :: Int`. Great! Simpler and more correct at the same time!
* I do not envision any negative performance impact.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on a patch fixing bugs in `numberToRangedRational`, which is used for `instance Read Double`. The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10933. 

@tomjaguarpaw @hasufell @chshersh @mixphix @angerman @parsonsmatt 

----

+1 from me.

**Comment by hasufell** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by mixphix** [comment]
+1

**Comment by chshersh** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
