### ISSUE TITLE
Introduce `TypeRepOf` pattern synonym

### ISSUE THREAD

**Issue by sheaf** [haskell/core-libraries-committee#197]
I propose to introduce the following pattern synonym definition to `Type.Reflection`:

```haskell
pattern TypeRepOf :: forall {k1 :: Type} {k2 :: Type} {a :: k1} (b :: k2). Typeable b => (b ~~ a) => TypeRep a
pattern TypeRepOf <- ( eqTypeRep @k2 @k1 @b @a ( typeRep @b ) -> Just HRefl )
  where TypeRepOf = typeRep @a
```

This allows one to match on a `TypeRep`, e.g.

```haskell
foo :: TypeRep a -> a
foo = \case
  TypeRepOf @Int  -> 3
  TypeRepOf @Bool -> False
  TypeRepOf @Char -> 'x'
```

**Comment by sheaf** [comment]
GHC merge request is [!11132](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11132).

**Comment by adamgundry** [comment]
@sheaf I think you mean to add this to `Type.Reflection` rather than `Data.Typeable`?

**Comment by sheaf** [comment]
> @sheaf I think you mean to add this to `Type.Reflection` rather than `Data.Typeable`?

Indeed; in the MR I'm adding it to `Data.Typeable.Internal` and re-exporting it from `Type.Reflection` but not `Data.Typeable`, following suit from the prior introduction of the `TypeRep` pattern synonym.

**Comment by RyanGlScott** [comment]
What is the difference between this `TypeRepOf` pattern synonym and the existing [`TypeRep`](https://hackage.haskell.org/package/base-compat-0.13.0/docs/Type-Reflection-Compat.html#v:TypeRep) pattern synonym? I suspect the answer has to do with how the type variables are quantified, but it would be helpful to make this clearer.

**Comment by sheaf** [comment]
> What is the difference between this `TypeRepOf` pattern synonym and the existing [`TypeRep`](https://hackage.haskell.org/package/base-compat-0.13.0/docs/Type-Reflection-Compat.html#v:TypeRep) pattern synonym? I suspect the answer has to do with how the type variables are quantified, but it would be helpful to make this clearer.

The `TypeRep` pattern synonym, when used in a pattern, matches on a given `TypeRep` and returns the corresponding `Typeable` evidence. So it allows one to convert a `TypeRep` to a `Typeable` instance. The pattern never fails to match.

On the other hand, the `TypeRepOf` pattern synonym takes in an argument (through a visible type application), and only succeeds when the types match. So it's a way to do type-dispatch, as in the example in the OP. A use of `TypeRep @b` in a pattern **requires** a `Typeable b` constraint, as opposed to **providing** it (like the `TypeRep` synonym does).

**Comment by RyanGlScott** [comment]
Thanks for the clarification.

The [`SNat`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-TypeLits.html#v:SNat) pattern synonym (as well as its cousins, [`SSymbol`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-TypeLits.html#v:SSymbol) and [`SChar`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-TypeLits.html#v:SChar)) was directly inspired by the `TypeRep` pattern synonym. In the same vein as `TypeRepOf`, one could imagine an `SNatOf` pattern synonym that lets you match on a type-level `Nat`, e.g.,

```hs
bar = \case
  SNatOf @0  -> ..
  SNatOf @2 -> ...
  SNatOf @42 -> ...
```

You could accomplish the same thing with `TypeRepOf`, of course, but I imagine that `SNatOf` would be slightly more efficient since it would check for integer equality under the hood, rather than checking for full [`Fingerprint`](https://hackage.haskell.org/package/base-4.18.0.0/docs/GHC-Fingerprint-Type.html#t:Fingerprint) equality under the hood as in `TypeRepOf`.

**Comment by sheaf** [comment]
I agree, I think `S{Nat,Char,Symbol}Of` would make sense too. I'd be happy to propose those in a followup proposal if this one goes through.

**Comment by Ericson2314** [comment]
This is useful, but it is using an unstable part of the language. These are "input" type arguments to the pattern and I think they will need new syntax, especially when type variables are involved.

I think therefore it would be prudent to put this in `ghc-experimental` or another less stable location.

**Comment by tomjaguarpaw** [comment]
I strongly agree with @Ericson2314

**Comment by Bodigrim** [comment]
> This is useful, but it is using an unstable part of the language. These are "input" type arguments to the pattern and I think they will need new syntax, especially when type variables are involved.

Sorry, I don't follow: what's exactly unstable here? https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11132 does not introduce any new language extensions to `Data.Typeable.Internal`. The type signature is a bit scary, but not really out of the line with the rest of `Data.Typeable`.

**Comment by Bodigrim** [comment]
Re-reading the discussion, I assume that @Ericson2314's comment https://github.com/haskell/core-libraries-committee/issues/197#issuecomment-1690852201 referred the suggestion in https://github.com/haskell/core-libraries-committee/issues/197#issuecomment-1690765343, and not the actual MR under consideration https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11132/diffs. 

Dear CLC members, any more opinions on this before we vote?

**Comment by mixphix** [comment]
I'd really appreciate adding some documentation to `pattern TypeRepOf` out of the gate. At least the bit [explained above](https://github.com/haskell/core-libraries-committee/issues/197#issuecomment-1690410411) about how it's different from `pattern TypeRep`.

**Comment by Bodigrim** [comment]
@sheaf could you possibly update the MR, including more discussion of difference to `pattern TypeRep` into the documentation? And we'll go for a vote.

**Comment by Bodigrim** [comment]
Closing as abandoned. Feel free to reopen when there is resource to execute.
