### ISSUE TITLE
Exception backtrace proposal: Part 2: Backtraces

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#199]
*Tracking ticket: #164*

This proposal attempts to summarise the interface design of the backtrace annotations proposed in [GHC Proposal #330][GHCP330]. Specifically, this proposal covers sections [2.2][s2.2], [2.7][s2.7], and [2.9][s2.9].

Note that the GHC Proposal is free-standing; no reading of the discussion which lead to its current accepted state should be necessary to understand its contents. Consequently, to avoid repetition I will refer back to the GHC Proposal instead of repeating myself here. I will, however, attempt to give some color to the interfaces by providing typical usage examples where necessary. However, the GHC Proposal is to be considered the canonical definition of the interfaces; in particular, [section 2][s2] and its subsections precisely captures the changes proposed in `base`.

## Capturing Backtraces

Equipped with the general-purpose annotation mechanism from [part 1][part1], we can easily extend exceptions with information on their provenance within the source program. As described in [Section 2.2][s2.2], GHC has developed a number of mechanisms for capturing execution state over the years. We propose to capture these in a `Backtraces` type which can function as an `ExceptionAnnotation`:
```haskell
-- In Control.Exception.Backtrace
data Backtraces =
    Backtraces {
        btrCostCentre :: Maybe (Ptr CostCentreStack),
        btrHasCallStack :: Maybe GHC.Stack.CallStack,
        btrExecutionStack :: Maybe [GHC.ExecutionStack.Location],
        btrIpe :: Maybe [StackEntry]
    }
  
displayBacktraces :: Backtraces -> String

instance ExceptionAnnotation Backtraces where
    displayExceptionAnnotation = displayBacktraces
```

## Selecting which backtrace mechanisms to capture

As backtrace collection can be expensive and may not always be desirable, we propose adding an interface to select which of the above-described mechanisms should be captured when an exception is thrown. This is controlled via global state:
```haskell
-- In Control.Exception.Backtrace
data BacktraceMechanism
  = CostCentreBacktrace
  | HasCallStackBacktrace
  | ExecutionBacktrace
  | IPEBacktrace
  
getBacktraceMechanismState :: BacktraceMechanism -> IO Bool
setBacktraceMechanismState :: BacktraceMechanism -> Bool -> IO ()
```

## Suppressing backtrace collection

Some exception types (particularly of the asynchronous variety) are used to achieve non-local control flow in expected cases (c.f. `ThreadKilled`). Incurring backtrace collection in this case would be extremely problematic. To avoid this we introduce a new method to the `Exception` class ([section 2.7][s2.7]) and amend the `SomeException` instance as necessary:
```haskell
class (Show e, Typeable e) => Exception e where
    ...
    backtraceDesired :: e -> Bool
    backtraceDesired _ = True
    
instance Exception SomeException where
    ...
    backtraceDesired (SomeException e) = backtraceDesired e
```
`throw` and `throwIO` will then be modified to not collect a backtrace when `backtraceDesired exception == False` (see [section 2.7][s2.7]).

Since the user may want to suppress backtrace collection for a particular `throw` site, we propose adding a `NoBacktrace` `newtype` to allow this (see [section 2.7][s2.7]).

Finally, given its intended semantics, it seems appropriate that the `onException` function should not capture a new backtrace when rethrowing. We propose to modify `onException` to this end.

## Usage

We expect that the principle impact of this proposal will be the textual backtraces in printed exceptions. Most users will not need to manipulate any of the interfaces described above in their Haskell programs. The notable exception is the `[gs]etBacktraceMechanismState` functions, which will be needed by users who want to enable or disable specific backtrace mechanisms.

## Migration

The majority of interfaces proposed here are new and will not affect existing users. The addition of `backtraceDesired` to `Exception` will be transparent to users due to its default method definition. The operational impact of backtrace collection can be eliminated when not desired through use of `setBacktraceMechanismState`.

[paper]: https://simonmar.github.io/bib/papers/ext-exceptions.pdf
[s2]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#2proposed-change-specification
[s2.1]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#21annotations
[s2.2]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#22backtraces
[s2.3]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#23representing-exception-context
[s2.4]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#24attaching-context-to-exceptions
[s2.5]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#25providing-context-to-handlers
[s2.6]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#26preserving-exception-causes-on-rethrowing
[s2.7]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#27capturing-backtraces-on-exceptions
[s2.8]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#28hascallstack-backtraces-for-thrown-exceptions
[s2.9]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#29asynchronous-exceptions
[s2.10]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#210modifying-the-top-level-handler
[s8.6]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#86providing-solver-support-for-exceptioncontext
[displayException-clc]: https://mail.haskell.org/pipermail/libraries/2014-November/024176.html
[displayException-ghc]: https://gitlab.haskell.org/ghc/ghc/-/issues/9822
[CLC198]: https://github.com/haskell/core-libraries-committee/issues/198
[part1]: TODO
[GHCP330]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#decorate-exceptions-with-backtrace-information

**Comment by mixphix** [comment]
+1

**Comment by Bodigrim** [comment]
@bgamari 

```haskell
data Backtraces =
    Backtraces {
        costCentreBacktrace :: Maybe (Ptr CostCentreStack),
        hasCallStackBacktrace :: Maybe GHC.Stack.CallStack,
        executionBacktrace :: Maybe [GHC.ExecutionStack.Location],
        ipeBacktrace :: Maybe [StackEntry]
    }
```

I think the name of the second field is unfortunate, intuitively I'd expect `hasSmth` to be `:: Bool`. IMO `callStackBacktrace` would be less confusing, even if not matching [`HasCallStack`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-Stack-Types.html#t:HasCallStack). Also how about `btr*` prefix instead of `*Backtrace` suffix? I think it's more common style of field naming.

```haskell
-- In Control.Exception.Backtrace
data BacktraceMechanism
  = CostCentreBacktrace
  | HasCallStackBacktrace
  | ExecutionBacktrace
  | IPEBacktrace
  
getBacktraceMechanismState :: BacktraceMechanism -> IO Bool
setBacktraceMechanismState :: BacktraceMechanism -> Bool -> IO ()
```

Is it better than a record `BacktraceMechanismState` with four `Bool` fields, matching `Backtraces` structure? And then 
```haskell
getBacktraceMechanismState :: IO BacktraceMechanismState
setBacktraceMechanismState :: BacktraceMechanismState -> IO ()
```

**Comment by bgamari** [comment]
Sure, I would be fine with changing `hasCallStackBacktrace` to `btrcallStack` (and the same for the other fields).






> Is it better than a record `BacktraceMechanismState` with four `Bool` fields, matching `Backtraces` structure? 

They are certainly both designs; I have no strong opinion in either direction.

**Comment by adamgundry** [comment]
One slight advantage of the current design is that it's very easy to toggle a particular mechanism while otherwise leaving the others at the default, e.g. via `setBacktraceMechanismState CostCentreBacktrace True`. That seems like it will be common and is nicer than
```hs
x <- getBacktraceMechanismState
setBacktraceMechanismState (x { costCentreBacktraceEnabled = True })
```
The record-of-booleans design makes it easier to capture or set the state of all the mechanisms at once, but my guess is that's less common.

**Comment by Bodigrim** [comment]
One advantage of record-of-booleans is that we can potentially make it match the `Backtraces` by construction so that less vocabulary is needed:
```haskell
data BacktracesGen a b c d =
    Backtraces {
        costCentreBacktrace :: Maybe a,
        hasCallStackBacktrace :: Maybe b,
        executionBacktrace :: Maybe c,
        ipeBacktrace :: Maybe d
    }

type Backtraces = BacktracesGen (Ptr CostCentreStack) GHC.Stack.CallStack [GHC.ExecutionStack.Location] [StackEntry]

getBacktraceMechanismState :: IO (BacktracesGen Bool Bool Bool Bool)
setBacktraceMechanismState :: BacktracesGen Bool Bool Bool Bool -> IO ()
```
Or is it too arcane?..

> The record-of-booleans design makes it easier to capture or set the state of all the mechanisms at once, but my guess is that's less common.

FWIW my guess would be the opposite but we cannot know at the moment.

@bgamari what's the reason behing `Maybe [GHC.ExecutionStack.Location]` and `Maybe [StackEntry]` in `Backtraces`? Is there a semantic difference between `Nothing` and `Just []`?

**Comment by phadej** [comment]
Does `backtraceDesired` ever examine its' argument? Shouldn't it rather be `backtraceDesired :: Proxy# e -> Bool`? E.g. mention of `NoBacktrace` suggests that bactrack desirety is always a property of a type, not values.

**Comment by adamgundry** [comment]
> what's the reason behing `Maybe [GHC.ExecutionStack.Location]` and `Maybe [StackEntry]` in `Backtraces`? Is there a semantic difference between `Nothing` and `Just []`?

I would expect that `Nothing` means "no backtrace was collected" whereas `Just []` means "a backtrace was collected, but it happened to be empty". I'm not sure if any of the existing backtrace mechanisms can generate an empty backtrace, but it doesn't seem fundamentally implausible? And it seems more consistent to use `Maybe` in all cases.

> Does `backtraceDesired` ever examine its' argument?

It looks like this doesn't happen in the built-in instances (except `SomeException`, and I think that can be worked around if you use the proxy approach). So I guess it's a question of whether we want to force this to be a property of the type, or allow it to be determined by the specific exception constructor. The existing approach is more flexible; is there a downside to it?

**Comment by bgamari** [comment]
Just to confirm, @adamgundry's expectation is correct. `Nothing` means that "we cannot collect a backtrace with this means" (e.g. due to missing library support) whereas `Just []` means that a backtrace was collected but was empty. Both of these things can happen with the DWARF mechanism since a) we need `libdw` in order to collect DWARF backtraces, and b) the backtrace will be empty if program was compiled without debug information.

**Comment by bgamari** [comment]
@bodigrim, just a gentle ping.

**Comment by Bodigrim** [comment]
> Sure, I would be fine with changing `hasCallStackBacktrace` to `btrCallStack` (and the same for the other fields).

@bgamari did you make your mind one way or another? Please update the top post. 

----

Dear CLC members, last chance to opine before we vote.

**Comment by bgamari** [comment]
> @bgamari did you make your mind one way or another? Please update the top post.

Done.

**Comment by Bodigrim** [comment]
Dear CLC members let's vote on the proposal to extend `class Exception` with a new member `backtraceDesired :: e -> Bool` with a default implementation `backTraceDesired _ = True` and provide mechanisms to select which backtrace mechanisms to capture. As an exception, these proposals for exceptions go without an MR upfront, because they depend on lots of internal work in the compiler (already approved by GHC SC). Please refer to the top post for details. This is a non-breaking change.

@tomjaguarpaw @mixphix @hasufell @angerman @parsonsmatt @velveteer 

----

+1 from me, I'm convinced by the discussion above.

**Comment by tomjaguarpaw** [comment]
+1

----

Some comments/observations

> we propose adding a `NoBacktrace` `newtype`

I can't see a technical reason why we couldn't have a `throwWithBacktrace` function. Is there one? If not then I would suggest that would be a better API to this functionality than a `newtype`

> This is controlled via global state

It's unfortunate to introduce global state but I suppose that it's inevitable if we want the functionality in question to be picked up by the standard `throw` and `throwIO` functions.

**Comment by Bodigrim** [comment]
@mixphix @hasufell @angerman @parsonsmatt @velveteer just a gentle reminder to vote.

**Comment by velveteer** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by Bodigrim** [comment]
OK, 4 votes out of 7 are enough to approve.

**Comment by bgamari** [comment]
> One advantage of record-of-booleans is that we can potentially make it match the `Backtraces` by construction so that less vocabulary is needed:
> 
> ```haskell
> data BacktracesGen a b c d =
>     Backtraces {
>         costCentreBacktrace :: a,
>         hasCallStackBacktrace :: b,
>         executionBacktrace :: c,
>         ipeBacktrace :: d
>     }
> 
> type Backtraces = BacktracesGen (Ptr CostCentreStack) GHC.Stack.CallStack (Maybe [GHC.ExecutionStack.Location]) (Maybe [StackEntry])
> 
> getBacktraceMechanismState :: IO (BacktracesGen Bool Bool Bool Bool)
> setBacktraceMechanismState :: BacktracesGen Bool Bool Bool Bool -> IO ()
> ```
> 
> Or is it too arcane?..

I realize now that this never received the response that it deserves.

I personally think that this is a bit archane. However, it is fairly similar to @int-index's original [GADT-based suggestion](https://github.com/ghc-proposals/ghc-proposals/pull/330#issuecomment-1330446106):
```haskell
data BacktraceMechanism a where
  CostCentreBacktrace   :: BacktraceMechanism (Ptr CostCentreStack)
  HasCallStackBacktrace :: BacktraceMechanism GHC.Stack.CallStack
  ExecutionBacktrace    :: BacktraceMechanism [GHC.ExecutionStack.Location]
  IPEBacktrace          :: BacktraceMechanism [StackEntry]

type EnabledBacktraceMechanisms = forall a. BacktraceMechanism a -> Bool
type Backtraces = forall a. BacktraceMechanism a -> Maybe a
```
While I do appreciate the elegance of this solution, I nevertheless pushed back against this as there isn't much precedent for relying on GADTs in `base`, it makes the interface less approachable, and the advantages seem fairly minor.

**Comment by bgamari** [comment]
@tomjaguarpaw has hit the nail on the head. It's not unlikely that a user would want more than one mechanism to be collected (e.g. `HasCallStack` and IPE, for instance).
