### ISSUE TITLE
Exception backtrace proposal: Part 3: `HasCallStack` Improvements

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#201]
*Tracking ticket: #164*

This proposal attempts to summarise the interface design of the backtrace annotations proposed in [GHC Proposal #330][GHCP330]. Specifically, this proposal covers section [2.8][s2.8].

Note that the GHC Proposal is free-standing; no reading of the discussion which lead to its current accepted state should be necessary to understand its contents. Consequently, to avoid repetition I will refer back to the GHC Proposal instead of repeating myself here. I will, however, attempt to give some color to the interfaces by providing typical usage examples where necessary. However, the GHC Proposal is to be considered the canonical definition of the interfaces; in particular, [section 2][s2] and its subsections precisely captures the changes proposed in `base`.

## Preserving `HasCallStack` backtraces

The `HasCallStack` mechanism is an early attempt at addressing the problem of error localization in Haskell. As the mechanism is very popular with users we want to ensure that `HasCallStack` backtraces are usable as annotations.

To facilitate this, we propose adding `HasCallStack` constraints to functions used to throw exceptions. These include:

 * `Control.Exception.throwIO` (and its definition in `GHC.IO`)
 * `Control.Exception.throw` (and its definition in `GHC.Exception`)

## Migration

This change is fully backwards compatible as `HasCallStack` is trivially satisfiable. The runtime cost of these dictionaries should be negligible as they only affect cold failure paths.

[paper]: https://simonmar.github.io/bib/papers/ext-exceptions.pdf
[s2]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#2proposed-change-specification
[s2.1]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#21annotations
[s2.2]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#22backtraces
[s2.3]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#23representing-exception-context
[s2.4]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#24attaching-context-to-exceptions
[s2.5]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#25providing-context-to-handlers
[s2.6]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#26preserving-exception-causes-on-rethrowing
[s2.7]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#27capturing-backtraces-on-exceptions
[s2.8]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#28hascallstack-backtraces-for-thrown-exceptions
[s2.9]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#29asynchronous-exceptions
[s2.10]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#210modifying-the-top-level-handler
[s8.6]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#86providing-solver-support-for-exceptioncontext
[displayException-clc]: https://mail.haskell.org/pipermail/libraries/2014-November/024176.html
[displayException-ghc]: https://gitlab.haskell.org/ghc/ghc/-/issues/9822
[CLC198]: https://github.com/haskell/core-libraries-committee/issues/198
[part1]: 
[part2]: 
[GHCP330]: https://github.com/ghc-proposals/ghc-proposals/blob/b4b6042760444a5fdfb2f78d3ab01777c7cde8d4/proposals/0330-exception-backtraces.rst#decorate-exceptions-with-backtrace-information

**Comment by parsonsmatt** [comment]
Big +1 from me!

**Comment by bgamari** [comment]
What can we do to move this along?

**Comment by Bodigrim** [comment]
Dear CLC members, last call for comments on this. We'd have to vote very soon to give @bgamari an opportunity to merge this work before GHC 9.10 fork (which is in 4 weeks).

@tomjaguarpaw @parsonsmatt @angerman @mixphix @hasufell @velveteer

**Comment by tomjaguarpaw** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by Bodigrim** [comment]
Dear CLC members, let's proceed with a formal vote. @tomjaguarpaw @parsonsmatt I'll count your votes above as final, unless you say otherwise. 

@hasufell @mixphix @velveteer @angerman 

----

+1 from me.

**Comment by velveteer** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that’s enough votes to approve.
