### ISSUE TITLE
Add missing {int,word}2{Float,Double} rules on 64 bit architectures

### ISSUE THREAD

**Issue by sheaf** [haskell/core-libraries-committee#203]
# Context

We currently have rules to convert between `Word#` and `Float#`/`Double#` in the `GHC.Float` module (in `base`):

```
"Int# -> Integer -> Float#"
  forall x. integerToFloat# (IS x) = int2Float# x

"Int# -> Integer -> Double#"
  forall x. integerToDouble# (IS x) = int2Double# x

"Word# -> Integer -> Float#"
  forall x. integerToFloat# (integerFromWord# x) = word2Float# x

"Word# -> Integer -> Double#"
  forall x. integerToDouble# (integerFromWord# x) = word2Double# x

"Word# -> Natural -> Float#"
  forall x. naturalToFloat# (NS x) = word2Float# x

"Word# -> Natural -> Double#"
  forall x. naturalToDouble# (NS x) = word2Double# x #-}
```

However, since GHC 9.4, `Word64` wraps `Word64#` instead of `Word#`. This means that these rules no longer fire when using `Word64`. This was the cause of regressions in the `splitmix` package reported in [GHC ticket #23907](https://gitlab.haskell.org/ghc/ghc/-/issues/23907).

# Proposal

Add the following rules to `GHC.Float` to handle `Word64#` and `Int64#` on 64-bit architectures:

```
"Int64# -> Integer -> Float#"
  forall x. integerToFloat# (integerFromInt64# x) = int2Float# (int64ToInt# x)

"Int64# -> Integer -> Double#"
  forall x. integerToDouble# (integerFromInt64# x) = int2Double# (int64ToInt# x)

"Word64# -> Integer -> Float#"
  forall x. integerToFloat# (integerFromWord64# x) = word2Float# (word64ToWord# x)

"Word64# -> Integer -> Double#"
  forall x. integerToDouble# (integerFromWord64# x) = word2Double# (word64ToWord# x)
```

This proposal is implemented in [GHC MR !11170](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11170).

Moreover, we propose to backport this change to GHC 9.6 and GHC 9.8.

## Addendum 1

We do not propoe adding rules going through `Natural` at this stage, as this would require defining a new function `naturalFromWord64#`, and adding several other rules mirroring those for `integerFromWord64#`.

## Addendum 2

Note that similar rules should also be implemented on 32 bit architectures, but that would require introducing new primops (see [GHC ticket #23908](https://gitlab.haskell.org/ghc/ghc/-/issues/23908)), so we don't propose doing that for the moment.

**Comment by Bodigrim** [comment]
Given the importance of `splitmix` for `random` and `QuickCheck` and the intention to backport the change, if approved, to GHC 9.8, I'll wait a few days more and trigger a vote. Looks pretty unambiguous to me.

**Comment by sheaf** [comment]
I've clarified in the proposal that we would like to backport this to GHC 9.6 and 9.8 to limit the impact of the performance regression as much as possible (given that we do not currently plan to make any more 9.4 releases).

**Comment by tomjaguarpaw** [comment]
If we're voting, then it'll be +1 from me

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add missing RULES to fix the regression caused by changing `data Word64 = Word64 Word#` to `data Word64 = Word64 Word64#`.

@chshersh @mixphix @angerman @parsonsmatt @hasufell 

----

+1 from me.

**Comment by parsonsmatt** [comment]
+1

**Comment by chshersh** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by angerman** [comment]
+1

**Comment by mixphix** [comment]
+1
