### ISSUE TITLE
Laws for `Bifoldable` / `Bitraversable`  which are also `Foldable` / `Traversable`

### ISSUE THREAD

**Issue by Bodigrim** [haskell/core-libraries-committee#205]
(This was originially submitted by @Topsii as a part of #93 / [!9489](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9489/diffs), but I think it's worth its own discussion)

Let's add the following text to [`class Bifoldable`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Bifoldable.html#t:Bifoldable):
```haskell
-- If the type is also a 'Foldable' instance, it should satisfy (up to laziness):
--
-- @
-- 'bifoldl' 'const' ≡ 'foldl'
-- 'bifoldr' ('flip' 'const') ≡ 'foldr'
-- 'bifoldMap' ('const' 'mempty') ≡ 'foldMap'
-- @
```
and to [`class Bitraverssable`](https://hackage.haskell.org/package/base-4.18.0.0/docs/Data-Bitraversable.html#t:Bitraversable):
```haskell
-- If the type is also a 'Traversable' instance, it should satisfy (up to laziness):
--
-- @
-- 'traverse' ≡ 'bitraverse' 'pure'
-- @
```
The qualification "up to laziness" is necessary, because at the moment the laws do not hold for tuples: for instance, `instance Bitraversable (,)` is lazier than `instance Traversable (a,)`:
```haskell
-- >>> (bitraverse pure pure undefined :: IO (Int, Word)) `seq` ()
-- ()
-- >>> (traverse pure undefined :: IO (Int, Word)) `seq` ()
-- *** Exception: Prelude.undefined
```

(IMO this extreme laziness is a sore state of affairs, and `instance Bitraversable (,)` should be stricter, but well. Cf. #107 for a similar issue with another type adopted by `base` from kmettoverse)

**Comment by konsumlamm** [comment]
I think it should be "also has a ... instance" instead of "is also a ... instance", since types aren't instances, they have instances.

**Comment by tomjaguarpaw** [comment]
> types aren't instances, they have instances

Can you provide a reference for that?

**Comment by konsumlamm** [comment]
I didn't find a reference for it, but I think it makes more sense to say that a type has an instance. For one, a type can have more than one instance (albeit not in the same module). Then there are multi-parameter type classes, which don't "belong" to a single type. Also, under the hood, an instance is a dictionary, not part of the type.

I think it would be fine to say "if the type is also a 'Foldable'", but "If the type is also a 'Foldable' instance" somehow implies to me that the type definition itself is also an instance definition.

**Comment by hasufell** [comment]
From the report 7.6.4:

> Each type in a default declaration must be an instance of Num or of IsString.

This suggests that types are instances.

**Comment by tomjaguarpaw** [comment]
Ah, then maybe we can split the difference here and change the language to

> If the type is also an instance of 'Foldable'

because that is consistent with the report and seems to also address @konsumlamm's point:

>  "If the type is also a 'Foldable' instance" somehow implies to me that the type definition itself is also an instance definition

**Comment by Bodigrim** [comment]
Thanks @Topsii! 

Dear CLC members, let's vote on the proposal to state laws for `Bifoldable` / `Bitraversable` which also happen to be `Foldable` / `Traversable`, as detailed above. The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11536. This is just a documentation change, and up to my best knowledge no existing instances violate the proposed law.

(We do not normally vote on documentation changes, unless it's about adding new class laws, which is exactly the case)

@tomjaguarpaw @mixphix @hasufell @angerman @parsonsmatt @velveteer 

----

+1 from me.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by velveteer** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
