### ISSUE TITLE
Introduce Data.Enum and Data.Bounded

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#208]
In #146 I noticed that the `Enum` and `Bounded` typeclasses currently have no proper home (currently exposed only via `Prelude` and `GHC.Enum`). I propose that we remedy this by introducing a pair of new modules, `Data.Bounded` and `Data.Enum`, to `base`:

```haskell
module Data.Bounded where

class Bounded a where
  minBound :: a
  maxBound :: a

module Data.Enum where

class Enum a where
  succ :: a -> a
  pred :: a -> a
  toEnum :: GHC.Types.Int -> a
  fromEnum :: a -> GHC.Types.Int
  enumFrom :: a -> [a]
  enumFromThen :: a -> a -> [a]
  enumFromTo :: a -> a -> [a]
  enumFromThenTo :: a -> a -> a -> [a]
```

This has been implemented in [!10422](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10422) and [!11347](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11347).

**Comment by mixphix** [comment]
+1, and please, oh please, let's include `enumerate = [minBound .. maxBound]` as an export.

**Comment by int-index** [comment]
Why the name `enumerate`? I expected `enumerate = zip [0..]` because there is a similar function in Python.

**Comment by Kleidukos** [comment]
Ah indeed that would be not too great to have a conflict on this. I've seen [`universe`](https://hackage.haskell.org/package/relude-1.2.0.0/docs/Relude-Enum.html#v:universe) in Relude. That would be a reasonable alternative?

**Comment by tomjaguarpaw** [comment]
I think discussion about a new function needs a new proposal. Can we please avoid scope creep in this discussion?

**Comment by bgamari** [comment]
Given there is some disagreement on the details here, I have dropped `enumerate` from the proposal. As I don't have a particular interest here, I will leave a proposal introducing it to someone else (but they should feel free to reference [!11321](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11321)).

**Comment by tomjaguarpaw** [comment]
I'm confused. [ghc-!0422](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10422) looks like it has already been merged.

**Comment by bgamari** [comment]
@tomjaguarpaw , yes, this proposal arose out of a [miscommunication ](https://github.com/haskell/core-libraries-committee/issues/146#issuecomment-1728483612)  in #146.

**Comment by tomjaguarpaw** [comment]
Aha, I see. Thanks!

**Comment by ocharles** [comment]
Does `Bounded` make sense to be in `Data.Enum`? An alternative is to house that in `Data.Bounded`.

**Comment by bgamari** [comment]
My initial thought was that `Enum` and `Bounded` tend to be appear together (and indeed they are both defined in the `GHC.Enum` module) but yes, I agree that exposing them as separate modules makes some amount of sense.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to provide canonical home for `class Enum` and `class Bounded` in `Data.*` land (namely, `Data.Enum` and `Data.Bounded`) as opposed to being exported only from `GHC.Enum` and `Prelude`. Status quo is unfortunate: if you do not want to import entire `Prelude`, you have to import `GHC.Enum` which has a flavour of internal module, prone to rapid changes. We discussed the issue earlier in #64 and #146.

@tomjaguarpaw @hasufell @mixphix @angerman @parsonsmatt @velveteer 

----

+1 from me.

**Comment by velveteer** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve. 

@bgamari please make sure that both MRs land into the same GHC release.

**Comment by bgamari** [comment]
Implementation in [!11347](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11347).

**Comment by Bodigrim** [comment]
@bgamari I'm not sure what's happened here. The proposal we approved meant to introduce `Data.Bounded` for `class Bounded` and `Data.Enum` for `class Enum`. Yet in `base-4.20` I observe [`Data.Enum`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Enum.html) with both type classes, but no `Data.Bounded` at all. There is neither changelog nor `@since` pragma. Even more confusingly, the MR which was meant to implement the proposal remains unmerged: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11347

I'm not sure what to do, the genie is out of the bottle. We cannot reasonably remove `class Bounded` from `Data.Enum` now. Does it still make sense to introduce `Data.Bounded`?..
