### ISSUE TITLE
Represent `GHC.InfoProv.InfoProv.ipDesc` and `GHC.Stack.CloneStack.StackEntry.closureType` as `ClosureType`

### ISSUE THREAD

**Issue by TeofilC** [haskell/core-libraries-committee#210]
### Summary

`GHC.InfoProv.InfoProv` and `GHC.Stack.CloneStack.StackEntry` both represent information about Haskell heap values. Part of this information is the closure type of the heap object. Currently this is represented as the C-enum value that corresponds to the relevant closure type.

`GHC.InfoProv` exports a `whereFrom` function that allows users to access IPE information for debugging purposes. As this is a user facing function, it would be nicer to directly see the closure type rather than having to look up the meaning of the constant in the RTS. 

A type already exists that represents GHC's closure types: `GHC.Exts.Heap.ClosureTypes.ClosureType`. Yet, since this type lives in `ghc-heap`, it can't be imported by a module in `base`. 

But it could easily be moved to new `ghc-internal` package, so, `base` can access it with it's "true home" staying in `ghc-heap`.

### Proposal

1.  Change the `ipDesc` field of `GHC.InfoProv.InfoProv` from `String` to `ClosureType`.
2.  Change `closureType` field of `GHC.Stack.CloneStack.StackEntry` from  `Word` to `ClosureType`.

My understanding is that the work to move the `ClosureType` sum type into `ghc-internal` is outside the purview of the CLC, but of course feedback is welcome.

My aim is to get this merged as part of GHC 9.10 (base-4.20).

I have written up an MR here: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9560

Here is what the output from `whereFrom` now looks like:
```
> whereFrom x
Just (InfoProv {ipName = "Foo_con_info", ipDesc = CONSTR_1_0, ipTyDesc = "", ipLabel = "", ipMod = "Test", ipSrcFile = "", ipSrcSpan = ""})
```

### History
There was a previous proposal to accomplish something similar: https://github.com/haskell/core-libraries-committee/issues/122 (thanks to @mpickering for writing it up!).

This differs in that it doesn't propose exporting `ClosureType` from `base`, which seemed to be the main objection.

### Impact assessment
AFAICT neither of these types are used on Hackage (yet). 
Additionally `GHC.InfoProv` is among the list of modules marked as having an unstable interface in: https://github.com/haskell/core-libraries-committee/issues/146#issuecomment-1579347317

My understanding is that `GHC.Stack.CloneStack` is part of the native Haskell backtraces initiative that will be part of GHC-9.10. And so wont have any uses until that's done.

In addition, as I said on the other proposal, if this gets accepted I'd be happy to publish a compatibility package that allows users to depend on either the old or new interface of `whereFrom` (via two major versions of the package).

**Comment by TeofilC** [comment]
I've prepared a package candidate for a version of the wherefrom compat package that exports the same interface for all previous versions of GHC that have this operation: https://hackage.haskell.org/package/wherefrom-compat-0.1.0.0/candidate

If this proposal gets accepted I'll start a new major version that will do the same for the new interface.

**Comment by TeofilC** [comment]
I will probably have to rebase the MR once Ben's [Move `base` implementation to `ghc-internal` MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11400) is merged. That shouldn't change anything outward facing about the MR just where typeclass instances are defined.

If no one has any thoughts by that point, then it might make sense to call a vote on this then. While the previous version of this was controversial because we were newly exporting GHC internals from base, I think this version is much less so.

Though if CLC feels they'd like more time to think it over, that's also OK and I'd be happy to delay until the next GHC release to not have to put pressure on folks.

**Comment by TeofilC** [comment]
I have rebased the GHC [MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9560). I think this should be ready for a vote now. How does that sound @Bodigrim?

Since it's been a while since this has been opened, I've redone the impact assessment.
Hackage search shows that `whereFrom` (from `base`) now has just 1 user: https://hackage-search.serokell.io/?q=whereFrom (the rest are stuff with the same name, just ghc/ghc-lib, or stuff  that uses `wherefrom-compat`)
1. `wherefrom-compat`, which is my compatibility package that allows depending on a stable interface even if the one in `base` changes

`nothunks` briefly used `whereFrom` directly but now goes through my compatibility package.

Because these are the only uses I don't think this should break any code on Hackage at all.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to represent `GHC.InfoProv.InfoProv.ipDesc` and `GHC.Stack.CloneStack.StackEntry.closureType` as `ClosureType` instead of `String`. This is a follow-up to #122, designed to address concerns raised by CLC members there, which I take as a sign that it's a priority for GHC developers to resolve.

@TeofilC did a very good job to summarise changes and impact in https://github.com/haskell/core-libraries-committee/issues/210#issue-1911762788. Essentially the change happens in `ghc-internal`, and `base` is affected only insofar it re-exports heap-related types. We already approved in https://github.com/haskell/core-libraries-committee/issues/146#issuecomment-1591871779 that `GHC.InfoProv` is to be designated as unstable. There are no customers affected on Hackage, and there is a compatibility package [`wherefrom-compat`](https://hackage.haskell.org/package/wherefrom-compat-0.1.1.0) in place. 

@tomjaguarpaw @hasufell @mixphix @velveteer @angerman @parsonsmatt 

----

+1 from me.

**Comment by parsonsmatt** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

----

This seems fine, given that we've designated `GHC.InfoProv` as unstable. (The Haddock comments explaining that it is unstable were added in August 2023 in `be1fc7df81736b5c8e42377b249ecf781de397f3`. I guess that was too late to be included in base-4.19.)

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.

**Comment by TeofilC** [comment]
Thanks folks!
