### ISSUE TITLE
Remove internal declarations from `GHC.InfoProv`

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#211]
I propose that the following declarations be removed from the exports of `GHC.InfoProv`:

* the `InfoProvEnt` kind (which is used internally to instantiate `Ptr`)
* the `ipeProv` function
* the `peekInfoProv` function

These were originally exposed only to use in the implementation of `GHC.Stack.CloneStack`. There are no users of any of these declarations on Hackage.

**Comment by hasufell** [comment]
Do you think it is not possible that someone uses this module for some meta programming? It seems usable. So maybe a deprecation period is better.

**Comment by bgamari** [comment]
While anything is possible, I don't see how these declarations are particularly useful for metaprogramming. Naturally, I may be missing something; perhaps you could clarify what use-case you had in mind?

**Comment by bgamari** [comment]
@hasufell ping.

**Comment by bgamari** [comment]
I would like to bring this to a vote.

**Comment by Bodigrim** [comment]
@bgamari is it possible to have a short deprecation period for these entities?

**Comment by Bodigrim** [comment]
@bgamari it would be great to hear from you on [the question above](https://github.com/haskell/core-libraries-committee/issues/211#issuecomment-1957982153).

**Comment by Bodigrim** [comment]
@bgamari I'll close as abandoned in two weeks unless you answer a question about a deprecation period.

**Comment by Bodigrim** [comment]
Closing as abandoned, feel free to reopen when there is time to respond.
