### ISSUE TITLE
Remove unstable heap representation details from `GHC.Exts`

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#212]
We propose to remove the following exports from `GHC.Exts`:
```haskell
data BCO#
mkApUpd0#      :: BCO# -> (# a #)
newBCO#        :: ByteArray# -> ByteArray# -> Array# a -> Int# -> ByteArray# -> State# s -> (# State# s, BCO# #)
```

 These functions expose extremely low-level interfaces which are likely to leak unstable implementation details to the user. To avoid future breakage, we propose that they be only accessible via `ghc-internal` after a deprecation period of one GHC release.

**Comment by konsumlamm** [comment]
It seems the type is actually called [`BCO`](https://hackage.haskell.org/package/base-4.18.1.0/docs/GHC-Exts.html#t:BCO), not `BCO#`.

**Comment by bgamari** [comment]
> It seems the type is actually called [`BCO`](https://hackage.haskell.org/package/base-4.18.1.0/docs/GHC-Exts.html#t:BCO), not `BCO#`.

Yes, quite right; I had forgotten that we renamed it due to [#17424](https://gitlab.haskell.org/ghc/ghc/-/issues/17424).

**Comment by hasufell** [comment]
If there's even a 1% chance someone might use it, we should do a deprecation phase first. I don't understand the purpose of those symbols enough to judge that. If in doubt, we can just deprecate with a short period.

**Comment by bgamari** [comment]
I would like to bring this to a vote.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to deprecate [`GHC.Exts.BCO`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-Exts.html#t:BCO), [`GHC.Exts.mkApUpd0#`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-Exts.html#v:mkApUpd0-35-) and [`GHC.Exts.newBCO#`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-Exts.html#v:newBCO-35-), and remove them one release later. They will remain accessible through future  `ghc-internal` package though. 

There does not seem to be any Hackage users outside of `ghc` itself: https://hackage-search.serokell.io/?q=%28%5E%7C%5B%5E%22%5D%5Cb%29%28BCO%5Cb%28%24%7C%5B%5E%23%27%5D%29%7CnewBCO%23%7CmkApUpd0%23%29

@tomjaguarpaw @hasufell @mixphix @velveteer @angerman @parsonsmatt 

----

+1 from me. No idea what it does, less cryptic stuff in `base` is better.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by velveteer** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.

**Comment by Bodigrim** [comment]
@bgamari please link an MR when ready.

**Comment by adamgundry** [comment]
I've opened https://gitlab.haskell.org/ghc/ghc/-/issues/25110 to track this on the GHC side.
