### ISSUE TITLE
Remove IOPort# and operations from `GHC.Exts`

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#213]
We propose to remove the following exports from `GHC.Exts`:
```haskell
data IOPort# s a
newIOPort# :: State# s -> (# State# s, IOPort# s o #)
readIOPort# :: IOPort# s o -> State# s -> (# State# s, o #)
writeIOPort# :: IOPort# s o -> o -> State# s -> (# State# s, Int# #)
```
These expose the `IOPort#` type used internally to implement WinIO. The semantics of this type are not of use to end users and there are no users on Hackage. We intend to remove this type from GHC as it is no longer used.

**Comment by hasufell** [comment]
I think I'd be fine with removing these without deprecation, unless someone can come up with an example how these might be used.

Unless other members have an argument why we should apply a deprecation policy without exceptions.

**Comment by bgamari** [comment]
Can we bring this to a vote?

**Comment by tomjaguarpaw** [comment]
+1

----

Even if someone was using them, if the type is no longer used in GHC then it won't be usable for that use case ...

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to remove `IOPort#` and operations on it from `GHC.Exts` as explained above. 

@hasufell @mixphix @velveteer @angerman @parsonsmatt 

----

+1 from me. Indeed there are [no users of `IOPort#` outside of `ghc-*` packages](https://hackage-search.serokell.io/?q=IOPort%23).

**Comment by velveteer** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.

**Comment by bgamari** [comment]
This will ultimately be implemented in [!8776](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8776)

**Comment by adamgundry** [comment]
I've opened https://gitlab.haskell.org/ghc/ghc/-/issues/25111 to track this on the GHC side.
