### ISSUE TITLE
Remove `.Internal` modules from `base`

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#217]
I propose that we remove the following `.Internal` modules from `base` after a deprecation period of one GHC release:

 * `GHC.TypeNats.Internal`
 * `GHC.TypeLits.Internal`
 * `GHC.ExecutionStack.Internal`

None of these have any uses on Hackage other than those which blindly reexport bits of `base`.

**Comment by phadej** [comment]
See https://github.com/haskell/core-libraries-committee/issues/171

**Comment by tomjaguarpaw** [comment]
> None of these have any uses on base other than ...

Should this be "None of these have any uses on *Hackage* other than ..."?

**Comment by bgamari** [comment]
Sigh, yes, thank you @tomjaguarpaw . The brain can be a strange thing.

**Comment by hasufell** [comment]
> See previous proposal #171, seems CLC wanted first deprecation, and only then removal.

I agree: even for morally internal modules, removing without deprecation period is not acceptable.

**Comment by bgamari** [comment]
I have proposed a deprecation period of one GHC release.

**Comment by bgamari** [comment]
I would like to bring this to a vote.

**Comment by adamgundry** [comment]
@Bodigrim is there anything blocking the CLC considering this? Did it perhaps slip through the cracks?

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to mark `GHC.TypeNats.Internal`, `GHC.TypeLits.Internal` and `GHC.ExecutionStack.Internal` as deprecated first and then remove them from `base` in the subsequent release. 

@tomjaguarpaw @angerman @parsonsmatt @velveteer @mixphix @hasufell 

----

+1 from me.

**Comment by velveteer** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

----

Great stuff

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve. @bgamari please link an MR when ready.

**Comment by alt-romes** [comment]
I have put up the MR for the deprecation of these modules in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12907.
