### ISSUE TITLE
Add a traceShowWithLabel function to Debug.Trace

### ISSUE THREAD

**Issue by OlegAlexander** [haskell/core-libraries-committee#224]
Hello! I'm new to Haskell coming from Python, Dart, and F#. When doing printf debugging in other languages, I usually add a label to the variable I'm printing. For example, in Python, I write `print("label", val)`.

Therefore, I've defined this function:

```haskell
debug :: Show a => String -> a -> a
debug label expr = trace (label ++ " " ++ show expr) expr
```

As a newcomer to Haskell, I was surprised that this function isn't already defined in `Debug.Trace` because it seems like a very common use case. The closest is `traceShowId`, but there is no label. The second closest is `traceShow`, which can be used like this: `traceShow ("label", val) val`, but then `val` has to be mentioned twice and the tuple doesn't look as nice as the space-separated version when printed.

This function does exist in the `hledger` library as [`dbg0`](https://hackage.haskell.org/package/hledger-lib-1.31/docs/Hledger-Utils-Debug.html#v:dbg0), but I may not want to install that entire package just to use this function. 

Does anyone have an appetite for a `debug` function like this? Or is there a better way to do what I'm trying to do with the existing `Debug.Trace` functions? Thank you!

Related: https://github.com/haskell/core-libraries-committee/issues/36

**Comment by hasufell** [comment]
Imo, `trace` is a low level primitive. Building on top of it should be left to libraries, especially when it's about formatting etc. E.g. in your proposed example, I can see a couple of alternative ways to format, e.g. using `": "`  instead of just whitespace. 

I don't think we want to get in the business of that.

Maybe contact @simonmichael whether he wants to build something like `trace-combinators`.

**Comment by OlegAlexander** [comment]
Thank you for replying. 

The colon can be left up to the user. If the user wants it, they can include it as part of the label, like `debug "label:" val`. But there should always be a space, regardless of punctuation. This isn't much different than the decision to include a newline at the end of `trace`. (By contrast, `printf` in C doesn't include a newline.)

I completely understand your point about `trace` being a primitive to build on. But other functions in Debug.Trace build on `trace` also, so the function I'm proposing would do the same. 

Do you at least agree that adding a label to a traced value is a very common use case?

**Comment by hasufell** [comment]
Sure, whitespace is a fairly safe default. I just don't see this function as a primitive anymore and can see this in different incarnations in more opinionated libraries.

**Comment by tomjaguarpaw** [comment]
+1 to @hasufell. The benefit of `debug label expr` over `traceShow (label, expr) expr` isn't big enough to be worth enlarging `base`, for me.

**Comment by OlegAlexander** [comment]
Ok, I see there's no appetite :) I agree that `traceShow` with a tuple is the closest, and it's actually the first solution I came up with. But it wasn't obvious at first. Can we at least update the doc string for `traceShow` from:

```haskell
>>> let f x y = traceShow (x,y) (x + y) in f (1+2) 5
(3,5)
8
```

to something like:

```haskell
>>> let f x y = traceShow ("x", x, "y", y) (x + y) in f (1+2) 5
("x",3,"y",5)
8
```

?

**Comment by tomjaguarpaw** [comment]
No need for CLC approval to update the docs. Just make an MR to the [ghc repo](https://gitlab.haskell.org/ghc/ghc/) and ask someone to review it.

**Comment by OlegAlexander** [comment]
Will do! Thanks!

**Comment by clyring** [comment]
If you don't mind `TupleSections`, `traceShowWith ("label",) expr` is reasonably adequate.

**Comment by OlegAlexander** [comment]
Hello again. I've created an account on https://gitlab.haskell.org/. However, I can't log in because of the following message:

```
Your account is pending approval from your GitLab administrator and hence blocked. 
Please contact your GitLab administrator if you think this is an error.
```

I waited for a few days, but I still can't log in. Can someone please help? My username is OlegAlexander.

**Comment by Bodigrim** [comment]
CC @chreekat

**Comment by chreekat** [comment]
@OlegAlexander is now approved

**Comment by chreekat** [comment]
@OlegAlexander ping me on the MR if you need anything else :)
