### ISSUE TITLE
Add `pure'` to `Control.Applicative`

### ISSUE THREAD

**Issue by liamzee** [haskell/core-libraries-committee#225]
### **Problem** ###
***

In do-notation, `pure` on its own is sort of useless with the left identity given that let expressions in do exist. In theory, it should be useful as a way to force evaluation to WHNF, but it isn't strict by default. You can get around it via `pure $!`, but that's a bit more verbose, and contains an operator that can be confusing to newbies.

`evaluate` is another alternative, and it avoids imprecise exceptions, but that's specialized to `IO`.

### **Proposed Change** ##
***

Add `pure'` to Control.Applicative,  where `pure'` is defined as `pure $!`, or better yet, `pure :: Applicative f => a -> f a; pure' !a = pure a`.

This also makes it easier to explain the identity laws because `foo <- pure $! foo` is a valid idiom when you want to specify an order of evaluation, whereas `foo <- pure foo` is usually better written with let expressions.

### **Impact Assessment** ##
***

A quick search on Hoogle shows that no libraries use pure', although one library uses return', which is exactly what it sounds like.

**Comment by konsumlamm** [comment]
`pure' foo` is just two characters less than `pure $! foo`, so I don't see any point in this. Also, you can just write `let !bar = foo` instead of `bar <- pure $! foo`. About the laws, I don't see how you think this would simplify them, laws usually ignore laziness anyway.

**Comment by liamzee** [comment]
https://book.purescript.org/chapter8.html

Purescript monad explanations, which seem to provide a reasonable justification for laws, except that who would foo <- pure someValue anyways? foo <- pure $! someValue at least has some point to it, and it's obvious why a normal person would be dependent on the Right Identity Law.

But you're right that this is essentially a spurious proposal, and I'll withdraw it.

**Comment by liamzee** [comment]
Someone pointed out that there is another way to get pure foo, so you can still recover the "why the left identity matters" part of the monad laws. Sorry, once again for spam, but thanks for the information, and otherwise, all's well that ends well.
