### ISSUE TITLE
Derive instance {Fractional, RealFrac, Floating, RealFloat} Compose f g a

### ISSUE THREAD

**Issue by jship** [haskell/core-libraries-committee#226]
In the same vein as #160, seems like `Compose` could use a few more instances:

```haskell
deriving instance Fractional (f (g a)) => Fractional (Compose f g a)
deriving instance RealFrac (f (g a)) => RealFrac (Compose f g a)
deriving instance Floating (f (g a)) => Floating (Compose f g a)
deriving instance RealFloat (f (g a)) => RealFloat (Compose f g a)
```

I'm working with a DSL that is compatible with `Compose`, so with these instances (in particular, `Fractional` and `Floating`) I can make numerical functions that are unconcerned with whether or not `Compose` is used under the hood for the values.

**Comment by tomjaguarpaw** [comment]
Can you show some examples?

**Comment by mixphix** [comment]
Yeah... we've already got `Num` instances, might as well add the rest of the `RealFrac` hierarchy. Writing integer literals for types that aren't plain numbers is fine I think, so why not decimals?

**Comment by Bodigrim** [comment]
@jship could you please raise an MR which CLC can vote on?

**Comment by jship** [comment]
Here's the MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11890

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add more numeric instances for `Compose f g a`, continuing the work started in #160. The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11890/diffs.

@tomjaguarpaw @mixphix @hasufell @velveteer @angerman @parsonsmatt 

----

+1 from me. The instances are automatic derivations, correct by construction.

**Comment by tomjaguarpaw** [comment]
+1

----

It seems like part of the point of having `Compose` is carrying all the instances over.

**Comment by velveteer** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
