### ISSUE TITLE
Add `sortOn` to `NonEmpty`, add haddock suggesting `sortBy . comparing`

### ISSUE THREAD

**Issue by 414owen** [haskell/core-libraries-committee#227]
<details>
<summary><h2>Initial proposal (obsolete)</h2></summary>

The same function has two different names across `List` and `List.NonEmpty`.
 I think we should unify the names with an add-deprecate-wait-remove cycle.

I think the name exported by both modules should be `sortOn`, for two reasons:
* It's less invasive to change `Data.List.NonEmpty` than `Data.List`.
* `sortOn` better describes what's happening, you're sorting the list on a projection of the elements.
   `sortWith` sounds like it might take a comparator, like `sortBy`.

I've done an initial impact assessment, and it looks like the only libraries using `Data.List.NonEmpty.sortWith` from [clc-stackage](https://github.com/Bodigrim/clc-stackage#how-to) are:

* [`rio`](https://hackage.haskell.org/package/rio)
* [`megaparsec`](https://hackage.haskell.org/package/megaparsec)
* [`extra`](https://hackage.haskell.org/package/extra)
* [`monad-schedule`](https://hackage.haskell.org/package/monad-schedule)

All of which are one or two line fixes.

</details>

### Problem

`List` exposes different sorting functions than `NonEmpty`. This is confusing and unintuitive. We should smooth out the APIs.

#### Current state of the world:

| |sortWith|sortOn|
|---|---|---|
| List | | ✓ |
| NonEmpty | ✓ | |

### Solution

* Add `sortOn` to `NonEmpty`
* Add performance notes to `{List,NonEmpty}.sortOn`, suggesting using `sortBy . comparing` for fast projections

#### Proposed state of the world:

| |sortWith|sortOn|
|---|---|---|
| List | | ✓ |
| NonEmpty | ✓ | ✓ |

Due to the existence and triviality of `sortBy . comparing`, which amounts to `sortWith`, `sortWith` will not be added to `List`.

This proposal has been implemented [here](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11826)

**Comment by 414owen** [comment]
*edit* there might be more packages affected than I thought. Will update with a more accurate picture when the rest compile.

**Comment by Bodigrim** [comment]
It's a complicated story :) 

* There exists [`GHC.Exts.sortWith :: (a -> b) -> [a] -> [a]`](https://hackage.haskell.org/package/base-4.19.0.0/docs/GHC-Exts.html#v:sortWith), which is operationally different from [`Data.List.sortOn :: (a -> b) -> [a] -> [a]`](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-List.html#v:sortOn). 
  * https://gitlab.haskell.org/ghc/ghc/-/issues/12044
  * https://gitlab.haskell.org/ghc/ghc/-/issues/14524

* Here is a discussion about `Data.List.sortOn` naming: https://mail.haskell.org/pipermail/libraries/2014-April/022489.html
* And here is one for `Data.List.NonEmpty.sortWith` https://github.com/ekmett/semigroups/pull/52#issuecomment-134751635
 
* A similar CLC proposal has been raised in 2020, left without a formal resolution (?):
  * https://groups.google.com/g/haskell-core-libraries/c/VuzuTH0n9bQ
  * https://mail.haskell.org/pipermail/libraries/2020-February/030256.html

**Comment by 414owen** [comment]
Interesting, thanks for the background.

It sounds like there's a raison d'être for functions with both sets of operational semantics (project once then sort, or project many times while sorting).

Maybe a way to make everyone happy would be to export both versions from `Data.List` and `Data.List.NonEmpty`.
This wouldn't require changing the implementation of any of the existing functions, but would be a purely-additive change?

**Comment by ChickenProp** [comment]
It was me who raised this before, so unsurprisingly I'm broadly +1; there are a lot of possible options here.

Fully in favor: add `NonEmpty.sortOn` with performance matching `List.sortOn`, and *document the difference from `sortWith`*. I think this is basically just a pure good.

I'm currently on the fence about subsequently deprecating and removing `NonEmpty.sortWith`. If we're just going to have one I'd prefer it be `sortOn`, but if it's a choice between `sortOn` and both... I think I lean towards keeping `sortWith` around, and maybe adding it to `Data.List` as well? Choosing some more descriptive name would also be reasonable, but offhand idk what that would be.

The thing is that I somewhat expect that `sortWith` has the performance characteristics that people want most often. E.g. `sortOn fst` will be inferior to `sortWith fst`. I expect people will pick what's convenient, so they'll use `sortOn` over `sortBy . comparing` even if the latter would be better for them. (Certainly that's how I behave. `comparing` isn't even in prelude! You can't expect me to add another import just for this.)

But when someone does want `sortOn`'s performance, that should be easily accessible to them as well, and currently in `NonEmpty` it's not really. The implementation in `Data.List` is

```haskell
sortOn f =
  map snd . sortBy (comparing fst) . map (\x -> let y = f x in y `seq` (y, x))
```

In particular, if that `seq` is doing something important then I expect people trying to implement this themselves to miss it.

So maybe it makes sense to have both easily available with a name. But having both of them feels like it imposes mental load on users, and that's not ideal either.

**Comment by 414owen** [comment]
Thanks @ChickenProp. I completely agree with adding `NonEmpty.sortOn`.

I ran some [quick benchmarks](https://414owen.github.io/sort-bench-hs/sorton-sortwith/) to determine at which point one should prefer `sortOn` to `sortWith`.  
If you're just accessing fields and not doing computation, then the answer is approximately six nested fields deep.

*insert usual benchmark disclaimers here*.

Additional disclaimer: `fst` is the fastest field accessor, `snd` is slightly more expensive, and accessing the seventh field is more expensive than that. *something something* cache lines.

## Which is more useful in practice

I work on a >100k line industrial haskell codebase, and we had 19 occurrences of `sortOn`.
All of these occurrences, bar one (which calls `length`), would be more efficient as `sortWith`.
There were all just accessing a single field of a product type.

I really think we should export `sortWith` from `Data.List`. It's often more efficient, and is buried in `GHC.Exts`.

**Comment by 414owen** [comment]
I would like to add that I think `sortOn` is a far better name for this function, and logically, the more common best choice (currently called `Exts.sortWith`) should have the best name, but I suspect that that ship has long since sailed, so it won't be part of any proposal I bring forth.

---

# Draft of proposal

1. Export `sortWith` from `Data.List`
2. Export `sortOn` from `Data.List.NonEmpty`
3. PR hackage packages that break. I suspect that a small subset of [this query](https://hackage-search.serokell.io/?q=import%5Cs*Data.List.NonEmpty%5Cs*%24) will break.

**Comment by 414owen** [comment]
Hi @tomjaguarpaw 

I certainly see the appeal for maintaining a lean API, but I'm primarily concerned with consistency between `List` and `NonEmpty` (where it makes sense, of course), and now that I know that these functions serve different use cases, I think that adding the missing functions symmetrically would be both less disruptive to the ecosystem, and more useful for end-users.

Your approach would presumable be something like:
- Add `sortOn` to `NonEmpty` (otherwise there would be *no* function with this type)
-  *Deprecate/Remove* `sortWith` from `NonEmpty`
- Add a note about `sortBy . comparing` to the haddock of `sortOn` (for people like me, who that `comparing` existed)

If you think that this is the way to go, I'd be happy to hear why the benefits outweigh the costs in a little more detail.

**Comment by tomjaguarpaw** [comment]
Yes, I think that's the way to go[^1], the benefit being that we avoid proliferating needless definitions, cf. [The Fairbairn Threshold](https://wiki.haskell.org/Fairbairn_threshold).

[^1]: although it might also suggest adding a note to `sortOn`, and perhaps breaking out `sortOn` and `sortBy` into their own "Sorting" section of the document, with some commentary that elaborates even further.

**Comment by 414owen** [comment]
I think that this is also a pretty reasonable solution. As long as the same functions end up exposed from `List` and `NonEmpty`, I'd be happy. Part of me would also be happy to see the back of `sortWith` because I don't think the name is very helpful.

Is there any chance people will get annoyed if we rip out `NonEmpty.sortWith` from under them?

It would be useful to have some idea of the support for both solutions. If you're reading this and have an opinion, I'd love to hear it. Should we migrate both modules to `sortOn`, or expose `sortWith` and `sortOn` from both `List` and `NonEmpty`?

**Comment by 414owen** [comment]
> I can confidently state we will not remove `sortWith`

That's a shame. Seems a bit like the worst of both worlds, we keep the function with the worse name around, and the modules still aren't consistent.

> but we should definitely disrecommend it in the documentation

I'm not sure I understand why. Surely being able to type `sortBy . comparing` isn't a reason *not* to use `sortWith`, if we have to keep it around?

**Comment by hasufell** [comment]
> In my opinion it absolutely is, because I don't want to see a proliferation of usage of small functions whose behavior is trivially replicated by composition of more basic functions. Others may have a different opinion.

I somewhat agree. I find it hard to memorize function names, unless they're natural concepts in my mind that I need **all the time**.

The same goes for `fromMaybe f`. I usually write `maybe f id`, because `maybe` , `either` etc. are inherently idiomatic.

**Comment by ChickenProp** [comment]
For whatever it's worth, I predict that:

* Given the choice between `sortOn` and `sortBy . comparing`, in cases where the latter is preferable, the former will still get used more than 2x as often; even if the docs say something like "prefer `sortBy . comparing` unless the sort key is expensive to compute".
* But if `sortWith` exists and the difference is well documented, people will use it significantly more often than `sortBy . comparing`; maybe still less than `sortOn` because people are used to `sortOn`, but like, trending in the right direction.

For example, I expect `sortOn fst` to be much more common than `sortBy (comparing fst)` or ``sortBy (compare `on` fst)`` in existing code. This is something we could test, I'm not sure if there's a good way to search hackage for parsed expressions but maybe a simple text search would be fine. (It would be less likely to find the more complicated expressions.) If I'm wrong about that then I think adding `Data.List.sortWith` does seem kinda pointless to me, though I'm still likely to use `sortOn` myself even if I "shouldn't".

(But if I'm right then it might still be pointless: the `sortOn` docs don't currently say that, they actually just describe it as a performance improvement over `sortBy . comparing`. And maybe this just isn't a crux for people.)

(`sortOn` only got added in base 4.8, I dunno offhand how old that is. But obviously code written before then or intended to be compatible that far back should be excluded from the comparison. Dunno how much of that there is.

**Comment by tomjaguarpaw** [comment]
> in cases where the latter is preferable, the former will still get used more than 2x as often

Amongst those 2x as many cases, how many do you think there will be where performance really matters? That is, how many will there be where someone is actually noticeably worse off by using the "wrong" formulation?

**Comment by ChickenProp** [comment]
My guess is probably not often, but that mostly depends on "how often does performance matter"; I don't think people will be much more likely to use `sortBy . comparing` when it does. (A little more likely, but not much.)

If we're talking about say a library that might get used with large data sets, I think that even when `sortBy . comparing` would be noticeably faster, it would be very easy to fail to notice that. So that seems like the kind of situation where "encourage people to do the right thing by default" is especially helpful.

But also, even when the difference is noticeable, I expect it to rarely be *very* noticeable.

**Comment by tomjaguarpaw** [comment]
Thanks. My current contention is that, in this case, the concern of keeping the API small and manageable far outweighs the concern of "make the naive choice the best performing one". As such I am inclined to hold to my original belief that we should include `sortOn` and deprioritise `sortBy` in the documentation, recommending `sortBy . comparing` as the alternative. I'm open to persuasion otherwise, but I expect to be hard to persuade.

**Comment by ChickenProp** [comment]
Yeah, seems reasonable. I think I disagree about how to weigh things, but I don't feel strongly about it, and I don't think I have anything to add that I expect to be persuasive.

**Comment by 414owen** [comment]
Okay, so it seems that the likely agreed upon way forward would be to:

* Add `sortOn` to `NonEmpty`
* Add notes about `sortBy . comparing` to `List.sortOn` and `NonEmpty.sortOn`

I've prepared an MR, implementing this change: [here](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11826)

Any extra changes anyone wants to get in?

**Comment by 414owen** [comment]
@Bodigrim do you think this is a good time to trigger a vote? It seems pretty uncontroversial now that there's no function removal happening...

**Comment by hasufell** [comment]
I don't see any argument against adding `sortOn`.

**Comment by ChickenProp** [comment]
To clarify, what compatibility patch are you thinking?

Taking a look, I found that it already has `sortOn` (going back to [1.6.15](https://hackage.haskell.org/package/extra-1.6.15/docs/Data-List-NonEmpty-Extra.html#v:sortOn), April 2019), which might cause some issues. Do you mean something to help resolve that, like "use CPP to only define that if base < whatever"?

**Comment by 414owen** [comment]
@ChickenProp that's what I assumed. The PR would look like [this](https://github.com/ndmitchell/extra/compare/master...414owen:extra:os/forward-compat-nonempty-sorton). I'll publish it when this is approved.

I'm happy to do similar for `base-compat`, etc.

**Comment by Bodigrim** [comment]
> @Bodigrim do you think this is a good time to trigger a vote? It seems pretty uncontroversial now that there's no function removal happening...

@414owen sorry, I'm being slow recently. Could you please update the top post, adding the final proposal at the end? So that there is no ambiguity what we are voting for.

**Comment by 414owen** [comment]
@Bodigrim No problem. Done.

**Comment by Bodigrim** [comment]
> Taking a look, I found that it already has `sortOn` (going back to [1.6.15](https://hackage.haskell.org/package/extra-1.6.15/docs/Data-List-NonEmpty-Extra.html#v:sortOn), April 2019), which might cause some issues. Do you mean something to help resolve that, like "use CPP to only define that if base < whatever"?

Yes, e. g., https://github.com/ndmitchell/extra/pull/103 and https://github.com/ndmitchell/extra/pull/101.

----

Dear CLC members, let's vote on the proposal to improve consistency between `Data.List` and `Data.List.NonEmpty` by introducing `Data.List.NonEmpty.sortOn`, which has the same memory and performance characteristics as `Data.List.sortOn` (different from existing `Data.List.NonEmpty.sortWith`, please refer to the discussion above). The MR https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11826 also adds some valuable documentation, which however does not require an explicit CLC approval.

@tomjaguarpaw @mixphix @hasufell @angerman @parsonsmatt @velveteer 

----

+1 from me, improved consistency and documentation are most welcome.

**Comment by angerman** [comment]
Looks reasonable to me: +1

**Comment by velveteer** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

----

> Do you mean something to help resolve that, like "use CPP to only define that if base < whatever"?

The suggested approach doesn't make sense to me. If I use `extra` to obtain `sortOn` then my code will break in GHC 9.10. By contrast, if the compatibility patch re-exported `Data.List.NonEmpty.sortOn` for GHC 9.10 then this would provide a genuine compatibility shim.

**Comment by ChickenProp** [comment]
Data.List.NonEmpty.Extra already re-exports all of Data.List.NonEmpty.

**Comment by tomjaguarpaw** [comment]
Ah, got it, thanks!

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
