### ISSUE TITLE
Expand Ord instance for Down

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#23]
This seems like a rather shocking oversight for a type explicitly designed around `Ord`, but the `Ord (Down a)` instance doesn't define most `Ord` methods, making any method-specific optimizations and domain expansions(*) unavailable. Currently,

```haskell
instance Ord a => Ord (Down a) where
    compare (Down x) (Down y) = y `compare` x
```

I propose we change this to

```haskell
instance Ord a => Ord (Down a) where
    compare (Down x) (Down y) = y `compare` x
    Down x < Down y = y < x
    Down x > Down y = y > x
    Down x <= Down y = y <= x
    Down x >= Down y = y >= x
    min (Down x) (Down y) = Down (max y x)
    max (Down x) (Down y) = Down (min y x)
```

Unfortunately, that's not the only way to do it. We could, for example, write `Down a < Down b = a > b`, or `min (Down x) (Down y) = Down (max y x)`. I think the way I proposed is the right way:

1. It follows the pattern set by `compare`.
2. I conjecture that `<=` and `<` are more likely to be given optimized custom definitions, and also used more often, than `>=` and `>`. If that's the case, then keeping them matched might be better for performance.
3. ~~Swapping `min` and `max` arguments would be surprising.~~ Swapping the `min` and `max` arguments makes any laziness work out consistently. For each method, the `Down` version is lazy in its first/second argument if and only if the underlying version is lazy in its second/first argument.

(*) There is a semantic improvement for `min` and `max` in some special cases.

```haskell
data LNat = Z | S LNat
  deriving Eq
instance Ord LNat where
  compare Z (S _) = LT
  compare (S _) Z = GT
  compare Z Z = EQ
  compare (S m) (S n) = compare m n

  min (S m) (S n) = S (min m n)
  min _ _ = Z

  max Z n = n
  max m Z = m
  max (S m) (S n) = S (max m n)

inf :: LNat
inf = S inf
```

Currently, `min inf inf = max inf inf = _|_`. With the proposed change, `min inf inf = max inf inf = inf`.

**Comment by Bodigrim** [comment]
LGTM. I do not particularly care about `Down x < Down y = y < x` vs `Down x < Down y = x > y`, but having methods spelt out is an improvement.

**Comment by treeowl** [comment]
I'm having second thoughts about `min` and `max`. I now think we probably *should* swap their argument orders. With the rest of the proposed definitions, `method` is lazy in its first/second argument if and only if `method` for `Down` is lazy in in its second/first argument. We should probably make it work the same way for `min` and `max`. I don't know the right proposal amendment process; should I just edit the above?

**Comment by Bodigrim** [comment]
@treeowl feel free to edit.

**Comment by treeowl** [comment]
Edited!

**Comment by Bodigrim** [comment]
@treeowl could you please raise an MR, so that we can have a formal vote?

**Comment by treeowl** [comment]
Sure!

**Comment by treeowl** [comment]
@cgibbard I would particularly appreciate your thoughts on the `max`/`min` question.

**Comment by gwils** [comment]
+1 on this.

**Comment by Bodigrim** [comment]
@treeowl this awaits for an MR.

**Comment by cgibbard** [comment]
> @cgibbard I would particularly appreciate your thoughts on the `max`/`min` question.

I don't feel super-strongly about it, but what you have there at the moment looks good to me -- seems natural to uniformly flip the arguments.

**Comment by Bodigrim** [comment]
@treeowl just a gentle reminder that this proposal needs an MR before holding a vote.

**Comment by konsumlamm** [comment]
Would it be fine if I raised an MR instead, using the definition proposed above? I'd like to see this moving forward!

**Comment by Bodigrim** [comment]
Please go ahead!

**Comment by konsumlamm** [comment]
Done: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8565.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8565. 
@tomjaguarpaw @chessai @mixphix @emilypi @cgibbard 

----

+1 from me.

**Comment by mixphix** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by emilypi** [comment]
+1

**Comment by chessai** [comment]
+1

**Comment by cgibbard** [comment]
+1

**Comment by Bodigrim** [comment]
Approved unanimously! Thanks all.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Author**             |  @treeowl, @konsumlamm   |
| **Status**             |  merged |
| **`base` version**     | `4.18.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8565 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | missing (please, [raise an MR to `base` to update changelog][changelog])  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
