### ISSUE TITLE
Treat all FDs as "nonblocking" on wasm32

### ISSUE THREAD

**Issue by TerrorJack** [haskell/core-libraries-committee#234]
Hi CLC members! Based on my recent work in the ghc wasm backend, I would like to make a wasm-specific proposal. The high level tl;dr is simple: on wasm32, treat all FDs as "nonblocking" unconditionally, therefore always performing the underlying read/write operation directly while avoiding the usage of `poll()` to actually wait for the FD's readiness. This makes I/O much more robust on wasm32, especially in browsers, where there's no satisfactory implementation of the `poll_oneoff` wasi syscall.

This has already been implemented in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11697. The patch only affects the `wasm32` platform and doesn't touch any other platforms, while fixing a few test cases previously marked as fragile on `wasm32`. The merge request contains more detailed explanations, so I'd like to use that as the source of truth for the time being, but feel free to ask any questions or require more clarifications here :)

**Comment by Bodigrim** [comment]
The only change in question is in `cbits/InputReady.c`, not even in Haskell parts of `base`, and indeed guarded by `#if defined(wasm32_HOST_ARCH)`. I trust @TerrorJack to know what is best for WASM backend; unless there are other opinions, I'll trigger a vote soon.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to change `fdReady` in `cbits/InputReady` to be `const True` under WASM backend. See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11697/diffs for details and tests. 

@mixphix @hasufell @velveteer @angerman @parsonsmatt @tomjaguarpaw 

----

+1 from me. The change fixes several tests, which were marked as fragile before.

**Comment by hasufell** [comment]
+1

**Comment by velveteer** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

----

I agree with @Bodigrim's assessment here: https://github.com/haskell/core-libraries-committee/issues/234#issuecomment-1890470215

**Comment by Ericson2314** [comment]
Is there some upstream discussion of `poll_oneoff` not working well? I would be curious.

**Comment by angerman** [comment]
+1 on this.

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
