### ISSUE TITLE
Add `CostCentreId`, `currentCallStackIds`, `ccsToIds`, and `ccId` to base

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [haskell/core-libraries-committee#235]
`GHC.Stack` and `GHC.Exts` export `currentCallStack :: IO [String]`, which provides the current cost centre stack as a list of cost centre names. It would be nice if these modules also exported an opaque `CostCentreId` type and a function `currentCallStackIds :: IO [CostCentreId]`, which provided the current cost centre stack as a list of cost centre IDs. The `CostCentreId` would be a newtype around the current internal `Word32` representation of cost centre IDs.

Since the event log profiling events represent the current cost centre stack as a list of IDs, such a function would make it easier to link cost centre stacks included in the event log with cost centre stacks sampled by the mutator. Additionally, it would make it easier to convert cost centre stacks sampled by the mutator into formats acceptable by tooling that typically supports the event log representation. The latter is the use case I have encountered.

I've implemented [a patch](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11798) for this, and the specific changes to the exposed modules are as follows:

- `GHC.Stack` and `GHC.Stack.CCS`: Add the following exports:
    - Opaque `CostCentreId` newtype with stock-derived `Show` and `Read` instances and newtype-derived `Eq`, `Ord`, `Bounded`, `Enum`, `Integral`, `Num`, and `Real` instances
    - `currentCallStackIds :: IO [CostCentreId]`
    - `ccsToIds :: Ptr CostCentreStack -> IO [CostCentreId]`
    - `ccId :: Ptr CostCentre -> IO CostCentreId`
- `GHC.Exts`: Add the `CostCentreId` and `currentCallStackIds` exports.

Searching Hackage for `CostCentreId`, `currentCallStackIds`, `ccsToIds`, and `ccId` only yields results for `ccId`. As far as I can tell, none of the modules which already include a `ccId` identifier import the affected modules directly or transitively, so there should be minimal to no breakage.

**Comment by hasufell** [comment]
Since these are potentially GHC internals, CCing @bgamari @mpickering

**Comment by TeofilC** [comment]
A minor point: Is it necessary that we expose that these are represented internally as a `Word32`? Would it be enough to export an opaque newtype (say called `CostCentreId`) with appropriate instances instead?

**Comment by Bodigrim** [comment]
Sorry, @FinleyMcIlwaine, this fell through the cracks.

> A minor point: Is it necessary that we expose that these are represented internally as a `Word32`? Would it be enough to export and use a newtype (say called `CostCentreId`) with appropriate instances instead?

I think this is a very good idea.

**Comment by bgamari** [comment]
> I think this is a very good idea.

I wholeheartedly agree. I am opposed to exposing this as `Word32` directly.

**Comment by FinleyMcIlwaine** [comment]
Thanks for the comments! I've addressed them and updated the implementation and description of this proposal to reflect the new details. With that I believe this is ready for another review.

**Comment by Bodigrim** [comment]
Thanks @FinleyMcIlwaine, makes sense to me. 

How important is to export it from `base` and not just from `ghc-internals`? Do we expect this interface to be stable? Do we expect this interface to be used by packages, which otherwise do not rely on low-level GHC details from `ghc-internals`?

**Comment by FinleyMcIlwaine** [comment]
I do expect this interface to be stable, but I don't expect it to be used by many packages that do not otherwise rely on low-level GHC details. So reconsidering this, I think exporting from just `ghc-internal` would be most appropriate. I'll go that route and close this for now. Thanks for the comments and feedback!
