### ISSUE TITLE
Add `MonadFix` instance for tuples

### ISSUE THREAD

**Issue by ncfavier** [haskell/core-libraries-committee#238]
```haskell
instance Monoid a => MonadFix ((,) a) where
  mfix f = let (a, b) = f b in (a, b)
```

This is already implemented for `WriterT` in `transformers`, so not having it for tuples seems like an oversight?

Note that this enables a terse implementation of a [trace](https://ncatlab.org/nlab/show/traced+monoidal+category) operator as `trace f = fst . mfix . f`.

**Comment by tomjaguarpaw** [comment]
Could you give an example of how one might use `mfix` or `trace`?

**Comment by ncfavier** [comment]
See [Circular programming on the Haskell wiki](http://wiki.haskell.org/Circular_programming) for a concrete example, and [Value Recursion in Monadic Computations](https://leventerkok.github.io/papers/erkok-thesis.pdf) by Levent Erkök for more in-depth exploration of the theory, especially section 4.5 for the proposed instance (RepM being the usual writer monad for tuples) and section 9 for examples.

**Comment by tomjaguarpaw** [comment]
Thanks. Those are rather involved works! A small self-contained example, or collection of examples, pasted in a comment here, would go a long way to motivating this proposal.

**Comment by Bodigrim** [comment]
@LeventErkok could you possibly comment on the addition of `instance MonadFix ((,) a)` to `base`?

**Comment by LeventErkok** [comment]
Not that I'm the decision maker here, but I'm really hesitant to add new instances to the `(,) a` zoo.

Strictly speaking, there's nothing wrong with this. It makes sense, it's lawful, and from one perspective it's "missing." On the other hand, I never liked the instances for `(,) a` for any class: The asymmetry in the treatment of arguments always bothered me, along with the fact that only tuples are supported, but not n-tuples, for any other `n`. Of course, the `MonadFix` instance is not as bad as one for `Foldable` (which still gives me nightmares, to be honest), but the point stands.

So, in terms of "completeness," I'd say sure. But from a practitioner's perspective, I see very little value in adding this instance. Users can define it if they want (at the cost of an orphan-instance, perhaps?), and the fact that you're recursing on the second argument isn't forced on anyone; if they have a more compelling reason to do it in some other way, and perhaps even wrap it in a custom data-type to make it absolutely clear. Generic instances like this make unnecessary choices, which make them hard to grok.

That's my take on it; sorry not a simple "yes/no" answer. My gut instinct says don't pollute the already confusing `(,) a` instance zoo in Haskell, but perhaps @ncfavier can argue why this instance would make life really easy for some application. If that's the case, then I don't see any harm.

**Comment by hasufell** [comment]
I'm also rather -1 on this.

Wrt classes and instances I'm very conservative, unless Edward starts getting annoyed, which usually means there's a solid use case in the kmettverse.

Here I don't see a solid case yet.

**Comment by ncfavier** [comment]
Fair enough, I don't have anything to add.

**Comment by hasufell** [comment]
@ncfavier only 2 out of 7 committee members gave their non-binding opinion. I suggest to still see the discussion through, maybe some of the other members are strongly in favor or even have arguments to convince the rest.

**Comment by phadej** [comment]
FWIW, the `Monad ((,) a` instance is relatively fresh (GHC-8.0, haven't been around "always"):

```haskell
-- | @since 4.9.0.0
instance Monoid a => Monad ((,) a) where
    (u, a) >>= k = case k a of (v, b) -> (u <> v, b)
```

https://gitlab.haskell.org/ghc/ghc/-/commit/9db005a444722e31aca1956b058e069bcf3cacbd

> This was proposed a couple of times in the past, e.g.
> 
> - https://mail.haskell.org/pipermail/libraries/2011-November/017153.html
>  - https://mail.haskell.org/pipermail/libraries/2013-July/020446.html
>
> but its implementation had been blocked by the fact that `Monoid` wasn't
> in scope where the `Monad` class was defined. Since the AMP/FTP restructuring
> this is no longer the case.

It's arguable that if `MonadFix` instance doesn't fit into `base`, maybe `Monad` instance could be also marked as "don't use, use `Writer`" e.g. if/when GHC would be able to warn about use of "questionable" instances, surely many will agree to warn about `Foldable ((,) a)`, but what about `Monad ((,) a`?

**Comment by Bodigrim** [comment]
I'm largely in favor of the proposal: paraphrasing Polonius, let there at least be method in this madness. If there is `instance Monoid a => Monad ((,) a)`, having `instance Monoid a => MonadFix ((,) a)` is more self-consistent, does not hurt anyone and makes at least one person (the proposer) happier.

**Comment by Bodigrim** [comment]
That said, I'd like to see proofs that all `MonadFix` laws hold for the proposed instance.

**Comment by ncfavier** [comment]
The laws are proved in section 4.5 of the aforementioned [thesis](https://leventerkok.github.io/papers/erkok-thesis.pdf), but I will spell them out below; see there for details.

I will use the following equivalent definitions for `mfix`:

```haskell
mfix :: (b -> (a, b)) -> (a, b)
mfix f = let (a, b) = f b in (a, b)
mfix f = fix (f . snd)
```

### Purity

```haskell
h :: a -> a

  mfix (return . h)
= let (a, b) = (mempty, h b) in (a, b)
= let b = h b in (mempty, b)
= (mempty, fix h)
= return (fix h)
```

### Left shrinking

```haskell
(a, b) :: (a, b)
f :: c -> b -> (a, c)

  mfix (\x -> (a, b) >>= \y -> f x y)
= mfix (\x -> let (a', c) = f x b in (a <> a', c))
= fix (\x -> let (a', c) = f (snd x) b in (a <> a', c))
= let (a', c) = f c b in (a <> a', c)
= let (a', c) = fix (\x -> f (snd x) b) in (a <> a', c)
= let (a', c) = mfix (\x -> f x b) in (a <> a', c)
= (a, b) >>= \y -> mfix (\x -> f x y)
```

### (Strong) sliding

Note the absence of a precondition on `h`.

```haskell
f :: a -> (b, c)
h :: c -> a

  mfix (fmap h . f)
= fix (fmap h . f . snd)
= fmap h (fix (f . snd . fmap h)) -- dinaturality of fix
= fmap h (fix (f . h . snd))      -- naturality of snd
= fmap h (mfix (f . h))
```

### Nesting

```haskell
f :: (b, b) -> (a, b)

  mfix (\x -> mfix (\y -> f x y))
= fix (\x -> fix (\y -> f (snd x) (snd y)))
= fix (\x -> f (snd x) (snd x))             -- Bekič's property for f `on` snd
= mfix (\x -> f x x)
```

**Comment by tomjaguarpaw** [comment]
I realised that you can write `f -> let b = fix (fst . f) in (b, snd (f b))` to get something equivalent, except that it loses the opportunity to share work in `f`. So `mfix` for pairs is something like "`fix` but also return an additional result depending on the recursive value". I guess that's plausibly useful, but I don't see how to use it immediately.

**Comment by Bodigrim** [comment]
@mixphix @parsonsmatt @angerman @velveteer any non-bindings opinions on this please?

**Comment by parsonsmatt** [comment]
I don't have an opinion on this one

**Comment by Bodigrim** [comment]
@ncfavier if you wish to proceed with the proposal, could you please prepare a GHC MR before we vote?

**Comment by Bodigrim** [comment]
Also I would love to hear more non-binding opinions on this from CLC members. CC @mixphix @angerman @velveteer

**Comment by ncfavier** [comment]
https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12060

**Comment by angerman** [comment]
I'm leaning +1 for consistency reasons.

**Comment by Bodigrim** [comment]
> Wrt classes and instances I'm very conservative, unless Edward starts getting annoyed, which usually means there's a solid use case in the kmettverse.

@ekmett any opinions? ;)

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add `instance Monoid a => MonadFix ((,) a)`, matching modulo newtypes the existing `MonadFix` instance for `WriterT Identity`. There is already `instance Monoid a => Monad ((,) a)`. The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12060 and proofs of `MonadFix` laws are given in https://github.com/haskell/core-libraries-committee/issues/238#issuecomment-1887593544.

@tomjaguarpaw @mixphix @velveteer @angerman @parsonsmatt @hasufell 

----

+1. If there is `instance Monoid a => Monad ((,) a)` and also all `Monad` / `MonadFix` instances for `WriterT Identity`, it would be more consistent to have `instance Monoid a => MonadFix ((,) a)`. It does not harm anybody and it makes at least one person (the proposer) happier :) 

I verified the proofs of `MonadFix` laws, seems all correct.

**Comment by angerman** [comment]
Still +1 on this.

**Comment by tomjaguarpaw** [comment]
-1

----

I prefer to add this only when we've seen a practical use case.

**Comment by hasufell** [comment]
-1

**Comment by ncfavier** [comment]
Changes to the `MonadFix` documentation are orthogonal to this proposal. I am suggesting to add the¹ `MonadFix` instance for tuples, not some "esoteric" instance that needs explanation. There is nothing interesting or new about this instance that you can't get from its type.

[1] I can produce a proof that this instance is unique, if pressed sufficiently hard.

**Comment by Bodigrim** [comment]
@velveteer @parsonsmatt just a gentle reminder to vote.

**Comment by parsonsmatt** [comment]
+1

**Comment by velveteer** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
