### ISSUE TITLE
Representation-polymorphic `flip`

### ISSUE THREAD

**Issue by Bodigrim** [haskell/core-libraries-committee#245]
In the same vein as #132 and #158, I'd like to make `flip` representation-polymorphic:
```haskell
flip :: forall repc a b (c :: TYPE repc). (a -> b -> c) -> b -> a -> c
flip f x y = f y x
```
This would allow, for instance, to define `(&) = flip id` without compromising its representational polymorphism.

The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12795

The change is strictly speaking breaking, but only in very minor way. It adds another `forall`'d variable, so explicit type applications `flip @t` will be affected. This seems to be an unlikely pattern to encounter (you'd probably better apply types to the argument of `flip`, not to `flip` itself) and indeed impact assessment using [`clc-stackage`](https://github.com/haskell/clc-stackage) did not reveal any breakage. Another point of reference is that the same breaking change to `($)` in `base-4.19` passed entirely unnoticed in the wild, I have not seen a single report of breakage.

----

As suggested [below](https://github.com/haskell/core-libraries-committee/issues/245#issuecomment-1952561935), we could have used "curly braces" syntax to hide `repc` from a list of explicitly applicable types. This would however introduce a discrepancy with [`($)`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Function.html#v:-36-) and [`(&)`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Function.html#v:-38-), while the goal of the proposal is to reduce it.

**Comment by tomjaguarpaw** [comment]
My vote will be -1, similar to https://github.com/haskell/core-libraries-committee/issues/132#issuecomment-1485331648 and https://github.com/haskell/core-libraries-committee/issues/158#issuecomment-1538458756.

**Comment by sjoerdvisscher** [comment]
Should it maybe be
```haskell
flip :: forall {r} a b (c :: TYPE r). (a -> b -> c) -> b -> a -> c
flip f x y = f y x
```
to prevent this from being a breaking change?

**Comment by Bodigrim** [comment]
@mixphix thanks for noticing it. I think it's exceedingly rare to use visible type applications with `flip`, because one would be better off to specify type of `flip`'s argument. But I'll prepare an impact assessment to be sure.

@sjoerdvisscher that's a good idea, I keep forgetting about the curly syntax. OTOH it would be not consistent with the current definitions of `($)` and `(&)`.

**Comment by sjoerdvisscher** [comment]
It's probably a good rule of thumb to use curly braces on all type arguments that can be inferred from the kinds of other type arguments. The types of `($)` and `(&)` really should be changed too in my opinion.

**Comment by tomjaguarpaw** [comment]
This isn't just levity polymorphic, right? It's polymorphic over all representations. I think a levity polymorphic `flip` would be more restrictive:

```.hs
flip :: forall (lev :: Levity) a b (c :: TYPE (BoxedRep lev)). (a -> b -> c) -> b -> a -> c
flip f x y = f y x
```

**Comment by phadej** [comment]
> It's probably a good rule of thumb to use curly braces on all type arguments that can be inferred from the kinds of other type arguments.

I slightly disagree. As GHC doesn't give a way to explicitly apply curly type arguments, it's not an easy choice when designing the API. Not being able to explicitly type apply can be quite annoying when you really need that.

**Comment by tomjaguarpaw** [comment]
I agree with @phadej. Having an argument which is *impossible* to supply manually is actually extremely annoying in some cases.

**Comment by Bodigrim** [comment]
> This isn't just levity polymorphic, right? It's polymorphic over all representations.

You are right, let me update the title.

----

Given that there was no backlash for representational polymorphism changes to `($)` and `(&)` and there are zero known examples of breakage, I'd rather keep things explicit and pursue for `flip :: forall r a b (c :: TYPE r). ...` without curly braces. I have to prepare an impact assessment though.

**Comment by Bodigrim** [comment]
I've updated the proposal. The impact assessment did not reveal anything, so I believe it is good to go without "curly braces" contraption.

**Comment by Bodigrim** [comment]
If there are no further comments, I'll trigger a vote soon.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to make [`flip`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Function.html#v:flip) representation-polymorphic, so that the return value is not limited to [lifted data](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Kind.html#t:Type):
```haskell
flip :: forall repc a b (c :: TYPE repc). (a -> b -> c) -> b -> a -> c
flip f x y = f y x
```
The change is a continuation of earlier proposals #132 and #158 and aims to make `flip` more consistent with `($)` and `(&)`. The impact assessment did not reveal any breakage. 

@hasufell @mixphix @velveteer @angerman @parsonsmatt @tomjaguarpaw 

----

+1 from me, unsuprisingly.

**Comment by tomjaguarpaw** [comment]
-1

----

as per https://github.com/haskell/core-libraries-committee/issues/245#issuecomment-1949244983

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
@velveteer @angerman @parsonsmatt just a gentle reminder to vote.

**Comment by velveteer** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
