### ISSUE TITLE
Add specialized sconcat implementation for Data.Semigroup.First

### ISSUE THREAD

**Issue by Celestial-Gemstone** [haskell/core-libraries-committee#246]
The default implementation of `sconcat` is strict in its spine.
This means that even though in the instance of `First a` we have the lazy `x <> _ = x`, `sconcat $ First () :| undefined` outputs `First {getFirst = *** Exception: Prelude.undefined...`.

I think this should be changed, by having a non-default implementation of `sconcat` as
```hs
sconcat (x :| _) = x
```

This will also have performance benefits when the spine takes time to compute.

This is 'breaking' in the sense that a program that might previously have errored would work fine now. No program that previously worked would not work with this change *unless* the strictness in the spine triggered a side-effect, which would only be possible with `unsafePerformIO` I believe.

This would make this instance more in line with other `Semigroup` instances like `()` which also provides a custom `sconcat` implementation for laziness.

**Comment by tomjaguarpaw** [comment]
> The default implementation of `sconcat` is strict in its spine.

It's not strict in the spine, it's just strict in the first `:` of (the second component of) the `NonEmpty`. This works fine, for example:

```
sconcat (First () :| (First () : undefined))
```

That's because the default implementation of `sconcat` is:

```.hs
        sconcat :: NonEmpty a -> a
        sconcat (a :| as) = go a as where
          go b (c:cs) = b <> go c cs
          go b []     = b
```

You can't do better than forcing `:` in general, because you need to know whether there will be another element coming -- you don't have `mempty`! But yes, it seems pretty plausible that for `First` we should have a specialised implementation.

It should be

```.hs
        sconcat :: NonEmpty a -> a
        sconcat (a :| as) = go a as where
          go b ccs = case css of
            c : cs -> go c cs
            []     = b
```

**Comment by parsonsmatt** [comment]
There are two `First`s - one in [`Data.Monoid`](https://www.stackage.org/haddock/lts-22.7/base-4.18.2.0/Data-Monoid.html#t:First) which is `newtype First a = First (Maybe a)` and one in [`Data.Semigroup`](https://www.stackage.org/haddock/lts-22.7/base-4.18.2.0/Data-Semigroup.html#t:First), which is `newtype First a = First a`.

For the `Semigroup.First` type, I think the specialized implementation of `sconcat (a :| _) = a` makes sense.#248 

For the `Monoid.First` type, I think the implementation can be improved too. 

```haskell
instance Semigroup (Monoid.First a) where
  sconcat (Monoid.First ma :| rest) = 
    case ma of
      Nothing -> mconcat rest
      Just a -> Monoid.First (Just a)
```

This allows the implementation to avoid forcing the list if the first value is present, and only inspect the rest of the list if the first element is `Nothing`.

**Comment by Celestial-Gemstone** [comment]
> Do you have a merge request?

Not yet but I would be happy to implement these

**Comment by Celestial-Gemstone** [comment]
I have opened a merge request at [!11983](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11983)
As far as I understand I now need to wait for the approval (or disapproval) of the CLC (?)

**Comment by treeowl** [comment]
This is yet another example of what I see as an unnatural definition of `NonEmpty` in the context of a lazy language. For this type, we don't have that problem:

```haskell
data NE a
  = End a
  | a :< NE a

neConcat :: Semigroup a => NE a -> a
neConcat (End a) = a
neConcat (a :< as) = a <> neConcat as
```

**Comment by Bodigrim** [comment]
@tomjaguarpaw @parsonsmatt are you happy with the MR? https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11983/diffs

**Comment by tomjaguarpaw** [comment]
Yes, fine.

**Comment by parsonsmatt** [comment]
Looks great to me!

**Comment by Bodigrim** [comment]
Seems we are good to go for a vote then. 

Dear CLC members, let's vote on the proposal to write specialised implementations of [`sconcat`](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Semigroup.html#v:sconcat) for [`Data.Semigroup.First`](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Semigroup.html#t:First) and [`Data.Monoid.First`](https://hackage.haskell.org/package/base-4.19.0.0/docs/Data-Monoid.html#t:First) as implemented at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11983/diffs. The default implementations are surprisingly strict, forcing list's spine past the first element even if it was sufficient to determine the outcome.

@tomjaguarpaw @parsonsmatt @angerman @hasufell @mixphix @velveteer 

----

+1 from me, this is a neat improvement.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by angerman** [comment]
+1 🤞 no one relies on the oddities of the current behavior.

**Comment by velveteer** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
