### ISSUE TITLE
Expose a `DynFlags` API in TH

### ISSUE THREAD

**Issue by MathiasSven** [haskell/core-libraries-committee#247]
Currently, accessing `DynFlags` seems to be possible only through the use of `unsafeCoerce` in order to interact with the `TcM`. I propose the addition of a new API under `Language.Haskell.TH.Syntax` that provides a principled way to access this information in Template Haskell. This shift in responsibility would ensure a stable API for `DynFlags` regardless of `Q` internals.

In line with preprocessors, there are situations where we desire different code generation based on compiler arguments, with TH today, we can already query a lot of information about the environment such as package root, env variables, and consequently a lot more via `runIO`. Compiler arguments, specially ones that impact the final code object, should be part of the list.

One example where that might be useful is dependency tracking via `addDependentFile`. With it, we can signal to GHC when a curtain file should be recompiled based on changes to another, but identifying what files should be tracked and where they reside might be information passed to the compiler, but not be present in the environment, as it is the case with C/C++ dependencies.

**Comment by Ericson2314** [comment]
Please no. `DynFlags` is terrible, and the big advantage of TH over plugins is it is not supposed to leak arbitrary compiler guts.

**Comment by Bodigrim** [comment]
@MathiasSven AFAIK `Language.Haskell.TH.Syntax` is a part of `template-haskell`, not `base`. CLC does not govern `template-haskell`, you might want to raise an issue at https://gitlab.haskell.org/ghc/ghc/-/issues instead.

**Comment by MathiasSven** [comment]
@Bodigrim Apologies, my understanding was that since `template-haskell` is a part of the core libraries, and this might be a rather controversial change, it was prudent to raise it here first. Should I withdraw the issue as out of scope?

**Comment by Bodigrim** [comment]
The policy for core libraries (except `base`) is to raise suggestions in respective issue trackers. If maintainers are not comfortable to decide on their own, they can seek CLC advice, but they are the first line of contact.

**Comment by parsonsmatt** [comment]
I would also be opposed to this - `DynFlags` is a really messy thing and would make upgrading `template-haskell` much harder across GHC versions. If I were the maintainers of TH or GHC then I would want to provide a much more specific API where maintaining backwards compatibility would be easier, both for library consumer and the author.

**Comment by MathiasSven** [comment]
If the concerns are around `DynFlags` itself not being a stable, I don't see that view as incompatible with the proposal. Although I disagree with the sentiment, in that, TH does not need to guarantee a stable `DynFlags`, it would only need to provide a stable way to access it. Would there be any objections on that front if some form of `DynFlags` (for better or worse) made its way in the current, ongoing effort to stabilize the GHC API?

No matter, a more specific API would still achieve the goal of giving TH more of the same information GHC has been given, my only concern is, how would one decide what should go in such an API? Some flags haven't had an update in over a decade, while some have seen some change in the last couple of years.

**Comment by Bodigrim** [comment]
Let me close this for now, please continue the discussion at GHC issue tracker. If stakeholders of `template-haskell` feel that they must get input from CLC, feel free to (ask to) reopen.
