### ISSUE TITLE
Improve documentation of `transformers`' `StateT` and `ExceptT` to highlight subtle interactions

### ISSUE THREAD

**Issue by Qqwy** [haskell/core-libraries-committee#251]
### Motivation
Whereas for hard-core long-time Haskellers these might _not_ be a surprise, as they are an (indirect) consequence of the fudamental nature of `ExceptT` and `StateT`, for people new to monad transformers (or frankly anyone not having been bitten by these subtle interactions before) these behaviours can be really surprising so it would be good to improve awareness.

Up to this point, and with the exception of [this article](https://github.com/haskell-effectful/effectful/blob/master/transformers.md), I believe these subtle interactions have been mostly 'tacit knowledge' which was obtained either from learning it from a senior haskeller already knowing about it, or by having to debug its symptoms in the wild yourself.

### Proposal

- Mention in the documentation of `StateT` that whenever a normal (`Control.Exception`) exception is caught, its state will have been reset to the point of before entering the 'try' action of the catch.
- Mention in the documentation of `ExceptT` and `StateT` that when a `StateT` is nested inside an `ExceptT`, its state will have been reset whenever `catchE`/`handleE` runs, and that the state does _not_reset when they are nested the other way around.
  - And that one should be especially mindful of this when programming against `(MonadError a m, MonadState b m)` constraints, as then a caller is free to choose either order, so behaviour can change based on a rearranged transformer stack in some remote place in the codebase. Also mention this in the documentation of the `MonadError`/ `MonadState` classes.
- Make it extra clear in the documentation of the `Control.Monad.Trans.ExceptT` (and `Except`) types that its 'exceptions' are plain values which are different from and incompatible with the exceptions of `Control.Exceptions`.
  - Also, use the term 'exception value' instead of 'exception' in all documentation of the module, to make it extra clear that they are plain values. <sub>Maybe in the future we could even move back to its original name `Error`/`ErrorT` and 'error value' though since that change would probably be more controversial, which is why it's not part of this proposal.</sub>

**Comment by Bodigrim** [comment]
Adding to @mixphix, documentation changes generally do not require a CLC approval, please take it to package's maintainers first. 

CC @RossPatterson on behalf of `transformers`.

**Comment by Bodigrim** [comment]
Adding to @mixphix, documentation changes generally do not require a CLC approval, please take it to package's maintainers first. 

CC @RossPaterson on behalf of `transformers`.

**Comment by RossPatterson** [comment]
> Adding to @mixphix, documentation changes generally do not require a CLC approval, please take it to package's maintainers first.
> 
> CC @RossPaterson on behalf of `transformers`.

Somehow this cc got sent to me.  Must be for some other "Ross".  Unsubscribing.

**Comment by gbaz** [comment]
indeed it should be @RossPaterson who is cc'd -- one t and not two. :-)

**Comment by Bodigrim** [comment]
Closing as out of scope.
