### ISSUE TITLE
Export `Data.Traversable.for` from the Prelude

### ISSUE THREAD

**Issue by mixphix** [haskell/core-libraries-committee#256]
[Merge request](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12113)

I did not test `clc-stackage` as there are many packages with version bounds in both the current cabal file and the latest Stackage Nightly release that do not include `base-4.19`.

**Comment by phadej** [comment]
> I did not test clc-stackage as there are many packages with version bounds in both the current cabal file and the latest Stackage Nightly release that do not include base-4.19.

That is very bad excuse. You are the member of CLC, if you don't bother to do that yourself, dont' ask anyone else either.

E.g. it looks that
- `Agda` will break https://hackage-search.serokell.io/viewfile/Agda-2.6.4.1/src/full/Agda/Utils/Functor.hs#line-33
- `hakyll` https://hackage-search.serokell.io/viewfile/hakyll-4.16.2.0/lib/Hakyll/Web/Template/Internal/Element.hs#line-204
- `statistics` https://hackage-search.serokell.io/viewfile/statistics-0.16.2.1/Statistics/Function.hs#line-125
- `streaming-bytestring` https://hackage-search.serokell.io/viewfile/streaming-bytestring-0.3.2/lib/Streaming/ByteString.hs#line-650

**Comment by Bodigrim** [comment]
@mixphix could you please give another go to https://github.com/haskell/clc-stackage? I was able to build it in full recently. 

(You'd have to backport your changes from GHC `master` to [`ghc-9.8`](https://gitlab.haskell.org/ghc/ghc/-/tree/ghc-9.8?ref_type=heads) branch, there is no newer Stackage)

**Comment by tomjaguarpaw** [comment]
If we're going to do this kind of thing could it be done based on an assessment of what actually gets imported from non-`Prelude` `base` libraries in practice?

**Comment by tomjaguarpaw** [comment]
I was thinking of doing an analysis of all code on Hackage to determine which identifiers are most imported from modules in `base` and adding the most commonly imported ones to the `Prelude` (in the absence of obvious name clashes, etc.).

**Comment by tomjaguarpaw** [comment]
As you wish. I think your proposal would be much stronger if it was backed by numerical evidence, but you're free to manage it as you prefer, of course.

**Comment by chessai** [comment]
I would like to express a weak preference against this, because I have always felt that `Data.Traversable.for` is a misnomer in a world where we have `forM = flip mapM`. I have always wanted `for = flip Data.List.map`.

**Comment by phadej** [comment]
> I would like to express a weak preference against this, because I have always felt that `Data.Traversable.for` is a misnomer in a world where we have `forM = flip mapM`. I have always wanted `for = flip Data.List.map`.

Sure, it would been more consistent to have `Functor` with `map` (and `for`) (and have the monomorphic `Data.List.map` not in the prelude), `Traversable` with `mapA`/`forA` (`Applicative`) and `mapM`/`forM`; but that renaming won't happen; so I guess the ecosystem is stuck with current naming scheme.

**Comment by Bodigrim** [comment]
@mixphix the best is to drop a message to https://mail.haskell.org/cgi-bin/mailman/listinfo/ghc-devs, but also CC @chreekat.

**Comment by treeowl** [comment]
Isn't `for` used for some streaming/iteration stuff? It doesn't strike me as a great word to steal.

**Comment by chreekat** [comment]
@mixphix did you get access to GitLab yet?

**Comment by chreekat** [comment]
@mixphix ok, can you email me at bryan@haskell.foundation from the email address associated with your account?

**Comment by Bodigrim** [comment]
Thanks! Note that the proposal process asks for patches to be prepared upfront (but not submitted as PRs):

* Patching affected packages locally would allow you to progress further in impact assessment, beyond the first level of breakage.
* Looking at patches helps CLC to determine the scale of breakage and to formulate a migration guide. 

To be more specific, `pipes` and `streaming` are dependencies of many packages, so it would be really important to patch them locally (`cabal unpack` them somewhere, patch and add the folder to `cabal.project`) to progress further.

What's the suggested migration guide for `pipes` and `streaming`? Both APIs contain `for` functions, incompatible with `Prelude`: [`Pipes`](https://hackage.haskell.org/package/pipes-4.3.16/docs/Pipes.html#v:for) and [`Streaming.Prelude`](https://hackage.haskell.org/package/streaming-0.2.4.0/docs/Streaming-Prelude.html#v:for). At least `Pipes` are often imported unqualified. Should they be advised to rename the combinator (which is a breaking change for them and consumers)? Or should consumers be advised to import `Pipes` qualified? Or just keep `import Prelude hiding (for)` everywhere for foreseeable future?

Same question for other packages offering `for` in public API, see https://www.stackage.org/lts-22.33/hoogle?q=for for an approximate list. I suspect that quite a few of them are usually imported unqualified.
