### ISSUE TITLE
Use custom warning category for Data.List.NonEmpty.unzip

### ISSUE THREAD

**Issue by Bodigrim** [haskell/core-libraries-committee#258]
In https://github.com/haskell/core-libraries-committee/issues/86#issuecomment-1480224739 we decided to attach to `Data.List.NonEmpty.unzip` a warning `{-# DEPRECATED unzip "This function will be made monomorphic in GHC 9.14, consider switching to Data.Functor.unzip" #-}`. 

Since then, following [GHC#541](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0541-warning-pragmas-with-categories.rst), GHC gained an ability to annotate warnings with custom categories to allow users disable them in a fine-grained manner. Because of this material change, I suggest we amend #86 by adding a category: 

```diff
-{-# DEPRECATED unzip "This function will be made monomorphic in GHC 9.14, consider switching to Data.Functor.unzip" #-}
+{-# WARNING in "x-data-list-nonempty-unzip" unzip "This function will be made monomorphic in GHC 9.14, consider switching to Data.Functor.unzip" #-}
```

This would allow users, who already use `Data.List.NonEmpty.unzip` with monomorphic `NonEmpty` arguments, just disable the warning with `{-# OPTIONS_GHC -Wno-data-list-nonempty-unzip #-}` instead of changing their code to use `Data.Functor.unzip` (which arguably pushes them into a wrong direction of intentionally polymorphic function).

I'm not sure what's the best category name here. I provisionally put `x-data-list-nonempty-unzip`, but open for other options. 

GHC 9.10 will be the first GHC release shipped with #86, so I'm keen to reach a conclusion on this very soon, before a release branch is forked.

Cf. https://gitlab.haskell.org/ghc/ghc/-/issues/24316

The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12157.

**Comment by parsonsmatt** [comment]
Sounds great! Let's do it.

Maybe we should even `WARN` when a `WARNING` *doesn't* have a custom name 🤔

**Comment by hasufell** [comment]
Do we want short lived warning categories? The proposed one seems very specific. 

I don't have a better idea though, so whatever works.

**Comment by tomjaguarpaw** [comment]
I'm not sure I see the point in making this change so users can suppress a warning in merely two releases (9.10 and 9.12). If a user has already migrated away then it's irrelevant to them. If a user has already suppressed this deprecation it's going to cause them churn. If they haven't, do they really care?

**Comment by tomjaguarpaw** [comment]
Ah yes, I see

> GHC 9.10 will be the first GHC release shipped with https://github.com/haskell/core-libraries-committee/issues/86

That makes more sense. The deprecation has not yet appeared: https://hackage.haskell.org/package/base-4.19.1.0/docs/Data-List-NonEmpty.html#v:unzip. 

So the proposal is to not use `DEPRECATED` at all but instead use a custom warning. That sounds fine.

**Comment by Bodigrim** [comment]
If there are no more comments / opinions, I'll trigger a vote soon.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to amend #86 by adding a category: 

```diff
-{-# DEPRECATED unzip "This function will be made monomorphic in GHC 9.14, consider switching to Data.Functor.unzip" #-}
+{-# WARNING in "x-data-list-nonempty-unzip" unzip "This function will be made monomorphic in GHC 9.14, consider switching to Data.Functor.unzip" #-}
```

The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12157.

@tomjaguarpaw @mixphix @hasufell @velveteer @parsonsmatt @angerman 

----

+1 from me, unsurprisingly.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by velveteer** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
(Sorry for cutting it short, I'm keen to get the MR merged and backported before GHC 9.10 alpha 1)

**Comment by hsenag** [comment]
Just to note that I had to add two suppressions to keep some code that is already using it monomorphically warning-free across a range of GHCs, which was a bit frustrating particularly as it took me a while to work out that was the right solution. My first instinct was to switch to Data.Functor.unzip as suggested, but that isn't available in older GHCs and anyway calling the monomorphic variant is more sensible here.

```
{-# OPTIONS_GHC -Wno-unrecognised-warning-flags #-}
{-# OPTIONS_GHC -Wno-x-data-list-nonempty-unzip #-}
```

**Comment by andreasabel** [comment]
I am seeing this when building Agda-2.6.4.3 with GHC 9.10.1:
```
src/full/Agda/Syntax/Translation/ConcreteToAbstract.hs:2755:23: warning: [GHC-63394] [-Wx-data-list-nonempty-unzip]
    In the use of ‘unzip’
    (imported from Agda.Utils.List1, but defined in Data.List.NonEmpty):
    "This function will be made monomorphic in base-4.22, consider switching to Data.Functor.unzip"
     |
2755 |       let (nps, es) = List1.unzip
     |                       ^^^^^^^^^^^
```
This is a false alarm; `List1` is our alias for nonempty lists.

If one goes all the way to add a new warning to GHC, why not implement it properly so that it is just triggered when there is something to warn about?

**Comment by tomjaguarpaw** [comment]
As a point of information: it's not a warning in GHC, it's a warning in `base`. It therefore has no type information to be able to avoid warning on correct uses (i.e. on `NonEmpty`).

**Comment by andreasabel** [comment]
Ok, I see.

Is there any data on the ratio of correct alarms and false alarms the warning gives?
Because if there are not many that are actually affected by the coming monomorphisation of `Data.List.NonEmpty.unzip`, then having no warning (and just some breakage in a base bump) could be preferable for the community as a whole.
(The whole scenario of importing `unzip` from `Data.List.NonEmpty` and then expecting it to work on any `Functor` seems unlikely, even if there was an initial anecdote.)

The other design question is whether reexports should actually also reexport the deprecation warning.  Making your custom prelude for a project is quite usual in Haskell projects, and then you would not want to automatically get deprecation warnings for your custom prelude functions coming from `base` etc.  
But this design question is beyond the scope of `base` that would have to be solved at the level of GHC.

**Comment by tomjaguarpaw** [comment]
The impact assessment showed that no packages on Stackage were affected by the coming change. You may well be right that the deprecation process is not worth the pain in this case. It's hard to know how to make that call in general.

https://github.com/haskell/core-libraries-committee/issues/86#issuecomment-1397145338
