### ISSUE TITLE
Improve `toInteger @Word32` on 64-bit platforms

### ISSUE THREAD

**Issue by clyring** [haskell/core-libraries-committee#259]
MR: [!12164](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12164)

Commit message:

> On 64-bit platforms, every `Word32` fits in an `Int`, so we can
> convert to `Int#` without having to perform the overflow check
> `integerFromWord#` uses internally.

This is not a breaking change; no impact assessment is required. The change is sufficiently invisible that I think it is probably fine to omit it from the user-facing changelogs.

**Comment by clyring** [comment]
Some additional context:

 * An `Integer` value is constructed using the `IS` data constructor iff it is small enough to fit into an `Int`. (See [the `Integer` documentation](https://hackage.haskell.org/package/ghc-bignum-1.3/docs/GHC-Num-Integer.html#t:Integer).)
 * The largest `Word` values are always too large to fit into an `Int`, so `integerFromWord#` has to check for overflow in its internal word-to-int conversion.
 * Additionally, `integerFromWord#` is opaque and can result in function call overhead when no rewrite rule is able to eliminate it.

------

@Bodigrim I would like to trigger a vote.

**Comment by Bodigrim** [comment]
@clyring please do mention the change in the changelog however small it is. 

----

Dear CLC members, let's vote on a very small proposal to improve `toInteger :: Word32 -> Integer` on 64-bit platforms, shaving off an overflow check, as implemented in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12164.

@tomjaguarpaw @mixphix @angerman @hasufell @parsonsmatt @velveteer 

----

+1 from me, an obvious (even if minor) improvement.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by clyring** [comment]
> @clyring please do mention the change in the changelog however small it is.

I have done so.

**Comment by hasufell** [comment]
+1

**Comment by angerman** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
