### ISSUE TITLE
Add `<$<` and `>$>` to Data.Functor

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell/core-libraries-committee#265]
`<$<` and `>$>` would be use useful functions to have exported from `Data.Functor`. There is already a precedence for this syntax with `>=>` so it would be intuitive for most.

I only see [one conflict](https://hoogle.haskell.org/?hoogle=%3E%24%3E) with the package [configuration-tools](https://hackage.haskell.org/package/configuration-tools-0.7.0/docs/Configuration-Utils-Operators.html#v:-62--36--62-).

```haskell
infixr 4 <$<
(<$<) :: Functor f => (b -> c) -> (a -> f b) -> a -> f c

infixr 4 >$>
(>$>) :: Functor f => (a -> f b) -> (b -> c) -> a -> f c
```

**Comment by BebeSparkelSparkel** [comment]
@mixphix I don't appreciate your attitude. Especially, since this is basically the exact implementation of the useful infix functions `<=<` and `>=>` that are already in base shown below.

https://gitlab.haskell.org/ghc/ghc/-/blame/master/libraries/ghc-internal/src/GHC/Internal/Control/Monad.hs?ref_type=heads#L185

```haskell
(>=>)       :: Monad m => (a -> m b) -> (b -> m c) -> (a -> m c)
f >=> g     = \x -> f x >>= g

(<=<)       :: Monad m => (b -> m c) -> (a -> m b) -> (a -> m c)
(<=<)       = flip (>=>)
```

Please elaborate on your rejection.

**Comment by thielema** [comment]
On Thu, 18 Apr 2024, mixphix wrote:

> The implementations being,
> 
> (<$<) :: Functor f => (b -> c) -> (a -> f b) -> a -> f c
> (<$<) = (.)
> 
> (>$>) :: Functor f => (a -> f b) -> (b -> c) -> a -> f c
> (>$>) = flip (.)
> 
> Yeah, I don't think so.

The function (b -> c) is applied to the Functor element.

**Comment by Bodigrim** [comment]
I'd like to remind everyone to remain respectful to each other. 

@BebeSparkelSparkel could you possibly explain why you find these combinators particularly useful? There are quite a few combinations of `(.)` and `fmap` possible, but apparently you feel that these two are more interesting than others. Is there a prior art (e. g., alternative preludes or helper libraries such as `extra` and `MissingH`)?

**Comment by BebeSparkelSparkel** [comment]
@ocharles It is useful for modifying the result of monadic composition. My specific case is

```haskell
BB.lazyByteString <$< BL.hGet h . fromInteger
```

reading in `n :: Integer` bytes from a file and then wrapping it in a ByteString Builder.

It is also used in

[futurice/futuLog](https://github.com/futurice/futuLog/blob/75f90a257b28954aa5f7c6cebc2cbafb8fc12e98/backend/src/Server.hs#L25)#L25
```haskell
swaggerHandler :: S.Server SwaggerAPI
    putAdmin = DB.putAdmin >$> NoContent
    editRegistrationsHandler = mapM (uncurry (DB.tryRegistrations (Just admin)) . toRegistrations) >$> NoContent
    setOfficeHandler = DB.setOffice >$> NoContent
```

Centril/TDA283-compiler-construction [many examples](https://github.com/search?q=repo%3ACentril%2FTDA283-compiler-construction%20%3E%24%3E&type=code)
```haskell
_sfType <$$> getStructDef (_tIdent typ) >>= mapM compileType >$> LStruct
```

[oisdk/HaskAlgebra](https://github.com/oisdk/HaskAlgebra/blob/25f49e5dfc526bce668acaf1a1406c3807933230/SAlgebra/src/Data/Simplify.hs#L128)
```haskell
simplify (SSum xs) = either id SSum $ (factorise <=< sort <$< diff . c extractConst . extractSum . map simplify) xs
```

[chainweb-node](https://github.com/search?q=repo%3Anopool%2Fchainweb-node+%3C%24%3C&type=code) Not really sure why they use it but they use it a lot.

**Comment by BebeSparkelSparkel** [comment]
@Bodigrim It is possible to use . and fmap together but if a function has arguments it becomes a bit messier

```
fmap (splitAt 5) . getLines
splitAt <$< getLines
```

Basically it is good for concluding monaic composition.

**Comment by Bodigrim** [comment]
> It is also used in [futurice/futuLog](https://github.com/futurice/futuLog/blob/75f90a257b28954aa5f7c6cebc2cbafb8fc12e98/backend/src/Server.hs#L25)#L25

Just to be clear, this one is `(>$>) :: Functor f => (a -> f b) -> c -> a -> f c`, different from your proposal.

> [chainweb-node](https://github.com/search?q=repo%3Anopool%2Fchainweb-node+%3C%24%3C&type=code) Not really sure why they use it but they use it a lot.

I think they use `Configuration.Utils.(<$<) :: Functor f => f (a -> b) -> (b -> c) -> f (a -> c)`, again different from what you propose.

> It is possible to use `.` and `fmap` together but if a function has arguments it becomes a bit messier
> 
> ```haskell
> fmap (splitAt 5) . getLines
> splitAt <$< getLines
> ```

Sorry, I don't quite follow the example. I assume `getLines` is `Handle -> IO [String]`, in which case `fmap (splitAt 5) . getLines :: Handle -> IO ([String], [String])`, but then `splitAt <$< getLines` is ill-typed.

**Comment by BebeSparkelSparkel** [comment]
@Bodigrim Sorry for not looking at those examples more closely and wasting your time, I'll review them more thoroughly and update it.

**Comment by BebeSparkelSparkel** [comment]
Thanks for all your comments. This seems to be a personally useful function and not a community demanded function.
