### ISSUE TITLE
Add MonadFail instance for Product

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [haskell/core-libraries-committee#267]
MonadFail is useful for more expressive failures than `empty` and is useful for allowing Product to be used where there is a MonadFail constraint.

```haskell
instance (MonadFail m, MonadFail n) => MonadFail (Product m n) where fail x = Pair (fail x) (fail x)
```

**Comment by Bodigrim** [comment]
This seems fairly uncontroversial to me. Could you please prepare an MR?

**Comment by BebeSparkelSparkel** [comment]
Me too, but I am unsure if `Product` should even have an `Applicative` or `Monad` instance after the discussion in #268 .

I think I will wait until that discussion has been resolved.

**Comment by Bodigrim** [comment]
@BebeSparkelSparkel It's very much unlikely that we will remove `instance Monad (Product f g)`. Anyway, given that you have withdrawn #268, how would you like to proceed here?
