### ISSUE TITLE
Why does template-haskell not provide basic QuasiQuoters?

### ISSUE THREAD

**Issue by brandonchinn178** [haskell/core-libraries-committee#27]
Is there a reason why `template-haskell` doesn't provide QuasiQuoters corresponding to TH quotes `[e| ... |]`, `[d| ... |]`, etc.? A lot of packages provide QuasiQuoters that could be written as "`[e| ... |]` + extra stuff"; for example, a text interpolation library could be implemented as
```hs
-- the QuasiQuoter corresponding to [e| ... |]
eQQ :: QuasiQuoter

-- Interpolate: (let x = 1 in [text|x is: #{x}|]) == "x is: 1"
text :: QuasiQuoter
text =
  eQQ
    { quoteExp =
        appE [| concat |]
        . listE
        . map
          ( \case
            Left raw -> litE $ stringL raw
            Right interpolated -> quoteExp eQQ interpolated
          )
        . parse
    }

-- Parses "x is: #{x}" into [Left "x is: ", Right "x"]
parse :: String -> [Either String String]
```
Whereas currently, it'd have to pull in `haskell-src-meta` to parse the string.

As another example, we have a use case for easily writing lists of hlists:
```hs
rows =
  eQQ
    { quoteExp = listE . map (toHList . quoteExp eQQ) . lines
    }

-- generates [1 :& "hello" :& True :& Nil, 2 :& "world" :& False :& Nil]
[rows|
  [1, "hello", True]
  [2, "world", False]
|]
```
Today, the best way to do this without `haskell-src-meta` is to do
```hs
rows = listE . map toHList

$( rows
     [ [| [1, "hello", True] |]
     , [| [2, "world", False] |]
     ]
 )
```

**Comment by gbaz** [comment]
I'd really like this, but as the discussion says, this is really a ghc issue, not a clc issue, since it involves extending GHC. I doubt there'd be any opposition to this, but I do suspect it wouldn't be entirely straightforward to implement.

**Comment by treeowl** [comment]
Was I wrong? Isn't this a library thing?

**Comment by brandonchinn178** [comment]
Sorry, yes, you're right. I'll post in GHC. I was at the airport on my phone (just landed on the plane) so I didnt do my due diligence of looking at the readme of the repo. I'll ask on the ghc repo (which contains both the compiler implementation and the TH library, so thats probably the best place)
