### ISSUE TITLE
Is `transformers` a core library?

### ISSUE THREAD

**Issue by hasufell** [haskell/core-libraries-committee#271]
Sparked by https://discourse.haskell.org/t/github-com-haskell-appropriating-transformers-package/9668

Not that I agree with the demands in that thread, but it struck me as confusing that transformers is not listed in our README as a core library. It is a dependency of core libraries after all.

@emilypi

**Comment by fishtreesugar** [comment]
https://redd.it/qij5kc

> A few years back, Ross Paterson handed me control of mtl, but very explicitly retained control of transformers.
> I passed down the mtl to the CLC to ensure that any new classes for MonadAccum, MonadSelect, etc. would be designed with all due care.
> Would it be cleaner to have the transitive closure property you expected? Yes. Do we have that? No.

**Comment by hasufell** [comment]
I see, would it make sense for the CLC to ask Ross whether he would consider handing ownership over to CLC with him as the maintainer?

It looks like a possibly precarious situation to me.

**Comment by Bodigrim** [comment]
I sent Ross an email asking for his opinion.

**Comment by Bodigrim** [comment]
Ross kindly agreed to nominate `transformers` as a core library, which was approved by CLC in https://groups.google.com/g/haskell-core-libraries/c/Sze-oPF7pXQ/m/UgXqtRHrAAAJ. I've update `README` to reflect it.
