### ISSUE TITLE
Add vector shuffle primops

### ISSUE THREAD

**Issue by sheaf** [haskell/core-libraries-committee#274]
I would like to propose introducing and exposing a set of vector shuffle primops from `GHC.Exts`:

```haskell
shuffleFloatX4# :: FloatX4# -> FloatX4# -> (# Int#, Int#, Int#, Int# #) -> FloatX4#
shuffleDoubleX2# :: DoubleX2# -> DoubleX2# -> (# Int#, Int# #) -> DoubleX2#
shuffleWord32X8#:: Word32X8# -> Word32X8# -> (# Int#, Int#, Int#, Int#, Int#, Int#, Int#, Int# #) -> Word32X8#
-- ...
```

There would be one such primop for each vector type, following the same naming structure as other primops such as `plusFloatX4#` etc. The type of these primops is:

```haskell
shuffleTyXN# :: TyXN# -> TyXN# -> UnboxedTuple N Int# -> TyXN#
```

where `UnboxedTuple N Int#` is just shorthand for a tuple of the form `(# Int#, ..., Int# #)` of the same size as the vector.

These primops would have the same semantics as the [Clang `__builtin_shufflevector`](https://clang.llvm.org/docs/LanguageExtensions.html#langext-builtin-shufflevector) function.  Namely, we imagine concatenating the two input vectors, and indexing into it like an array to form the output vector. For example with `shuffleFloatX4#`:

```
v1 = { f_0, f_1, f_2, f_3 }
v2 = { f_4, f_5, f_6, f_7 }
shuffleFloatX4# v1 v2 (# i, j, k, l #) = { f_i, f_j, f_k, f_l }
```

Note that usage of these primops come with the following important restriction:

  - the `Int#` indices used to form the resulting vector must all be literals (because in practice they are used to e.g. compute the correct immediate to pass to a `VSHUFPD` AVX instruction).

This means users are NOT allowed to abstract over indices, e.g. one cannot do:

```haskell
myBroadcast :: Int# -> FloatX4# -> FloatX4#
myBroadcast i v = shuffleFloatX4# v v (# i, i, i, i #)
```

because on the RHS here we have an occurrence of `shuffleFloatX4#` in which the indices are not literal numbers.

## Implementation

I have implemented these primops in [GHC MR !12860](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12860). Note that this MR is still a draft at the moment and is not ready for careful review.

**Comment by tomjaguarpaw** [comment]
Could these be exposed from `ghc-internal` instead?

**Comment by sheaf** [comment]
> Could these be exposed from `ghc-internal` instead?

That would be fine as well; in that case it would not even need a CLC proposal.

**Comment by tomjaguarpaw** [comment]
That's the benefit of `ghc-internal` :)

**Comment by adamgundry** [comment]
Yes, please let's not add anything more to `GHC.Exts`. We should deprecate the whole module.

**Comment by Bodigrim** [comment]
@sheaf how would you like to proceed? If you are happy to expose it from `ghc-internal` only, we can close the issue.

**Comment by sheaf** [comment]
Only exposing these primops from ghc-internal is OK with me. Closing.
