### ISSUE TITLE
Add `HasCallStack` constraint to `ioError`

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#275]
I propose that the type of `ioError` as exposed by `Control.Exception` and `System.IO.Error` be augmented with a `HasCallStack` constraint:
```haskell
ioError         :: HasCallStack => IOError -> IO a
```

This will allow `HasCallStack` constraints to be propagated to exception backtraces from callsites.

Implementation: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12861

**Comment by parsonsmatt** [comment]
I'm in favor!

**Comment by Bodigrim** [comment]
Seems fairly uncontroversial to me, especially given that it's usually GHC HQ who are opposed to splashing `HasCallStack` around ;) Let's wait a few more days and vote.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to augment `ioError` with `HasCallStack` constraint. This is not a breaking change. It will allow `HasCallStack` constraints to `propagated` to exception backtraces, a new feature in GHC 9.10.

@hasufell @velveteer @tomjaguarpaw @mixphix @parsonsmatt @angerman 

----

+1 from me.

**Comment by angerman** [comment]
+1

**Comment by velveteer** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, approved unanimously.
