### ISSUE TITLE
Add `readTixFile` flag to `HpcFlags` record in `GHC.RTS.Flags`

### ISSUE THREAD

**Issue by BinderDavid** [haskell/core-libraries-committee#276]
The MR https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11401 adds a new RTS flag to GHC's runtime system. Correspondingly, this flag would be exposed in `GHC.RTS.Flags` as an additional field in the `HpcFlags` record, which changes the definition of a type exposed in base.

The module description explicitly states that "The API of this module is unstable and is tightly coupled to GHC's internals. If depend on it, make sure to use a tight upper bound, e.g., base < 4.X rather than base < 5, because the interface can change rapidly without much warning."

**Comment by Bodigrim** [comment]
The proposal is similar to #243, #254 and #263. Ideally we should work towards deprecation and removal of `GHC.RTS.Flags` from `base`, but in the meantime let me trigger the vote without further ado.

@tomjaguarpaw @hasufell @mixphix @velveteer @angerman @parsonsmatt 

----

+1 from me. The changes have been already approved by GHC SC in https://github.com/ghc-proposals/ghc-proposals/pull/612.

**Comment by parsonsmatt** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by angerman** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
