### ISSUE TITLE
New core library unicode-data-core

### ISSUE THREAD

**Issue by wismill** [haskell/core-libraries-committee#278]
Currently the [Unicode version](https://www.unicode.org/versions/Unicode15.1.0/) in `base` is not upgradable because it depends of the GHC version via the `ghc-internal` package.

This raises two main issues:
1. Unicode version is tied to the compiler version.
2. It makes hard for libraries to ensure consistency: e.g. `text` has case mappings from Unicode 14.0 but uses also `Data.Char`, which may have a different Unicode version (`base-4.20` uses Unicode 15.1).

The [`unicode-data`](https://github.com/composewell/unicode-data) ([Hackage](https://hackage.haskell.org/package/unicode-data)) package family offers a way to choose an exact Unicode version and access to Unicode features unavailable in `base`. Some of its core features were merged in `base` (see #59).

I propose that we go further and decouple the Unicode version from GHC version, by introducing a new _core_ library `unicode-data-core` that would back `Data.Char`. Its code would be the one currently in `GHC.Internal.Unicode*` (probably under another namespace), with the optional addition of the complex case mappings for `text` and any other basic feature deemed useful for core libraries.

Such package would have _low maintenance effort:_ Unicode publishes versions on a yearly basis and the API is very stable.

However, it is not clear to me if `ghc-internal` could depend on `unicode-data-core` as well, as we do not want the compiler to fix the Unicode version.

CC `unicode-data` team: @adithyaov @Bodigrim @harendra-kumar

**Comment by Bodigrim** [comment]
> However, it is not clear to me if `ghc-internal` could depend on `unicode-data-core` as well, as we do not want the compiler to fix the Unicode version.

That sounds unlikely to me, `ghc-internal` is not meant to be reinstallable.

**Comment by harendra-kumar** [comment]
Having `unicode-data-core` as a separate package sounds like a good idea to me because `unicode-data` is too big and might grow with more stuff. But we also need to figure out how GHC can share it so that the maintenance effort is reduced.

**Comment by Bodigrim** [comment]
Up to my best knowledge, `ghc-internal` is not meant to be reinstallable. So if `unicode-data-core` will be a dependency of `ghc-internal`, it will not be reinstallable as well, defeating the purpose of its introduction into the dependency tree of `base`. I don't really see a good path forward here.

CC @mpickering who's been recently interested in making `base` reinstallable.

**Comment by hsyl20** [comment]
> Up to my best knowledge, ghc-internal is not meant to be reinstallable.

I hope it will, as well as `ghc-bignum`. Otherwise we won't be able to select a different backend for Integer. If we automatically build and use an external interpreter (see [GHC#24731](https://gitlab.haskell.org/ghc/ghc/-/issues/24731)) when we use a reinstalled `ghc-internal` it should be fine (except for plugins which don't work with the external interpreter).

**Comment by Bodigrim** [comment]
@wismill I'm inclined to close this as dormant until `ghc-internal` becomes reinstallable.

**Comment by wismill** [comment]
> I'm inclined to close this as dormant until `ghc-internal` becomes reinstallable.

@Bodigrim we _could_ make `base:Data.Char` depend on `unicode-data-core` and not `ghc-internal`. But then it would not be sync with `base:GHC.Unicode`. On the other hand, are there imports of `GHC.Unicode` when `Data.Char` would suffice? AFAIK, only `unicodeVersion` is not exposed in `Data.Char`.

It seems the real issue is rather that some definitions in `ghc-internal` use `GHC.Internal.Unicode` _and_ are then used (directly or not) in `base`. Keeping track of these dependencies would be a nightmare.

So yeah, we should wait for either `ghc-internal` to be re-installable or a clear separation of what depends (transitively) on `GHC.Internal.Unicode` from `base` (i.e.: keep `GHC.Internal.Unicode` for internal use in the compiler only).

**Comment by Bodigrim** [comment]
I think using different Unicode data in `ghc-internal` and `base` would be pretty bad, much worse than status quo when `base` and `text` could somewhat disagree on details.

----

Let me close this as dormant then.
