### ISSUE TITLE
Adopt `file-io` as a core library

### ISSUE THREAD

**Issue by hasufell** [haskell/core-libraries-committee#280]
I seem to have made it a habit to create new core libraries.

So here's another: https://github.com/hasufell/file-io

It is part of the abstract filepath proposal (now called `OsPath`). The directory package now depends on it, so it seems reasonable to move it under CLC governance.

Related discussions:

* https://github.com/hasufell/file-io/issues/22
* https://gitlab.haskell.org/ghc/ghc/-/issues/25145

@mpickering @Rufflewind @bgamari

**Comment by Bodigrim** [comment]
Given that `file-io` is now a boot library (= required to build GHC), it would be prudent to safeguard its future by adopting it as a core library. We've been aiming to minimise discrepancies between boot and core libraries for some time now. 

Shall we vote? +1 from me.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by angerman** [comment]
+1, seems additive, I don't see a reason to be specifically against it.

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
