### ISSUE TITLE
Mitigate precise exception divergence demand in `Control.Exception.throw` via disabling of inlining

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#290]
@simonpj observed in [#25066](https://gitlab.haskell.org/ghc/ghc/-/issues/25066) that the backtrace collection logic introduced in #199 has resulted in a rather subtle regression in the demand signature inferred for the `throw` operation. Specifically, the pure `throw` function, due to a rather delicate cascade of optimisations involving `unsafePerformIO`, is now considered by GHC's demand analyzer to potentially diverge with a precise exception (N.B. I have described the precise reasoning in [`Note [Hiding precise exception signature in throw]`](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13275/diffs#af30c6b99312124f2098e256a7a9eb43d6d40011_87_111) in the implementation, [!13275](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13275)). As GHC must tread carefully when optimising around functions terminating with precise exceptions this constitutes a runtime performance regression on the order of 1%.

Sadly we do not currently have a principled means in GHC to control the propagation of precise exceptions through across `unsafePerformIO`. However, we can avoid the simplification leading to this regression with a judicious use of `GHC.Exts.noinline`:
```patch
diff --git a/libraries/ghc-internal/src/GHC/Internal/Exception.hs b/libraries/ghc-internal/src/GHC/Internal/Exception.hs
index 50005ba363c..dba92921b34 100644
--- a/libraries/ghc-internal/src/GHC/Internal/Exception.hs
+++ b/libraries/ghc-internal/src/GHC/Internal/Exception.hs
@@ -81,9 +81,86 @@ import GHC.Internal.Exception.Type
 throw :: forall (r :: RuntimeRep). forall (a :: TYPE r). forall e.
          (HasCallStack, Exception e) => e -> a
 throw e =
-    let !se = unsafePerformIO (toExceptionWithBacktrace e)
+    let !se = noinline (unsafePerformIO (toExceptionWithBacktrace e))
     in raise# se
```
This gives up a small bit of optimisation in the body of `throw` (which is used only in cold, erroring codepaths) in exchange for considerably better optimisation at use-sites. Specifically, the use of `noinline` prevents `unsafePerformIO` from being inlined, in turn preventing the `raise#` application from being floated into the `runRW#` continuation it contains, ensuring that the demand analysers' divergence heuristics do not conclude that the the `runRW#` might throw a precise exception. This should have no effect on the types or semantics observed by the end-user, but will make their program a bit faster.

Note that this is a temporary measure which we propose to use for GHC 9.10 and 9.12. We hope that by 9.14 we might have a set of primops to more explicitly control the demand analyser's divergence heuristics, allowing us to again allow inlining.

* Motivating ticket: [#25066](https://gitlab.haskell.org/ghc/ghc/-/issues/25066)
* Implementation: [!13275](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13275)

**Comment by simonpj** [comment]
Perhaps it would help to explain what user-visible (and hence of interest to CLC) changes this proposal involves.

As I understand it:
* No changes to base API
* Recovery of some accidental loss of performance due to the implementation of the backtrace proposal.  

Is that an accurate summary?

**Comment by bgamari** [comment]
@simonpj yes, your summary is spot on. I have added a short sentence reiterating this.

**Comment by bgamari** [comment]
@haskell/core-language-committee, I believe this is ready for a vote.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to fix a regression in demand signature (basically, which arguments are used lazily and which are used strictly) for `throw` by judiciously applying `noinline`. The MR is available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13275

Somewhat counterintuitively, disabling inlining improves performance here. The thing is that benefits of inlining are realised only in "cold" code paths: when we throw an exception, performance barely matters. What matters is a large picture of demand signature, because it enables to unbox / force / apply worker-wrapper transfomation in all code paths, including normal execution.

@tomjaguarpaw @mixphix @velveteer @hasufell @angerman @parsonsmatt 

----

+1 from me, I trust @simonpj and @bgamari know what they are doing.

**Comment by velveteer** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
