### ISSUE TITLE
Attach exception backtrace in `GHC.Conc.throwSTM`

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#297]
The `throwSTM` combinator exposed by `GHC.Conc`, `GHC.Conc.Sync`, and the `stm` package currently does not capture and attach a `Backtraces` annotation to the thrown exception. This functionality was requested in [GHC #25365](https://gitlab.haskell.org/ghc/ghc/-/issues/25365).

I propose that `throwSTM` gain a `HasCallStack` constraint and its body be adjusted to attach the appropriate annotation:
```patch
-throwSTM :: Exception e => e -> STM a
-throwSTM e = STM $ raiseIO# (toException e)
+throwSTM :: HasCallStack => Exception e => e -> STM a
+throwSTM e = do
+    -- N.B. Typically use of unsafeIOToSTM is very much frowned upon as this
+    -- is an easy way to end up with nested transactions. However, we can be
+    -- certain that toExceptionWithBacktrace will not initiate a transaction.
+    se <- unsafeIOToSTM (toExceptionWithBacktrace e)
+    STM $ raiseIO# se
```

Implemented in [GHC !13408](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13408).

**Comment by bgamari** [comment]
@Bodigrim, just a gentle ping.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
