### ISSUE TITLE
Attach `WhileHandling` annotations in exceptions thrown from `catchSTM` handlers

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#298]
The `catchSTM` combinator exposed by `GHC.Conc`, `GHC.Conc.Sync`, and the `stm` package currently does not attach `WhileHandling` annotations to exceptions thrown from its handler, as described in #202. This functionality was requested in [GHC #25365](https://gitlab.haskell.org/ghc/ghc/-/issues/25365).

I propose that we introduce an `annotateSTM` combinator to `GHC.Conc` and `GHC.Conc.Sync`:

```patch
+-- | Execute an 'STM' action, adding the given 'ExceptionContext'
+-- to any thrown synchronous exceptions.
+annotateSTM :: forall e a. ExceptionAnnotation e => e -> STM a -> STM a
+annotateSTM ann (STM io) = STM (catch# io handler)
+  where
+    handler se = raiseIO# (addExceptionContext ann se)
```
and use it from `catchSTM`:
```patch
 catchSTM (STM m) handler = STM $ catchSTM# m handler'
     where
       handler' e = case fromException e of
-                     Just e' -> unSTM (handler e')
+                     Just e' -> unSTM (annotateSTM (WhileHandling e) (handler e'))
                      Nothing -> raiseIO# e
```

Implemented in [GHC !13408](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13408).

**Comment by Bodigrim** [comment]
The proposed `annotateSTM` handler is a mirror of existing `annotateIO`:
```haskell
annotateIO :: forall e a. ExceptionAnnotation e => e -> IO a -> IO a
annotateIO ann (IO io) = IO (catch# io handler)
  where
    handler se = raiseIO# (addExceptionContext ann se)
```
and then `catchSTM` follows the pattern of `catch`:
```haskell
catch (IO io) handler = IO $ catch# io handler'
  where
    handler' e =
      case fromException e of
        Just e' -> unIO (annotateIO (WhileHandling e) (handler e'))
        Nothing -> raiseIO# e
```
Seems uncontroversial to me.

----

Dear CLC members, let's vote on the proposal to introduce `annotateSTM` and amend `catchSTM` to benefit from recent advances in exception annotations. 

@tomjaguarpaw @hasufell @velveteer @parsonsmatt @angerman @mixphix 

+1 from me.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by angerman** [comment]
+1 lgtm.

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
