### ISSUE TITLE
`Data.Ix.Ix` instances for the `Foreign.C.Type` newtypes

### ISSUE THREAD

**Issue by Kleidukos** [haskell/core-libraries-committee#30]
I would like to add a `Data.Ix.Ix` instance to the following newtypes (whose underlying representation are `Word<n>` or `Int<n>` already have an `Ix` instance):

* CChar
* CSChar
* CUChar
* CShort
* CUShort
* CSize

etc.

I can contribute the patch myself.

The usecase is a `Storable` instance for FFI:

```haskell
newtype Blake2bState = Blake2bState (StorableArray CSize CUChar)

-- @since 0.0.1.0
instance Storable Blake2bState where
  sizeOf _ = 384

  alignment _ = 64

  peek :: Ptr Blake2bState -> IO Blake2bState
  peek ptr = do
    let bytePtr :: Ptr Word8 = castPtr ptr
    xs <- traverse (\i -> peek (plusPtr bytePtr i)) [0..383]
    Blake2bState <$> newListArray (0, 383) xs -- <<-- This is where it's needed
```

cc @kozross

**Comment by sjakobi** [comment]
I had some difficulty understanding the motivating example. It seems to require an `Ix` instance for `CSize`, but not one for `CUChar`. But I suspect you want to add instances for both `CSize` _and_ `CUChar`.

Maybe it would be helpful if you'd clarify which types you're requesting `Ix` instances for.

**Comment by Kleidukos** [comment]
@sjakobi well, `newListArray`'s type signature is the one that has the `Ix` constraint, so I figured I'd point to the use site?

I made the code work by adding an instance for `CSize` actually:

```haskell
instance Ix CSize where
  range (CSize m, CSize n) = CSize <$> range (m, n)
  unsafeIndex (CSize m, CSize n) (CSize i) = unsafeIndex (m, n) i
  inRange (CSize m, CSize n) (CSize i) = inRange (m, n) i
```

> But I suspect you want to add instances for both CSize and CUChar.

And as stated in the description of the ticket, for all of the other newtypes, yes;

**Comment by sjakobi** [comment]
Hmm, I'm still not quite certain precisely which types you want these instances for.

Is `CInt` excepted because it's defined as `CInt Int32`, so the underlying type is not a `Word<n>`?

I think the best way to remove any uncertainty is to name each relevant type.

**Comment by Kleidukos** [comment]
Sure, here is the list that we can start with.

* CChar     
* CSChar    
* CUChar    
* CShort    
* CUShort   
* CInt      
* CUInt     
* CLong     
* CULong    
* CPtrdiff  
* CSize     
* CWchar    
* CSigAtomic
* CLLong
* CULLong   
* CBool     
* CIntPtr   
* CUIntPtr  
* CIntMax   
* CUIntMax

**Comment by Bodigrim** [comment]
That's probably fine from my perspective. One might argue that `Ix` leaks information about `C*` underlying platform-dependent representation, but it's already leaked in `instance Bounded`, so `Ix` does not make it worse.

**Comment by Kleidukos** [comment]
@Bodigrim Understood. I imagine that your opinion alone doesn't constitute a binding answer from the CLC, so is there a possibility to get this proposal reviewed formally? :)

**Comment by cigsender** [comment]
i'm +1 on this! seems like more utility for no (or negligible) breakage. i can't imagine much going horribly wrong with an Ix instance for these types.

**Comment by Bodigrim** [comment]
@Kleidukos could you please raise a GHC MR, so that we can formally vote on it?

**Comment by Kleidukos** [comment]
MR is here ~> https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7385

**Comment by recursion-ninja** [comment]
A bit late to the conversation but, as someone who has used FFI extensively and appreciates the fact that the `Ix` type-class usefully communicates to the maintainer/API-user that a value is intended to be used for indexing and not it's numeric properties, I think facilitating application of the foreign types to be useable where an `Ix`constraint is required would be incredibly valuable feature improvement with negligible costs.

**Comment by Bodigrim** [comment]
Dear CLC members, let’s vote on the proposal. @cgibbard @cigsender @gwils @emilypi @chessai

**Comment by cgibbard** [comment]
+1

**Comment by Bodigrim** [comment]
+1

**Comment by Bodigrim** [comment]
@emilypi @chessai @cigsender just a gentle reminder.

**Comment by chessai** [comment]
+1

**Comment by cigsender** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, approved.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @Kleidukos   |
| **Status**             |  merged  |
| **`base` version**     | `4.16.1.0` |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7385 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | present |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
