### ISSUE TITLE
Specify `instance Functor NonEmpty` using `map`

### ISSUE THREAD

**Issue by mpilgrem** [haskell/core-libraries-committee#300]
EDIT: The conversation develops in the posts further below to change the proposal to be vice versa and specify `instance Functor NonEmpty` using `map`.

----
Motivation: eliminate existing code duplication.

In `base`, `Data.List.NonEmpty.NonEmpty` is, ultimately, a re-export from `ghc-internal` of `GHC.Internal.Base.NonEmpty`. `GHC.Internal.Base` also defines an instance of `Functor`, namely:
~~~haskell
-- | @since base-4.9.0.0
instance Functor NonEmpty where
  fmap f ~(a :| as) = f a :| fmap f as
  b <$ ~(_ :| as)   = b   :| (b <$ as)
~~~

`Data.List.NonEmpty` exports `map`, defined as:
~~~haskell
-- | Map a function over a 'NonEmpty' stream.
map :: (a -> b) -> NonEmpty a -> NonEmpty b
map f ~(a :| as) = f a :| fmap f as
~~~

To eliminate code duplication, I propose that should be:
~~~haskell
-- | Map a function over a 'NonEmpty' stream.
map :: (a -> b) -> NonEmpty a -> NonEmpty b
map = fmap
~~~

**Comment by mpilgrem** [comment]
@mixphix, I think that `[]` and `NonEmpty` can be distinguished because `[]` and `map` feature in the Haskell 2010 Language Report but `NonEmpty` does not. Section 9 has:
~~~haskell
instance Functor [] where
fmap = map

-- Map and append
map :: (a -> b) -> [a] -> [b]
map f [] = []
map f (x:xs) = f x : map f xs
~~~

**Comment by phadej** [comment]
I usually tend to do `fmap = map`, rather then opposite. (I cannot think when I'd do otherwise). For example, IMHO. it's more natural  to say that list has a `Monad` instance with `return = singleton` and `(>>=) = concatMap` rather then define `singleton = return` and `concatMap = (>>=)`. Sometimes specific combinators may also have less constraints than the instance member (of a multi-member type-class). I'm also quite sure that `fmap = map` way is a must for `[]` for RULES to work, not the case for `NonEmpty` as it doesn't have any RULES, but it could.

**Comment by mpilgrem** [comment]
Below, I've set out a comparison of `List a` and `NonEmpty a`.

|`List a`|`NonEmpty a`|
|--------|------------|
|package `ghc-prim`||
|* Defines type `List a = [] : List a`||
|package `ghc-internal` (depends on `ghc-prim`)|package `ghc-internal`|
||Defines type `NonEmpty a = a :\| [a]`|
|* Defines `Functor` instance|Defines `Functor` instance|
|* Defines `map`||
|* `fmap = map`| * `fmap = <source code>`|
|package `base` (depends on `ghc-internal`)|package `base` (depends on `ghc-internal`)|
|* Re-exports above|* Re-exports above|
||* Defines `map`|
||* `map` duplicates `fmap` source code|

Another approach to eliminating source code duplication would be to move the source code for `map :: (a -> b) -> NonEmpty a -> NonEmpty b` out of the `base` package into the `ghc-internal` package and have `base` re-export it.

**Comment by AndreasPK** [comment]
Why is `Defines map` and `Defines type ...` in both tables but in different rows? Just an accident?

I think changing List would be more likely to have accidental sideeffects in regards to perf or otherwise. So changing `NonEmpty` to be implemented the way List is seems more pragmatic given the wider use of lists. 

And as @phadej mentioned it also allows rules to be defined more sensibly in base in the future or in user code today.

**Comment by Ericson2314** [comment]
I don't like this. The actual problem is that `List` needs to be in `ghc-prim` / `ghc-internal` at all; it should not be, because its definition is regular bog-standard portable Haskell. We should plan organization of `base` and friend with an eye towards getting that code out of there.

**Comment by Bodigrim** [comment]
> I think that `[]` and `NonEmpty` can be distinguished because `[]` and `map` feature in the Haskell 2010 Language Report but `NonEmpty` does not.

On many occasions `base`, even if provides the same API, diverges from implementations in the Report. 

> The actual problem is that `List` and `NonEmpty` need to be in `ghc-prim` / `ghc-internal` at all; they should not be, because their definitions are regular bog-standard portable Haskell. We should plan organization of `base` and friend with an eye towards getting that code out of there.

This gets out of proportion: surely deduplication of `map` and `fmap` has nothing to do with a grand design of removing lists from `ghc-prim` / `ghc-internal`, which is extremely unlikely to happen. You cannot unwire lists without losing all special syntax for them.

----

I think it's better to define `fmap = map`, mostly because of `{-# RULES #-}`.

**Comment by Bodigrim** [comment]
@mpilgrem how would you like to proceed with this proposal? `map = fmap` or `fmap = map`?

**Comment by mpilgrem** [comment]
@Bodigrim, when it comes to Haskell, I consider myself a 'janitor' rather than an 'architect': I raised this issue because I thought I had spotted something 'untidy' to be 'swept up'. With that qualification, it seems to me that the most 'consistent' thing to do would be:
* move the specification of `map` from its current location to be in the same place as the specification of the `Functor` instance
* specify, there, `fmap = map`
* have the `base` package re-export

**Comment by Bodigrim** [comment]
Makes sense to me, but hard to validate without an MR.

**Comment by mpilgrem** [comment]
@Bodigrim, I'm happy to attempt an MR - but I understand [the process](https://github.com/haskell/core-libraries-committee/blob/main/PROPOSALS.md) requires the CLC to invite one.

**Comment by Bodigrim** [comment]
Sure, you are welcome to prepare one.

(The process aims to discourage from investing into a sizeable MR only to learn later that CLC categorically disagrees. For small proposals, where you can manage the risk of rejection without too much pain, it's not a crime to make an MR without a formal invitation)

**Comment by mpilgrem** [comment]
I ran into an immediate problem with an MR, namely `ghc-internal` provides all of:
* `GHC.Internal.Base.map :: (a -> b) -> [a] -> [b]`
* from module `GHC.Internal.Base`, the `[]` instance of `Functor`
* `GHC.Internal.Base.NonEmpty`
* from module `GHC.Internal.Base`, the `NonEmpty` instance of `Functor`

Module `GHC.Internal.Base` can't also export another `map` with signature `(a -> b) -> NonEmpty a -> NonEmpty b`.

With other types, you have modules of `ghc-internal` that are 'built on top of' `GHC.Internal.Base` - for example, `GHC.Internal.Data.Maybe`. However, the decision has already been taken that `NonEmpty` and its instance of `Functor` are down at the `GHC.Internal.Base` level. I am assuming that changing that (e.g. a new `GHC.Internal.Data.NonEmpty` - providing `NonEmpty`, `map`, and its instance of `Functor`) would be ... irritating.

So, perhaps the design choices are indeed:
1. the existing code duplication; or
2. `map = fmap` but that would mess with any future rewrite `RULES` (if there were ever any).

**Comment by Bodigrim** [comment]
> With other types, you have modules of `ghc-internal` that are 'built on top of' `GHC.Internal.Base` - for example, `GHC.Internal.Data.Maybe`. However, the decision has already been taken that `NonEmpty` and its instance of `Functor` are down at the `GHC.Internal.Base` level. I am assuming that changing that (e.g. a new `GHC.Internal.Data.NonEmpty` - providing `NonEmpty`, `map`, and its instance of `Functor`) would be ... irritating.

IIRC the only reason for `NonEmpty` in `GHC.Internal.Base` is that the type of [`sconcat`](https://hackage.haskell.org/package/base-4.20.0.1/docs/Data-Semigroup.html#v:sconcat) in `class Semigroup`, which is wired-in for the purpose of warnings about non-canonical definition of `(<>)`.

One can probably keep only the data type definition in `GHC.Internal.Base` and move everything else `NonEmpty`-related into `GHC.Internal.Data.NonEmpty`. This would anger `-Worphans`, but overall it's a more sane architecture than lumping everything together in `GHC.Internal.Base`.

**Comment by mpilgrem** [comment]
In the `GHC` repository, I think there are about 255 places where `import GHC.Internal.Base` is used (most of them without explicit imports). It will take me a little while to work through them to understand what, in fact, is being used.

**Comment by Bodigrim** [comment]
Yes, I'm not sure that gains justify means here. Maybe it's easier just to leave it as is. 

Regarding your original proposal `map = fmap`, both pros and cons seem minuscule to me. Not like inability to write RULES is a terribly big deal, but also deduplication of a single-line function is not a huge win.

**Comment by mpilgrem** [comment]
Having been through the 255 places (at least, I hope I did not miss any), it was not as bad as it could have been. My MR is at:
* https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13540

**Comment by Bodigrim** [comment]
@mpilgrem could you please update the top post with the final version of the proposal (which is `fmap = map`)?

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to reduce code duplication between `instancd Functor NonEmpty` and `Data.List.NonEmpty.map` by defining `map = fmap`. See the executive summary in https://github.com/haskell/core-libraries-committee/issues/300#issue-2583388758. The implementation available at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13540 is somewhat complicated by the fact that entities are spread between `base` and `ghc-internal` and require extra care to avoid circular dependencies, but despite that there are no user-visible changes to `base` API.

@tomjaguarpaw @hasufell @mixphix @angerman @parsonsmatt @velveteer 

----

+1 from me. Besides obvious benefits of code deduplication, I also like that the forced refactoring in `ghc-internal` led to extracting `NonEmpty`-related stuff from `GHC.Base` into a separate module.

**Comment by konsumlamm** [comment]
> Dear CLC members, let's vote on the proposal to reduce code duplication between `instance Functor NonEmpty` and `Data.List.NonEmpty.map` by defining `map = fmap`.

The updated proposal is to define `fmap = map`, not the other way around. This is also what the MR does.

**Comment by Bodigrim** [comment]
Thanks @konsumlamm and sorry for confusion. I updated the post above.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by Bodigrim** [comment]
@hasufell @parsonsmatt @angerman @velveteer just a gentle reminder to vote.

**Comment by parsonsmatt** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
