### ISSUE TITLE
Apply thread labels to internal worker threads

### ISSUE THREAD

**Issue by bgamari** [haskell/core-libraries-committee#305]
Various functions in `base` are implemented via the use of auxiliary threads. Recently a user [requested](https://gitlab.haskell.org/ghc/ghc/-/issues/25452) that GHC apply thread labels to these threads to make these threads clearly identifiable in the event log and `listThreads` output.

Specifically, I propose that the following functions' implementations be augmented with thread labels where appropriate:

* `Control.Concurrent.threadWaitRead`
* `Control.Concurrent.threadWaitWrite`
* `Control.Concurrent.threadWaitReadSTM`
* `Control.Concurrent.threadWaitWriteSTM`
* `System.Timeout.timeout`
* `GHC.Conc.Signal.runHandlers`

The proposed thread labels are static and consequently should have negligible impact on runtime.

Implementation: [!13566](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13566)

**Comment by tomjaguarpaw** [comment]
How would this work with `listThreads` exactly?  [We have](https://www.stackage.org/haddock/lts-22.41/base-4.18.2.1/GHC-Conc.html#v:listThreads) `listThreads :: IO [ThreadId]`, and we can label a thread with [`labelThread`](https://www.stackage.org/haddock/lts-22.41/base-4.18.2.1/GHC-Conc.html#v:labelThread) (presumably overwriting any existing label). But I don't see a way of reading the label. How would one do that?

**Comment by bgamari** [comment]
Is there anything I can do to move this along? I would very much appreciate being able to get this off my desk.

**Comment by tomjaguarpaw** [comment]
@Bodigrim, what's the next step?

**Comment by Bodigrim** [comment]
(Sorry, I'm massively overwhelmed for the past month or so)

Related discussion:
* https://kazu-yamamoto.hatenablog.jp/entry/2024/11/20/160218
* https://www.reddit.com/r/haskell/comments/1gvxl5e/labeling_threads_in_haskell/

@tomjaguarpaw following the Reddit discussion, do you have any specific concerns about the proposal at hand? I understand that you are somewhat unhappy about the existence of `listThreads` at all, but labelling threads does not seem to make it materially worse.

**Comment by tomjaguarpaw** [comment]
> but labelling threads does not seem to make it materially worse.

I agree. I don't see the labels themselves as a problem. This proposal is fine by me.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to annotate internal worker threads in `base` with helpful labels as detailed in https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13566/diffs. This is purely a quality-of-life change.

@tomjaguarpaw @velveteer @mixphix @hasufell @angerman @parsonsmatt 

----

+1 from me.

**Comment by parsonsmatt** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by hasufell** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
