### ISSUE TITLE
`Exception` instance for `SomeAsyncException` should define `displayException`

### ISSUE THREAD

**Issue by alt-romes** [haskell/core-libraries-committee#309]
The instance for `SomeAsyncException` is currently is currently defined as

```
-- | @since base-4.7.0.0
instance Exception SomeAsyncException
```

with an empty implementation.
This means that if the wrapped exception has a custom displayException definition, that definition is lost.Given that the Show instance simply omits the SomeAsyncException wrapper, perhaps a reasonable definition would be:

```
instance Exception SomeAsyncException where
  displayException (SomeExceptionException e) = displayException e
```

**We propose to update the instance `Exception SomeAsyncException` to the snippet above**.

Originally by @edsko on the GHC issue tracker.

**Comment by parsonsmatt** [comment]
Yes please! Great catch

**Comment by Bodigrim** [comment]
Yes, seems uncontroversial to me: we unpack `e` in `instance Exception SomeException`, we should do the same for `SomeAsyncException`. 

Dear CLC members, as an _exception_, given that the proposed change is very simple, holidays are looming and I trust @alt-romes to create a GHC MR promptly, let's vote on it without waiting for MR. 

@tomjaguarpaw @parsonsmatt @angerman @hasufell @velveteer @mixphix 

+1 from me.

**Comment by alt-romes** [comment]
I had forgotten about preparing an MR, but promptly made one now

https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13725

Thanks @Bodigrim

**Comment by hasufell** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by parsonsmatt** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, that's enough votes to approve.
