### ISSUE TITLE
`Data.Map` memory leaks after an inline 

### ISSUE THREAD

**Issue by nikivazou** [haskell/core-libraries-committee#310]
Hey, my program returns within seconds with the below function, but runs forever when the first occurrence of `f1'` is replaced with the equivalent `f1 m`.

```
import qualified Data.Map as M

combine :: (Ord k) => (M.Map k v -> [(k, v)]) -> (M.Map k v -> [(k, v)])
        -> (M.Map k v -> [(k, v)])
combine f1 f2 m =
  let f1' = f1 m
      f2' = f2 (m `M.union` M.fromList f1') -- program does not terminate when f1' is replace with f1 m 
  in f1' ++ f2'
  ```

Not sure if this expected or known, but I cannot explain it, so reporting it in case it's worth further investigation. 

I am using `containers-0.7` and `ghc-9.10.1`.

(@pacastega)

**Comment by tomjaguarpaw** [comment]
Hello Niki, you might have better luck filing this on the `containers` issue tracker. The library is not directly maintained by the Core Libraries Committee.

https://github.com/haskell/containers/issues/new

**Comment by simonpj** [comment]
I note that `f1'` occurs twice.  Replacing one occurrence by `f1 m` will duplicate the `f1 m` redex.  Sometimes duplicating a redex gives rise to an exponential blowup.  E.g.
```
f n = let k = f (n-1) in k + k
```
vs
```
f n = let k = f (n-1) in f (n-1) + k
```
Maybe that is happening here, and "loops forever" just means exponential?  

Guessing wildly!

**Comment by nikivazou** [comment]
Thanks @simonpj! Your guess makes sense! But from seconds to hours seems too much. 

Moving the issue to the containers. Thanks @tomjaguarpaw!
