### ISSUE TITLE
Proposal: Add Floating and Fractional instances to Ap

### ISSUE THREAD

**Issue by noughtmare** [haskell/core-libraries-committee#32]
## Motivation

The newtype `Data.Monoid.Ap` witnesses the pointwise lifting of monoid operations into any applicative. Additionally, it has a similar instance for the `Num` type class. With the `DerivingVia` extension we can use this newtype to derive instances for `Semigroup`, `Monoid` and `Num` for any applicative. However, similar instances for `Fractional` and `Floating` are missing, while I believe they could easily be implemented as well. 

A concrete place where these instances could be useful is in the `reflex` package: https://github.com/reflex-frp/reflex/blob/90891e177ffb1647324cce4c023b97a82bb59936/src/Reflex/Class.hs#L666-L669, this module also contains similar instances for `Semigroup`, `Monoid`, and `Num` which could all be derived via `Ap Behavior`.

## Proposal

I propose adding the following `Fractional` and `Floating` instances, which are very similar to the existing `Num` instance:

```haskell
instance (Applicative f, Fractional a) => Fractional (Ap f a) where
  (/) = liftA2 (/)
  recip = fmap recip
  fromRational = pure . fromRational

instance (Applicative f, Floating a) => Floating (Ap f a) where
  pi = pure pi
  exp = fmap exp
  log = fmap log
  sqrt = fmap sqrt
  (**) = liftA2 (**)
  logBase = liftA2 logBase
  sin = fmap sin
  cos = fmap cos
  asin = fmap asin
  acos = fmap acos
  atan = fmap atan
  sinh = fmap sinh
  cosh = fmap cosh
  asinh = fmap asinh
  acosh = fmap acosh
  atanh = fmap atanh
  log1p = fmap log1p
  expm1 = fmap expm1
  log1pexp = fmap log1pexp
  log1mexp = fmap log1mexp
```

These should be accompanied by a note similar to the one added to the `Num` instance about the lawfulness/lawlessness of these instances for some applicatives. I believe that the benefit of being able to derive these instances outweighs the chance that users will overlook the warning and derive incorrect instances.

**Comment by tomjaguarpaw** [comment]
> These should be accompanied by a note similar to the one added to the Num instance about the lawfulness/lawlessness of these instances for some applicatives.

Yikes, [that `Num` instance](
https://hackage.haskell.org/package/base-4.15.0.0/docs/Data-Monoid.html#t:Ap
) is rather unfortunate, but ...

> I believe that the benefit of being able to derive these instances outweighs the chance that users will overlook the warning and derive incorrect instances.

I guess the idea is that `Ap` is not really a thing you're supposed to use as a type, you're only "supposed" to use it as a hook for DerivingVia. If so, it makes me wish even more strongly for value-level DerivingVia hooks (related: https://github.com/ghc-proposals/ghc-proposals/pull/324).

**Comment by noughtmare** [comment]
Another alternative would be to add a subclass of `Applicative` which requires it to be pointwise like `ZipList`, then you could write a proper `(Pointwise f, Num a) => Num (Ap f a)` instance. But then `Pointwise` probably has no methods, which is unusual (maybe even discouraged?). I think an appropriate law for that `Pointwise` class could be:

```
p <*> q = flip ($) <$> q <*> p
```

**Comment by gbaz** [comment]
One should check the history, but it looks like that Num instance was in there from the start, and only later someone documented it didn't really work. Rather than doubling down on a mistake, ideally the Num instance would be removed. Barring that, I would prefer to leave things be than to write more unlawful instances.

Users may well use `Ap` directly rather than purely for newtype deriving. In such a case, they'd have functions that "do the wrong thing" just lying around. This seems to be a very bad idea.

**Comment by noughtmare** [comment]
> One should check the history, but it looks like that Num instance was in there from the start, and only later someone documented it didn't really work.

I checked and that seems to be what happened, although not with so many words (relevant commits are [introduce Ap](https://gitlab.haskell.org/ghc/ghc/-/commit/b67e8a3f107f7e7b2cefb526a5f956a4a3abc852) and [document lawlessness](https://gitlab.haskell.org/ghc/ghc/-/commit/bb35c0e573b0bc8fe6a28c00734fa124da02a755)).

But should we then remove the `Num` instance or just leave it like this?

**Comment by Bodigrim** [comment]
I don't think adding more slightly broken numeric instances is a good idea. "Unlawful" instances essentially reduce our ability to reason polymorphically. Plenty of existing numeric instances have warts and pitfalls, let's not make it worse. 

I'm sympathetic to `instance Num Ap` removal, if someone raises such proposal.

**Comment by josephcsible** [comment]
> Another alternative would be to add a subclass of `Applicative` which requires it to be pointwise like `ZipList`, then you could write a proper `(Pointwise f, Num a) => Num (Ap f a)` instance. Something like this:
> 
> ```haskell
> -- | law: zipWith f xs ys = zipWith (flip f) ys xs
> class Applicative f => Pointwise f 
> 
> zipWith :: Pointwise f => (a -> b -> c) -> f a -> f b -> f c
> zipWith = liftA2
> ```

That instance isn't lawful either. For example, `x + negate x = fromInteger 0` isn't true when `x = ZipList []`.

**Comment by noughtmare** [comment]
> That instance isn't lawful either. For example, x + negate x = fromInteger 0 isn't true when x = ZipList [].

You could consider a variant of `ZipLists` which is equal when the smallest common prefixes are equal, then it works. Also, you can simply add an extra law to forbid `ZipList` too:

```haskell
pure x = zipWith (\_ _ -> x) y z
```

Then you still have the lawful instances `(->) a` and `Behavior` from FRP.

But I feel we have strayed too far from the original topic of this proposal and I am convinced that this is not the right way to go, so I will close this. I now think that `DerivingVia` is not the golden bullet I had hoped for and I eagerly look forward to a proposal like https://github.com/ghc-proposals/ghc-proposals/pull/324.
