### ISSUE TITLE
Export PrintfType implementation

### ISSUE THREAD

**Issue by brandon-leapyear** [haskell/core-libraries-committee#34]
I'm curious why `PrintfType` isn't already exported. The comment here seems to indicate that the error message would be weird, but I don't see how that would be the case:

https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/Text/Printf.hs#L81-88

I just tried downloading `Printf.hs` and writing
```hs
let x = printf "asdf%s" True
putStrLn x
```
and I got the same error message whether I export `PrintfType (..)` or not.

Exporting this would be useful to allow `printf` to return other types, e.g. the `text` package could implement
```hs
instance PrintfType Text where
    spr a b = pack $ spr a b

let x = printf "asdf %s" "hello world" :: Text
```

# Proposal

I propose to change the
```hs
PrintfType, HPrintfType
```
export to
```hs
PrintfType(..), HPrintfType(..)
```

**Comment by Bodigrim** [comment]
Why do you need to define `instance PrintfType Text` and not `instance PrintfArg Text`?

**Comment by brandon-leapyear** [comment]
Because I'm trying to make `printf "foo: %d" 1` return a Text instead of a
String.

**Comment by Bodigrim** [comment]
Is it that bad to apply `T.pack` atop? If your goal is efficiency then you probably want to use `Builder` instead of `Text`, but it does not play well with `printf` interface.

**Comment by brandon-leapyear** [comment]
No, it's not terrible to just call pack, but why not give users the option
to defining PrintfType for more types? I see zero downside to just
exporting it.

**Comment by Bodigrim** [comment]
Adding `instance PrintfType Text` (or other instances) will make `printf` type checking very fragile in the absense of explicit type signatures. At the moment type checker knows that `instance PrintfType a` means that `a` is a variadic function to `String`, and even this is sometimes a source of cryptic error messages. But if there is a choice of result type, type mismatches can get seriously worse.

**Comment by brandon-leapyear** [comment]
> At the moment type checker knows that `instance PrintfType a` means that `a` is a variadic function to `String`

Well today, it's `String` or `IO ()`, so the typechecker already has to make a choice.

> , and even this is sometimes a source of cryptic error messages. But if there is a choice of result type, type mismatches can get seriously worse.

I agree that `printf` can be a source for cryptic error messages. What I'm saying is that exporting `PrintfType` and even adding extra instances for it (for the sake of argument, let's pretend overlapping instances don't exist) wouldn't make the current situation any worse.

Can you give an example of a code snippet that would result in worse UX by adding a `PrintfType Text` instance in scope (and again, just to be clear, I'm not saying `base` should add this instance, I'm asking to make it possible for some other library like `text` to add it)? To my understanding, any ambiguous usage of `printf` with `PrintfType Text` in scope is ambiguous today, and the error message should be not much more cryptic than it is today (it should just be an extra "These potential instances exist" line in the error message)

**Comment by Bodigrim** [comment]
Sorry, I must admit I don't have a working knowledge of `Text.Printf`. I'm still at loss why one might wish for `instance PrintfType Text` - is it any more useful than `instance PrintfType String`?

**Comment by brandon-leapyear** [comment]
Sure:
```hs
output :: [Text] -> IO ()

output [T.toUpper key, printf "number: %d" x, printf "string: %s" str]
-- vs
output [T.toUpper key, T.pack $ printf "number: %d" x, T.pack $ printf "string: %s" str]
-- or
output $ map T.pack [map toUpper key, printf "number: %d" x, printf "string: %s" str]
```
It's certainly _nice to have_; it's completely workaroundable. But this is just an example; it's not inconceivable for someone's personal project to have some special `MyString` type that they'd like to overload `printf` for, to easy ergonomics for their particular use-case.

My point, though, is to increase flexibility; there is absolutely no benefit to not re-export `PrintfType`. The comment linked above says that re-exporting it would cause cryptic error messages, but I don't see anything more cryptic than usual. I'm not suggesting we add `instance PrintfType Text` in `base`; it's probably not "useful enough" to make the change there. But why should we stop a user from being able to define it themselves in their own project because they like it?

**Comment by Bodigrim** [comment]
Is `instance PrintfType Text` a good motivating example here? Is it possible to implement `printf` for it in efficient way? Anyway, we can trigger a vote, if you are happy with the feedback received.

**Comment by tomjaguarpaw** [comment]
I'm confused. [Your link](https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/Text/Printf.hs#L81-88) shows that `PrintfType` _is_ exported (as is `HPrintfType`). Do you rather mean "Export `spr` (and `hspr`)"?

If so, given that their types leak implementation details, if we are going to consider this, I would rather define an abstract type for them. I believe this would be a non-breaking change as their type is not currently publicly exposed.

Existing types:

```haskell
class PrintfType t where
    spr :: String -> [UPrintf] -> t

-- | The 'HPrintfType' class provides the variable argument magic for
-- 'hPrintf'.  Its implementation is intentionally not visible from
-- this module.
class HPrintfType t where
    hspr :: Handle -> String -> [UPrintf] -> t

-- This is the type carried around for arguments in
-- the varargs code.
type UPrintf = (ModifierParser, FieldFormatter)
```

Proposed change:

```haskell
spr :: Spr t
hspr :: HSpr t
```

`Spr` and `Hspr` can be given functor instances, and then the instance for `Text` written as

```haskell
instance PrintfType Text where
    spr = fmap pack spr
```

**Comment by brandon-leapyear** [comment]
> I'm confused. [Your link](https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/Text/Printf.hs#L81-88) shows that PrintfType is exported (as is HPrintfType). Do you rather mean "Export spr (and hspr)"?

Yes, you're right. I'm specifically wishing to change this sentence:

> Their implementation is intentionally not visible from this module.

Updated the issue title to reflect this.

> `Spr` and `Hspr` can be given functor instances, and then the instance for `Text` written as
> 
> ```haskell
> instance PrintfType Text where
>     spr = fmap pack spr
> ```

That would solve my issue, so if that's good with everyone, that's good enough for me.

**Comment by tomjaguarpaw** [comment]
I think exporting that abstract interface is worth considering, though I'd like some evidence from maintainers of relevant libraries (including `text`) that they would want to take advantage of it.

**Comment by brandon-leapyear** [comment]
@tomjaguarpaw  I think it's worthwhile to do even if libraries like `text` don't want it, so that users could define `instance PrintfType Text` in their own projects if they so want.

@Bodigrim Sorry, I'm still new to this process; [`PROPOSALS.md`](https://github.com/haskell/core-libraries-committee/blob/main/PROPOSALS.md#the-when) says that once there have been no issues in 7 days, the CLC will have 14 days to reach a conclusion. Should the CLC have discussed this issue 7 days after Jan 26 or 7 days after Mar 21? But yes, I'd appreciate a vote when this current thread is finished.

**Comment by Bodigrim** [comment]
@brandon-leapyear I'm terribly sorry, that's my fault, this proposal fall off my radar. 

I think the discussion can benefit from engaging more participants, so I've posted a link on [Reddit](https://www.reddit.com/r/haskell/comments/uu8z44/export_printftype_implementation/) and I'm inclined to wait for a week or so. But as a proposer you have a right to trigger CLC vote immediately, if you wish.

**Comment by brandon-leapyear** [comment]
No worries! Happy to wait for more input

**Comment by endgame** [comment]
> I think it's worthwhile to do even if libraries like `text` don't want it, so that users could define `instance PrintfType Text` in their own projects if they so want.

This really doesn't look that compelling to me - my experience is that the more "implicit conversion"-ish stuff that happens through typeclasses, the less I know what's going on. I also don't think "allowing people to define more orphan instances" is an especially compelling argument.

**Comment by tomjaguarpaw** [comment]
An even less radical alternative is to not expose the `Functor` instance of `Spr` and `HSpr` but instance to only expose values of types `IsString s => Spr s` and `IsString s => HSpr s`.

**Comment by Bodigrim** [comment]
On one side, I think that exposing these internals (even as is) is not a big deal; `Text.Printf` is an old and stable module. On the other hand, I feel that the proposal lacks a motivating example. E. g., which specific instance for `Text` could be offerred? Is it any better than unpacking format string to `String`?

**Comment by Bodigrim** [comment]
My conclusion is that the change is unlikely to harm, but also unlikely to help, because I struggle to imagine instances for `Text` or others. @brandon-leapyear would you like us to vote on the proposal as is or would you prefer to expand it with motivational examples?

**Comment by Bodigrim** [comment]
@brandon-leapyear just a gentle reminder.

**Comment by brandon-leapyear** [comment]
Sorry! I swore I replied, but I guess I didn't. Yes, feel free to move to a
vote.

**Comment by Bodigrim** [comment]
@brandon-leapyear could you please update the proposal text to reflect what specifically would you like to change? Is it to export `PrintfType(..)` instead of `PrintfType`? What about `HPrintfType`?

**Comment by brandon-leapyear** [comment]
done

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to export type class members for `PrintfType` and `HPrintfType` from `Text.Printf`. @tomjaguarpaw @cgibbard @emilypi @chessai @mixphix

**Comment by cgibbard** [comment]
+1, seems fine to add instances of this if one really wants, and I'm usually in favour of classes being exposed to the possibility of new instances *somehow*. I agree it's a little bit sad that we still couldn't do better than just packing the Text at the end though.

**Comment by mixphix** [comment]
Yeah, +1, I suppose. I've personally never used this module, so if it could be beneficial to others to expose more existing functionality that seems like a reasonable thing to do.

**Comment by emilypi** [comment]
-1. 

I don't think any of us have had time to consider the code. It seems grotty af to me.

**Comment by Bodigrim** [comment]
@chessai could you please vote on this?

**Comment by chessai** [comment]
-1

IMO this api shouldn't even be in base, especially as it currently stands. I consider its use bad practise.

**Comment by Bodigrim** [comment]
Altogether 2 votes in favour, 3 against. Sorry @brandon-leapyear, the proposal is declined.

**Comment by brandon-leapyear** [comment]
I think my biggest point is what you said: is it really that big of a deal
to expose internals? Even moving this into an Internal.hs module and not
exporting from Text.Printf is fine.

To your second point, remember, this is PrintfType, not PrintfArg, so we're
talking about the return type of printf, not what to interpolate into the
string. It's already possible to define PrintfArg for Text such that %s
interpolates a Text

**Comment by brandon-leapyear** [comment]
Feel free to vote as-is. I'm happy with either resolution with the given
conversation
