### ISSUE TITLE
Generalise the instances of Eq, Ord, Read and Show for Compose

### ISSUE THREAD

**Issue by cgibbard** [haskell/core-libraries-committee#35]
Presently, Compose has the following two sensible derived instances:

```
Semigroup (f (g a)) => Semigroup (Compose f g a)
Monoid (f (g a)) => Monoid (Compose f g a)
```
These instances specify precisely what is required by the instance, and nothing more.

But also, it has these:
```
(Eq1 f, Eq1 g, Eq a) => Eq (Compose f g a)
(Ord1 f, Ord1 g, Ord a) => Ord (Compose f g a)
(Read1 f, Read1 g, Read a) => Read (Compose f g a)
(Show1 f, Show1 g, Show a) => Show (Compose f g a)
```

The constraints here are a bit silly, because they specify something much more stringent than what is required by an implementation of the class. I would propose we change the instances to the derived ones, and obtain:

```
Eq (f (g a)) => Eq (Compose f g a)
Ord (f (g a)) => Ord (Compose f g a)
Read (f (g a)) => Read (Compose f g a)
Show (f (g a)) => Show (Compose f g a)
```

These would behave much better for example in the case where f or perhaps g is a GADT with instances that do not really depend on the index type -- indeed, the index type may not even have the right kind for, e.g. a Show instance to exist, or it may involve types that we don't want such instances for, such as function types or IO.

**Comment by treeowl** [comment]
Yes please. I'd love to see `Eq1`, `Ord1`, etc., gradually move toward deprecation. The overgeneralization they got in the move to `base` makes them pretty painful to deal with.

**Comment by thielema** [comment]
On Sat, 29 Jan 2022, cgibbard wrote:

> Presently, Compose has the following two sensible derived instances:
> 
> Semigroup (f (g a)) => Semigroup (Compose f g a)
> Monoid (f (g a)) => Monoid (Compose f g a)
> 
> These instances specify precisely what is required by the instance, and nothing more.
> 
> But also, it has these:
> 
> (Eq1 f, Eq1 g, Eq a) => Eq (Compose f g a)
> (Ord1 f, Ord1 g, Ord a) => Ord (Compose f g a)
> (Read1 f, Read1 g, Read a) => Read (Compose f g a)
> (Show1 f, Show1 g, Show a) => Show (Compose f g a)

I guess, these ones are Haskell 98 and the other ones are 
FlexibleInstances, right?

**Comment by cgibbard** [comment]
Yeah, the existing instances are possible under Haskell 98's restrictions, though since the module already requires FlexibleInstances, it's unclear that we should contort the other instances there to avoid it (especially when it harms the usefulness of the type in certain applications).

**Comment by cgibbard** [comment]
If Haskell 98 were still really a thing and there was even a single other implementation of the language which didn't support FlexibleInstances, I would maybe agree.

**Comment by treeowl** [comment]
Has there *ever* been a Haskell implementation that didn't support it? I'm pretty sure at least Hugs and nhc98 did.

**Comment by thielema** [comment]
On Sat, 29 Jan 2022, cgibbard wrote:

> If Haskell 98 were still really a thing and there was even a single 
> other implementation of the language which didn't support 
> FlexibleInstances, I would maybe agree.

It may be the other way round: Since even simple libraries require 
language extensions there will be hardly new Haskell compilers, since they 
have no chance to support a useful range of libraries.

**Comment by treeowl** [comment]
> On Sat, 29 Jan 2022, cgibbard wrote: If Haskell 98 were still really a thing and there was even a single other implementation of the language which didn't support FlexibleInstances, I would maybe agree.
> It may be the other way round: Since even simple libraries require language extensions there will be hardly new Haskell compilers, since they have no chance to support a useful range of libraries.

This would be a valid complaint about, say, GADTs. Is there any Haskell implementation strategy where flexible contexts are hard to implement? Or even more work than prohibiting them?

**Comment by cgibbard** [comment]
It's actually more work to implement Haskell 98's restriction on instances than to not do so. So in this case, I don't think FlexibleInstances is holding anyone back from their implementation of the language. In fact, the counterpart to this, FlexibleContexts, was simply a bug in GHC for many years before it was named because nobody realised that what was implemented technically fell afoul of what the Report specified.

**Comment by treeowl** [comment]
This is flexible contexts, not flexible instances. The latter has somewhat trickier complications relating to overlap and orphanhood.

**Comment by cgibbard** [comment]
Oh, that does seem to be true, haha!

**Comment by treeowl** [comment]
Flexible instances should almost certainly be broken up into at two different extensions, since it does (at least?) two very different things:

1. Allows a bare type variable in an instance head, such as `instance ... => Foo Int a`.
2. Allows non-variable type arguments in an instance head, such as `instance Eq (Bar Int a)`.

My own somewhat naive experience suggests that 1 is much more often necessary than 2, and also seems less potentially problematic. 2 brings in a lot of the same challenges as MPTCs.

**Comment by cgibbard** [comment]
@thielema I'd just like to say that I agree with your sentiment when it comes to many language extensions (especially everything that does anything with records, as well as LinearHaskell), but just not these ones.

**Comment by treeowl** [comment]
@cgibbard I would have similar reservations about GADTs and type families, at least.

**Comment by cgibbard** [comment]
> @cgibbard I would have similar reservations about GADTs and type families, at least.

Yeah, GADTs in particular I think are extremely worthwhile, but definitely a lot of additional implementation complexity (though I do think they punch over their weight class in terms of what you get -- they subsume many other extensions). Type families have all that complication, but don't seem to buy you quite as much in exchange, and there are still many things about them which seem not well enough understood.

**Comment by Ericson2314** [comment]
I think this is a subset of my https://github.com/haskell/core-libraries-committee/issues/10 ?

**Comment by treeowl** [comment]
Type level computation (currently realized with type families) is really important for many GADT applications. Data families currently seem to punch well below their class, IMO.

**Comment by Ericson2314** [comment]
I agree with this, change. Not a big part of the additional quantified constraint change in #10 so that the old
```haskell
(Eq1 f, Eq1 g, Eq a) => Eq (Compose f g a)
(Ord1 f, Ord1 g, Ord a) => Ord (Compose f g a)
(Read1 f, Read1 g, Read a) => Read (Compose f g a)
(Show1 f, Show1 g, Show a) => Show (Compose f g a)
```
in fact imply the new
```haskell
Eq (f (g a)) => Eq (Compose f g a)
Ord (f (g a)) => Ord (Compose f g a)
Read (f (g a)) => Read (Compose f g a)
Show (f (g a)) => Show (Compose f g a)
```
rather than being logically independent (i.e. contradicting, since overlap rules preclude the "both" possibility of logical independence).

**Comment by cgibbard** [comment]
> I think this is a subset of my #10 ?

True! However, I think even without the changes to the *1 classes, I would now support this because I've realised the constraints on these instances are just so blatantly incorrect. Eq a should not be required to have Eq (Compose f g a), and that restricts the kinds in an unacceptable way, even. But if we can do both, let's do both. :)

**Comment by Bodigrim** [comment]
I'm in favor of this change, but it can be a breaking one, so we need an impact assessment.

**Comment by Bodigrim** [comment]
Approved as a part of #10.
