### ISSUE TITLE
Fast-track unique lawful instances

### ISSUE THREAD

**Issue by phadej** [haskell/core-libraries-committee#39]
There *was* a principle about 

> adding unambigously defined instances where they are well determined.

but the decision is hard to find and reference. (One indirect reference is in https://mail.haskell.org/pipermail/libraries/2019-April/029480.html, but I remember seeing it used to justify adding new instances to base).

---

I therefore request current CLC to either publicly acknowledge or reject this principle.

**Comment by andreasabel** [comment]
Would that principle have fast-tracked the famous _`Foldable` WAT_?
- https://mail.haskell.org/pipermail/libraries/2016-February/026678.html
- https://github.com/puffnfresh/wat-collection/pull/25/files

**Comment by andreasabel** [comment]
Ok, then I suggest the current CLC reject this principle.

**Comment by Bodigrim** [comment]
I cannot find any CLC vote on the matter. More importantly, I cannot distill a precise meaning of the statement: what kind of "fast-tracking" we are talking about if a vote is in order anyway, and who and how decides whether an instance is "unambiguous" and "well determined". 

It might be that previous CLC used to have a working convention of some sort, but it was not enshrined in writing and is not a part of the established formal process.

**Comment by cigsender** [comment]
From what I understand, `Functor` is the prototypical example of a "unique lawful instance": if there exists an implementation, then that implementation is uniquely determined by its structure. However I don't believe that bare tuples should be given more inherent functionality than strictly necessary: relying on `instance Foldable ((,) a)` is a code smell, and a sign that your domain logic is complex enough to merit a custom datatype.

**Comment by Bodigrim** [comment]
To answer the question more directly, the statement quoted is so vague that it hardly qualifies for a principle and it has never been formally approved.
