### ISSUE TITLE
Add `fromIntegerMaybe` to `Num` for safe numeric conversions

### ISSUE THREAD

**Issue by michaelpj** [haskell/core-libraries-committee#40]
EDIT: see revised proposal [below](https://github.com/haskell/core-libraries-committee/issues/40#issuecomment-1084395951).

It's fashionable to complain about `Num`, and very difficult to change it, given how pervasive it is. This is a small proposal that I think might actually be implementable and provide a meaningful improvement to the status quo. I expect it may well be more effort than it's worth, but I wanted to write down the idea.

## Motivation

Haskellers make frequent use of `fromInteger` (often via `fromIntegral`), but these conversions have a problem: they are typically partial or non-injective, and generally fail to be inverses of `toInteger`. For example, converting from a larger integral type to a smaller one will often wrap or truncate its argument. In my experience this is almost always bad, and a source of subtle bugs.

But for the more cautious Haskeller who wants a safe conversion function, there isn't much to hand.

## Proposal

Add a new method `fromIntegerMaybe :: Integer -> Maybe a` to `Num`. It has the following laws:

1. `fromIntegerMaybe` is always total, i.e. `fromIntegerMaybe x = _|_ ==> x = _|_`
2. `fromIntegerMaybe` agrees with `fromInteger` on its domain of definition, i.e. `fromIntegerMaybe i == Just j  ==> fromInteger i = j`
3. If `a` is an instance of `Integral`, then `fromIntegerMaybe` is an inverse to `toInteger` on its domain of definition, i.e. `fromIntegerMaybe (toInteger i) == Just i` and `fromIntegerMaybe i == Just j ==> toInteger j = i`

`fromIntegerMaybe` has a default definition of `fromIntegerMaybe i = Just $ fromInteger i`. This definition may not be lawful for existing instances!

`fromInteger` can similarly have a default definition of `fromInteger = fromJust . fromIntegerMaybe` (with a more suitable error).

Associated variants of functions which build on `fromInteger` should also be included, at the very least `fromIntegralMaybe = fromIntegerMaybe . toInteger`.

## Rationale

Unlike `toIntegralSized`, `fromIntegerMaybe` allows the typeclass definition to say under what conditions an `Integer` can be losslessly converted to the type. We can express this correctness condition with the laws above, particularly 3.

Given the importance of law 2, I could see the argument that `fromIntegerMaybe` should be a method of `Integral`. But also it naturally belongs with `fromInteger`.

Since there is a default definition for the method, I believe this change could be made without a backwards compatibility nightmare. But it may well be more complicated due to how fundamental `Num` is.

## Alternatives

`toIntegralSized` already exists in `base` and does the right thing in most cases. However, it has more stringent requirements (both types must be `Integral`, have `Bits` instances). It cannot be used for, say, `Int -> Maybe Complex`. Moreover, it is arguable that it doesn't even make much sense (as @treeowl [points out](https://gitlab.haskell.org/ghc/ghc/-/issues/19641#note_343970)), since it relies on implicit assumptions about the relationship between the `Bits` and `Integral` instances.

The `int-cast` package exists and provides specialized conversions for many types. Arguably it is superior as it allows non-`Maybe` conversions in the cases where it can be statically shown that the conversion is safe. However, in the case where dynamic checks are needed you have to use (essentially) `toIntegralSized`. So this proposal would improve the dynamically-checked part of `int-cast` and complement the statically-checked part.

**Comment by michaelpj** [comment]
Both good suggestions, thanks.

**Comment by Daniel-Diaz** [comment]
I don't have much to add, but I would appreciate something like this for `Num`. For numeric literals, `fromInteger` works great. But outside of that, I think `fromIntegerMaybe` is what's needed most of the time.

**Comment by Bodigrim** [comment]
> Add a new method `fromIntegerMaybe :: Integer -> Maybe a` to `Num`.

One can define a very similar function outside of `Num` type class:
```haskell
fromIntegerMaybe :: forall a. (Ord a, Bounded a, Integral a) :: Integer -> Maybe a 
fromIntegerMaybe n = if n < toInteger (minBound :: a) || n > toInteger (maxBound :: a) then Nothing else Just (fromInteger n)
```
Are there cases when `fromIntegerMaybe` can be defined more efficiently for a specific `a`?

> `fromIntegerMaybe` has a default definition of `fromIntegerMaybe i = Just $ fromInteger i`. This definition may not be lawful for existing instances!

This seems defeating the purpose: one can no longer use `fromIntegerMaybe` in polymorphic contexts and rest assured that it is safe. A default definition **must** be correct, even if not the most efficient.

**Comment by michaelpj** [comment]
> One can define a very similar function outside of Num type class:

One problem is that I don't believe this definition is universally correct. In particular, there are no laws on `fromInteger`, and in particular nothing that states how it is related to `Bounded`. You could write an implementation of `fromInteger` for a floating point number that threw on `0` because it wasn't clear if you meant `+0` or `-0`. Since `fromInteger` has a totally instance-dependent meaning, so must `fromIntegerMaybe`.

This is similar to the complaint that @treowl makes about `toIntegralSized`: it's fine for most actually-existing types, but there is no guarantee in the laws of the typeclasses that it will work. 

So perhaps I should put the point of the proposal more strongly: today there is *no* universally correct way to safely convert between numeric types. 

> Are there cases when fromIntegerMaybe can be defined more efficiently for a specific a?

That's a great question. I believe that in many cases we can be able to write efficient implementations depending on the bignum library being used for `Integer`. For example, `ghc-bignum` has a case for values that fit in an `Int#`: thus we can write:

```
integerToIntMaybe :: Integer -> Int
integerToIntMaybe (IS i) = Just I# i
integerToIntMaybe _ = Nothing
```

Of course, it's possible that the simple implementation with bounds checks could optimize into this version. I think that's unlikely (it would rely on being quite clever in eliminating the bounds checks), but it's possible.

But if my argument above is correct, then this is somewhat irrelevant. We need an instance-dependent `fromInteger` maybe to do safe conversions *correctly*, being able to do them fast is a bonus.

> This seems defeating the purpose: one can no longer use fromIntegerMaybe in polymorphic contexts and rest assured that it is safe. A default definition must be correct, even if not the most efficient.

I think you are right. However, I think that sinks this proposal, since I don't think we can provide a correct default implementation, even if we only provide it for instances that also have `Ord` and `Bounded`.

But without a default implementation I don't think this proposal is viable. We cannot break all `Num` instances!

**Comment by Bodigrim** [comment]
Re the last point: yeah, the only _correct_ way to proceed is without default implementation, which is a significant breaking change. I would not say it is completely out of question, but an obvious non-breaking alternative is `class Num a => SafeNum a where fromIntegerSafe :: Integer -> Maybe a`.

**Comment by michaelpj** [comment]
> For numeric literals, fromInteger works great. But outside of that, I think fromIntegerMaybe is what's needed most of the time.

This reminds me that `fromRational` also exists and probably would benefit from the same treatment as `fromInteger`. 

> an obvious non-breaking alternative is class Num a => SafeNum a where fromIntegerSafe :: Integer -> Maybe a.

Maybe that's the best we can do. Adding a whole new class for this one function doesn't feel all that satisfying, but I can't see any alternative.

-----

Troll suggestion:
```
fromIntegerMaybeDefault :: Num a => Integer -> Maybe a
fromIntegerMaybeDefault i = unsafePerformIO $ catch 
    (evaluate $ Just $ fromInteger i) 
    (\(e :: ErrorCall) -> pure Nothing)
```

**Comment by michaelpj** [comment]
I made a [repository] with an implementation of `SafeNum` and `SafeFractional`, some instances (not all that could be written and not all maximally fast) and a test suite that checks the laws.

Findings:
- It looks like all the existing instances _do_ obey the laws in 1, which is good.
- It's easy enough to write instances that obey the other laws also.

I'm coming around to having additional classes. It's not too bad.

**Comment by sjakobi** [comment]
@michaelpj The link to your repository seems to missing.

I like the solution with the new classes, but I think the `SafeNum` and `SafeFractional` class names seem to promise a bit much. E.g. `SafeNum` could be expected to contain checked (non-overflowing) and total variants of `(+)`, `(-)` and `(*)`. I'd actually love such functionality to be provided in `base`, but if it is out of scope for this proposal, `SafeFromInteger` might be a more appropriate name.

**Comment by michaelpj** [comment]
Ooops thanks, added the link back in.

> I like the solution with the new classes, but I think the SafeNum and SafeFractional class names seem to promise a bit much. 

That's a good point. I agree with you that it would be super to have non-overflowing total variants of the other `Num` methods, but I fear that there's a risk of growing this proposal too much...

That said, potentially we *could* add such methods with sensible default definitions, namely:

```
safePlus a b = fromIntegerMaybe (toInteger a + toInteger b)
```

etc. I think this might be sane - that equation might in fact be the law that we would expect `safePlus` to obey!

**Comment by sjakobi** [comment]
Are there any instances that have good definitions for `fromIntegerMaybe`, but not for `safePlus` (or `safeMinus`, `safeTimes`)? I suspect `Double` might be tricky?!

For now I'm tending towards the more fine-grained approach, i.e. `SafeFromInteger` and `SafeFromRational`.

I'd also like to request that the classes be defined without super-classes, because some users may prefer not to have instances for `Num` or `Fractional`.

(In the case of `SafeFromRational`, I wonder whether there should be instances for `Integer`, `Word8` etc. then…) 

And I have some concerns about efficiency: 

1. It would be great if these classes could be used in high-performance code, where you'd want to be sure that no `Maybe`s are allocated as results from `from[Integer,Fractional]Maybe`. Should we rely on GHC to take care of this?

   I see two alternatives:

   1. The methods could return unboxed sums, e.g.

        ```
        safeFromInteger :: Integer -> (# (# #) | a #)
        safeFromRational :: Rational -> (# (# #) | a #)
        ```
       `from[Integer,Fractional]Maybe` could then be defined in terms of these methods, outside of the classes.

    2. The methods could be CPS'd:

        ```
        safeFromInteger :: b -> (a -> b) -> Integer -> b
        safeFromRational :: b -> (a -> b) -> Integer -> b
        ```

     I'm not quite sure about the performance implications of these alternatives though. In the CPS-style you'd probably have to worry about the closures being allocated when `safeFrom[Integer,Rational]` isn't inlined.

2. How can we ensure that `fromIntegralMaybe` and `realToFracMaybe` don't allocate the intermediary `Integer`s / `Rational`s? `RULE`s?! Is there something more reliable?

**Comment by Bodigrim** [comment]
@michaelpj how do you feel about splitting this into separate proposals? I believe (1) can benefit from being voted separately.

**Comment by michaelpj** [comment]
Yes, that's a good idea. Adding the laws is cheap and easy, adding classes is much more work. I'll do that.

**Comment by Bodigrim** [comment]
With regards to `SafeNum` and `SafeRational`, I suggest to test them first in the user space, as a standalone library. The reasons are twofold:

* Changing type classes, which are already in `base`, is extremely difficult, as it's subject to three-release policy. I would rather add something which is already tested and proved being designed well.
* If `SafeNum` is implemented as a standalone library, people can start using it right away and provide feedback. If it's a part of `base`, then it will be available only starting from GHC 9.6 and any measurable adoption would not happen before H2 2023.

@michaelpj what do you think? (You can still exercise your right to table the proposal for a vote as is)

**Comment by michaelpj** [comment]
I think that's a good suggestion. Not being able to make them part of the original classes also removes most of the motivation for this being a part of `base`.

**Comment by brandonchinn178** [comment]
Related: https://github.com/ghc-proposals/ghc-proposals/issues/438#issuecomment-1199789374
