### ISSUE TITLE
Add `Fractional`, `Floating` and `IsString` instances to `Data.Monoid.Ap`

### ISSUE THREAD

**Issue by re-xyr** [haskell/core-libraries-committee#41]
### Motivation

`Ap` has "lifted" instances for `Num`, `Bounded`, `Monoid` and `Semigroup`:

```haskell
instance (Applicative f, Num a) => Num (Ap f a)
instance (Applicative f, Bounded a) => Bounded (Ap f a)
instance (Applicative f, Monoid a) => Monoid (Ap f a)
instance (Applicative f, Semigruop a) => Semigrup (Ap f a)
```

So by `deriving via (Ap f a)`, any applicative wrapper `f` over types `a` that have instances for those classes can provide lifted instances for notational convenience. I.e. instead of `liftA2 (+) (pure 1) (pure 2)` we can instead write `1 + 2`. 

There are other classes in `base` that also have trivial lifted instances for any `Applicative`, namely `Fractional`, `Floating` and `IsString`. Therefore it makes sense to also add their instances for `Ap` so that other `Applicatives` can derive these instances for free.

### What to change

Add the following instances to the `Data.Monoid.Ap` datatype:

```haskell
instance (Applicative f, Fractional a) => Fractional (Ap f a) where
  (/) = liftA2 (/)
  recip = fmap recip
  fromRational = pure . fromRational

instance (Applicative f, Floating a) => Floating (Ap f a) where
  pi = pure pi
  exp = fmap exp
  log = fmap log
  sqrt = fmap sqrt
  (**) = liftA2 (**)
  logBase = liftA2 logBase
  sin = fmap sin
  cos = fmap cos
  tan = fmap tan
  asin = fmap asin
  acos = fmap acos
  atan = fmap atan
  sinh = fmap sinh
  cosh = fmap cosh
  tanh = fmap tanh
  asinh = fmap asinh
  acosh = fmap acosh
  atanh = fmap atanh

instance (Applicative f, IsString a) => IsString (Ap f a) where
  fromString = pure . fromString
```

This is not a breaking change.

### Concerns

Like the `Ap` instance for `Num`, `Fractional` and `Floating` is not guaranteed to be lawful. It is lawful only when the `Applicative` produces exactly 1 value. Therefore we need to attach a similar warning as the `Num` instance to the new instances.

**Comment by tomjaguarpaw** [comment]
`Fractional` and `Floating` were [discussed previously](https://github.com/haskell/core-libraries-committee/issues/32) and soft-rejected.

**Comment by re-xyr** [comment]
I see, then I'm closing this.
