### ISSUE TITLE
Export minusNaturalMaybe from Numeric.Natural

### ISSUE THREAD

**Issue by Zemyla** [haskell/core-libraries-committee#45]
The function `minusNaturalMaybe` already exists in `GHC.Natural`, is safe, and is faster and more total than comparing two `Natural`s and optionally subtracting them.

**Comment by cigsender** [comment]
This particular definition of `minusNaturalMaybe` uses primitives, so it would be marginally faster than the obvious workaround would be, handwritten. If you'd like to draw up a PR for us to vote on, I'd most likely be in favour.

**Comment by Bodigrim** [comment]
@hsyl20 what do you think about exposing `minusNaturalMaybe` from `Numeric.Natural`?

**Comment by Bodigrim** [comment]
I think it's a reasonable proposal. I'm a bit concerned that `Numeric.Natural` does not export anything except `Natural` itself at the moment, but I cannot think of a better module. And making safe subtraction of `Natural` more accessible and discoverable is a noble goal indeed.

Dear CLC members, let's vote on the proposal. @tomjaguarpaw @cgibbard @cigsender @emilypi @chessai 

+1 from me.

**Comment by cigsender** [comment]
+1

**Comment by chessai** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by cgibbard** [comment]
+1

**Comment by Bodigrim** [comment]
With 5 votes in favour out of 6 possible, the proposal is approved by CLC. 

@Zemyla could you please create a GHC MR, which I can approve?

**Comment by Zemyla** [comment]
How do I do that?

**Comment by Bodigrim** [comment]
Fork https://gitlab.haskell.org/ghc/ghc, make a change in your fork and raise a merge request.

**Comment by Bodigrim** [comment]
@Zemyla just a reminder to open a merge request for this change.

**Comment by Zemyla** [comment]
I don't currently have a machine capable of doing that. Can someone else do it?

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @Zemyla, @ulysses4ever  |
| **Status**             |  merged |
| **`base` version**     | `4.18.0.0` |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8391/ |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | present   |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
