### ISSUE TITLE
Add `Control.Exception.throwIOLeft`

### ISSUE THREAD

**Issue by Gabriel439** [haskell/core-libraries-committee#46]
This function has type:

```haskell
throwIOLeft :: Exception e => Either e a -> IO a
```

I already created a pull request for this here:

https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7550

… and was told to open an issue here:

https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7550#note_411713

Edit: Here is the motivation copied from the original PR:

> The main motivation for this utility is to simplify working with
actions of type `IO (Either e a)`
>
> An alternative approach could have been to directly implement
a utility of type:
>
> ```haskell
> ??? :: IO (Either e a) -> IO a
> ```
>
> … but I went with the current type for two reasons:
> 
> * I conducted a poll to see which version people preferred:
> 
>   https://twitter.com/GabriellaG439/status/1428589302951268355
> 
> * The current version also has nicer theoretical properties, like
>   being a monad morphism
>
>   There's another property I didn't mention in the documentation, which
>   is that `throwLeft` distributes over exception handling, too:
>
>   ```haskell
>   throwIOLeft (m `catchError` \x -> f x) =
>     throwIOLeft m `catchError` \x -> throwIOLeft (f x)
> 
>   throwIOLeft (throwError e) = throwError e
>   ```
> 
> * It's fairly ergonomic to implement the latter type in terms of
>   the current type
> 
>   The latter type is just `(>>= throwIOLeft)`

**Comment by andreasabel** [comment]
It should be mentioned that a more special case already exists in `mtl-2.2.2`:
```haskell
liftEither :: MonadError e m => Either e a -> m a
liftEither :: Either IOException a -> IO a
```

**Comment by ChickenProp** [comment]
> It should be mentioned that a more special case already exists in mtl-2.2.2:

Though this isn't quite a special case because of `Exception`s other than `IOException`.

**Comment by tomjaguarpaw** [comment]
It looks to me like this is useful. @Gabriel439 has motivated its inclusion well. I think the only remaining question is whether we can remove duplication with `liftEither`, or perhaps change its naming so its relation

**Comment by tomjaguarpaw** [comment]
It looks to me like this is useful. @Gabriel439 has motivated its inclusion well. I think the only remaining question is whether we can remove duplication with `liftEither`, change its name so its relation to `liftEither` is clearer, or perhaps just note the similarity in the docs.  I haven't thought about it very hard but perhaps the last suggestion is the only practical one.

**Comment by Bodigrim** [comment]
@Gabriel439 could you please copy the motivation from https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7550 to this thread as well?

**Comment by andreasabel** [comment]
So we'd have
```haskell
liftEither = either throwError pure
throwIOLeft = either throwIO pure
```
both below the Fairbairn threshold.  But I concur that writing `either ... pure` is somewhat ugly.  A more versatile tool would be, maybe:
```haskell
fromRightM :: Applicative m => (a -> m b) -> Either a b -> m b
fromRightM f = either f pure
```
I'd be fine with writing `fromRightM throwError` instead of `liftEither` and `fromRightM throwIO` instead of `throwIOLeft`.

**Comment by dpwiz** [comment]
I like this, but I like `fromRightM` even more.

**Comment by fumieval** [comment]
The `>>= throwIOLeft` pattern is exactly the opposite of `try :: Exception e => IO a -> IO (Either e a)`, so we could name it `untry`

**Comment by Gabriel439** [comment]
`fromRightM f` is less ergonomic than `either f pure`:

* `fromRightM` is more characters
* `fromRightM f` requires an import, whereas `either f pure` does not

**Comment by mitchellwrosen** [comment]
I'm also a fan of `fromRightM`. I usually put it in a custom prelude under the name `onLeft`, though. (And `onLeftM` is what I call the variant that takes an `m (Either a b)` rather than an `Either a b`).

**Comment by ocharles** [comment]
Another option that is maybe worth mentioning is `unwrap`, taking inspiration from [Rust](https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap)

**Comment by Icelandjack** [comment]
> @fumieval: `untry`

hm or `giveUp`

**Comment by Gabriel439** [comment]
Just to be clear: I'm not volunteering to contribute a function other than the one I proposed (up to renaming).  If people want to propose other related changes to `base` they can open a new proposal.  If people don't want to add a `throwIOLeft` to `Control.Exception` then I'd prefer a simple "no" so that I can move on from this

**Comment by Bodigrim** [comment]
`throwIOLeft` is just `either throwIO pure`. The discussion above suggests that a name for this idiom is ambiguous, and vice versa I would not have guessed what `throwIOLeft` does from its name. Given this, I do not see an incentive to overbear Fairbairn threshold.

**Comment by ChickenProp** [comment]
I'd say that as a newbie, I think I wanted this and didn't know how to do it. That could be cleared up with documentation though.

**Comment by Bodigrim** [comment]
@Gabriel439 if you are satisfied with discussion/bikeshedding, as a proposer you have a right to trigger a vote on https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7550 as is.

**Comment by Gabriel439** [comment]
Yes, I would like to trigger a vote on the proposal as is

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7550 as is. @cgibbard @tomjaguarpaw @chessai @cigsender @emilypi 

----

-1 from me, because from my perspective it does not pass Fairbairn threshold and the name is not very telling.

**Comment by Bodigrim** [comment]
@cgibbard @tomjaguarpaw @chessai @emilypi just a gentle reminder to vote.

**Comment by tomjaguarpaw** [comment]
+0

I'm in favour of adding something of type `Exception e => Either e a -> IO a` but I think the name `throwIOLeft` puts the emphasis on the "left" when it should emphasise the "right". Normal control flow will proceed with the payload of the `Right`, after all. In my own packages I would add something useful and then get the name right later, but in `base` I don't feel I can be so cavalier.

So I abstain.

**Comment by Bodigrim** [comment]
@cgibbard @chessai @emilypi may I have your vote please?

**Comment by Bodigrim** [comment]
@cgibbard @chessai @emilypi this is the 4th time I ask you to vote in this thread alone. Could you please clarify your availability for CLC business?

**Comment by chessai** [comment]
-0.5

**Comment by Bodigrim** [comment]
Current tally is -2.5, so even if two remaining CLC members would vote in favor, the proposal is doomed to be declined anyway. Sorry, @Gabriel439.
