### ISSUE TITLE
Remove default method from Bitraversable

### ISSUE THREAD

**Issue by mpickering** [haskell/core-libraries-committee#47]
# Background

The `Bitraversable` class generalises the `Traversable` class to allow traversing over structures with two different types of holes.

```
class (Bifunctor t, Bifoldable t) => Bitraversable t where                                                                         
    bitraverse :: Applicative f => (a -> f c) -> (b -> f d) -> t a b -> f (t c d) 
```

The class contains a default implementation for `bitraverse`:

```
bitraverse f g = bisequenceA . bimap f g 
```
# Motivation

The problem is that the default instance leads to an infinite loop. `bisequenceA` is defined in terms of `bisquence` which is defined in terms of `bitraverse`. 

```
bitraverse f g
= (defn of bitraverse)
bisequenceA . bimap f g 
= (defn of bisequenceA)
bitraverse id id . bimap f g 
= (defn of bitraverse)
...
```

# Proposal

Remove the default method. Any instances defined without an explicit implementation are currently broken. 

# Relevant Links

* https://gitlab.haskell.org/ghc/ghc/-/issues/20329
* https://gitlab.haskell.org/ghc/ghc/-/issues/18901
* https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4692

**Comment by andreasabel** [comment]
+1, of course.  The current status quo is just broken.

**Comment by Bodigrim** [comment]
This is long overdue, so I'd like to trigger a vote immediately. Dear CLC members, please vote on removal of default definition of `bitraverse`. This is a rare case, when such change does not qualify as breaking, because any instance, which relies on it, necessarily diverges in runtime. CC @chessai @tomjaguarpaw @emilypi @cgibbard @cigsender 

----

+1 from me.

**Comment by cigsender** [comment]
+1 broken stdlib code bad!

**Comment by tomjaguarpaw** [comment]
+1

(I would be interested to learn how we got to this state in the first place. Was `bisequence` previously a class member?)

**Comment by chessai** [comment]
+1

**Comment by cgibbard** [comment]
+1 Yeah, I'd like to know as well. It definitely feels like the sort of thing that might be useful if bisequenceA had been a class method, but given that it's not, it should definitely not be left sitting there.

**Comment by treeowl** [comment]
Back in `bifunctors-5`, `bisequenceA` was a method. It was removed in `bifunctors-5.1`. `bimapM` was removed at the same time, which seems slightly more unfortunate.

**Comment by emilypi** [comment]
+1

**Comment by Bodigrim** [comment]
Approved unanimously. @mpickering ping me when there is an MR ready to approve.

**Comment by mpickering** [comment]
Thanks, MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7687

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @mpickering   |
| **Status**             |  merged  |
| **`base` version**     | `4.17.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7687 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | missing (please, [raise an MR to `base` to update changelog][changelog])  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
