### ISSUE TITLE
Export `liftA2` from `Prelude`

### ISSUE THREAD

**Issue by andreasabel** [haskell/core-libraries-committee#50]
(Transfered from https://gitlab.haskell.org/ghc/ghc/-/issues/20945):
As alternative to `<*>` method `liftA2` can be used to instantiate `Applicative`, but only the former is exported from `Prelude`.  I propose to also export the latter, for reasons of symmetry and clarity of error messages.

Detailed, anecdotic motivation:  Consider:
```haskell
{-# LANGUAGE DeriveFunctor #-}

data Foo a = Foo a deriving (Functor)

instance Applicative (Foo) where
  pure = Foo
```
Since `base` shipped with GHC 8.2, this gives the following warning:
```
warning: [-Wmissing-methods]
    • No explicit implementation for
        either ‘<*>’ or ‘GHC.Base.liftA2’
    • In the instance declaration for ‘Applicative Foo’
```

Trying to follow up on this literally,
```haskell
instance Applicative Foo where
  pure = Foo
  GHC.Base.liftA2 f (Foo a) (Foo b) = Foo $ f a b
```
I get other errors:
```
    ‘GHC.Base.liftA2’ is not a (visible) method of class ‘Applicative’
   |
10 |   GHC.Base.liftA2 f (Foo a) (Foo b) = Foo $ f a b
   |   ^^^^^^^^^^^^^^^

    Qualified name in binding position: GHC.Base.liftA2
   |
10 |   GHC.Base.liftA2 f (Foo a) (Foo b) = Foo $ f a b
   |   ^^^^^^^^^^^^^^^
```

GHC is giving me contradictory information here.  
The workaround is `import Control.Applicative`, but it seems inconsistent that some methods of `Applicative` are exported by `Prelude` and some not, especially those that comprise a `MINIMAL` definition of an instance.

Proposal: export `liftA2` also from Prelude.

Related, find some discussion there: 
- https://gitlab.haskell.org/ghc/ghc/-/issues/13191, referenced in https://hackage.haskell.org/package/base-4.10.0.0/changelog
- MR https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6468 (Note: this one is on `liftA2` _and_ `join`)

**Comment by treeowl** [comment]
Well I'm certainly in favor!

**Comment by googleson78** [comment]
Thanks! :bow:

And please! I use `liftA2` *way* more often than I use `(<*>)` too, regardless of symmetry and clarity of error messages.

**Comment by googleson78** [comment]
I also believe it's more beginner-friendly - it's always what I show first when teaching (instead of `(<*>)`). Explaining "lift this 2-argument function" is easier understood imo once you've seen a `Functor` which "lifts a 1-argument function" compared to the "scary" `f (a -> b)`. And beginners are the most affected by what's available by default, imo.

**Comment by tomjaguarpaw** [comment]
I'm in favour of this.

**Comment by Bodigrim** [comment]
While I'm totally in favor, this is a breaking change, so we need an impact assessment and patches. @andreasabel may I ask you to prepare it?

https://hackage-search.serokell.io/?q=%5EliftA2%5Cb gives a rough list of affected packages, including `hoopl`, `pandoc`, `parsley` and `shake`. There are might be more packages, which define `liftA2` locally, but I doubt it.

**Comment by andreasabel** [comment]
@Bodigrim wrote:
> we need an impact assessment and patches. @andreasabel may I ask you to prepare it?

Are there instructions how to go about it?  (Had a quick look, but didn't find such on this repo.)

**Comment by Bodigrim** [comment]
@andreasabel compile GHC 9.0 with `liftA2`exported from `Prelude` and try building https://github.com/Bodigrim/clc-stackage.

**Comment by andreasabel** [comment]
> compile GHC 9.0 with liftA2exported from Prelude and try building [Bodigrim/clc-stackage](https://github.com/Bodigrim/clc-stackage).

Ok, let me try to expand this instruction (WIP):
- Clone the GHC repo and switch to the `ghc-9.0` branch:
  ```
  git clone git@gitlab.haskell.org:ghc/ghc.git 
  cd ghc
  git checkout ghc-9.0
  git submodule update --init
  ```
- Modify `libraries/base/Prelude.hs`
- Activate old enough `ghc` (e.g. 9.0.2)
- Downgrade `happy` to `1.19`, e.g.:
  ```
  cabal install happy-1.19.12
  ```
- Build GHC-9.0
  ```
  ./boot
  ./configure
  make
  ```    
...

**Comment by Bodigrim** [comment]
@andreasabel I've updated  https://github.com/Bodigrim/clc-stackage to work with GHC 9.2.2. Could you please give it another go?

> * Build GHC-9.0
>       ```
>       ./boot
>       ./configure
>       make clean  # if you have leftovers from a previous compilation
>       make
>       ```

Why are you using `make` instead of `hadrian`?

**Comment by Bodigrim** [comment]
@andreasabel any chance you might have time to return to this?

**Comment by andreasabel** [comment]
@Bodigrim : Thanks for the nudge.  Unfortunately, I got too much on my plate atm.
If I was a routine GHC builder, I could do it on the side...

I would be happy if someone took over.

**Comment by googleson78** [comment]
I'll try to see what breakage happens given your instructions.

**Comment by googleson78** [comment]
Just as an update, I've been struggling with this, due to (probably) not building ghc right. As an example, I can't satisfy a dependency on `libffi`. If anyone has some tips, I'm happy to hear them (either here, or via other channels, e.g. email).

**Comment by Bodigrim** [comment]
@googleson78 could you quote an exact error message? If you are on macOS, [this incantation](https://gitlab.haskell.org/ghc/ghc/-/issues/20592#note_391266) works for me.

**Comment by Bodigrim** [comment]
@googleson78 `oeis2` fails to build because of `aeson-2.0`, and `hfsevents` probably lacks a system dependency; that’s fine. However I’m surprised with you results, because all packages defining their own `liftA2` (https://hackage-search.serokell.io/?q=%5EliftA2%5Cb) should have failed because of clashing identifiers.

**Comment by tek** [comment]
all of these search results are definitions, none of them are being used in expressions (except one, which is qualified). GHC doesn't complain about clashes for those

**Comment by googleson78** [comment]
Of the packages listed in the serokell search only these are in the stackage snapshot

### `linear-base`
Its `liftA2`s are always used qualified
### `netwire`
Doesn't actually define `liftA2`, it's only at the start of the line in some examples.
### `shake`
It actually defines `liftA2'`, not `liftA2`
### `special-functors`
I can't find it on Hackage even (what's going on here?), not on stackage either.
### `synthesizer-core`
It always uses its custom `liftA2` qualified.

The rest of the packages aren't in `clc-stackage.cabal`.

**Comment by ulysses4ever** [comment]
It seems to me that we should go ahead and open an MR.

**Comment by Bodigrim** [comment]
(I’m AFK, sorry for stupid questions)
@googleson78 could you please check https://hackage-search.serokell.io/viewfile/pandoc-2.18/src/Text/Pandoc/Readers/Odt/Arrows/Utils.hs#line-55 as well? I assume `pandoc` is on Stackage.

**Comment by googleson78** [comment]
It's not in nightly (and I assume it also wasn't when that snapshot was made), so that's why I missed it. But yeah, that should break, they hide `liftA2` from `Control.Applicative` and use their own in 3 places:

https://github.com/jgm/pandoc/blob/60974538b25657c9aa37e72cc66ca3957912ddec/src/Text/Pandoc/Readers/Odt/StyleReader.hs#L42

https://github.com/jgm/pandoc/blob/32297d56772e97ce39f54f6879ae2f69f3c4c6dd/src/Text/Pandoc/Readers/Odt/ContentReader.hs#L27

https://github.com/jgm/pandoc/blob/60974538b25657c9aa37e72cc66ca3957912ddec/src/Text/Pandoc/Readers/Odt/Generic/XMLConverter.hs#L57

**Comment by Bodigrim** [comment]
That’s surprising that `pandoc` is not on Stackage, but not a blocker. Thanks for the thorough investigation, @googleson78. 

@ulysses4ever agreed, an MR is due.

**Comment by googleson78** [comment]
I can send a MR.

**Comment by Bodigrim** [comment]
@googleson78 please go ahead.

**Comment by googleson78** [comment]
Since this will introduce a bunch of warnings into the ghc codebase, which seems like it's kept warning-free, I'm not sure how to proceed:

* just removing the redundant imports from everywhere doesn't work, because then we can't build stage1, since we're using an older compiler for that
* I can add `MIN_VERSION_base`/min ghc version macros, but I'm not sure what version I should put in there

Any advice on this?

**Comment by Bodigrim** [comment]
How about 
```haskell
import Prelude hiding (Applicative(..))
import Control.Applicative
```
?

**Comment by Bodigrim** [comment]
@googleson78 how does it look now?

**Comment by googleson78** [comment]
Sorry for the delay - I'll get around to it this week.

Re your suggestion - d'oh, thanks! I'll try it out. although I have some worries that then stage1 might still not build, but that's probably due to a lack of deeper understanding of the stages and/or being sleepy.

**Comment by googleson78** [comment]
MR - https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8449

**Comment by Bodigrim** [comment]
Dear CLC members, I think this is ready for a vote. The proposal is to export `class Applicative` from `Prelude` in full, including `liftA2`. This is a breaking change for packages, which define their own `liftA2` on the top level, but according to the analysis above the breakage is very limited. The change can also cause GHC warnings for redundant imports, but a backwards compatible solution exists, see above, so this is in line with the three release policy. 

@chessai @mixphix @cgibbard @tomjaguarpaw @emilypi 

----

+1 from me.

**Comment by mixphix** [comment]
+1, I look forward to this change!

**Comment by chessai** [comment]
+1

**Comment by emilypi** [comment]
+1 it cannot come soon enough.

**Comment by tomjaguarpaw** [comment]
+1

**Comment by cgibbard** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks all, approved unanimously. 

@andreasabel @googleson78 @ulysses4ever could someone of you please contribute a migration guide, similar to https://github.com/haskell/core-libraries-committee/tree/main/guides ?

**Comment by googleson78** [comment]
Opened #74 for a migration guide.

**Comment by Bodigrim** [comment]
We need a hero to do the same for `foldl'` in `Prelude` :)

**Comment by Bodigrim** [comment]
@treeowl could you please help us with https://github.com/haskell/containers/pull/841 ?

**Comment by ulysses4ever** [comment]
Could the link to migration guide be added to a visible place (e.g. top post here), that would be awesome. This issue is referenced from a number of places but the guide is a bit tricky to find (for me) currently.

**Comment by Bodigrim** [comment]
@ulysses4ever  All guides are in this very repository, https://github.com/haskell/core-libraries-committee/blob/main/guides/export-lifta2-prelude.md.

**Comment by ulysses4ever** [comment]
@Bodigrim I know, I just think that it's better UX to have the link posted on this thread. Kinda like GHC proposal threads have the rendered link in the top post.

**Comment by googleson78** [comment]
Hey @chshersh, the merged MR is actually not that one, it's - https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8449

**Comment by chshersh** [comment]
@googleson78 Thanks! Updated
