### ISSUE TITLE
Add `Enum` instance to `Down`, flipping direction

### ISSUE THREAD

**Issue by gergoerdi** [haskell/core-libraries-committee#51]
This is an idea that was prompted by my surprise that this behaviour is not already the case...

The ~`Bounded` and~ `Enum` instances of `Data.Ord.Down` should be changed such that 
```
succ @(Down a) = fmap pred
```

and all other methods implemented similarly.

Implementation is in [MR !8242](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8242).

**Comment by konsumlamm** [comment]
I'm not sure what `Down` you're looking at, but for the one in `base` (https://hackage.haskell.org/package/base-4.16.1.0/docs/Data-Ord.html#t:Down) the `Bounded` instance already works like that and there currently is no `Enum` instance.

**Comment by tomjaguarpaw** [comment]
[`Bounded` was `derived` in 4.14](https://hackage.haskell.org/package/base-4.14.0.0/docs/src/Data.Ord.html#line-64) but this has since been changed.

**Comment by gergoerdi** [comment]
> [`Bounded` was `derived` in 4.14](https://hackage.haskell.org/package/base-4.14.0.0/docs/src/Data.Ord.html#line-64) but this has since been changed.

Ah, that's good to know -- I was looking at 8.10.7, and didn't expect this has changed since.

**Comment by tomjaguarpaw** [comment]
Surprisingly I can't find where this was discussed, although I remember reading the discussion.

**Comment by gergoerdi** [comment]
> there currently is no `Enum` instance.

Looking at it in detail, the problem is that while `enumFrom*` could be implement with some smarts, `toEnum`/`fromEnum` would be tricky. Would it be acceptable to only have `Enum (Down a)` if not only `Enum a`, but also `Bounded a`? Because then, we could have

```
    fromEnum (Down x) = fromEnum (maxBound @a) - fromEnum x
    toEnum k = Down $ toEnum $ fromEnum (maxBound @a) - k
```

**Comment by tomjaguarpaw** [comment]
> not only `Enum a`, but also `Bounded a`

and also `Num a`? And also some fairly strong compatibility condition between them (that really ought to hold but I don't know if it actually holds for instances in practice).

**Comment by tomjaguarpaw** [comment]
I guess the compatibility condition is that `pred == subtract 1` and `succ == (+ 1)` so maybe not *that* strong.

**Comment by gergoerdi** [comment]
> > not only `Enum a`, but also `Bounded a`
> 
> and also `Num a`? And also some fairly strong compatibility condition between them (that really ought to hold but I don't know if it actually holds for instances in practice).

No, the subtraction is done on the `Int` side.

**Comment by tomjaguarpaw** [comment]
Ah so it is. That looks nice then!

**Comment by andreasabel** [comment]
@gergoerdi : Can you please change the issue title to reflect the updates?

**Comment by gergoerdi** [comment]
So I guess the actual implementation would look something like this:

```
instance (Enum a, Bounded a) => Enum (Down a) where
    succ = fmap pred
    pred = fmap succ

    fromEnum (Down x) = fromEnum (maxBound @a) - fromEnum x
    toEnum k = Down $ toEnum $ fromEnum (maxBound @a) - k

    enumFrom (Down x) = Down <$> enumFromThen x (pred x)
    enumFromTo (Down x) (Down y) = Down <$> enumFromThenTo x (pred x) y
```

**Comment by andreasabel** [comment]
> there currently is no `Enum` instance.

@gergoerdi : So would the title rather be: _Add `Enum` instance for `Down`_ ?

**Comment by gergoerdi** [comment]
Another approach that doesn't even require `Bounded a`, just flips the direction of  `succ`/`pred` via negating     `fromEnum`. Unfortunately, we still can't avoid also defining `enumFrom` and `enumFromThen` to ensure proper stopping:

```
instance (Enum a) => Enum (Down a) where
    fromEnum = negate . fromEnum . getDown
    toEnum = Down . toEnum . negate

    enumFrom (Down x) = Down <$> enumFromThen x (pred x)
    enumFromThen (Down x) (Down y) = map Down $ enumFromThen x y
```

TBH I don't know how kosher this is, because of the whole `negate @Int minBound == minBound` situation, but other than that corner case, it should work fine.

**Comment by Bodigrim** [comment]
Are there undesirable consequences of `negate @Int minBound == minBound` for `instance Enum (Down Int)` in particular?

**Comment by gergoerdi** [comment]
> Are there undesirable consequences of `negate @Int minBound == minBound` for `instance Enum (Down Int)` in particular?

One thing I'm aware of is that if all we have is `fromEnum`/`toEnum`, then, while `succ @Int` fails, `pred @(Down Int)` quietly returns a wrong result:

```
λ» succ @Int maxBound
*** Exception: Prelude.Enum.succ{Int}: tried to take `succ' of maxBound
λ» pred @(Down Int) (Down maxBound)
Down {getDown = -9223372036854775808}
```

Of course, this is easily fixed by adding `succ = fmap pred` and `pred = fmap succ`  as explicit method implementations.

**Comment by Bodigrim** [comment]
I think `coerce` is a better alternative to `fmap`.

**Comment by Bodigrim** [comment]
I like the proposal, but still feel a bit uneasy about it: it seems there is an unwritten assumption about connection between `Enum`, `Bounded` and `Ord`. Could it be spelled out? Are other existing instances in line with it?

**Comment by cigsender** [comment]
I'm not sure I support this proposal in its current form. `Down` has the explicit purpose of providing a simple wrapper with a flipped `Ord` instance. In this goal it excels. To add convoluted functionality to this class seems to diverge from its intent.

I would be more open to a new newtype (e.g. `Descending`) for this suggestion. Though `Down a` and `Descending a` would have the same `Ord` instance, the latter could require `instance (Enum a, Bounded a) => Ord (Descending a)` so that its purpose is more clearly stated as being "the enumeration from the other direction" instead of "flipped comparison".

**Comment by gergoerdi** [comment]
> I'm not sure I support this proposal in its current form. `Down` has the explicit purpose of providing a simple wrapper with a flipped `Ord` instance. In this goal it excels. To add convoluted functionality to this class seems to diverge from its intent.

FWIW, `Down a` already comes with a flipped `Bounded` instance, so this `Enum` instance merely extends that functionality. Also, with the version that goes via `Int`, we no longer have the `Bounded a` constraint on the proposed `Enum (Down a)` instance.

**Comment by Bodigrim** [comment]
@gergoerdi feel free to raise a GHC MR and trigger a vote.

**Comment by Bodigrim** [comment]
@gergoerdi just a gentle reminder that this awaits an action from your side.

**Comment by gergoerdi** [comment]
https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8242

**Comment by monoidal** [comment]
Earlier discussion which resulted in removal of `Enum (Down a)`: https://mail.haskell.org/pipermail/libraries/2020-September/030825.html

**Comment by Bodigrim** [comment]
@gergoerdi I left comments at https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8242

**Comment by Bodigrim** [comment]
@gergoerdi what's the status of this?

**Comment by Bodigrim** [comment]
@gergoerdi unless there is a progress within two weeks, I'll close this as abandoned.

**Comment by sjoerdvisscher** [comment]
Shouldn't the instance for `Bounded` be changed to `negate` the bounds instead of swapping them? Otherwise the `Enum` and `Bounded` instances will be incompatible.

**Comment by tomjaguarpaw** [comment]
@sjoerdvisscher Can you give an example?

**Comment by sjoerdvisscher** [comment]
Sorry that made no sense. (I was somehow thinking `Bounded` was working with indices instead of actual values. No🤦posting🤦before🤦coffee!)

**Comment by Bodigrim** [comment]
@gergoerdi  I think one solution is to add `Bounded a` constraint.

**Comment by Bodigrim** [comment]
@gergoerdi if you don't have a correct working patch to propose, I suggest we close this as withdrawn. What do you think?

**Comment by gergoerdi** [comment]
I'll try my hands at a `Bounded`-based implementation, it's just something
I was hoping we can avoid...

**Comment by Bodigrim** [comment]
@gergoerdi just a gentle reminder to make some progress, if you are still interested to champion this proposal. We are already past the initial deadline of two weeks.

**Comment by gergoerdi** [comment]
> @gergoerdi just a gentle reminder to make some progress, if you are still interested to champion this proposal. We are already past the initial deadline of two weeks.

Well tbf there was ICFP in the meantime :)

Looking at it now, I don't see how `Bounded a` helps with the `enumFrom` vs. `enumFromThen` problem, so I guess this is ultimately not meant to be...

**Comment by Ericson2314** [comment]
I would take `Enum` out of base if it could. It has always felt like a lousy class to me. `[x, ...]` stuff can be done in a different way, I hope.

**Comment by sjoerdvisscher** [comment]
@gergoerdi Although ugly, this seems to work: 

```haskell
    enumFrom (Down x) =
      if fromEnum x == fromEnum (minBound :: a)
        then [Down x]
        else coerce $ enumFromThenTo x (pred x) minBound
```

Or am I missing something?

**Comment by gergoerdi** [comment]
> Or am I missing something?

I've updated the MR based on this idea.

**Comment by Bodigrim** [comment]
Another opportunity is to require `Eq a` and check `if x == minBound`, which is probably slightly better than `if fromEnum x == fromEnum (minBound :: a)`. E. g., imagine [`Int128`](https://hackage.haskell.org/package/wide-word-0.1.1.2/docs/Data-WideWord-Int128.html) - it has `instance Enum` and `instance Bounded`, but `fromEnum x == fromEnum (minBound :: a)` results in too many false positives.

Dear CLC members, before we proceed to a vote, may I ask you to provide (non-binding) opinions on the proposal? @tomjaguarpaw @chessai @emilypi @cgibbard @mixphix

**Comment by mixphix** [comment]
We did have `Enum` for `Down`, before; it was just incorrect. [The MR to fix `instance Bounded a => Bounded (Down a)`](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4081), another problem mentioned in the discussion on the libraries mailing list @monoidal linked above, was backported to GHC 9.0. The patch also removed the `newtype`-derived `Enum` and `Integral` instances. I think this proposal (including @Bodigrim's point about checking the underlying type instead) adequately answers the remaining question from the mailing list: "does there exist an implementation of `Enum` for `Down` that respects the `Bounded` constraint?" in the affirmative, at the cost of adding an `Eq` constraint.

But `Eq` is not a superclass of `Bounded`, nor of `Enum`. This makes me wonder whether this instance is worth the trouble: what makes `[Down lg .. Down sm]` superior to `Down <$> [lg, pred lg .. sm]`? Is it simply to avoid (un)wrapping? I refer to my earlier argument that `Down` is intended to invert *comparison*, and that any further structure (on an arbitrary type) that that might entail is strictly accidental.

That being said, a type with `Enum` and `Bounded` surely has a unique total ordering given by `[minBound .. maxBound]`, which then fixes the total ordering on its `Down` type to `[Down maxBound .. Down minBound]`. It would be nice to have this truth represented by the instance.

---

I suppose I've come around on this. Despite this instance's removal from `base`, it was rightfully removed for being incorrect, while this proposal does seem to provide an accurate implementation. As such, pending moving the equality check to the underlying type, I'm in favour.

**Comment by gergoerdi** [comment]
> Another opportunity is to require `Eq a` and check `if x == minBound`, which is probably slightly better than `if fromEnum x == fromEnum (minBound :: a)`. E. g., imagine [`Int128`](https://hackage.haskell.org/package/wide-word-0.1.1.2/docs/Data-WideWord-Int128.html) - it has `instance Enum` and `instance Bounded`

Is the `Enum` instance of `Int128` really desired, though, since `fromEnum`/`toEnum` cannot possibly do the right thing?

**Comment by tomjaguarpaw** [comment]
@gergoerdi (or someone with administrator rights?) can you please [link the MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8242) in the top post so it's easy to find? 

The MR doesn't seem to compile. Is it missing `Bounded` and `Num` contexts?

**Comment by Bodigrim** [comment]
@gergoerdi It is well known that you cannot rely on `fromEnum` because of existence of `instance Enum Integer` or even more hideous `instance Enum Int64` on 32-bit arch.

**Comment by Bodigrim** [comment]
@gergoerdi your patch does not compile:
```
libraries/base/Data/Ord.hs:160:25: error: [GHC-39999]
    • Could not deduce ‘Enum a0’ arising from a use of ‘fromEnum’
      from the context: Enum a
        bound by the instance declaration
        at libraries/base/Data/Ord.hs:152:10-32
      The type variable ‘a0’ is ambiguous
      Potentially matching instances:
        instance Enum a => Enum (Down a)
          -- Defined at libraries/base/Data/Ord.hs:152:10
        instance Enum Ordering -- Defined in ‘GHC.Enum’
        ...plus 13 others
        ...plus 14 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the second argument of ‘(==)’, namely
        ‘fromEnum (minBound :: a)’
      In the expression: fromEnum x == fromEnum (minBound :: a)
      In a stmt of a pattern guard for
                     an equation for ‘enumFrom’:
        fromEnum x == fromEnum (minBound :: a)
    |
160 |         | fromEnum x == fromEnum (minBound :: a)
    |                         ^^^^^^^^
libraries/base/Data/Ord.hs:160:35: error: [GHC-39999]
    • Could not deduce ‘Bounded a1’ arising from a use of ‘minBound’
      from the context: Enum a
        bound by the instance declaration
        at libraries/base/Data/Ord.hs:152:10-32
      Possible fix:
        add (Bounded a1) to the context of
          an expression type signature:
            forall a1. a1
    • In the first argument of ‘fromEnum’, namely ‘(minBound :: a)’
      In the second argument of ‘(==)’, namely ‘fromEnum (minBound :: a)’
      In the expression: fromEnum x == fromEnum (minBound :: a)
    |
160 |         | fromEnum x == fromEnum (minBound :: a)
    |                                   ^^^^^^^^
```

As for non-binding opinions, I'm happy to vote in favour of the instance, if it uses `if x == minBound` instead of `fromEnum` as elaborated above.

**Comment by gergoerdi** [comment]
(build fixed)

> As for non-binding opinions, I'm happy to vote in favour of the instance, if it uses `if x == minBound` instead of `fromEnum` as elaborated above.

Even at the cost of the extra `Eq a` constraint?

**Comment by Bodigrim** [comment]
As we discussed, `fromEnum x == fromEnum (minBound :: a)` is wrong when (architecture-dependent) `Int` is smaller than `a`. This is simply not an option.

I mean, all this pile of `(Eq a, Bounded a, Enum a)` is indeed unwieldy. Ideally we should spell out our assumptions about the interaction between these classes (see https://github.com/haskell/core-libraries-committee/issues/51#issuecomment-1094087424), but given how botched `class Enum` is, I'm prepared to look at this from pragmatic viewpoint. Any `Enum a` should morally be `Eq a` as well, and I believe this is true for all types in `base`, so the additional constraint is not a burden.

**Comment by gergoerdi** [comment]
> Any `Enum a` should morally be `Eq a` as well, and I believe this is true for all types in `base`, so the additional constraint is not a burden.

This convinced me. I've pushed a version that requires `Eq a`.

**Comment by cgibbard** [comment]
+1

**Comment by mixphix** [comment]
-1. Considering that this implementation causes errors for unsigned types (see [the MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8242#note_455528)), I'm voting against this proposal.

**Comment by gergoerdi** [comment]
> -1. Considering that this implementation causes errors for unsigned types (see [the MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8242#note_455528)), I'm voting against this proposal.

[See this comment](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8242#note_455542), unsigned types work just fine, within the spelled-out constraints of `Enum`.

**Comment by mixphix** [comment]
> unsigned types work just fine, within the spelled-out constraints of `Enum`.

This is a great point that clears it up for me. Thank you, I'm now comfortable to vote in favour.

+1

**Comment by LSLeary** [comment]
Rather than `negate`, we want a function `f :: Int -> Int` that is an order-reversing map—one with the property that for all `x, y :: Int`, `x < y` ==> `f y < f x`. Since `Int` is finite, it's straightforward to see that this function exists and is unique. Possible implementations include `subtract 1 . negate` and `negate . (+1)`.

Order-reversing maps are to order-preserving maps as reflections are to translations; they're closed under composition, with an even number of the former giving you the latter. Since both `Down` and `getDown` are by definition order-reversing, it follows that using `f` as below preserves the property that `fromEnum` and `toEnum` are order-preserving at the underlying type, if indeed they are.

```haskell
  fromEnum = f . fromEnum . getDown
  toEnum = Down . toEnum . f
```

Note that, while not explicitly a law, I do expect `fromEnum` to satisfy this property whenever `Int` is large enough.

**Comment by LSLeary** [comment]
@tomjaguarpaw "Wrong" in the loose sense that it may destroy a property we wish to keep, and yes.

**Comment by Bodigrim** [comment]
FWIW `subtract 1 . negate` is `Data.Bits.complement`. 

When `x = minBound` and `y /= minBound`, we have `x < y` but at the same time somewhat counterintuitively `negate x < negate y`, because `negate minBound = minBound`. Subtracting 1 makes this peculiarity to disappear. 

Back into `Enum` realm, @LSLeary's desired property is that if `fromEnum x < fromEnum y` then `fromEnum (Down x) > fromEnum (Down y)`. For this purpose `subtract 1 . negate` indeed works better than just `negate` and does not seem to have other downsides, but I'm not terribly bullish on this: `fromEnum` is already broken for all means and purposes.

**Comment by tomjaguarpaw** [comment]
That's pretty convincing to me. If we are going to do this then it should be with `subtract 1 . negate` as @LSLeary says. I don't see the point of making a broken type class even worse.

-1

**Comment by Bodigrim** [comment]
More specifically, the argument goes like this. For `instance Enum Int` we enjoy `fromEnum = toEnum = id`, and `fromEnum` automatically preserves ordering. However if `fromEnum = negate` in `instance Enum (Down Int)`, the mapping is not order-reversing because of paradoxical behaviour of `negate minBound`. 

(@LSLeary I hope I'm not misrepresenting your point?)

@gergoerdi how do you feel about amending the proposal with `Data.Bits.complement` in place of `negate`?

**Comment by gergoerdi** [comment]
> @gergoerdi how do you feel about amending the proposal with `Data.Bits.complement` in place of `negate`?

I think at this point the best would be for me to just change the MR to use `complement`, and then remove any specifics from the proposal, since the proposal's intention was never to propose any specific implementation strategy...

**Comment by tomjaguarpaw** [comment]
Yes, my "-1" was for the specific MR, not the proposal. My understanding is that the CLC votes on specific MRs, not general proposals (although I suppose the wording of [@Bodigrim's message](https://github.com/haskell/core-libraries-committee/issues/51#issuecomment-1263979711) could be interpreted either way).

**Comment by Bodigrim** [comment]
The MR has been updated to use `complement`: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8242/diffs

@mixphix @cgibbard could you please confirm that this does not affect your approval?
@tomjaguarpaw is this change satisfactory?
@chessai @emilypi just a gentle reminder to vote.

**Comment by mixphix** [comment]
LGTM

**Comment by tomjaguarpaw** [comment]
+1

----

Yes, that's satisfactory. I think the `toEnum`/`fromEnum` is a big strange, but I don't think it actually violates any known laws.

**Comment by emilypi** [comment]
+1 from me

**Comment by Bodigrim** [comment]
Altogether this gives us at least 4 votes in favor, which is sufficient to approve. Thanks all!
