### ISSUE TITLE
Clarify laws of TestCoercion

### ISSUE THREAD

**Issue by Ericson2314** [haskell/core-libraries-committee#53]
See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7978. A follow up to our previous discussion in #21.

Per the thread below, this ended up being far hairier than I expected. But I hope we can arrive at a cautious point of consensus.

**Comment by Bodigrim** [comment]
I’ve left a question at GitLab.

**Comment by Bodigrim** [comment]
@Ericson2314 just a gentle reminder, please update MR if you wish to proceed.

**Comment by Ericson2314** [comment]
Hmm I don't think I meant the other way, but I do think this could be clearer!
 
A singleton type for test equality means there is one term for each possible type argument. That is simple enough. But for test coercible, easy answers defy us. We can't have one term per type argument, and also one term per *equivalence class* of type arguments quotiented by coerciability.

I would appreciate collaborative brainstorming on this! :)

**Comment by Icelandjack** [comment]
Should `TestEquality` have a `TestCoercion` superclass? 

```haskell
type    Default :: (k -> Type) -> (k -> Type)
newtype Default f a = Default (f a)
  deriving
  newtype TestEquality

instance TestEquality f => TestCoercion (Default f) where
  testCoercion :: Default f a -> Default f b -> Maybe (Coercion a b)
  testCoercion as bs = testEquality as bs <&> \Refl -> Coercion
```

**Comment by Ericson2314** [comment]
Yes that could be. I was sort of feeling coercibility is a slightly more unstable/GHC-ish concept, but I think that might be too abstract s concern at this point :).

**Comment by Ericson2314** [comment]
I am now thinking perhaps in the "good singleton" case the GADT *should* reflect equivalence classes.

So ones with data constructors like the latter one:
```haskell
data Rep :: Type -> Type where
  BadInt :: forall a. a ~ Int => Rep a -- same as `BadInt :: Rep Int`
  GoodInt :: forall a. a `Coercible` Int => Rep a
```

**Comment by Ericson2314** [comment]
`Rep` has these properties:

1. It's a singleton: One inhabitant only for valid indices.
2. Morally representational role: `Coercible a b => Coercible (f a) (f b)`, though GHC will struggle with this.

The `TestEquality` singleton extra law was written:
```haskell
testEquality (x :: f a) (y :: f b) = Just Refl ⟺ a = b ⟺ x = y
```
but this is kinda fishy (my bad!) because `x = y` isn't really a valid proposition if we don't know whether `x` and `y` are the same type.
So we can fix with:

reg law:
```haskell
testEquality (x :: f a) (y :: f b) = Just Refl ⟺ a = b
```

singleton law:
```haskell
-- a = b => f a = f b -- normal role at least, this is always true 
a = b ⟹ x = y
```

then the `testCoercion` equivalent is:
```haskell
testCoersion (x :: f a) (y :: f b) = Just Coerce ⟺ Coercible a b
```
```haskell
Coercible a b => Coercible (f a) (f b)
Coercible a b ⟹ x = coerce y
```

**Comment by Ericson2314** [comment]
The problem with the above suggestion is that GHC will need the things in https://github.com/ghc-proposals/ghc-proposals/pull/233 to realize the type is representational.

**Comment by Bodigrim** [comment]
@Ericson2314 I know that you are extremely busy improving Haskell ecosystem (greatly appreciated!), but it would be nice to make some progress here. If there is no action by 2023, I'll close the proposal as abandoned, feel free to reopen again when you get free time.

**Comment by Ericson2314** [comment]
Sorry I missed your previous comment. I am not sure exactly what you mean, but given the general impasse on the rest I like the sound of it. Would you mean leaving a big giant suggestion on the MR (or just force pushing)? I'll gladly accept that change.

**Comment by Bodigrim** [comment]
Sorry, I don't have time for "a big giant suggestion". It's a burden of a proposer to come up with a specific proposal.

The title is "Clarify laws of `TestCoercion`". However, your MR does three things at once:
* fixes capitalization typos in `TestEquality` docs (this is already fixed in `HEAD`),
* extends discussion of `TestEquality` properties (IMHO more confusing than enlightning),
* adds laws of `TestCoercion`.

If you limit your MR to the third point only to match its title, we can hold a vote.

**Comment by Bodigrim** [comment]
I don't feel like it's up to CLC to approve "Guidance on use with singleton types", it can go with the usual documentation process. However, it looks suitable for CLC to vote on the proposed law
```haskell
-- The result should be @Just Coercion@ if and only if the types applied to @f@
-- are coercible:
--
-- @testCoercion (x :: f a) (y :: f b) = Just Coercion@ ⟺ Coercible a b@
```
@Ericson2314 would you like us to go ahead?

**Comment by treeowl** [comment]
Personally, I'm not too keen on this proposal. The reason is that knowing two things are *not* coercible doesn't seem obviously useful. That doesn't mean it's not useful, but I need to know why it is. What's the purpose of this law? I would expect this to be a "best effort" method that either gives you a coercion or no info.

**Comment by Bodigrim** [comment]
@treeowl the idea is to mirror [`TestEquality` law](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Type-Equality.html#t:TestEquality):
```haskell
TestEquality (x :: f a) (y :: f b) = Just Refl ⟺ a = b
```

**Comment by treeowl** [comment]
I disagree with that law as well, but regardless, analogy doesn't seem adequate justification for any class law. There needs to be some purpose or reasoning principle. What does this law accomplish other than reducing the number and/or scope of potentially useful instances?

**Comment by Ericson2314** [comment]
Sure go ahead.

@treeowl I think analogies are important, otherwise we are sort of "Chesterton's fence trolling". I would not however if all this stuff was simply deprecated. I think  `GEq` is more useful, and none of this seems important enough to be in `base` (is anyone really abstracting over `Arbitrary` new types?). Then it will no longer take up CLC time.

**Comment by treeowl** [comment]
`GEq` is definitely more useful than `TestEquality`, when you can get it, yes! However, I would argue that:

1. `TestEquality` can usefully complement `GEq` if *and only if* it has no laws. For example,

    ```haskell
    data Foo a b where
      Yeah :: Foo a a
      Whatever :: Foo a b
    instance TestEquality (Foo a) where
      testEquality Yeah Yeah = Just Refl
      testEquality _ _ = Nothing
    instance (TypeError ..., Bottom) => GEq (Foo a) where
      gEq = no
    ```
3. A `Coercible` analogue of `GEq` would be almost completely useless.
4. `TestCoercion` can most usefully complement `GEq` and `TestEquality` if it has no laws.

Thus adding laws to `TestCoercion` makes things worse than they currently are, and does not help us move in a better direction.

**Comment by Bodigrim** [comment]
> I disagree with that law as well, but regardless, analogy doesn't seem adequate justification for any class law. There needs to be some purpose or reasoning principle. What does this law accomplish other than reducing the number and/or scope of potentially useful instances?

The reason we bother about laws for type classes is that we can have only one instance for each type, and class laws must limit potential choices to a single one (up to isomorphism). Leaving `TestCoercion` lawless, suggesting users to implement "best effort" methods is suboptimal, because it allows multiple "lawful" implementations, starting with `testCoercion _ _ = Nothing`. How would you choose which one of them is better?..

That said, we are edging to an anniversary of this ticket. While I appreciate the concerns raised by @treeowl, I don't feel like keeping the floor open longer will be fruitful. It's time to make a choice.

----

*...changing hats...*

Dear CLC members, let's vote on the proposal to add a law to [`TestCoercion`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Type-Coercion.html#t:TestCoercion) stating that
```haskell
testCoercion (x :: f a) (y :: f b) = Just Coercion ⟺ Coercible a b
```
This law is similar to the existing law for [`TestEquality`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Type-Equality.html#t:TestEquality), which requires 
```haskell
testEquality (x :: f a) (y :: f b) = Just Refl ⟺ a ~ b
``` 
@tomjaguarpaw @chessai @cgibbard @mixphix @emilypi 

----

+1 from me, I think it's important to restrict the number of potential implementations and to keep laws between `TestEquality` and `TestCoercion` in sync.

**Comment by treeowl** [comment]
@Bodigrim , a good instance is one that produces `Just` for as many values as possible for a given set of constraints. That's pretty obvious.

**Comment by Bodigrim** [comment]
It's not obvious to me that all potential instances form a total order to choose the supremum.

**Comment by treeowl** [comment]
I doubt they do. But we normally don't require that (or any) level of uniqueness for class instances!

**Comment by Ericson2314** [comment]
Erm why wouldn't they form a partial order with a supremum? I am having a hard time imagining why flipping a `Nothing` to a `Just` would necessitate flipping another `Just` to a `Nothing`.

**Comment by treeowl** [comment]
> Erm why wouldn't they form a partial order with a supremum? I am having a hard time imagining why flipping a `Nothing` to a `Just` would necessitate flipping another `Just` to a `Nothing`.

Hmmm ... Good question. I don't actually have an example. If that's impossible, then the argument against this proposal is certainly stronger.

**Comment by tomjaguarpaw** [comment]
+1

----

I'm not too familiar with this area, but for future work, would the direction in https://github.com/haskell/core-libraries-committee/issues/98 make laws redundant? That is, have a combinator that either produces a coercion for `a` and `b`, or evidence that that is impossible?

**Comment by treeowl** [comment]
@tomjaguarpaw Laws would be irrelevant for such a class, but that would be unimplementable for some types that can implement this one lawlessly.

**Comment by tomjaguarpaw** [comment]
Can you give an example?

**Comment by Ericson2314** [comment]
```haskell
data Foo x where
  Bar Int :: Foo Int
  Baz ::  forall a. (a -> a) :: Foo a

instance TestEquality Foo where
  testEquality = \cases
    (Bar _) (Bar _) -> Just Refl
    _ _ -> Nothing
```

**Comment by Ericson2314** [comment]
```haskell
newtype Zint = Zint Int

data Foo x where
  Bar :: Int -> Foo Int
  Baz :: Zint -> Foo ZInt
  Qux :: forall a. (a -> a) :: Foo a

instance TestCoercion Foo where
  testCoercion = \cases
    (Bar _) (Bar _) -> Just Coercion 
    (Bar _) (Baz _) -> Just Coercion 
    (Baz _) (Bar _) -> Just Coercion 
    (Baz _) (Baz _) -> Just Coercion 
    _       _       -> Nothing
````

**Comment by Ericson2314** [comment]
Perhaps I should have said more during #21, but at the time I was mainly focused on there being *some* resolution for what `TestEquality` was about, not which resolution it was.

**Comment by treeowl** [comment]
```haskell
data Intly a where
  Yop1 :: Intly Int
  Yop2 :: Coercible a Int => Intly a
  Meh :: Intly a
  Nah :: Intly Char
  Uhh :: Coercible a Char => Intly a

instance TestCoercion Intly where
  testCoercion Yop1 Yop1 = Just Coercion 
  testCoercion Yop1 Yop2 = Just Coercion
  testCoercion Yop2 Yop1 = Just Coercion
  testCoercion Yop2 Yop2 = Just Coercion 
  testCoercion Nah Nah = Just Coercion
  testCoercion Nah Uhh = Just Coercion
  testCoercion Uhh Nah = Just Coercion 
  testCoercion Uhh Uhh = Just Coercion
  testCoercion _ _ = Nothing
```

When you try to implement for this type, you run into multiple problems.

```haskell
gCo Nah _Any_pattern = -- oops, can't say
gCo Yop1 Uhh = \Coercion -> error "Can't prove this in Haskell"
```

One fundamental problem is that imports and context can change what's `Coercible`!

**Comment by tomjaguarpaw** [comment]
> One fundamental problem is that imports and context can change what's Coercible!

Interesting. I am beginning to doubt the value of this type class!

**Comment by treeowl** [comment]
When it's left alone to be lawless, I believe it can be useful as a best-effort optimization, though I don't have an immediate application. But laws seem to reduce its applicability without increasing its utility in any way I can imagine, so I think they make things worse.

**Comment by chessai** [comment]
-1

Typeclasses with laws, while incredibly useful for reasoning (among other things), are rigid. Typeclasses alone are already rigid, and their hierarchies even more so, to the point of "brittleness". Designing a sensible hierarchy is notoriously difficult, and making the wrong choice(s) can have lasting consequences. Attempts to address those consequences are resoundingly felt throughout the community of end users. (As a side note, for a language which mostly makes refactoring a dream, the presence of typeclasses often introduces a friction during refactoring not shared by most of Haskell)

Lawless typeclasses are not entirely useless. There are a number of typeclasses which are either lawless (`{To,From}JSON`, `Arbitrary`, `Read`, `Show`, etc.) or their concerns are too numerous (`Num`, `Enum`). The problem with many lawless classes is that they lack clear semantics, making it hard to reason with them. Laws are often great for reasoning, but a typeclass can have some intentions (supported by its types and its documentation) which guide users toward what is best for them. `mtl`'s typeclasses do not have laws (though there is some sparse effort to pin them down), but their semantics are clearly and widely understood.

The addition of this law at passing glance, seems sensible. So does the one for `TestEquality`. But with some more thought, here I'm inclined to agree with @treeowl - I think this one (and probably `TestEquality`) are better left lawless. We can provide clear semantics and guide users toward a best-effort, but in my opinion, imbuing a typeclass with laws will not always make it more useful, and can even do the opposite.

Also, as @tomjaguarpaw pointed out, `TestCoercion` may not even be that valuable to begin with, though that's a tangential issue.

**Comment by Bodigrim** [comment]
@mixphix @cgibbard @emilypi just a gentle reminder to vote.

**Comment by mixphix** [comment]
-1. I'm against adding laws to this typeclass for the following reasons:

- it is rarely used, save by people who know what they're doing with a `Coercion`
- those who know what they're doing with a `Coercion` and use this typeclass will likely be able to debug an instance that doesn't do what they're expecting
- explaining in the docs that, by including those laws, what you really want to use the typeclass for isn't even possible for GHC, isn't a great look

**Comment by Bodigrim** [comment]
Two votes in favor, two votes against. @cgibbard @emilypi let's finish this off.

**Comment by Ericson2314** [comment]
I'll rescind it for one deleting the laws in `TypeEquality`. I just want them to be consistent.
