### ISSUE TITLE
Make `GHC.Stack.Types.SrcLoc` more strict

### ISSUE THREAD

**Issue by konsumlamm** [haskell/core-libraries-committee#55]
See https://gitlab.haskell.org/ghc/ghc/-/issues/20449.

`SrcLoc` is currently defined as follows:
```hs
data SrcLoc = SrcLoc
  { srcLocPackage   :: [Char]
  , srcLocModule    :: [Char]
  , srcLocFile      :: [Char]
  , srcLocStartLine :: Int
  , srcLocStartCol  :: Int
  , srcLocEndLine   :: Int
  , srcLocEndCol    :: Int
  }
```

The non-strict `Int` fields cause a lot of noise in the core when using `HasCallStack` (e.g. through `error`) and compiling with optimizations, as they produce a bunch of top-level `Int` definitions.

I propose making the `Int` fields strict (and adding an `{-# UNPACK #-}` pragma if necessary) so that `SrcLoc` directly holds unboxed `Int#`s. This should make the generated core much cleaner, by eliminating all the top-level `Int` bindings. @AndreasPK pointed out that this shouldn't affect runtime allocations, since the `Int`s are allocated at compile time, but I think cleaning up the generated core is worthwhile regardless. Additionally, for manual uses of `SrcLoc`, this can still avoid unnecessary allocations.

Now the big question is: How does this affect code using `SrcLoc`? This is hard to answer, especially since there seem to be lots of uses (I looked at https://hackage-search.serokell.io/?q=SrcLoc, but note that not all of these are actually uses of `GHC.Stack.Types.SrcLoc`, e.g. the CSPM packages define their own `SrcLoc` and GHC seems to have its own `SrcLoc` too). Most (indirect) uses in practice are probably due to `error`, which shouldn't be affected, since the `SrcLoc`s for that are generated by the compiler at compile time. The semantics shouldn't be affected either (they types stay the same after all, only the point of evaluation changes), but I can imagine there being slowdowns due to relying on the laziness of the fields, to only compute the line/column locations when they're needed, although I believe this is very unlikely. On the other hand, it could also lead to performance improvements, when the evaluation of "simple" thunks isn't unnecessarily delayed.

**Comment by Bodigrim** [comment]
Strongly in favor as well.

**Comment by chessai** [comment]
+1, though I'm unsure if this is in the purview of CLC since it is a GHC
module

**Comment by Bodigrim** [comment]
It's in the purview of CLC as changes to `SrcLoc` may potentially affect performance of a wide class of programs. 

Dear CLC members, let's hold a vote on this. @tomjaguarpaw, @chessai, I'll count your comments above as votes in favor, and I'm in favor as well. @cigsender @emilypi @cgibbard could you please vote?

**Comment by emilypi** [comment]
Absolutely in favor of strictifying these - a `!` should be enough. `Int` is small enough that GHC should unpack those fields for us without the pragma.

**Comment by cgibbard** [comment]
Why would non-constant expressions ever be placed into those fields in the first place? Aren't source locations something which ought to be completely known statically? Strict vs. lazy should not really make any difference here and I'm curious about why it does if it does. Other than that though, +1.

**Comment by emilypi** [comment]
@cgibbard knowing what some Haskell galaxy brains get up to, someone is probably using `SrcLoc` for source spans and wrote a monoid instance for it that would benefit from unboxing.

**Comment by Bodigrim** [comment]
With 5 votes in favor out of 6 possible, the proposal is approved.

**Comment by Bodigrim** [comment]
@konsumlamm please notify once GHC MR is ready.

**Comment by konsumlamm** [comment]
GHC MR: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8122.

**Comment by konsumlamm** [comment]
Ok, so implementing this requires a helper function to deal with the fields possibly being unboxed (without optimizations, there is no unboxing being done, see https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8122#note_426449). Now I wonder where I should put that helper function (it's simply defined as `mkSrcLoc = SrcLoc`). Would it be fine to put it in `GHC.Stack.Types` (which is public, but documented as not supposed to be used directly) or should it go into a new internal module (if so, I'd appreciate help on what needs to be updated when adding a new module)?

**Comment by Bodigrim** [comment]
Do we expect the end users may ever benefit from `mkSrcLoc`? Or is its sole purpose to help GHC internals?

I tend to delegate the decision on `mkScrLoc` to GHC maintainers. Anyway, please attach a detailed comment explaining the purpose of the function, how is it different from `SrcLoc` and when users are expected to invoke it.

**Comment by konsumlamm** [comment]
> Do we expect the end users may ever benefit from `mkSrcLoc`? Or is its sole purpose to help GHC internals?

As far as I can tell, it wouldn't be useful for end users.

> Anyway, please attach a detailed comment explaining the purpose of the function, how is it different from `SrcLoc` and when users are expected to invoke it.

The purpose is that it can be used to construct the compiler generated `SrcLoc`s (used for `HasCallStack`) without having to worry about wether the `SrcLoc` fields are unboxed or not (without optimizations they're boxed, with optimizations they're unboxed). So the compiler generates core for `mkSrcLoc` calls with boxed `Int` arguments, which get simplified to constructor calls with the unboxed ints when optimizations are enabled.

**Comment by Bodigrim** [comment]
In such case it would be cleaner not to expose `mkSrcLoc` from `GHC.Stack.Types`, but not a terribly big deal. Please seek and follow an advice of GHC developers, as this is foremost an internal matter.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @konsumlamm   |
| **Status**             |  not merged  |
| **`base` version**     | Unknown  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8122 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | missing (please, [raise an MR to `base` to update changelog][changelog])  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂  

<hr>

@konsumlamm could you share a status update on the implementation and what are next steps? Also, please do let CLC know if you need any help, so we can coordinate and prioritise approved proposals accordingly!

**Comment by konsumlamm** [comment]
See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8122#note_457431. While the patch should work, it introduces significant performance regressions. Unfortunately, I have no idea what to do about this, so I'd be glad for any help.

**Comment by doyougnu** [comment]
> While the patch should work, it introduces significant performance regressions. Unfortunately, I have no idea what to do about this, so I'd be glad for any help.

I gave this a [go yesterday](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/13381) and saw a performance improvement. I think the improvement was from unboxing the `Int` fields so that instead of consuming 6 words (4 pointers and 4 half-words) we instead consume just the 4-half words. We could reduce this memory footprint in half again and fit this into a single word by using 24 bits for the line locs each and 8 bits for the column locs. Of course that will break if someone creates a  with more than 16 million lines or 256 columns but I digress.

**Comment by tomjaguarpaw** [comment]
> my changes have no been merged

"now" I guess? (I hope not "not"!)
