### ISSUE TITLE
(Alternative f, Foldable t) => t a -> f a

### ISSUE THREAD

**Issue by chris-martin** [haskell/core-libraries-committee#56]
I propose [this](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8069) small addition to `base` because I think it gets at something essential about the relationship between `Foldable` and `Alternative`, makes the `Alternative` class a bit more convenient to work with, and makes it a bit easier to understand.

```haskell
-- | Convert any collection that implements `Foldable` to another collection
-- that implements `Alternative`.
--
-- ==== __Examples__
--
-- This can be used in monadic contexts other than `[]` to emulate the style of
-- nondeterminism associated with programming in the list monad. In this view,
-- `foldA` signifies choosing an element from the `Foldable` collection:
--
-- > pythagoreanTriples :: (Monad m, Alternative m) =>
-- >                       m (Integer, Integer, Integer)
-- > pythagoreanTriples = do
-- >   a <- foldA [1..10]
-- >   b <- foldA [1..10]
-- >   c <- foldA [1..10]
-- >   guard (a^2 + b^2 == c^2)
-- >   pure (a, b, c)

foldA :: (Alternative f, Foldable t) => t a -> f a
foldA = Data.Foldable.foldr (\x xs -> pure x <|> xs) empty
```

This is a utility we can observe in several libraries:

1. In [`Agda`](https://hackage.haskell.org/package/Agda-2.6.2.2/docs/Agda-Utils-Applicative.html)

```haskell
-- | Branch over a 'Foldable' collection of values.
foldA :: (Alternative f, Foldable t) => t a -> f a
foldA = foldMapA pure
```

2. In [`fused-effects`](https://hackage.haskell.org/package/fused-effects-1.1.1.2/docs/Control-Effect-NonDet.html)

```haskell
-- | Nondeterministically choose an element from a 'Foldable' collection.
-- This can be used to emulate the style of nondeterminism associated with
-- programming in the list monad:
--
-- @
--   pythagoreanTriples = do
--     a <- oneOf [1..10]
--     b <- oneOf [1..10]
--     c <- oneOf [1..10]
--     guard (a^2 + b^2 == c^2)
--     pure (a, b, c)
-- @
oneOf :: (Foldable t, Alternative m) => t a -> m a
oneOf = foldMapA pure
```

3. In [`list-transformer`](https://hackage.haskell.org/package/list-transformer-1.0.7/docs/List-Transformer.html)

```haskell
{-| Convert any collection that implements `Foldable` to another collection that
    implements `Alternative`

    For this library, the most common specialized type for `select` will be:

> select :: [a] -> ListT IO a
-}
select :: (Foldable f, Alternative m) => f a -> m a
select = Data.Foldable.foldr cons empty
  where
    cons x xs = pure x <|> xs
```

4. In [`list-t`](https://hackage.haskell.org/package/list-t-1.0.5.1/docs/ListT.html); here it is specialized to `ListT` and uses `MonadPlus` rathen than `Alternative`, but it is still essentially the same as the rest because the `Alternative` and `MonadPlus` instances are the same for the `ListT` type.

```haskell
fromFoldable :: (Monad m, Foldable f) => f a -> ListT m a
fromFoldable = 
  foldr cons mzero
```

The haddock comment in the PR here is pieced together from the documentation from the above examples.

I suggest adopting the name `foldA` mostly because, of the choices above, it conflicts with the least with names in other packages.

**Comment by treeowl** [comment]
The implementation looks good for a left catch-style instance, but I'm less sure about a left distribution one. Another option is

```haskell
foldA = getAlt . foldMap (Alt . pure)
```

I don't know what the trade-offs are.

**Comment by chris-martin** [comment]
> The implementation looks good for a left catch-style instance, but I'm less sure about a left distribution one.

I'm not sure what you mean, could you link/elaborate on what "left catch-style" and "left distribution" mean? If there is a particular class of Alternatives that this isn't good for, maybe the docs could demonstrate.

> Another option is
> 
> ```haskell
> foldA = getAlt . foldMap (Alt . pure)
> ```
> 
> I don't know what the trade-offs are.

Neither do I (do different rewrite rules fire? I certainly see the style you gave appear in `base` more often, but I don't know why) but that certainly looks just as good to me.

**Comment by treeowl** [comment]
The law situation for `Alternative` is ... not great. All that's required of an instance is that it form a monoid under `<|>` with unit `empty`, and do something at least as defined as the defaults for `some` and `many`. Nothing relates those to `<*>`, `liftA2`, or `pure`.

For `MonadPlus`, the situation is only ever so slightly better. It additionally imposes a left zero law:

```haskell
empty >>= f = empty
```

The Haddocks also claim that it requires a right zero law:

```haskell
m *> empty = empty
```

but this seems more than likely to be a mistake—it's violated by the instances for `IO` as well as many if not most parsers.

The [Haskell wiki page for `MonadPlus`](https://wiki.haskell.org/MonadPlus) omits the right zero law, and points out that there are two other laws that have been proposed. I believe that most instances obey one of these:

```haskell
-- Left distribution
(m <|> n) >>= f = (m >>= f) <|> (n >>= f)

-- Left catch
pure a <|> m = pure a
```

These laws contradict each other for any instance with a nontrivial `<|>`:

```haskell
f a
= -- monad identity law
pure a >>= f
= -- left catch
(pure a <|> m) >>= f
= -- left distribution
(pure a >>= f) <|> (m >>= f)
= -- monad identity
f a <|> (m >>= f)
```

Letting `f = either id pure`, `a = Left u`, and `m = Right <$> v`, we get

```haskell
forall u v. u = u <|> v
```

Your implementation will always diverge if the container goes off infinitely to the left. That's certainly fine for left catch instances, which (unless trivial) can't do anything till they reach the leftmost operand. Is that also true for left distribution instances? I don't know.

**Comment by Gabriel439** [comment]
@treeowl: It seems to me that a reasonable compromise is to add the version that @chris-martin gave to `Control.Applicative` and add the version that you gave to `Data.Functor.Alt`, that way the user can select which behavior they intend to use by importing the module that has the corresponding class

**Comment by Gabriel439** [comment]
There's also prior art for each module providing its own version of `foldA`.  For example, there is a `Data.Functor.Alt.optional` which parallels `Control.Applicative.optional`

**Comment by Ericson2314** [comment]
> The law situation for `Alternative` is ... not great.

We are relating one infamously lawless class to another!

**Comment by tomjaguarpaw** [comment]
> >  The law situation for Alternative is ... not great.
>
> We are relating one infamously lawless class to another!

Yeah, for me this already puts the proposal deep in a hole that I suspect it will have difficulty struggling out of, in my opinion.

**Comment by Gabriel439** [comment]
Why would that be problematic?  Is the policy of the core libraries committee to not add new `Foldable` or `Alternative` utilities to `base`?

**Comment by tomjaguarpaw** [comment]
> Why would that be problematic?

Well, given the problems specifying `Alternative` and (especially) `Foldable` I don't see this as a particularly well-motivated piece of functionality.

> Is it the policy of the core libraries committee to not add new Foldable or Alternative utilities to base?

I'm just expressing a personal opinion, not a CLC policy.

**Comment by Gabriel439** [comment]
What needs to be specified, though?  How is this any different than, say, `asum`, which is already in `base`?

**Comment by treeowl** [comment]
> @treeowl: It seems to me that a reasonable compromise is to add the version that @chris-martin gave to `Control.Applicative` and add the version that you gave to `Data.Functor.Alt`, that way the user can select which behavior they intend to use by importing the module that has the corresponding class

I don't have anything against offering multiple versions of a function, but I don't really like remembering which one is left biased by process of elimination.

**Comment by Gabriel439** [comment]
Just to re-emphasize the point about `asum`, you can define the behavior of `foldA` in terms of `asum` like this:

```
foldA = asum . fmap pure
```

… so if you're arguing that the semantics of `foldA` are unclear then why do those objections not apply to `asum`?

**Comment by tomjaguarpaw** [comment]
It's not quite that, because that picks up a `Functor t` constraint. Anyway, my objections do apply to `asum`, and anything else that uses `Foldable`!

**Comment by tomjaguarpaw** [comment]
Clickable links and source for the `optional`s that Gabriella mentioned earlier.

[`Control.Applicative`](https://hackage.haskell.org/package/base-4.16.1.0/docs/Control-Applicative.html#v:optional)

```haskell
optional :: Alternative f => f a -> f (Maybe a)
optional v = Just <$> v <|> pure Nothing
```

[`Data.Functor.Alt`](https://hackage.haskell.org/package/semigroupoids-5.3.7/docs/src/Data.Functor.Alt.html#optional)

```haskell
optional :: (Alt f, Applicative f) => f a -> f (Maybe a)
optional v = Just <$> v <!> pure Nothing
```

**Comment by chris-martin** [comment]
If this proposal is being voted down because the committee doesn't like `Alternative` at all, then instead I propose to deprecate the class and make it clear in the documentation that there is a policy to add no further support for it, so folks like me can avoid wasting our time in the future.

**Comment by treeowl** [comment]
@tomjaguarpaw, @Gabriel439, it looks like there's been some misunderstanding. I was referring to `Data.Monoid.Alt`.

**Comment by tomjaguarpaw** [comment]
> If this proposal is being voted down because the committee doesn't like `Alternative` at all

Rest assured this is not the case.  I am but one CLC member with one opinion.  No other CLC member has yet spoken here.

I'm sorry if you got that impression from what I wrote.  If you can point out what it was that I said that gave you that impression then I will do my best to avoid doing so in the future.

**Comment by chris-martin** [comment]
> Rest assured this is not the case. I am but one CLC member with one opinion. No other CLC member has yet spoken here.
> 
> I'm sorry if you got that impression from what I wrote. If you can point out what it was that I said that gave you that impression then I will do my best to avoid doing so in the future.

It wasn't anything you said, it's that members aren't tagged here, so I never have any idea who represents the committee and who doesn't.

**Comment by tomjaguarpaw** [comment]
The list of committee members is available at https://github.com/haskell/core-libraries-committee#structure

**Comment by Jashweii** [comment]
What about a direct analogue of foldMap instead, abstracting over pure?
```Haskell
??? :: (Alternative f, Foldable t) => (a -> f b) -> t a -> f b
```
This doesn't use applicative, it is essentially coerce (foldMap @_ @(Alt _ _)).


On the law topic I think people have mentioned relating alternative to semirings before, in the sense of applicative = (*)/1, and alternative (+)/0. This is probably because of the cardinality of the type parameters (modulo fmap) in the following alternate presentation:
```Haskell
class Functor f => Applicative f where
  (<*>) :: f a -> f b -> f (a, b)
  one :: f ()
class Applicative f => Alternative f where
  (<+>) :: f a -> f b -> f (Either a b) -- not 100% on this, it is probably possible to have a current law abiding Alternative for which this isn't equivalent
  zero :: f Void
```
MonadPlus suddenly gaining left zero makes sense because empty :: forall a . f a, suppose you have (>>=) :: forall a b . f a -> (a -> f b) -> f b, how do you call f in empty >>= f if not returning some (forall b . f b) value like empty

**Comment by chris-martin** [comment]
> What about a direct analogue of foldMap instead, abstracting over pure?
> 
> ```haskell
> ??? :: (Alternative f, Foldable t) => (a -> f b) -> t a -> f b
> ```

[`Agda.Utils.Applicative`](https://hackage.haskell.org/package/Agda-2.6.2.2/docs/Agda-Utils-Applicative.html) has that, and a few others. It might make more sense to adopt the entire suite than to cherry-pick the one of them that I've proposed.

 > On the law topic I think people have mentioned relating alternative to semirings before, in the sense of applicative = (*)/1, and alternative (+)/0.

I've explored this a bit. I think the relevant term is *quasi-ring* because a semiring requires a commutative addition operation. A lot of instances I'd consider to be okay Alternatives aren't quite quasi-rings. For example:

- For `IO`, `empty` is not an annihilator for Applicative operations: `putStrLn "Fire!" *> empty` is not the same action as `empty`, because the former prints before throwing, and the latter only throws.
- A similar problem arises for parsers; they only form a quasi-ring if you pretend that all parsers that always fail are equivalent, ignoring whatever error message they may fail with.

As far as I can tell the only perfect quasi-ring alternatives are `STM` and `Maybe`.

It can roughly be said that `IO` and parsers are quasi-rings only if you modify the definition of a quasi-ring to say:

- It must have a *set* of annihilators
- `empty` must be *one of* the annihilators
- If `a` is an annihilator, then `a + b` and `b + a` must both be annihilators as well.

**Comment by treeowl** [comment]
@chris-martin, I believe the situation for parsers is rather worse than that. As I understand it, some (including, at least, Parsec) can fail while still consuming input, so `(p *> empty) <|> q` may parse a different language than `empty <|> q = q`.

**Comment by treeowl** [comment]
Then again, those parsers probably don't obey left distribution or left catch either.

**Comment by Gabriel439** [comment]
For the purpose of this discussion, I think we should ignore non-law-abiding `Alternative` instances like `IO`.  Specifically, I mean we should ignore instances that don't even obey the associativity/identity laws that everybody agrees with.  For example, `IO` doesn't obey the right identity law (`io <|> empty /= io`).

I think it's up for debate what additional laws `Alternative` should have, but we should at least all agree that they should obey the associativity/identity laws.

**Comment by konsumlamm** [comment]
Whatever you decide on, I'd suggest not using an `A` suffix for functions operating on `Alternative`, as that is usually used for `Applicative` functions (and at least I would find that confusing).

**Comment by treeowl** [comment]
@Gabriel439, `IO` obeys that law up to choice of exception, which is a pretty useful property. I think parsers' failing to obey left distribution is a much more serious problem for intuition.

**Comment by Gabriel439** [comment]
@treeowl: Just to clarify: I'm not saying that we should remove the `Alternative` instance for `IO` (I personally don't like it, but I think that's irrelevant to this discussion).  I only mean that we should not refer to its behavior when discussing how to reason about utilities that abstract over `Alternative`.

In other words, if you instantiate a generic `Alternative` utility to a non-law-abiding instance then you accept any risk of it misbehaving in unexpected way.

**Comment by Gabriel439** [comment]
I also think whether or not distributivity/zero/commutativity laws for `Alternative` should hold is irrelevant to this discussion, because the proposed utility does not use actually depend on distributivity or commutativity.  The only laws that are relevant to reasoning about the proposed utility are the associativity/identity laws

**Comment by mcallisterjp** [comment]
> I've explored this a bit. I think the relevant term is _quasi-ring_ because a semiring requires a commutative addition operation.
The terminology is a mess here, isn't it? [_Near-semiring_](https://en.wikipedia.org/wiki/Near-semiring) appears to be the standard term for the structure where a semigroup [right-]distributes over a monoid.

Perhaps for consistency they might be called _nearsemipseudorings_ unless they have a multiplicative identity?

Or extend the idea of _rig_ and _rng_ and drop another letter. Maybe the eight possibilities should just be `ri?n?g?`.

**Comment by chris-martin** [comment]
Some concrete real-world Alternatives and what this function does with them:

- For list-like Alternatives, it is a straightforward type conversion
  - `[a] -> ListT IO a`
- For IO, parsers, and maybe, it is essentially a "head" function.
  - `[a] -> IO a` - produces the first element in the list or a failure.
  - `[a] -> Maybe a` - produces `Just` the head, or `Nothing`

Are there any specific examples that would be problematic?

**Comment by Gabriel439** [comment]
Also, if you specialize the `Foldable` input to `[]`, this function obeys the following functor laws:

```haskell
foldA empty = empty

foldA (xs <|> ys) = foldA xs <|> foldA ys
```

**Comment by Gabriel439** [comment]
@chris-martin: Note that for parsers it is not a "head" function.  I believe that for parsers it would non-deterministically select from the elements in the list.

For example:

```
do  c <- foldA "ABC"
    char c
```

… would be a parser that matches either the character `'A'`, `'B'`, or `'C'`.  This is why I like to call this function `select` because it essentially picks one element (non-deterministically, in the case of lists or parsers, or deterministically, in the case of `IO` or `Maybe`)

**Comment by tomjaguarpaw** [comment]
```haskell
foldA "ABC" = pure "A" <|> pure "B" <|> pure "C"
```

and for a typical parser that will produce the value `"A"`, consuming no input.

**Comment by Gabriel439** [comment]
Yeah, I should have clarified that I meant a backtracking-by-default parser

**Comment by konsumlamm** [comment]
Repeating my earlier comment, I'd recommend not calling this `foldA` (if this proposal gets accepted in some form), as that implies that it has something to do with `Applicative` (at least to me, see `sequenceA`, `replicateA`, etc.). I think a name like `foldAlt` would be better.

**Comment by chris-martin** [comment]
Good point. I think `foldAlt` sounds quite nice.

**Comment by treeowl** [comment]
It would be nice to know how the two implementations compare for different functors and foldables.

**Comment by Bodigrim** [comment]
@chris-martin once you are satisfied with bikeshedding, please put up a final proposal.

**Comment by Bodigrim** [comment]
@chris-martin just a gentle reminder that this awaits for your action.

**Comment by chris-martin** [comment]
Sorry for the delay, getting back to this. Summary of the feedback so far:

### Naming

https://github.com/haskell/core-libraries-committee/issues/56#issuecomment-1112635386 The `A` suffix conventionally means "applicative", so it shouldn't also be used to stand for "alternative". `foldAlt` was suggested.

https://github.com/haskell/core-libraries-committee/issues/56#issuecomment-1113977378 Another proposed name: `select`

### Implementation

https://github.com/haskell/core-libraries-committee/issues/56#issuecomment-1110197440 Two equivalent implementations have been proposed; no comments yet as to which might be preferable.

```haskell
import Data.Foldable (foldr)
import Data.Monoid (Alt (..))

foldA = foldr (\x xs -> pure x <|> xs) empty

foldA = getAlt . foldMap (Alt . pure)
```

https://github.com/haskell/core-libraries-committee/issues/56#issuecomment-1112504453 Consider additional functions, see [`Agda.Utils.Applicative`](https://hackage.haskell.org/package/Agda-2.6.2.2/docs/Agda-Utils-Applicative.html) for more inspiration, e.g.:

```haskell
foldMapA :: (Alternative f, Foldable t) => (a -> f b) -> t a -> f b
```

### Documentation

https://github.com/haskell/core-libraries-committee/issues/56#issuecomment-1110286990 Since the `Alternative` class does not have laws relating it to `Applicative`, the function should include some documentation explaining what it assumes about this relationship. In particular it seems there should be something written about the conditions that are required for this function to terminate. I need to give this more thought -- and I might need some help?

https://github.com/haskell/core-libraries-committee/issues/56#issuecomment-1113666014 Mention that one of the uses of the proposed function is as a safe `head` function.

```haskell
foldA "abc" = Just 'a'
foldA "" = Nothing
```

https://github.com/haskell/core-libraries-committee/issues/56#issuecomment-1113668703 There are some nice properties can be stated:

* `foldA (empty @[]) = empty`
* `foldA (toList xs <|> toList ys) = foldA (toList xs) <|> foldA (toList ys)`

**Comment by chris-martin** [comment]
I am coming around to @Gabriella439's naming, but I think it requires some work in the documentation to explain the metaphor. Since nobody has yet made any comment on the `select` name, I'd like to ask -- what do y'all think, does this seem like something you can wrap your head around?

```haskell
{- | Selection from a list (or other 'Foldable') of possibilities

What /selection/ means depends on the meaning on the 'Alternative' instance.
For example, 'Maybe', which can hold at most one item, selects the first item
available.

> >>> select [1, 2, 3] :: Maybe Integer
> Just 1

> >>> select [] :: Maybe Integer
> Nothing

The list type '[]' can hold any number of items, so it is able to
select the entire input. Therefore, `select @[] @[] = id`.
-}
select :: (Alternative f, Foldable t) => t a -> f a
```

**Comment by mixphix** [comment]
Can someone describe a usecase for this that is more complex than simply `[]` and `Maybe`? The parser examples do not convince me. I struggle to see what niche this function fills, and how frequently it would be used that `foldr (<|>) empty` would not suffice.

**Comment by Gabriella439** [comment]
@mixphix: `foldr (<|>) empty` already exists in `base` as the `asum` function, but what is being proposed here is a different function, which is `foldr (\x xs -> pure x <|> xs) empty`

I can think of at least three examples of this function from just my own packages, which are special cases of the more general type being proposed here:

* My `turtle` package has this function (calling it `select`): https://hackage.haskell.org/package/turtle-1.6.1/docs/Turtle-Shell.html#v:select

* My `HasCal` model checker has this function (calling it `with`): https://github.com/Gabriella439/HasCal/blob/e59279fd0a733ef94d41b26f36ff16d42af4bba4/src/HasCal/Coroutine.hs#L546-L550

* My `list-transformer` package has this function (calling it `select`): https://hackage.haskell.org/package/list-transformer-1.0.8/docs/List-Transformer.html#v:select

You'll notice a common pattern for those well-behaved examples (and other examples in the wild), which is that they typically arise whenever you're using some sort of "`ListT` done right".  For example, the `Shell` type from `turtle`, the `Process` type from `HasCal` and (obviously) the `ListT` type from `list-transformer` are all three examples of `ListT`-like types.

I think the mistake people are making here are thinking about this utility and how it applies to parsers, when I think it's much more useful in the context of `ListT`-like `Monad`s.

**Comment by chris-martin** [comment]
Perhaps the simplest synopsis this function could be: It is a lifting operation from a plain list to any type with a list-like `Alternative`.

**Comment by mixphix** [comment]
I can now imagine a case where the `Alternative` is a random-choice monad, one where each `(<|>)` takes its left or right argument at random. Here `select` would, well, select a random element of the list.
- - -
That being said, I agree with @Ericson2314 on this point: https://github.com/haskell/core-libraries-committee/issues/56#issuecomment-1110399446 I think that `Foldable` is *okay* and that `Alternative` is *okay*, but that intertwining them as they currently exist may be a poor choice. I would prefer to see a finer functor hierarchy (like in `semigroupoids`) and to use `Alt` due to the irrelevant `Applicative` constraint being incurred at present. +0

**Comment by sjoerdvisscher** [comment]
> due to the irrelevant `Applicative` constraint being incurred at present.

It is not irrelevant since `pure` is used.

**Comment by ncfavier** [comment]
-1 for specialising. Pretty sure I had to use this on a `Map` at some point.

**Comment by Bodigrim** [comment]
@chris-martin could you please update the top post with any details / motivation / properties / implementation plan, so that we can hold a vote on it?

**Comment by Bodigrim** [comment]
@chris-martin just a gentle reminder: there was a subsequent discussion about naming, module and exact implementation. We need your final decision on which specific proposal you would like us to vote.

**Comment by Bodigrim** [comment]
Closing as abandoned, feel free to reopen when the proposal is ready.
