### ISSUE TITLE
Pure Haskell implementation of GHC.Unicode

### ISSUE THREAD

**Issue by wismill** [haskell/core-libraries-committee#59]
Following this [discussion](https://gitlab.haskell.org/ghc/ghc/-/issues/21375), the goal of this proposal is to **refactor `GHC.Unicode` from a C implementation to a pure Haskell implementation**.

## Motivation

- [Reportedly up to 4× faster](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8072#note_427599)
- Simplified maintenance (no FFI).
- More portable code.

## Implementation

I opened a [merge request](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8072) with a working implementation.

This work is based on the package [`unicode-data`](https://hackage.haskell.org/package/unicode-data), developed by @Bodigrim, @harendra-kumar, @adithyaov, me and others.

The re-licensing is discussed in [this issue](https://github.com/composewell/unicode-data/issues/62).

## Relevant links
- Package `unicode-data`: [Github](https://github.com/composewell/unicode-data), [Hackage](https://hackage.haskell.org/package/unicode-data) and [Discourse](https://discourse.haskell.org/t/ann-unicode-data-0-3-0-apis-to-efficiently-access-the-unicode-character-database).
- [GHC ticket](https://gitlab.haskell.org/ghc/ghc/-/issues/21375)
- [GHC MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8072)

## Further discussion

Other interesting functions could be imported from `unicode-data`. This proposal only use those already in `base`, in order to keep the interface unchanged.

## Aknowledgement

I would like to thank @Bodigrim, @harendra-kumar and @adithyaov for making `unicode-data` and @nomeata for his guidance.

**Comment by tomjaguarpaw** [comment]
This sounds absolutely tremendous!

**Comment by nomeata** [comment]
Thanks for pushing this forward! Highly appreciated

**Comment by harendra-kumar** [comment]
Nice to see one significant dependency on C libraries removed. I appreciate the contributions of @wismill to the `unicode-data` package, making it a drop-in replacement for `Data.Char` and now pushing this into GHC, actually replacing Data.Char! And thanks to @nomeata for taking the initiative and helping out on getting this done.

**Comment by Bodigrim** [comment]
I conducted a technical review of https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8072 and it looks good to me. 

Dear CLC members, let's vote on the proposal to speed up `Data.Char` 4 times :-P 
@tomjaguarpaw @cigsender @cgibbard @emilypi @chessai 

+1 from me.

**Comment by chessai** [comment]
+1

**Comment by tomjaguarpaw** [comment]
+1

**Comment by cigsender** [comment]
+1

**Comment by cgibbard** [comment]
+1

**Comment by Bodigrim** [comment]
With 5 votes in favor out of 6 possible, the proposal is now approved by CLC. Thanks @wismill.

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @wismill   |
| **Status**             |  merged |
| **`base` version**     | Unknown  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8072 |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | missing (please, [raise an MR to `base` to update changelog][changelog])  |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/ghc-9.6/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂  

<hr>

@wismill I find it hard to determine the exact version of `base` that implemented this proposal. Could you open an MR to `base` with the CHANGELOG entry for the corresponding `base` version?

**Comment by chshersh** [comment]
@wismill Thanks for confirming the `base` version!

In my understanding, if a change requires a CLC proposal, it should go to CHANGELOG, and I don't view CHANGELOG as API-only list of changes. But views of other CLC members may differ 😌

**Comment by parsonsmatt** [comment]
I would personally prefer to see nearly all changes in the changelog - subtle implementation differences can be hard to track down, and a changelog makes that much easier

**Comment by chessai** [comment]
> I would personally prefer to see nearly all changes in the changelog - subtle implementation differences can be hard to track down, and a changelog makes that much easier

I agree, and that base should be held to a very strict standard of this

**Comment by wismill** [comment]
[PR sent](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10178).
