### ISSUE TITLE
Nonsense mtimesDefault documentation

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#6]
`Data.Semigroup` contains the following:

```haskell
-- | Repeat a value @n@ times.
--
-- > mtimesDefault n a = a <> a <> ... <> a  -- using <> (n-1) times
--
-- Implemented using 'stimes' and 'mempty'.
--
-- This is a suitable definition for an 'mtimes' member of 'Monoid'.
mtimesDefault :: (Integral b, Monoid a) => b -> a -> a
```

There's just one problem: there's no `mtimes` method in `Monoid`. What's this about?

**Comment by gwils** [comment]
I think `mtimes` might have been a `Monoid` member way back in the day, made redundant by `stimes` in `Semigroup`. It would be worth tracking down that history, and perhaps updating the haddock here to explain it.
As Bodigrim said, I think this falls out of the (new) CLC scope.

**Comment by Bodigrim** [comment]
@Kleidukos could you possibly please take a look at this? I think just removing the line about `mtimes` would suffice. 

Closing as out of scope for CLC.

**Comment by treeowl** [comment]
I think it needs more documentation for when you'd actually want it. It's very specifically for cases like

```haskell
data T a = ...

-- class Constraint1 a => Constraint2 a

instance Constraint1 a => Semigroup (T a)
instance Constraint2 a => Monoid (T a)
```

So `stimes @(T a)` is *necessarily* partial, but `mtimes @(T a)` is not.

**Comment by Kleidukos** [comment]
@treeowl I will be happy to include what you want in `mtimesDefault` and `stimes` documentations. Open a ticket and assign it to me. :)
