### ISSUE TITLE
Add operator for building association lists

### ISSUE THREAD

**Issue by Gabriella439** [haskell/core-libraries-committee#60]
In the course of working on my [HasCal](https://github.com/Gabriella439/HasCal) project I stumbled upon a utility that I thought would be a useful addition to `base`.  Basically, given an input collection and an output collection it generates all possible mappings from inputs to outputs:

```haskell
(-->)
    :: (Traversable domain, Applicative range)
    => domain key -> range value -> range (domain (key, value)) 
keys --> values = traverse process keys
  where
    process key = fmap ((,) key) values
```

Here are some examples of how it works on lists:

```haskell
>>> [1,2] --> [3,4]
[[(1,3),(2,3)],[(1,3),(2,4)],[(1,4),(2,3)],[(1,4),(2,4)]]
>>> [] --> [3,4]
[[]]
>>> [1,2] --> []
[]
>>> [] --> []
[[]]
```

… but it also works on `Maybe`s, `NonEmpty` lists, `Identity`, and other collections, too.  To keep things short, I'll only include extra examples for `Maybe`:

```haskell
>>> [1,2] --> Just 3
Just [(1,3),(2,3)]
>>> [1,2] --> Nothing
Nothing
>>> Just 1 --> [3,4]
[Just (1,3),Just (1,4)]
>>> Nothing --> [3,4]
[Nothing]
>>> Just 1 --> Just 2
Just (Just (1,2))
>>> Nothing --> Just 3
Just Nothing
>>> Just 1 --> Nothing
Nothing
```

The reason the operator uses `Traversable` / `Applicative` for the domain and range, respectively, is because it improves the type safety.  For example, if you supply a `NonEmpty` range then the set of results is guaranteed to be `NonEmpty`.

I'm open to different names; the only reason I chose `-->` is to resemble the TLA+ function set operator (this is the Haskell analog of that operator).  The intuition here is that if you represent a type at the term level as a set of inhabitants of that type then `a --> b` is the set of all relations mapping the "type" `a` to the "type" `b` (which TLA+ calls a function set).

I'm also not sure what module this would belong in.  Maybe `Data.Traversable`?

**Comment by konsumlamm** [comment]
I'm not really sure where this would be useful, can you give an example? Most of the time a `Map` should be preferred over an association list, so I don't know if it's a good idea to add more operations for association lists to `base` (afaik the only such function is `Data.List.lookup` currently).

About the name, I don't think making it an operator is a good idea, since this isn't a very common operation, to my knowledge. I assume `-->` will be confusing for anyone who doesn't know TLA+, at least to me it means absolutely nothing (it suggests that it does some kind of mapping, but there are a lot of ways to do "a mapping"). Thus I think a normal name that describes what it does would be better.

**Comment by Gabriella439** [comment]
The reason it's not written to produce a `Map` is because it does not necessarily always produce an association list.  Consider the case where the `domain` is `Identity`, where the type specializes to:

```haskell
(-->)
    :: Applicative range
    => Identity key -> range value -> range (Identity (key, value)) 
```

That means that if you can guarantee that the domain is non empty, then each "association list" is actually a single key-value pair.  If you were to produce a `Map` then you would lose the type-level guarantee that each result would have exactly one pair.

```haskell
>>> Identity 1 --> [3,4]
[Identity (1,3),Identity (1,4)]
```

**Comment by Ericson2314** [comment]
I don't think we should do more "small clever utility functions" in base. The problem right now is `base` plays 3 rolls:
 - How we choose the default prelude
 - How we choose what all libraries depend on
 - How we wrap compiler-specific stuff

I have already written lots about the last two in trying to decouple base and GHC, but the first two should be decoupled too. I think this stuff belongs in some sort of alternative prelude first. To be fair, there ought to be a way to do custom "distributions" of GHC such that the custom prelude is the default. Only after that should it be discussed going in base.

(Really, I wish vanilla GHC didn't ship with a prelude at all. I don't really believe libraries should use preludes, just executables and "programming in the small". A stringent position indeed, but it removes a source of bikeshedding and encourages more modularity.)

**Comment by andreasabel** [comment]
I think additions to `base` should in general be harvested from utility libraries or utility modules that are already out there and have thus _proven_ to be useful in many contexts.  There are lots of utility modules out there which could be systematically searched for utility functions that have passed the test of time.  If a pattern is universally useful, it is rediscovered over and over again.  So, a suggestion of adding something to base should come with several links to its uses in the wild in different contexts...

**Comment by Gabriella439** [comment]
@andreasabel: Okay, then why hasn't https://github.com/haskell/core-libraries-committee/issues/56 been merged, yet?

**Comment by Bodigrim** [comment]
> @andreasabel: Okay, then why hasn't #56 been accepted, yet?

#56 awaits for https://github.com/haskell/core-libraries-committee/issues/56#issuecomment-1114356299

**Comment by andreasabel** [comment]
Sorry, I have not participated in the discussion of #56.  But, looking at it, it seems well-motivated, quoting 4 real-world incarnations in the OP.

**Comment by Bodigrim** [comment]
@Gabriella439 could you please extend the proposal, listing applications of `-->`? What are drawbacks of implementing `-->` in a standalone package?

**Comment by Gabriella439** [comment]
@Bodigrim: The original proposal already lists applications of `-->`

The downside of implementing it in a standalone package is that it's not worth importing an entire package just to obtain one function

**Comment by tomjaguarpaw** [comment]
> The downside of implementing it in a standalone package is that it's not worth importing an entire package just to obtain one function

Could you elaborate on what exactly are the costs of importing a package?

**Comment by Gabriella439** [comment]
@tomjaguarpaw: https://www.fosskers.ca/en/blog/wide-haskell

**Comment by tomjaguarpaw** [comment]
The relevance of that article to "it's not worth importing an entire package just to obtain one function" is not immediately clear to me.

**Comment by konsumlamm** [comment]
> The original proposal already lists applications of `-->`

I don't see any examples that show why we should want this in `base`. It's some examples that show what the function does, but not why it would be useful (at least to me).

**Comment by Bodigrim** [comment]
@Gabriella439 are you satisfied with the discussion? Shall I trigger a vote?

**Comment by Gabriella439** [comment]
Yeah, I'm ready for a vote

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal. @chessai @cigsender @emilypi @cgibbard 

----

-1 from me. The proposal covers semantics of the function (beautiful indeed), but I'm still at loss about practical applications. Expanding `base` puts a cost on every Haskell user and I do not feel it justified in this case.

**Comment by Bodigrim** [comment]
@chessai @cgibbard @emilypi @mixphix ping, this awaits your vote.

**Comment by cgibbard** [comment]
-1, just slightly too rare a meaning to want to steal such a good operator symbol.

**Comment by chessai** [comment]
-1 for reasons stated by others

**Comment by Gabriella439** [comment]
Alright, closing since that's enough votes against
