### ISSUE TITLE
Semigroup / Monoid instances for {Accum,EitherT,Identity,MaybeT,Reader,RWS,State,Writer}T?

### ISSUE THREAD

**Issue by Gabriella439** [haskell/core-libraries-committee#62]
I would like to contribute `Semigroup` / `Monoid` instances of the form:

```haskell
instance Semigroup a => Semigroup (F a) where
    (<>) = liftA2 (<>)

instance Monoid a => Monoid (F a) where
    mempty = pure mempty
```

… where `F` is each monad transformer.  Or equivalently:

```haskell
deriving (Semigroup, Monoid) via (Ap F a)
```

I motivate why these instances are useful and why the existence of `Ap` alone does not suffice in this post:

https://www.haskellforall.com/2022/03/applicatives-should-usually-implement.html

An alternative variation on this proposal that I'd also be fine with would be to omit the `Semigroup` / `Monoid` instance for monad transformers that have a non-lifted `Alternative` instance (such as `MaybeT`)

**Comment by tomjaguarpaw** [comment]
@Bodigrim can correct me if I am wrong, but I don't believe CLC has authority over `transformers`, so I believe this issue belongs on https://hub.darcs.net/ross/transformers/issues.

**Comment by Bodigrim** [comment]
Indeed, `transformers` are out of scope.

**Comment by Gabriella439** [comment]
Whoops, my mistake!  Closing…

**Comment by Gabriella439** [comment]
The matching issue on the `transformers` repository is: https://hub.darcs.net/ross/transformers/issue/86
