### ISSUE TITLE
Upstream Only type into base?

### ISSUE THREAD

**Issue by Gabriella439** [haskell/core-libraries-committee#63]
The context for this is the discussion on https://github.com/haskell-hvr/Only/issues/3

Specifically, there is already a `Solo` type in `base` that is essentially the same as `Only`, except that `Solo` uses `data` and `Only` uses `newtype`.  Given that the `Only` package is abandoned and `base` has approved the `Solo` type, it seems like a good time to decide whether or not to upstream `Only` into `base`

The `Only` type (or equivalent vendored types) is a widely used type (which is why the `Only` package was created in the first place), so the prior art for this type already exists

I don't feel too strongly about this proposal since the isomorphic `Identity` type already exists in `base`, too.  I would be equally fine with a verdict of "The `Identity` type is the blessed 1-tuple `newtype` for `base`"

**Comment by tomjaguarpaw** [comment]
If `Only` is unmaintained it seems like the first step should be to initiate a package takeover of `Only`. "A package has become abandoned" doesn't seem like a good rationale to vendor it into `base`.

**Comment by sjakobi** [comment]
Note that the `Only` package has not reached very wide adoption: https://packdeps.haskellers.com/reverse/Only

I think users of `Only` should consider switching to `Identity` or `Solo`.

**Comment by konsumlamm** [comment]
It seems you want `Only` as a 1-tuple that is a `newtype`? The reason `Solo` uses `data` is for consistency, since the other tuples also have an extra indirection for the elements.

As the others have mentioned, why should we add `Only` if we already have `Identity`?

**Comment by cigsender** [comment]
Row, row, row, your bloat, gently up the stream…

**Comment by Bodigrim** [comment]
@Gabriella439 The `Identity` type is the blessed 1-tuple `newtype` for `base`.

**Comment by Gabriella439** [comment]
@Bodigrim: Alright, then it seems like most people agree with using `Identity` in lieu of `Only` so I'll go ahead and close this
