### ISSUE TITLE
Friendlier non-GHC module for everything in the prelude

### ISSUE THREAD

**Issue by Ericson2314** [haskell/core-libraries-committee#64]
### Num

I was surprised that `GHC.Num` seems to be the only home for this report-specified class. In https://github.com/obsidiansystems/commutative-semigroups/pull/2 we are thinking we **might** need to create a `CommutativeProduct` subclass of `Num`. I was about to do that and put it in its own module, but I didn't know what to call that module! Surely I don't want to squat on `GHC` with something like `GHC.Num.CommutativeProduct`!

(To be clear, I am *not* suggesting the CLC worry about this `CommutativeProduct` itself. The base number classes are somewhat fraught, law-only classes are very fraught. Not trying to stir the pot with any of that! Just need a name for my module, and one that ideally would be based off a friendly module for `Num`.)

### Other things

https://gitlab.haskell.org/ghc/ghc/-/issues/3870#note_211961 @sjakobi made a nice issue here. Let's fix them all!

**Comment by Ericson2314** [comment]
(More broadly, I think we should have a principal that anyone using `-XNoImplicitPrelude` should be able to get everything in the `base`'s `Prelude` without getting it from `Prelude` or ` `GHC.*` module. In other words `Prelude` should only reexport things from "nice" modules.)

**Comment by sjakobi** [comment]
Here is a suggestion how to distribute the things that are currently available only from `Prelude` and `GHC.*` modules. Modules that would need to be created are marked `NEW`.

`(^^)` and `realToFrac` are exported from two new places each because they are associated with both `Fractional` and `Integral` (`(^^)`), or with `Real` and `Frac` (`realToFrac`).

```
NEW Data.Bounded
================
GHC.Enum.Bounded{GHC.Enum.maxBound GHC.Enum.minBound}

NEW Data.Enum
=============
GHC.Enum.Enum{GHC.Enum.enumFrom GHC.Enum.enumFromThen GHC.Enum.enumFromThenTo GHC.Enum.enumFromTo GHC.Enum.fromEnum GHC.Enum.pred GHC.Enum.succ GHC.Enum.toEnum}

NEW Data.Error
==============
GHC.Err.error
GHC.Err.errorWithoutStackTrace
GHC.Err.undefined

Data.Function
=============
GHC.Base.$!
GHC.Base.asTypeOf
GHC.Base.until

NEW Data.Seq
============
GHC.Prim.seq

NEW Numeric.Float
=================
GHC.Types.Float

NEW Numeric.Double
==================
GHC.Types.Double

NEW Numeric.Fractional
======================
GHC.Real.Fractional{GHC.Real./ GHC.Real.fromRational GHC.Real.recip}
GHC.Real.^^ :: (Fractional a, Integral b) => a -> b -> a
GHC.Real.realToFrac

NEW Numeric.Integer
===================
GHC.Integer.Type.Integer

NEW Numeric.Integral
====================
GHC.Real.Integral{GHC.Real.div GHC.Real.divMod GHC.Real.mod GHC.Real.quot GHC.Real.quotRem GHC.Real.rem GHC.Real.toInteger}
GHC.Real.even
GHC.Real.gcd
GHC.Real.lcm
GHC.Real.odd
GHC.Real.^ :: (Num a, Integral b) => a -> b -> a
GHC.Real.^^ :: (Fractional a, Integral b) => a -> b -> a
GHC.Real.fromIntegral

NEW Numeric.Num
===============
GHC.Num.Num{GHC.Num.* GHC.Num.+ GHC.Num.- GHC.Num.abs GHC.Num.fromInteger GHC.Num.negate GHC.Num.signum}
GHC.Num.subtract

NEW Numeric.Real
================
GHC.Real.Real{GHC.Real.toRational}
GHC.Real.realToFrac

NEW Numeric.RealFloat
=====================
GHC.Float.RealFloat{GHC.Float.atan2 GHC.Float.decodeFloat GHC.Float.encodeFloat GHC.Float.exponent GHC.Float.floatDigits GHC.Float.floatRadix GHC.Float.floatRange GHC.Float.isDenormalized GHC.Float.isIEEE GHC.Float.isInfinite GHC.Float.isNaN GHC.Float.isNegativeZero GHC.Float.scaleFloat GHC.Float.significand}

NEW Numeric.RealFrac
====================
GHC.Real.RealFrac{GHC.Real.ceiling GHC.Real.floor GHC.Real.properFraction GHC.Real.round GHC.Real.truncate}
```

**Comment by sjakobi** [comment]
The precedent for the various new `Numeric.*` modules is `Numeric.Natural` (soon to be enhanced by https://github.com/haskell/core-libraries-committee/issues/45).

However, `Data.Complex`, `Data.Fixed`, `Data.Int`, `Data.Ratio` and `Data.Word` also offer some precedent for number-related things in the `Data` hierarchy. I wouldn't mind replacing the various suggested `Numeric.X` modules with `Data.X` if that's what people prefer. Arguably, `Numeric.Natural` should be re-exported from `Data.Natural` in this case.

(Regarding the mess in the `Numeric` module, I'd prefer to leave that for future work.)

**Comment by chreekat** [comment]
My first and only thought when reading your comment was, "I will never remember what is in `Data` and what is in `Numeric`". It's troubling enough that I already have developed muscle memory for distinguishing between Data.Functor and Control.Monad.  :)

**Comment by andreasabel** [comment]
+1

> NEW Data.Seq
> ============
> GHC.Prim.seq

`seq` should go into `Data.Function`.
(Also because `Data.Seq` sounds like `Data.Sequence`.)

**Comment by andreasabel** [comment]
@sjakobi : I find `seq` similar enough to `const` to have them reside next to each other in the `Data.Function` module (which btw. should be `Function` as it is not about data---the Agda standard lib rectifies this).
I'd think that the `Data.*` hierarchy is (except for the `Function` glitch) about data structures, whereas `seq` is controlling evalution.  If you don't like `Data.Function` as a home, I'd be placing it somewhere into the `Control` hierarchy.

**Comment by Ericson2314** [comment]
Perhaps `Control.Seq`. and then `Control.DeepSeq` in https://hackage.haskell.org/package/deepseq-1.4.7.0 migrates to `Control.Seq.Deep`?

**Comment by sjakobi** [comment]
While I tend to agree that `Control.Seq` would be a more appropriate module for `seq` than `Data.Seq`, it would unfortunately clash with [`Control.Seq` from `parallel`](https://hackage.haskell.org/package/parallel-3.2.2.0/docs/Control-Seq.html), which is still [relatively widely used](https://packdeps.haskellers.com/reverse/parallel). https://haskell-code-explorer.mfix.io/package/parallel-3.2.1.1/show/Control/Seq.hs indicates that the contents of `Control.Seq` itself are not widely used though.

How about not re-homing `seq` for now and asking the `parallel` maintainer whether their `Control.Seq` could be re-named?!

**Comment by Ericson2314** [comment]
That plan sounds good to me, but I might also propose `Control.Evaluation`. `seq` is, after all, a sort of nonsense jargon shorthand

Either option is good to me.

**Comment by sjakobi** [comment]
@Ericson2314 Thanks, I like `Control.Evaluation`.

Updated plan:

```
NEW Control.Evaluation
======================
GHC.Prim.seq
GHC.Base.$!

NEW Data.Bounded
================
GHC.Enum.Bounded{GHC.Enum.maxBound GHC.Enum.minBound}

NEW Data.Double
==================
GHC.Types.Double

NEW Data.Enum
=============
GHC.Enum.Enum{GHC.Enum.enumFrom GHC.Enum.enumFromThen GHC.Enum.enumFromThenTo GHC.Enum.enumFromTo GHC.Enum.fromEnum GHC.Enum.pred GHC.Enum.succ GHC.Enum.toEnum}

NEW Data.Error
==============
GHC.Err.error
GHC.Err.errorWithoutStackTrace
GHC.Err.undefined

NEW Data.Float
=================
GHC.Types.Float

NEW Data.Fractional
======================
GHC.Real.Fractional{GHC.Real./ GHC.Real.fromRational GHC.Real.recip}
GHC.Real.^^ :: (Fractional a, Integral b) => a -> b -> a
GHC.Real.realToFrac

Data.Function
=============
GHC.Base.$!
GHC.Base.asTypeOf
GHC.Base.until

NEW Data.Integer
===================
GHC.Integer.Type.Integer

NEW Data.Integral
====================
GHC.Real.Integral{GHC.Real.div GHC.Real.divMod GHC.Real.mod GHC.Real.quot GHC.Real.quotRem GHC.Real.rem GHC.Real.toInteger}
GHC.Real.even
GHC.Real.gcd
GHC.Real.lcm
GHC.Real.odd
GHC.Real.^ :: (Num a, Integral b) => a -> b -> a
GHC.Real.^^ :: (Fractional a, Integral b) => a -> b -> a
GHC.Real.fromIntegral

NEW Data.Num
===============
GHC.Num.Num{GHC.Num.* GHC.Num.+ GHC.Num.- GHC.Num.abs GHC.Num.fromInteger GHC.Num.negate GHC.Num.signum}
GHC.Num.subtract

NEW Data.Real
================
GHC.Real.Real{GHC.Real.toRational}
GHC.Real.realToFrac

NEW Data.RealFloat
=====================
GHC.Float.RealFloat{GHC.Float.atan2 GHC.Float.decodeFloat GHC.Float.encodeFloat GHC.Float.exponent GHC.Float.floatDigits GHC.Float.floatRadix GHC.Float.floatRange GHC.Float.isDenormalized GHC.Float.isIEEE GHC.Float.isInfinite GHC.Float.isNaN GHC.Float.isNegativeZero GHC.Float.scaleFloat GHC.Float.significand}

NEW Data.RealFrac
====================
GHC.Real.RealFrac{GHC.Real.ceiling GHC.Real.floor GHC.Real.properFraction GHC.Real.round GHC.Real.truncate}
```

**Comment by andreasabel** [comment]
You are (rightfully!) fine to place`$!` in `Data.Function`, but `seq` not...
I look at `Data.Function` a bit as a collection of tools (esp. `$` and `.`) akin to the primitives of the Haskell language, so I am not worried by `seq` not used on functions if it was placed there.

**Comment by Ericson2314** [comment]
Glad we got a plan! Let's make a PR! We can also create a new hlint rule to make sure `Prelude` never imports from `GHC.*` again :).

**Comment by sjakobi** [comment]
@andreasabel I still feel that `seq` would be a bit misplaced in `Data.Function`. I'd also like to have `Control.Evaluation` as _the_ home module for `seq`, i.e. haddock references to `seq` should link to `Control.Evaluation`. I fear that additional modules exporting `seq` might get into the way of that goal.

I wouldn't protest against a follow-up proposal to add `seq` to `Data.Function` though.

@Ericson2314 I'll try to make an MR next week or so.

**Comment by Ericson2314** [comment]
Conversely, just so we're all clear, `$!` *is* in both places and I think that is good.

**Comment by andreasabel** [comment]
Fine with me, if you do not worry about a new module `Control.Evaluation` with a single function.

**Comment by sjakobi** [comment]
> Fine with me, if you do not worry about a new module `Control.Evaluation` with a single function.

The plan is to export `$!` from `Control.Evaluation` too. And I may make a follow-up proposal to add `<$!>`.

**Comment by Ericson2314** [comment]
Can still do `Control.Deepseq` -> `Control.Evaluation.Deep`, which will at least give that module hierarchy more purpose.

**Comment by Bodigrim** [comment]
@Ericson2314 @sjakobi @andreasabel did you come to any conclusion? Is any of you interested in moving it forward formally?

**Comment by Bodigrim** [comment]
Folks, just a gentle ping to anyone interested to proceed with this idea. We need a specific proposal, which can be voted on.

**Comment by Ericson2314** [comment]
@sjakobi would you like to make a PR? I could but am already multi-tasking on many things.

**Comment by phadej** [comment]
Sorry for being late at the party.

Sad we cannot have `Control.Seq` just because `parallel` defines it. That module is barely used: https://hackage-search.serokell.io/?q=import.*Control.Seq%28%24%7C%5B%5Eu%5D%29. Essentially `lens` and `ghcide`...

Also there is `Control.Exception` which exports `throw`. (`GHC.Err` imports `GHC.Exception` to define `error` and `undefined`)

Also, instead of creating a lot of `Data.Num` etc. modules, why not just shove all of that into [`Numeric`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Numeric.html#)? It exports `Floating`, but IMO could export whole `Num` type-class hierarchy. Types could be in `Data.*` namespace.

**Comment by andreasabel** [comment]
> . So `error` and `undefined` could be in `Control.Exception` or new `Control.Error`. There is nothing `Data.*` about them.

I totally agree with @phadej.

**Comment by Bodigrim** [comment]
Unless someone comes with a specific proposal, I'll close this as abandoned in two weeks.

**Comment by Bodigrim** [comment]
Closing as abandoned.

**Comment by andreasabel** [comment]
In the end, the fundamental question we need to solve is how to decouple `base` from GHC.  After we have removed this major roadblock, there might be a new perspective on issues like the present one.

**Comment by Ericson2314** [comment]
Now that we have `ghc-internal`, maybe it would be good for someone to resurrect this.
