### ISSUE TITLE
Port nTimes and applyWhen from ghc GHC.Utils.Misc

### ISSUE THREAD

**Issue by schuelermine** [haskell/core-libraries-committee#66]
I suggest to include `nTimes` and `applyWhen` from ghc GHC.Utils.Misc in `Data.Function`. They’re simple & versatile utility functions. 

Specifically, add the following to `Data.Function`:

```hs
applyWhen :: Bool -> (a -> a) -> a -> a
applyWhen True f x = f x
applyWhen _    _ x = x
```

```hs
nTimes :: Integral i => i -> (a -> a) -> (a -> a)
nTimes 0 f x = x
nTimes n f x = f $ nTimes (n-1) f x
```

…and its strict version:
```hs
nTimes' :: Integral i => i -> (a -> a) -> a -> a
nTimes' 0 f x = x
nTimes' n f x = nTimes' (n-1) f $! f x
```

**This proposal text has been updated. Immediately following discussion refers to the original text**

**Comment by tomjaguarpaw** [comment]
`nTimes` is rather problematic because it leaks (stack) space when `f` is strict. Consider `nTimes n (+1)`:

```haskell
nTimes n (+1) 0
-> (+1) (nTimes (n-1) (+1) 0)
-> (+1) ((+1) (nTimes (n-2) (+1) 0))
-> (+1) ((... ((+1) 0) ...))
-> (+1) ((... 1 ... ))
-> n
```

In practice the version of this that is most likely wanted is the strict accumulating version

```haskell
nTimesAcc :: Int -> (a -> a) -> a -> a
nTimesAcc 0 f x = x
nTimesAcc n f x = nTimesAcc (n-1) f $! f x
```

The lazy version does have some use when `f` is lazy, e.g.:

```haskell
nTimes n ("hello":) []
-> "hello" : nTimes (n-1) ("hello":) []
```

which can be consumed in a streaming fashion. I'd guess these uses occur an order of magnitude less frequently than the uses in which the strict accumulating version is appropriate.

**Comment by tomjaguarpaw** [comment]
Regarding `applyWhen`, in a codebase I was working in I would honestly prefer to see

```haskell
\cond f -> if cond then f else id
```

or even

```
\case True -> f; False -> id
```

which are clear and obvious, than `applyWhen` which would make me think for at least a second, and maybe have to look something up.

**Comment by schuelermine** [comment]
How about `nTimes'` for the strict version?

**Comment by schuelermine** [comment]
Also, I disagree with the thing about `applyWhen`. `\cond f -> if cond then f else id` is too verbose. Using `applyWhen` in higher-order functions is more concise and doesn’t clutter with syntax. `applyWhen` communicates the function’s purpose well.

**Comment by andreasabel** [comment]
+1 on `applyWhen` (and its dual `applyUnless`).
Pretext for `applyWhen`:
- https://hoogle.haskell.org/?hoogle=applyWhen&scope=set%3Astackage (lists 5 utility libraries)
- https://github.com/ndmitchell/extra/issues/63

Pretext for `applyUnless`:
- https://hoogle.haskell.org/?hoogle=applyUnless&scope=set%3Astackage (lists 3 utility libraries)

**Comment by alexfmpe** [comment]
>  \cond f -> if cond then f else id is too verbose. Using applyWhen in higher-order functions is more concise and doesn’t clutter with syntax. applyWhen communicates the function’s purpose well.

I typically use `Data.Bool.bool :: [bool :: a -> a -> Bool -> a]` on these cases

`applyWhen b f = bool id f b`

**Comment by Bodigrim** [comment]
@schuelermine would you like to make any changes to the text of your proposal? E. g., strict variants.

**Comment by schuelermine** [comment]
Oh, yeah, thanks for reminding me, will do tomorrow.

**Comment by sgraf812** [comment]
> +1 on `applyWhen` (and its dual `applyUnless`). Pretext for `applyWhen`:
> 
> * https://hoogle.haskell.org/?hoogle=applyWhen&scope=set%3Astackage (lists 5 utility libraries)
> * [Add applyWhen :: Bool -> (a -> a) -> a -> a ndmitchell/extra#63](https://github.com/ndmitchell/extra/issues/63)
> 
> Pretext for `applyUnless`:
> 
> * https://hoogle.haskell.org/?hoogle=applyUnless&scope=set%3Astackage (lists 3 utility libraries)

FWIW, I ripped `applyWhen` from Agda a while ago

**Comment by stephen-smith** [comment]
Shouldn't nTimes be implemented via stimes + Endo to minimize duplication? https://hackage.haskell.org/package/base/docs/Data-Semigroup.html#v:stimes

... and then applyWhen is just nTimes . fromEnum ?

**Comment by schuelermine** [comment]
@stephen-smith Can an Endo implementation also be used for the strict version?

**Comment by Lysxia** [comment]
> Shouldn't nTimes be implemented via stimes + Endo to minimize duplication? https://hackage.haskell.org/package/base/docs/Data-Semigroup.html#v:stimes

There's a subtlety here because `stimes` uses fast exponentiation, which doesn't seem to benefit `Endo`, so maybe that should be changed instead, defining `stimes` using `nTimes` which is then the "obvious" definition.

**Comment by schuelermine** [comment]
That sounds like a more reasonable way of doing that

**Comment by tomjaguarpaw** [comment]
I think this proposal should be split into two.  The two proposed functions have nothing to do with each other and there's no reason to vote on them together. In particular `nTimes` and its variations require considerable care in their design, but `applyWhen` requires no care at all.

**Comment by nomeata** [comment]
They seem to be related:
```
applyWhen b = nTimes (fromEnum b)
```

**Comment by andreasabel** [comment]
Two observations:
- `nTimes (0 - 1) f x` from the OP gives an infinite application of `f` to `x`, which is usually not what one wants.
- I sometimes wanted `nTimes`, and the workaround for its absence was `nTimes n f x = iterate f x !! n`, which isn't terrible either (but goes via lists and uses an a priori partial function `!!`).

**Comment by Bodigrim** [comment]
@tomjaguarpaw whatever works for the proposer better. We can continue discussion for both additions here, I’ll ask for a split vote anyway.

**Comment by schuelermine** [comment]
If I want to split the proposal, should I edit this one and create 1 new one, or create 2 new ones?

**Comment by tomjaguarpaw** [comment]
Perhaps `StrictEndo` could be made to work:

```haskell
StrictEndo f <> StrictEndo g = StrictEndo (\x -> f !$ g x)
```

**Comment by schuelermine** [comment]
Speaking of `stimes`, I just looked at Data.Semigroup—why was `mtimes` removed from `Monoid` in favour of the *partial* function `stimes`? Why doesn’t `stimes` take an initial value?

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

I see that this proposal was split into two separate and independent proposals:

* https://github.com/haskell/core-libraries-committee/issues/71
* https://github.com/haskell/core-libraries-committee/issues/72

I find having both `approved` and `declined` labels a bit confusing. So I'm removing them and adding the `withdrawn` label as in "withdrawn in favour of other more modular proposals"
