### ISSUE TITLE
WrappedMonoid should define stimes

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#7]
Of course, we should have `stimes = stimesMonoid`!

**Comment by cigsender** [comment]
Seeing as `WrappedMonoid` is on the way out I lean against adding functionality shortly before its removal. -1

**Comment by Bodigrim** [comment]
Sorry, @treeowl, I do not follow. How could `WrappedMonoid` be useful for `deriving via`?

**Comment by treeowl** [comment]
@Bodigrim, today, we can write things like

```haskell
instance Monoid T where
  ...

deriving via WrappedMonoid T
  instance Semigroup T
```

That will work as long as `Monoid` retains the `mappend` method. Is there an active plan to remove `mappend`?

**Comment by Bodigrim** [comment]
This raises a `-Wcompat` warning about a non-canonical definition. What's the motivation to write it this way? It's not even shorter than a straightforward definition of both classes.

**Comment by treeowl** [comment]
Eh, I guess it's not really important.
