### ISSUE TITLE
Add `nTimes`

### ISSUE THREAD

**Issue by schuelermine** [haskell/core-libraries-committee#72]
**This is a proposal split from #66**

### Suggestion

I suggest to add the following function to `Data.Function`:
```hs
nTimes :: Int -> (a -> a) -> a -> a
nTimes n f | n < 0 = g 0
           | otherwise = g n
    where g 0 x = x
          g n x = f $ g (n - 1) x
```
and a strict version:
```hs
nTimes' :: Int -> (a -> a) -> a -> a
nTimes' n f | n < 0 = g 0
            | otherwise = g n
    where g 0 x = x
          g n x = g (n - 1) $! f x
```

`nTimes` is taken from `GHC.Utils.Misc`.  
The error message is copied from `stimesDefault` from `Data.Semigroup.Internal.stimesDefault`.

### Alternatives

⇒ Instead of throwing an error, all values less than zero could be clamped to zero.

⇒ This simpler alternative doesn’t check for negative multipliers. This means that `nTimes (-1)` is equivalent to `fix`:
```hs
nTimes :: Int -> (a -> a) -> a -> a
nTimes 0 f x = x
nTimes n f x = f $ nTimes (n-1) f x
```
```hs
nTimes' :: Int -> (a -> a) -> a -> a
nTimes' 0 f x = x
nTimes' n f x = nTimes' (n-1) f $! f x
```

⇒ `nTimes` could be implemented in terms of `stimes`: `nTimes n = appEndo . stimes n . Endo`
I *think* this *might* be a bad idea, as `stimes` working with 0 *seems* to be a convenience feature to the specific dispatch implementer’s discretion and not an intentional feature.

### Notice

**This proposal has been edited. Check the original version for better understanding of the discussion.**

**Comment by treeowl** [comment]
I'd go with smashing all negatives to 0 as well, since many other functions do that.

Your strict version is only strict in the initial value if `n = 0` or `f` is strict. Is that what you want? If not, you might consider

```haskell
nTimes' :: Integral i => i -> (a -> a) -> a -> a
nTimes' 0 f x = x
nTimes' n f !x = nTimes' (n-1) f (f x)
```

None of these implementations allow any inlining, due to recursion. Consider, for example,

```haskell
nTimes :: Integral i => i -> (a -> a) -> a -> a
nTimes n0 f = go n0
  where
     go 0 x = x
     go n f x = f $ go (n-1) x
```

Why do you use a polymorphic `Integral` count? That doesn't seem to match the convention, and it could lead to inefficient defaulting and/or annoying type errors. I would consider specializing to `Int`, even though `Natural` would be more theoretically satisfying.

**Comment by treeowl** [comment]
It's theoretically possible on a 64-bit architecture too, but in practice I believe it'll take years.

**Comment by andreasabel** [comment]
+1 for `Int -> (a -> a) -> a -> a`.

**Comment by mitchellwrosen** [comment]
Protolude defies this under the name `applyN`, fwiw: https://hackage.haskell.org/package/protolude-0.3.0/docs/Protolude.html#v:applyN

**Comment by nomeata** [comment]
The name `nTimes` doesn't allude to function application at all (and we shouldn't necessarily take GHC code as a source for good naming, lots of idiosyncrasies there).

`iterateN` maybe? As Andreas Abel pointed out it _is_ just indexing into `iterate f`.

**Comment by konsumlamm** [comment]
> `iterateN` maybe? As Andreas Abel pointed out it _is_ just indexing into `iterate f`.

`iterateN` alludes even less to function application imo. It is already used in `Data.Sequence` and `Data.Vector` to mean "`iterate`, but only n elements".

**Comment by tomjaguarpaw** [comment]
> I’d still argue “function iteration” is more common and less ambiguous than “function multiplication” (as the `nTimes` name is derived from).

I don't think `nTimes` is derived from "function multiplication". Saying "do this thing five times" is perfectly normal in non-technical English and no one would assume it means anything to do with "multiplication".

**Comment by nomeata** [comment]
Maybe I should defer this discussion to native speakers, but to me it seems that “five times” still needs a verb (“iterate 5 times”, “apply 5 times”, “multiply five times”, “compose five times”, “concatenate 5 times”, “do 5 times), and without that verb, `nTimes` does not necessarily indicate that this is iterated function composition.

**Comment by JakobBruenker** [comment]
> still needs a verb

Not a native speaker, but the function is the verb. e.g. `nTimes 5 (subtract 4)` means "subtract 4, 5 times"

**Comment by nomeata** [comment]
Ah, interesting point of view, I didn’t consider that! I was expecting the new combinator to be the verb, and the function its object (as in `iterate (subtract 4)`). But ``subtract 4 `nTimes` 5`` has its appeal as well. I’ve made my point, and will leave the stage to others now  :-)

**Comment by schuelermine** [comment]
I wanna bring up `Int` again. How big of a problem is `Integral i => i -> …` really? It’s 100% compatible with `Int` and they work just the same (I think). Also, it’s easier to plug in things if you’re working with `Integer`s already—having to call `fromIntegral` could be annoying.

**Comment by JakobBruenker** [comment]
On the other hand, if you write `nTimes 5 f` and have `-Wall` enabled, GHC will complain about defaulting to Integer if the type uses `Integral`. Though I suspect using non-`Int` expressions will be more common than using concrete literals.

**Comment by mixphix** [comment]
I would be more strongly in favour of `_ :: Int -> (a -> a) -> a -> a` to avoid running into `-Wtype-defaults` where possible. As a rule, unsafe conversions should be explicit at the call site: I see no reason we ought to guide the user into avoiding potential pitfalls like this.

Another option is to expose `genericNTimes :: (Integral n) => n -> (a -> a) -> a -> a` in the same vein as `genericTake`, `genericDrop`.

**Comment by schuelermine** [comment]
…but also, that brings this up to four functions that do basically the same thing. Is that really necessary?

**Comment by Lysxia** [comment]
`genericNTimes` doesn't look much better than `nTimes . fromIntegral`. However, the situation is more subtle than it seems because these functions are technically different: `nTimes . fromIntegral` will overflow in the conversion `Integer -> Int`, but `genericNTimes` can work correctly on all non-negative `Integer`.

I am also on the camp that the "default" function `nTimes` should be specialized to `Int` to avoid accidentally doing arithmetic on the wrong type.

I'm indifferent about the inclusion of `genericNTimes`. It's difficult to imagine a situation where you would want to apply it to a number greater than 2^31 or 2^63. But maybe for formal verification it's not too far-fetched to not want to worry about overflow. And including the more general functions can help documenting these subtle differences.

**Comment by schuelermine** [comment]
I have updated the proposal to list the version that errors on negative numbers first. I believe it is a more reasonable version.

**Comment by schuelermine** [comment]
I don’t know about clamping to zero. This seems like unexpected behaviour to me. It doesn’t gel with the theoretical interpretation and I can’t see a situation where this would be desirable. Explicit error/bounds checking seems the way to go for me.

**Comment by Ericson2314** [comment]
Why don't we make a new natural number class that will actually do what we want? (implemented by `Word`, `Word<N>`, and `Natural`.)

I am not really interested in seeing _de novo_ code that will live with us forever hack around Haskell's lousy number hierarchy.

**Comment by Ericson2314** [comment]
For example:
```haskell
class Peano n where
  zero :: n
  succ :: n -> n
  peano :: n -> Maybe n

pattern Zero -> Nothing <- peano where
  Zero = zero

pattern Succ n -> Just n <- peano where
  Succ n = succ n
```

**Comment by schuelermine** [comment]
I really like that idea, but that sounds like it’d need to be a separate proposal

**Comment by Ericson2314** [comment]
Fair enough. If someone else could make that that would be much appreciated --- I have a number of things going on already, and don't want to take on another.

**Comment by JakobBruenker** [comment]
> pattern Zero -> Nothing <- peano where
  Zero = zero

Note that those particular pattern synonyms produce ``parse error on input `->'``, with just `{-# LANGUAGE PatternSynonyms #-}`

**Comment by schuelermine** [comment]
Just remembered that `nTimes` is theoretically interesting as well as it converts numbers to their Church encoding, just as `bool` does to booleans.

**Comment by Bodigrim** [comment]
@schuelermine is there a reason behind `errorWithoutStackTrace`? I'd suggest `error` and `HasCallStack` instead, in line with other partial function from `Prelude`.

**Comment by schuelermine** [comment]
@Bodigrim The reason was that an implementation using `stimes` would’ve produced that as well, since `stimesDefault` uses `errorWithoutStackTrace`. I think the idea was that calling with a dynamic multiplier is unlikely? Also, other primitive partial functions in `Prelude` and beyond *do* error without stack trace, e.g. `head` and `(!!)`.

The question we need to ask is how common it will be to have a value travel through the program and be processed to a negative integer that is placed as the dynamic multiplier of `nTimes`. I don’t know the answer so I went with what `stimes` did. Do you believe `stimes`’ approach is inapplicable here and/or was misguided in the first place?

**Comment by Bodigrim** [comment]
> Also, other primitive partial functions in Prelude and beyond do error without stack trace, e.g. head and (!!).

This is no longer the case, I believe: http://downloads.haskell.org/ghc/9.4.1-alpha2/docs/libraries/base/src/GHC.List.html#errorEmptyList

`stimes` was left with `errorWithoutStackTrace` because it's a member of type class, which may prevent optimizations to eliminate call stack overhead. This reason does not apply to `nTimes`.

**Comment by schuelermine** [comment]
I’ve updated the proposal to use `error`. I agree that it’s probably a good choice.

**Comment by Bodigrim** [comment]
`error` asks for `HasCallStack` to be more useful.

I'm still uneasy with adding more partial functions to `Prelude`. How about `nTimes :: Word -> (a -> a) -> a -> a`, which is total?

**Comment by emilypi** [comment]
I'm in favor of @Ericson2314's natural number typeclass proposal as opposed to taking the `Integral` partiality hit on the chin, yet again. We remove ourselves from the horns of this particular dilemma if we're clear about which `Integral i => i` we want here. I'm in favor of tabling this until that proposal goes in.

**Comment by andreasabel** [comment]
I think `nTimes :: Int -> (a -> a) -> a -> a` is still the best option, with `nTimes n f x | n <= 0` being `x`.  This is consistent with `replicate :: Int -> a -> [a]`.  So, basically:
```haskell
nTimes n f x = foldr ($) x (replicate n f)
```
`Int` is the default type for not too large integers in the Haskell standard.

**Comment by emilypi** [comment]
Which Haskell standard specifies standard inputs and partial functions? If so, i would like to advocate we depart from that standard, because it is outdated and contrary to the many efforts that exist to remove these kinds of warts.

**Comment by andreasabel** [comment]
The Haskell 2010 standard, e.g.: https://www.haskell.org/onlinereport/haskell2010/haskellch9.html#x16-1720009.1
All numeric types you can see in `PreludeList` are `Int`.
It might make sense to develop a new standard with using an unsigned number instead.
But it does not make much sense to place an alien like `nTimes :: Word -> (a -> a) -> a -> a`amoung the other list function (all using `Int`) which does not harmonize with them.

**Comment by schuelermine** [comment]
The natural number class proposal would require updating a lot of existing functions. Wouldn't it make sense to, in the mean time, strive mostly for harmonisation with the compromises already made?

**Comment by emilypi** [comment]
Ah yes, the Haskell Standard from 12 years ago that GHC deviated from in 7.4 and hasn't since returned to? I see it as a very poor example of what should guide both current Haskell thinking or future additions to the language. Citing it has no weight with me.

**Comment by andreasabel** [comment]
> Citing it has no weight with me.

My arguments have weight even without citing anything, out of inner consistency alone.

**Comment by emilypi** [comment]
Considering the number of proposals from the community asking for us to drop partial functions, I'd say "consistency" is not a valuable goal here.

**Comment by Bodigrim** [comment]
Currently I use `iterate f x !! n` instead of `nTimes n f x`. Is the proposed `nTimes` a better option?

**Comment by schuelermine** [comment]
Yes, I believe `nTimes` is better because it communicates the intent better. Although the usage of the generate-filter pattern is great, I believe it does tend to communicate a sense that the intermediate values are exposed or needed, when their existence is entirely hidden through `nTimes`.

**Comment by andreasabel** [comment]
@Bodigrim wrote:
> Currently I use `iterate f x !! n` instead of `nTimes n f x`. Is the proposed `nTimes` a better option?

I do so as well, for lack of a primitive `nTimes`.  In a code base banning partial functions like `!!`, the total implementation `foldr ($) x (replicate n f)` is better, but also harder to comprehend.

**Comment by schuelermine** [comment]
Sorry for replying late.

I think there are currently too many options for a vote—several people have mentioned salient variations in type and function.
Would it be OK if I take a short while to contemplate and select a variation to vote on?

For an eventual vote think a @nomeata’s concerns are justified and the best voting system is approval voting (+1 or +0 for each option) between none, lazy only, strict only, or both.

**Comment by nomeata** [comment]
(the Condorcet winner can be determined in a short-circuit way, too - SCNR)

**Comment by schuelermine** [comment]
I've updated the type to use `Int`. @Bodigrim You can vote on it now.

**Comment by Bodigrim** [comment]
@schuelermine Sorry, I don't follow, https://github.com/haskell/core-libraries-committee/issues/72#issue-1254046443 still contains `Integral a`.

**Comment by schuelermine** [comment]
It appears my connection in GitHub is faulty in more ways than two. I'm really sorry! This is the third mistake I've made today, I'll be more through next time.

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal https://github.com/haskell/core-libraries-committee/issues/72#issue-1254046443 to add `nTimes, nTimes' :: Int -> (a -> a) -> a -> a` with clamping behaviour to `Data.Function`. Please vote separately on inclusion of `nTimes` and `nTimes'`.

@tomjaguarpaw @chessai @emilypi @mixphix @cgibbard 

----

-1 for both functions.
I don't know any widespread use case for these function outside of recreational setting. I failed to find such applications in the prior art. `nTimes` is just `coerce stimes` via `Endo`, and in my opinion does not deserve a separate name. `nTimes' n f` is `iterate f !! max 0 n`, which again is not too bad. If sufficient demand could be demonstrated, I'd rather add `StrictEndo` newtype.

**Comment by chessai** [comment]
-1 for both, for reasons similar to what @Bodigrim states. Also, I typically use similar fix functions not by picking an N and iterating N times, but by iterating until a fixpoint is reached or iterating until my result matches some predicate.

**Comment by emilypi** [comment]
-1 for the reasoning stated above.

**Comment by Bodigrim** [comment]
@tomjaguarpaw @mixphix @cgibbard just a gentle reminder to vote.

**Comment by mixphix** [comment]
I'm +1, for the `Int` version.

**Comment by tomjaguarpaw** [comment]
-1

----

I'm broadly in favour of adding something like this but I'm against this specific proposal, firstly because I don't see a strong use case for the lazy version, and secondly because I'm not convinced a type of `Int` makes sense when we're trying to move the ecosystem away from too-loose types.

**Comment by cgibbard** [comment]
-1, I'm feeling similar to @tomjaguarpaw about it.

**Comment by Bodigrim** [comment]
Sorry, @schuelermine, the proposal is declined. Thanks all.

**Comment by schuelermine** [comment]
Good thing the original proposal got split. Thanks @tomjaguarpaw for that notice.
