### ISSUE TITLE
Add blackbird 

### ISSUE THREAD

**Issue by MonAaraj** [haskell/core-libraries-committee#73]
Blackbird is a very simple operator which is the composition of composition with itself. It's simple, and easy to define in anyone's project; but it improves code readability, because it is essentially composing functions that have 2 arguments. It is also easy to implement in a central place (like haskell). 

```hs
(.:) = (.) . (.)
-- example usage
bind = join .: fmap
```

**Comment by googleson78** [comment]
I'm not sure that this is encountered with that meaning *that* often. It's used by a bunch of libs for a bunch of different stuff:
https://hoogle.haskell.org/?hoogle=(.%3A).

**Comment by mixphix** [comment]
-1. Use a separate package for this.

**Comment by Bodigrim** [comment]
No need to waste three dots, where two are enough: `join .: fmap == (join .) . fmap`.

**Comment by andreasabel** [comment]
Hoogle shows many definitions of this operator: https://hoogle.haskell.org/?hoogle=%28a+-%3E+b%29+-%3E+%28c+-%3E+d+-%3E+a%29+-%3E+c+-%3E+d+-%3E+b&scope=set%3Astackage

<img width="489" alt="Screenshot 2022-06-04 at 09 59 54" src="https://user-images.githubusercontent.com/1155218/171990545-0b42653d-8c56-4927-8b04-7474b38d85b5.png">

This is initial evidence that such an operator is lacking from `base`.

However, a proposal for a composition operator with a function of arity 2 should also have a story for higher arities.  I.e. there should be a naming scheme rather than just a name.


@Bodigrim wrote:
> `(join .) . fmap`.

I find this completely incomprehensible.

**Comment by Bodigrim** [comment]
A name clash with `aeson` is pretty much a deal breaker from my perspective.

**Comment by alt-romes** [comment]
It could be useful, but maybe under another name (e.g. `(...)`), the clash is indeed quite bad

**Comment by MorrowM** [comment]
I think an operator like this would be right at home in `Data.Function`. Perhaps that would reduce concerns about name clashes?

**Comment by Ericson2314** [comment]
I am not pleased about this deluge of issues where folks are trying to get their favorite combinator in `Prelude`. I suppose just as ghc-proposals invite endless new sugar, so CLC proposals will invite this. :(

**Comment by andreasabel** [comment]
> I am not pleased about this deluge of issues where folks are trying to get their favorite combinator in `Prelude`.

I agree.  
I imagine a more evidence-based process, where a committee would regularly (maybe once a year or once every two years) mine the Haskell eco-system for functions involving the `base` data types.  Functions that enjoy a significant usage and are not in `base` yet could then be added, after a bikeshedding process for the naming; but the naming decision should also be dominated by evidence: which name is most frequent in the wild, or in other programming languages.

Maybe such a mining tool would be an interesting GSoC project...

**Comment by MonAaraj** [comment]
First of all, It's really nice that people here discussed how it wouldn't be that useful given the other issues such an addition has. I didn't think that this would be such a controversial suggestion, as I haven't really thought of all the other aspects that people here showed. I think I wouldn't like to waste people's time any longer. Thank you very much for the response everyone, and I hope you have a great day. I apologize once again.
