### ISSUE TITLE
[Meta] Are CLC members allowed to submit CLC proposals?

### ISSUE THREAD

**Issue by chshersh** [haskell/core-libraries-committee#79]
I didn't notice any clarification about this particular policy (maybe I missed it) and I'm not sure what is the default behaviour here.

I see several potential options:

+ **Allowed and can vote:** This gives CLC members an advantage over other members of the community as they have more votes.
+ **Alloweved and can't vote:** They don't have an advantage but still, other CLC members can be biased towards proposals by their colleagues and favour them more.
+ **Not allowed:** CLC members simply accept that they can't submit CLC proposals on their behalf. But maybe they should be allowed because they have more context about the `base` state and potentially more expertise? Even if CLC members are not allowed, they can always create _fake_ GitHub accounts to submit proposals but at least there won't be any bias towards this proposal.

I'm not telling CLC what option to choose (or maybe it's already implicitly chosen?) but I believe it's worthwhile to explicitly write it.

**Comment by tomjaguarpaw** [comment]
My guess is it should be the first, "Allowed and can vote". They (we) could subvert the intent of the other two options by getting a non-CLC friend to submit the proposal on their (our) behalf.

**Comment by goldfirere** [comment]
As a non-CLC member: I favor "Allowed and can vote". The CLC has a very high level of context, and I would expect their proposals to be more informed, on average, than outside proposals. Proposals are accepted when the majority of the CLC is in favor. If a proposal happens to come from within the CLC, that means that a member is so strongly in favor that they devoted time to write the proposal themselves. While I'm not blind to the possibility that this could all be abused, I favor not policing this aspect of the process too much and just allowing the votes.
