### ISSUE TITLE
The cyclical dependency between GHC.Base and Data.Semigroup.Internal is a mess

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#8]
`GHC.Base` source imports `Data.Semigroup.Internal`, which imports `GHC.Base`. So what? Well, one pain point is that we end up with Core saying (approximately)

```haskell
class Semigroup a where
  ...
  stimes = noinline stimesDefault
```

That is, the *default* definition of `stimes` isn't specialized to the `Semigroup` in question! That seems fairly awful. The same `noinline` issue applies to all the explicit definitions of `stimes` in `GHC.Base` that use functions in `Data.Semigroup.Internal`. We could improve things for some of these easily by moving `stimesIdempotent` and `stimesIdempotentMonoid` to `GHC.Base`, generalizing their constraints from `Integral b` to `Num b`. But fixing the rest ... I don't know.

**Comment by treeowl** [comment]
I *think* we can fix some of these problems by adding `hs-boot` files for `GHC.Enum` and `GHC.Num`, putting more info in the `hs-boot` file for `GHC.Real`, and shuffling a few other things around. It ... isn't pretty.

**Comment by treeowl** [comment]
I do think it's better, though. WIP as part of https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6850/diffs

**Comment by gwils** [comment]
I have a very strong preference against orphan instances in base. If you find a happy combination of `hs-boot` trickery, we could look at fixing this.

**Comment by treeowl** [comment]
I'm working on it. I'll need to add different `.hs-boot` files, but I *think* I can limit them to class and type definitions, which I think shouldn't cause the inlining interference that functions and instances do.

**Comment by treeowl** [comment]
@gwils I have managed to do it with no orphan instances and without substantially more mess: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6863. There are some compile-time stat increases in four tests that the GHC folks probably won't be happy about, but those don't look like they're really my fault.

**Comment by Bodigrim** [comment]
@treeowl are there any user-facing consequences of this reshuffling?

**Comment by treeowl** [comment]
@Bodigrim, users are not supposed to import `GHC.Base` directly. No one following that rule should be affected at all, aside from changes in specialization/inlining. Anyone breaking the rule will see an extra binding for `stimesDefaultError`.

**Comment by Bodigrim** [comment]
I'm inclined to say that such reshuffling is out of scope for CLC and does not require a specific approval. Opinions?

**Comment by treeowl** [comment]
I'd like to ask for a vote now: yes, no, or out of scope, so I can proceed with the MR.

**Comment by cigsender** [comment]
I lean towards this being out-of-scope for the CLC; correct me if I’m mistaken, but the `.hs-boot` files seem to relate more to GHC that to `base` as a library.

**Comment by cigsender** [comment]
(ping @cgibbard @emilypi @chessai)

**Comment by emilypi** [comment]
I vote that this is out of scope, but I'm happy to review a MR if you put one up @treeowl. I'd certainly want more eyes on it than just us - this affects @bgamari and the other core GHC devs as well.

**Comment by Bodigrim** [comment]
@chessai @gwils @cgibbard what is your opinion?

**Comment by gwils** [comment]
I vote out of scope given users won't be affected.

**Comment by treeowl** [comment]
@emilypi, please see [this merge request] (https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6863). Your review would of course be welcomed.

**Comment by emilypi** [comment]
Thanks @treeowl! I'll take a look during the week 😄

**Comment by Bodigrim** [comment]
Closing as out of scope for CLC.
