### ISSUE TITLE
Improve the `Show` instance for `Rational` to be more standard and easier to read.

### ISSUE THREAD

**Issue by davidsd** [haskell/core-libraries-committee#81]
I do a lot of math with Rational numbers in Haskell, and the Show instance for Rational is a common annoyance, due to being non-standard and difficult to read (at least for me). In Haskell, the number `1/3` is rendered as `1 % 3`.  The use of `%` makes it impossible to copy-paste into other programs (e.g. Mathematica). For example, here's an expression from a recent computation:

    (1 % 1)*y^0*u^0*x^0 + 0*x^1 + ((-9) % 2)*y^2*u^2*x^2 + ((-23) % 15)*y^4*u^2*x^3

(Most of this string comes from a custom show instance for some data structure, but the `(a % b)` are Rationals.) I wish it looked more like this:

    (1/1)*y^0*u^0*x^0 + 0*x^1 + (-9/2)*y^2*u^2*x^2 + (-23/15)*y^4*u^2*x^3

Fortunately, we can write `1/3` to create a `Rational` literal -- we do not need to write `1 % 3`.

I propose changing the `Show` instance for `Rational` to use `/` instead of ` % ` (I prefer without spaces, but spaces would be fine too). Because `Rational` is `Ratio Integer`, changing its `Show` instance would require changing it for `Ratio a` in general. And it appears this unfortunately would be a departure from the Haskell 98 standard. Still, I thought this proposal might be worth a try.

**Comment by Bodigrim** [comment]
As someone who works with `Rational` a lot, I have a lot of synpathy to this proposal. However, this kind of thing is relatively niche and can be easily fixed by a newtype wrapper.  

If you wish to move this further, please demonstate desired `instance Show` and `instance Read`.

**Comment by phadej** [comment]
The instance is specified in the report: https://www.haskell.org/onlinereport/haskell2010/haskellch22.html#x30-25900022.1

In my opinion the motivation to change it should be stronger than "easier to copy paste to Mathematica".

**Comment by stepcut** [comment]
Normally, when you call `show` on a value, it will produce a string, which if pasted into GHCi produces the original value. This is not strictly enforced, but it is often true.

With this proposal, you'd be able to copy and paste the string into Mathematica, but not Haskell. That doesn't seem like a win in my book.

Perhaps your code should be using a different class than `Show`.

**Comment by davidsd** [comment]
> In my opinion the motivation to change it should be stronger than "makes it easier to copy paste to Mathematica".

I agree -- how many people really care about Mathematica? Maybe it is better to say that `1 % 2` is simply non-standard, while `1/2` is standard. A standard Show instance would be easier to copy-paste basically everywhere (and it would still work in ghci), in addition to being easier to parse by eye (at least for me).

**Comment by cartazio** [comment]
This seems like it would break pretty much any serialization code that uses show. For relatively little gain in what’s essentially better solved by having a dedicated pretty printing class for humans in either a library or base.

**Comment by friedbrice** [comment]
`Show` is not really meant for copying-and-pasting to Mathematics. It's meant for copying-and-pasting into a Haskell source file or into Ghci.

I think what you really want, @davidsd, is to modify your program so that it emits output in a standardized serialization format, just as JSON, rather than emitting output in a serialization format that's specific to Haskell.

**Comment by friedbrice** [comment]
> having a dedicated pretty printing class for humans in either a library or base

The probably I can see with this approach (especially if it's in `base`, less so if it's a third-party library) is that one application's notion of pretty printing is going to differ from another application's notion. I think any such class means for pretty printing is going to suffer from the same things that people find annoying about `Show`. Namely, instance coherence makes customization inconvenient. This is not a condemnation of instance coherence, but rather some indication (to me, at last) that concerns that demand degrees of customization are not well-suited to being modeled by a class.

**Comment by davidsd** [comment]
> It's meant for copying-and-pasting into a Haskell source file or into Ghci.

I am confused about this point of view because `1/2` *is* what I would copy-and-paste into a Haskell file or ghci -- not `1 % 2`. In fact, let's compare the two in a fresh ghci session:

    > 1/2 :: Rational 
    1 % 2
    > 1 % 2 :: Rational
    <interactive>:346:3: error:
        Variable not in scope: (%) :: t0 -> t1 -> Rational

(Of course, I should have done `import Data.Ratio ((%))` first.) The point is that `1/2` is also friendly to Haskell source code and ghci. Admittedly, it doesn't work in patterns.

**Comment by davidsd** [comment]
I agree with @friedbrice about pretty printing. I am relatively confident in saying there will never be a widely-used, coherent, pretty-printing class in Haskell in addition to `Show`. `Show` is what we have. This is why I would like to improve `Show`.

**Comment by friedbrice** [comment]
That is a poignant demonstration, @davidsd. I guess I am not really expression my point all that well, though. The part that I really care about is the part about _native Haskell data_. I know that `%` is not technically the data constructor for `Ratio`, but `/` is just a bit too dynamic to capture the idea that good (by my metric) `Show` instances satisfy.

**Comment by Bodigrim** [comment]
> The instance is specified in the report: https://www.haskell.org/onlinereport/haskell2010/haskellch22.html#x30-25900022.1

FWIW `Data.Ratio` in Report (and in `base`) is broken beyond repair anyway and anything other than `Ratio Integer` should not exist. I wonder if we should just mark `Data.Ratio` as deprecated and introduce `Data.Rational`, providing `data Rational = Integer :% Natural` only, potentially with a better `instance Show` as well.

**Comment by phadej** [comment]
> > The instance is specified in the report: https://www.haskell.org/onlinereport/haskell2010/haskellch22.html#x30-25900022.1
> 
> FWIW `Data.Ratio` in Report (and in `base`) is broken beyond repair anyway and anything other than `Ratio Integer` should not exist. See https://www.fpcomplete.com/blog/hidden-dangers-of-ratio/ and https://gitlab.haskell.org/ghc/ghc/-/issues/21646. I wonder if we should just mark `Data.Ratio` as deprecated and introduce `Data.Rational`, providing `data Rational = Integer :% Natural` only, potentially with a better `instance Show` as well.

If you are ready to write patches for Stackage (especially if `Rational` exported from `Prelude` will be the new one).

**Comment by tomjaguarpaw** [comment]
> If you are ready to write patches for Stackage (especially if Rational exported from Prelude will be the new one).

Are you saying that Stackage patches would be required even if a new type `Data.Rational.Rational` *wasn't* exported from Prelude? If so could you explain your reasoning?

**Comment by phadej** [comment]
> Are you saying that Stackage patches would be required even if a new type Data.Rational.Rational wasn't exported from Prelude? 

No. But adoption will be *slow*, as there is really no incentive to change from `Ratio Integer` to `Data.Rational.Rational`. If `Rational` is used in public interfaces, that would be breaking change in these libraries.

Also what would happen with `Fractional` class (which has `fromRational` as a member).

But it's probably better to take the `Data.Rational.Rational` discussion into own issue.

**Comment by Bodigrim** [comment]
I know that this is tangential to the topic, but... Is my understanding correct that [`(%)`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Ratio.html#v:-37-) operator is actually absolutely redundant and can always be replaced by `(/)`?

**Comment by mixphix** [comment]
With a type annotation, you're correct:
```
ghci> :m +Data.Ratio
ghci> (3 / 2) :: Rational
3 % 2
ghci> 3 / 2
1.5
```

**Comment by friedbrice** [comment]
What? Clearly it's not redundant. % has completely different constraints. And it's of form X -> X -> Y whereas / is form X -> X -> X...

**Comment by Daniel-Diaz** [comment]
Just a bystander here, but `a / b` is dividing two values of type `Ratio a`, while `a % b` is building a fraction `Ratio a` from two values of type `a`. They are not the same.

If you are using literals, the results should be the same, but what they do is actually different.

`3 / 2` gets turned into `fromInteger 3 / fromInteger 2`, which then becomes `(3 :% 1) / (2 :% 1)`, and finally a division followed by a reduction gets us `3 :% 2`.

`3 % 2` doesn't do any division, it only reduces the fraction and returns `3 :% 2`. It's the smart constructor of `Ratio`.

(`:%` is the internal data constructor of the `Ratio` type)

**Comment by mixphix** [comment]
The implementation of `(/)` for `Ratio a` also does not perform division:

```hs
instance  (Integral a)  => Fractional (Ratio a)  where
    {-# SPECIALIZE instance Fractional Rational #-}
    (x:%y) / (x':%y')   =  (x*y') % (y*x')
```

This seems very similar, but not exactly identical, to the implementation of `(%)`:

```hs

reduce ::  (Integral a) => a -> a -> Ratio a
{-# SPECIALISE reduce :: Integer -> Integer -> Rational #-}
reduce _ 0              =  ratioZeroDenominatorError
reduce x y              =  (x `quot` d) :% (y `quot` d)
                           where d = gcd x y

x % y                   =  reduce (x * signum y) (abs y)
```

[(source)](https://hackage.haskell.org/package/base-4.17.0.0/docs/src/GHC.Real.html)

**Comment by Bodigrim** [comment]
Thanks @mixphix @friedbrice @Daniel-Diaz and sorry for digression.

----

> Also what would happen with `Fractional` class (which has `fromRational` as a member).

An excellent point, @phadej, I don't have a good plan for this. Anyway I have no bandwidth to raise such proposal in my own name. 

@davidsd how would you like to proceed? One option is that you prepare a GHC MR changing `instance Show (Ratio a)` and `instance Read (Ratio a)` and the committee votes on it as is. It's hard to tell an outcome, because some people may feel that the breaking change and divergence from the Report are not quite justified by purely esthetical reasons. 

Another option is to make a more ambitious proposal, targeting other known infelicities in `Ratio` and also improving `Show`, so that the breakage is justified by fixing more material bugs and everything is fixed at once (so that clients can migrate in one step). Again, it's hard to judge what amount of bikeshedding this will entail and what will be the final outcome.

The third option is just to withdraw.

**Comment by davidsd** [comment]
Hi @Bodigrim , regarding option (2), could you list which infelicities your have in mind? Would the proposal be that we implement a separate `Data.Rational` that essentially only implements `Ratio Integer` (since other uses of `Ratio` can be unsafe). Are there any other infelicities (besides the `Show` instance discussed here)?

**Comment by Bodigrim** [comment]
@davidsd I was mostly refering to https://gitlab.haskell.org/ghc/ghc/-/issues/21646. The specific way to address this is up to a prospective proposer, I should not overstep any further. I should not really push more ambitious path onto you, feel free to proceed with your original proposal only.

**Comment by Bodigrim** [comment]
@davidsd are you still interested in the proposal? Let's make some progress one way or another.

**Comment by Bodigrim** [comment]
@davidsd if there is no progress on this proposal, I'll close it as abandoned in two weeks.

**Comment by davidsd** [comment]
Hi @Bodigrim , it seems like the best way to proceed would be to try to push forward a separate `Data.Rational`. Unfortunately, I don't have time to spearhead that effort right now. So I will close this proposal for now.
