### ISSUE TITLE
More NonEmpty zips 

### ISSUE THREAD

**Issue by treeowl** [haskell/core-libraries-committee#83]
`Data.List.NonEmpty` offers `zip`, `zipWith`, and `unzip`. `Data.List`, on the other hand, offers each of these up to arity 7. I propose to add all the rest for `NonEmpty`:

* `zip2` ... `zip7`
* `zipWith2` ... `zipWith7`
* `unzip` ... `unzip7`

**Comment by Bodigrim** [comment]
@treeowl 
https://github.com/haskell/core-libraries-committee/blob/dcaf3f217d286e046494d7c48deb7ca8d46f0c1d/PROPOSALS.md?plain=1#L54-L57
Given the state of #23, #24 and #31, could you please confirm that you have bandwidth to propose yet another one?

**Comment by Bodigrim** [comment]
I mean, I think this is a very reasonable proposal, but in the event it's accepted I really do not want to push and prod for months before it is implemented and merged. Do we have an enthusiatic volunteer with spare time to add `zip{3,4,5,6,7}`, `zipWith{3,4,5,6,7}` and `unzip{3,4,5,6,7}` for `NonEmpty`?

**Comment by Bodigrim** [comment]
@treeowl could you please clarify the status of this? Unless there is someone with enough bandwidth to champion the proposal and write an MR implementing it, I'll close this as abandoned in two weeks.

**Comment by treeowl** [comment]
I would be happy to attempt an MR.

**Comment by Bodigrim** [comment]
@treeowl then please go ahead with a draft MR, which we can vote on.

**Comment by treeowl** [comment]
@Bodigrim Now that I'm looking at it, I think it may actually be better to postpone implementation of these until the strictness issues have been settled. I don't really want to write a bunch of excessively lazy code or introduce a bunch of inconsistencies.

**Comment by Bodigrim** [comment]
Understood. Extreme laziness of `Data.List.NonEmpty` is quite a footgun. Would you like to make a proposal to change it?

**Comment by treeowl** [comment]
Closing pending action on #107.

**Comment by Bodigrim** [comment]
Dear CLC members, now that #107 has landed, could we please get back to this proposal? I'm happy to prepare an MR if there are no further comments / suggestions.

**Comment by ChickenProp** [comment]
I'd be positive.

**Comment by Bodigrim** [comment]
@hasufell @TeofilC could you reopen the ticket please?

**Comment by TeofilC** [comment]
@Bodigrim I would recommend creating a new proposal and linking to this one, since then you will be able to edit the top-level post.
