### ISSUE TITLE
Add `Data.Functor.unzip`

### ISSUE THREAD

**Issue by ocharles** [haskell/core-libraries-committee#88]
Currently `Data.List.NonEmpty` defines:

```haskell
-- | The 'unzip' function is the inverse of the 'zip' function.
unzip :: Functor f => f (a,b) -> (f a, f b)
unzip xs = (fst <$> xs, snd <$> xs)
```

But this is a very strange place for such a generally useful function.

I'd like to propose that `Data.Functor` gains this function. I don't feel strongly on whether it should be a new definition, nor what should happen with `Data.List.NonEmpty.unzip`, only that after this proposal I can do:

```haskell
import Data.Functor (unzip)
```

**Comment by treeowl** [comment]
The version in `Data.Functor` can be no better than that one. `Data.Traversable` can do rather more, in principle, using something like `Data.Biapplicative.traverseBia`.

**Comment by ocharles** [comment]
Ok, I am fine with the version I proposed. Are you saying it is not suitable for `Data.Functor`?

**Comment by treeowl** [comment]
I'm just saying that there are more and more options the more is known about the structure. The bare minimum version would fit very well in `Data.Functor`, but I don't think I'd personally find it very useful.

**Comment by ekmett** [comment]
It is also worth noting the existence of `munzip` in `Control.Monad.Zip`, which is _almost always_ the same as the functor-based definition. Except it uses `liftM` internally and inefficiently for historical reasons. (I was able to come up with a couple of monads for which it actually helped to have it in the class, but they are decidedly weird.) I'm not calling for concrete action around this fact, just raising awareness.

**Comment by phadej** [comment]
`unzip` could be a member of `Functor` type-class, for the same reason `(<$)` is, there can be more efficient implementations: `[a]` and `NonEmpty a` come to mind immediately.

And as there is default implementation, it shouldn't be too intrusive change either.

**Comment by Ericson2314** [comment]
I would move the function, and only then worry about making it a class member. Baby steps.

**Comment by treeowl** [comment]
@phadej, I'm not sure making it a method magically solves the problems. The strictness and other properties of the most "obvious" unzip depend on the type, which makes a class method hard to reason about. Furthermore, one may want less-obvious unzips in certain cases. Ignoring the strictness of the outermost pair (because it's boring), there's just one unzip that makes sense for every `Functor`, which is also boring. There are two additional ones that make sense for every `Traversable`. Some types have sensible unzips that are none of these, such as lists (but, perhaps surprisingly, not `Data.Sequence` sequences). Note that while the lazy `Traversable` unzip has less space leak potential than the `Functor` one, it will actually use significantly more memory in certain *call site* contexts.

**Comment by phadej** [comment]
@treeowl it doesn't need to solve all the problems. Is there drawbacks of `unzip` being a class member?

No ordinary person will be able to pick up from three+ different `unzip`s for lists.

**Comment by treeowl** [comment]
@phadej, I'm concerned for the poor programmer who has to implement the method. From a practical perspective, I think most applications/call sites will want one of three things.

1. Totally eager unzipping. This is natural for arrays, and might make sense for other things if they're sufficiently short.
2. Something lazier than that, but designed to avoid leaks.

Another concern: I don't actually think non-traversable functors necessarily have *sensible* unzips. For example, you *can* use the simple `fmap` thing to "unzip" an `IO` action, but that doesn't strike me as something very reasonable to do.

**Comment by phadej** [comment]
@treeowl 

> but that doesn't strike me as something very reasonable to do.

So you are against adding general

```haskell
unzip :: Functor f => f (a,b) -> (f a, f b)
unzip xs = (fst <$> xs, snd <$> xs)
```

as it can be used with `IO`?

**Comment by phadej** [comment]
```haskell
unzipWith :: (c -> (a, b)) -> f  c -> (f a, f b)
```

Is slightly more general, and composes better. (Think a variant for `Compose`).

**Comment by ocharles** [comment]
Perhaps it would help for me to supply a bit more motivation for why *I* want this? Here is a use of `Data.List.NonEmpty.unzip` in my current work project (none of which are used on `NonEmpty` lists):

```haskell
  let (onFailedToSaveImage, onSuccessfullySavedImage) =
        unzip $
          inputs.onSavedImage <&> \e ->
            split $
              e <&> \(image, res) -> do
                case res of
                  Left e -> Left e
                  Right () -> Right image
```

Where the thing being `unzip`ed here (`inputs.onSavedImage ..`) is `:: Cameras (Event SomeException, Event ())`. `Cameras` is a two-tuple as a functor, and `Event` is from `reactive-banana`.

This isn't much, but it felt wrong to import `Data.List.NonEmpty` for this, and I didn't want to depend on any other libraries *or* have to define `unzip` to make this code work.

**Comment by treeowl** [comment]
@phadej I don't think I'm against that... but I have doubts about a class method that doesn't make much sense for a pretty large category of instances. It makes me nervous, anyway. I'd be substantially *less* nervous about adding one for `Traversable`.

**Comment by treeowl** [comment]
But `Traversable` isn't quite right either, is it, because that requires an ordering. Perhaps morally it belongs in some class between? Or does unzipping `IO` make more sense than I'm giving it credit for?

**Comment by ocharles** [comment]
> Do you mean type Camera a = (Something, a) and you are using unzip :: (a, (b, c)) -> ((a, b), (a, c))? Otherwise I don't understand what you mean by "two-tuple as a functor".

No, sorry. I mean:

```haskell
data Cameras a = Cameras a a
```

**Comment by tomjaguarpaw** [comment]
I see, so you are using `unzip` at a type isomorphic to `unzip :: ((a, b), (a, b)) -> ((a, a), (b, b))`. This fits with @treeowl's hypothesis that it is sensible to require at least `Traversable`. Perhaps it should be `Traversable` and `Applicative`. Then it's a sort of "transpose" operation, I think.

**Comment by ocharles** [comment]
Other definitions of this function:

* https://www.stackage.org/haddock/lts-19.23/utility-ht-0.0.16/Control-Functor-HT.html#v:unzip
* https://www.stackage.org/haddock/lts-19.23/rio-0.1.22.0/RIO-NonEmpty.html#v:unzip
* https://www.stackage.org/haddock/lts-19.23/semialign-1.2.0.1/Data-Semialign.html#v:unzipDefault
* https://www.stackage.org/haddock/lts-19.23/Agda-2.6.2.2/Agda-Utils-List1.html#v:unzip
* https://www.stackage.org/haddock/lts-19.23/adjunctions-4.4.2/Data-Functor-Adjunction.html#v:unzipR

**Comment by tomjaguarpaw** [comment]
Thanks! Definitions are somewhat persuasive. Actual usages (particularly at the fully-general type) would be even more persuasive.

**Comment by alexfmpe** [comment]
> `unzipWith :: (c -> (a, b)) -> f  c -> (f a, f b)`
 > Is slightly more general, and composes better. (Think a variant for Compose).

More general in that it can be specialized to `unzip = unzipWith id`, but actually more specific when it comes to available instances.
We can have types that can be unzipped but not mapped over. For instance, if there are invariants on the values or on the relationship between them.
```haskell
data Monotonic a = Ord a => Monotonic (Vector a)

unzip :: (Ord a, Ord b) => Monotonic (a,b) -> (Monotonic a, Monotonic b)
unzip (Monotonic a) = bimap Monotonic Monotonic (Vector.unzip a)

instance TypeError ('Text "Cannot perform arbitrary point-wise operations") => Functor Monotonic where
  fmap = error "Impossible"
```

**Comment by phadej** [comment]
@alexfmpe Sure. But as you mention yourself, these types are not `Functor`. So `unzip x = (fst <$> x, snd <$> x)` default implementation wouldn't work for them. And having `Unzip f` as a superclass of `Functor` won't fly, as it breaks almost everything.

**Comment by treeowl** [comment]
There is one potential complication with making it a `Traversable` method: the default lazy implementation can't be written in Report Haskell without `unsafeCoerce`—it seems to need either that or GADTs. The default fully eager implementation is likely only desirable in most circumstances for rigid-spined types (maps, hash maps, arrays, and such).

**Comment by phadej** [comment]
@treeowl which `Traversable` default lazy implementation. You never wrote it down it in this issue (nor described how it's different (& better?) than `unzip x = (fst <$> x, snd <$> x)`

**Comment by treeowl** [comment]
@phadej ,

```haskell
unzipWithLazy :: Traversable t => (a -> (b, c)) -> t a -> (t b, t c)
unzipWithLazy = Data.Biapplicative.traverseBia
```

The above assumes the `Biapplicative (,)` instance in the master branch of `bifunctors`. In the current Hackage version you'd need a bit of `newtype` trickery to get the right behavior.

The advantage over the simple `fmap` thing: for lazy-spined types, the two results are built "in parallel", (likely) avoiding leaking first components into second components or vice versa.

**Comment by phadej** [comment]
@treeowl is that the same as

```haskell
-- | 'unzip' transforms a list of pairs into a list of first components
-- and a list of second components.
--
-- >>> unzip []
-- ([],[])
-- >>> unzip [(1, 'a'), (2, 'b')]
-- ([1,2],"ab")
unzip    :: [(a,b)] -> ([a],[b])
{-# INLINE unzip #-}
-- Inline so that fusion `foldr` has an opportunity to fire.
-- See Note [Inline @unzipN@ functions] in GHC/OldList.hs.
unzip    =  foldr (\(a,b) ~(as,bs) -> (a:as,b:bs)) ([],[])
```

when specialized `t = []`? It's difficult to understand what `traverseBia` does, and in fact `bifunctors` tries to rewrite it (and bunch of other specializations) to

```haskell
-- Rewrite rules for traversing a few important types. These avoid the overhead
-- of allocating and matching on a Mag.
{-# RULES
"traverseBia/list" forall f t. traverseBia f t = traverseBiaList f t
#-}
traverseBiaList :: Biapplicative p => (a -> p b c) -> [a] -> p [b] [c]
traverseBiaList f = foldr go (bipure [] [])
  where
    go x r = biliftA2 (:) (:) (f x) r
```

which looks like above.

I fail to grasp a benefit of having `unzipWithLazy = Data.Biapplicative.traverseBia` over `unzipWith` as a member of `Functor`. There aren't that many lazy-spined types, that special implementations for them cannot be written by hand, without overly-complicating things.

---

All this discussion just makes me think: let's just add what @ocharles proposed, and let you & me discuss options as our own proposals if we think if just having `unzip` in `Data.Functor` (as it's already in `Data.List.NonEmpty`) is not good enough.

The original proposal is very simple. I suggest @ocharles to trigger a vote.

**Comment by treeowl** [comment]
@phadej , it's not quite the same, no. The `traverseBia` one is lazier; `unzip [undefined, undefined]` will produce `([undefined, undefined], [undefined, undefined])` rather than `undefined`. I believe that *semantically* we have

```haskell
unzipUsingTraverse xs = xs `seq` unzipUsingFmap xs
```

but they're operationally different. I agree this discussion should be continued elsewhere.

**Comment by ekmett** [comment]
Similarly, there are lots of other representable functors that are not traversable that have sensible unzips:

```
Moore c (a,b) -> (Moore c a, Moore c b)
Mealy c (a, b) -> (Mealy c a, Mealy c b)
```
etc.

Then there are compositions of traversable things and representable things that are neither, which have sensible unzips, etc. etc. etc.

`Functor` captures that sort of broader space. Admittedly if you move an overloadable method into the `Functor` class you are making everyone pay for it and hoisting users on the horns of a dilemma of "do I increase the requirements on my `Functor` instance or do I accept a suboptimal 'unzip'?"

**Comment by treeowl** [comment]
@ekmett , I didn't think about the extra constraint issue. That's pretty nasty.

**Comment by phadej** [comment]
There's also `Unzip (Event t)` instance in `reflex`, with `unzip = splitE`: https://hackage.haskell.org/package/reflex-0.8.2.1/docs/Reflex-Class.html#v:splitE

And that's actually the only use-case why I'm not removing `Unzip` class from `semialign` (or restructuring the hierarchy there, `semialign` works now, and there is very little motivation to change it).

**Comment by phadej** [comment]
Btw. `Prelude` exports `unzip :: [(a,b)] -> ([a], [b])`. If `unzip` is added to `Functor`, it would make sense to export the `Functor` version instead, but  if it's just defined as a `unzip x = (fst <$> x, snd <$> x)` then the `Prelude` version should stay list-specific (a pity).

**Comment by ekmett** [comment]
This sounds like this should be `funzip` or something to avoid clash on unqualified import of Data.Functor unless you move it into the class where it can be overridden to suit.

**Comment by phadej** [comment]
There are indeed plenty of unqualified Data.Functor imports: https://hackage-search.serokell.io/?q=import%5Cs*Data.Functor%24

Hard to say how many of them use `unzip` though.

**Comment by phadej** [comment]
If `Data.OldList` unzip is changed as

```diff
-let unzip =  foldr (\  (a,b) ~(as,bs) -> (a:as,b:bs)) ([],[])
+let unzip =  foldr (\ ~(a,b) ~(as,bs) -> (a:as,b:bs)) ([],[])
```

(which would be own issue)

Then

```haskell
>>> bimap length length $ unzip' [undefined, undefined]
(2,2)
```

it would be as lazy as `traverseBia` variant.

I'm not competent enough to comment what are implications of that change.

**Comment by mixphix** [comment]
@ocharles, if you will be triggering a vote, shall we collaborate on an MR to close #86 simultaneously? I find it hard to imagine there will be people in favour of one but not the other.

**Comment by ekmett** [comment]
> There's also Unzip (Event t) instance in reflex, with unzip = splitE: https://hackage.haskell.org/package/reflex-0.8.2.1/docs/Reflex-Class.html#v:splitE

Another example is Lindsey Kuper's LVish, where the monad would admit an unzip that creates a "future" for the computation, and returns two different computations that each force the future and then apply fst or snd to the result.

**Comment by tomjaguarpaw** [comment]
@mixphix @ocharles As a point of information, in case it changes the design you come up with, I give fair warning that I will vote against any proposal that breaks existing consumers of `Data.List.NonEmpty.unzip` without a deprecation cycle. One such cycle (and the one I wrote about at [Opaleye's API breakage policy](h2.jaguarpaw.co.uk/posts/opaleyes-api-breakage-policy/)) is

1. GHC version `n`:
  * Add `Data.List.NonEmpty.unzipNonEmpty`, specialised to the `NonEmpty` type.
  * Add `Data.Functor.unzip` at general type
  * Change the documentation of `Data.List.NonEmpty.unzip` to say that it will be deprecated in GHC version `n+1` and to use `Data.List.NonEmpty.unzipNonEmpty` or `Data.Functor.unzip`
2. GHC version `n+1`:
  * `{-# DEPRECATE #-}` `Data.List.NonEmpty.unzip`
3. GHC version `n+2`:
  * Either remove `Data.List.NonEmpty.unzip`
  * or make it a synonym of `Data.List.NonEmpty.unzipNonEmpty` (in which case document `Data.List.NonEmpty.unzipNonEmpty` as obsolete and that `Data.List.NonEmpty.unzip` should be preferred instead)

I am open to alternative forms of deprecation cycle but we need *something* that ensures users get a deprecation warning before their code breaks. Is this very heavyweight?  Yes. Is this very annoying for those of us who want to move fast and fix things? Also yes. Is it essential if we want Haskell to be taken even minimally seriously in the backwards compatibility stakes? Even more yes.

**Comment by phadej** [comment]
I find that deprecation cycle worse than e.g. `Data.List` monomorphisation process.

- Deprecating a name which is going to be undeprecated
- Introducing another name `unzipNonEmpty` which is going to be obsolete.

The `Data.List` monomorphization way of "Just make patches for everything which breaks (in Stackage)" is considerably less polluting, and in this case shouldn't even need much work. I'm sure @mixphix is happy to gauge the impact.

- In https://hackage-search.serokell.io/?q=%28N%7CNE%7CNEL%7CNonEmpty%29%5C.unzip there seems to be only one (compaREST which is not on Stackage) which for sure will break.

**Comment by ocharles** [comment]
I haven't given you a proposal yet, but maybe it's time for me to get to that. The TL;DR of my proposal would just be to add `unzip` to `Data.Functor` though. It's a purely additive change

**Comment by phadej** [comment]
@ocharles Sorry for playing a devils advocate.

 See comments https://github.com/haskell/core-libraries-committee/issues/88#issuecomment-1247050108 and https://github.com/haskell/core-libraries-committee/issues/88#issuecomment-1247054109

There is a chance of a name clash. Probably rare, but given that `Data.Functor` is likely imported unqualified, I'd say it should be assessed. (Do you hide `unzip` from Prelude in your work project?)

**Comment by ocharles** [comment]
> Do you hide unzip from Prelude in your work project?

Yes. Perhaps more extremely, I am explicit with my imports (never unqualified), and when I have to hide things from Prelude I actually go as far as `NoImplicitPrelude` and import everything I need (that is, I don't use `hiding` and I don't use unqualified imports. Thank you HLS!)

> There is a chance of a name clash. [..] I'd say it should be assessed.

How does one do such an assessment? Should I make the change and rebuild Hackage?

**Comment by tomjaguarpaw** [comment]
> I find that deprecation cycle worse than e.g. Data.List monomorphisation process.

You're welcome to find it as you like. I'm just making my position clear in advance to the proposers to avoid unwelcome surprises.

**Comment by Bodigrim** [comment]
@ocharles while it is your right as a proposer, I'd strongly suggest against triggering a vote after two days only. However, you are not obliged or expected to react to all suggestions in the thread. Once ready, please prepare a GHC MR with desired changes. 

I usually do not require impact analysis for additive changes, but it strengthens the proposal and eliminates doubts. Building https://github.com/Bodigrim/clc-stackage takes a day or two on my laptop, but besides that is a fairly automatic process. See instructions inside the cabal file.

**Comment by alexfmpe** [comment]
@phadej 
> But as you mention yourself, these types are not Functor. So unzip x = (fst <$> x, snd <$> x) default implementation wouldn't work for them. And having Unzip f as a superclass of Functor won't fly, as it breaks almost everything.

Right. I guess what I was trying to get at is that neither `fmap` nor `unzip` are stronger than each other per-se (at least if we take invariants into account), but `unzipWith :: (c -> (a, b)) -> f c -> (f a, f b)` allows both
```haskell
  fmap f = fst . unzipWith (dup . f)
  unzip = unzipWith id
```
though whether that `fmap` is lawful depends on the laws we add to `unzipWith`. I assume `unzip` would trivially be lawful.

Now, a default implementation of `unzip` in terms of `fmap` does allow for
```haskell
unzipWith f = unzip . fmap f
```
so in the specific case of functor-based unzipping, it seems going with `unzip` or `unzipWith` is equivalent.

**Comment by treeowl** [comment]
For a `Functor` class method (which I'm nervous about), `unzipWith` seems rather better. For a `Traversable` method (less nervous), one option is

```haskell
unzipUsing :: Applicative f => (a -> f (b, c)) -> t a -> f (t b, t c)
```

A less conservative thing would be to move `Biapplicative` to `base` and make `traverseBia` a `Traversable` method.

**Comment by Bodigrim** [comment]
@ocharles if you made you mind, please raise a draft MR, so that we know what exactly we are voting on.

**Comment by ocharles** [comment]
@Bodigrim Will do, thanks for the nudge.

**Comment by ocharles** [comment]
@Bodigrim Done: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9434

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to add `Data.Functor.unzip` as per https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9434/diffs:
```
unzip :: Functor f => f (a,b) -> (f a, f b)
unzip xs = (fst <$> xs, snd <$> xs)` 
```
The same function already exists in `base` as `Data.List.NonEmpty.unzip`, but it's a very strange place for something polymorphic by `Functor`. Cf. #86, which aims to restrict the type of existing `Data.List.NonEmpty.unzip` to non-empty lists only. This proposal however does not introduce any breakage per se and is a purely additive change.
@mixphix @chessai @cgibbard @emilypi @tomjaguarpaw 

----

+1 from me.

**Comment by mixphix** [comment]
+1

**Comment by tomjaguarpaw** [comment]
-1

----

This doesn't really seem useful enough to me to warrant inclusion in `base`. I also think it's not at all what you want in many cases, `IO (a, b) -> (IO a, IO b)` for example.  I holding off until we work out a `Traversable` variant.

**Comment by emilypi** [comment]
+1

**Comment by Ericson2314** [comment]
I this ends up being a rejection, I think the one in `Data.List.NonEmpty` should be deprecated too. If this doesn't deserve to exist then that also doesn't deserve to exist.

**Comment by treeowl** [comment]
> _If_ this ends up being a rejection, I think the one in `Data.List.NonEmpty` should be deprecated too. If this doesn't deserve to exist then that also doesn't deserve to exist.

The one currently there should be replaced with one specific to `NonEmpty` with the right semantics. Please go over to #107 and join the discussion.

**Comment by emilypi** [comment]
>  it's sort of universal

It's tough cuz of the dilemma posed in Ed's comment. Imo I'd rather see good abstractions that apply to everyone go in `base`, with the proper announcement for people to write their own versions than to leave them unwritten. We can track those implementations through the CLC process, and lead the way. However, I agree as a sort of soft +1 that this also poses a burden.

**Comment by Bodigrim** [comment]
@chessai could you please cast your vote?

**Comment by chessai** [comment]
> > it's sort of universal
> 
> It's tough cuz of the dilemma posed in Ed's comment. Imo I'd rather see good abstractions that apply to everyone go in `base`, with the proper announcement for people to write their own versions than to leave them unwritten. We can track those implementations through the CLC process, and lead the way. However, I agree as a sort of soft +1 that this also poses a burden.

This is how I feel - I'm also a soft +1.

**Comment by Bodigrim** [comment]
I'm not sure how soft +1 is different from just +1 for the purposes of voting :) 

I'll wait for another week, just in case someone wishes to clarify/change their vote, but as it stands there are 4 votes in favour and 2 votes against.

**Comment by ocharles** [comment]
@Bodigrim has enough time passed now?

**Comment by Bodigrim** [comment]
@ocharles sorry, thanks for reminder.

With 4 votes in favor the proposal has been approved.

**Comment by ocharles** [comment]
Thanks for your input, everyone!

**Comment by chshersh** [comment]
I'm trying to summarise the state of this proposal as part of my volunteering effort to track the progress of all `approved` CLC proposals.

| Field | Value |
|---|---|
| **Authors**            |  @ocharles   |
| **Status**             |  merged  |
| **`base` version**     | `4.19.0.0`  |
| **Merge Request (MR)** | https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9434/diffs |
| **Blocked by**         | nothing |
| **CHANGELOG entry**    | present |
| **Migration guide**    |  not needed |

[changelog]: https://gitlab.haskell.org/ghc/ghc/-/blob/master/libraries/base/changelog.md

Please, let me know if you find any mistakes 🙂
