### ISSUE TITLE
Add standard Unicode case predicates

### ISSUE THREAD

**Issue by wismill** [haskell/core-libraries-committee#90]
# Motivation

This proposal intends to fix a [GHC issue about character case predicates](https://gitlab.haskell.org/ghc/ghc/-/issues/14589).

Currently the predicates `isUpper` and `isLower` in `Data.Char` have counter-intuitive (but _expected_, see hereinafter) behaviours:

```haskell
> import Data.Char
> -- ⓐ: U+24D0 CIRCLED LATIN SMALL LETTER A
> -- Ⓐ: U+24B6 CIRCLED LATIN CAPITAL LETTER A
> toUpper 'ⓐ' == 'Ⓐ'
True
> toLower 'ⓐ' == 'ⓐ'
True
> toLower 'Ⓐ' == 'ⓐ'
True
> isUpper 'Ⓐ'
False
> isUpper 'ⓐ'
False
> isLower 'ⓐ'
False
```

Here we can observe a contradiction:
- The `toLower` function does not alter its argument for 'ⓐ', but `toUpper` does, which tells us that the character 1) has the notion of case 2) it must be lower-cased. 
- On the other hand, both `isUpper` and `isLower` functions return `False` for `ⓐ` suggesting that it has no notion of case.

This behaviour is _expected_ because the predicates are based on the `General_Category` property, but `LowerCase` and `Uppercase` seem more appropriate; see [Unicode Standard §4.2 “Case”](http://www.unicode.org/versions/Unicode15.0.0/ch04.pdf#G124722):

> The first set of values involved in the definition of case are based on the General_Category
property in UnicodeData.txt. The relevant values are General_Category = Ll (Lower-
case_Letter) and General_Category = Lu (Uppercase_Letter). For most ordinary letters of
bicameral scripts such as Latin, Greek, and Cyrillic, these values are obvious and non-
problematical. However, the General_Category property is, by design, a partition of the
Unicode codespace. This means that each Unicode character can only have one General_-
Category value, which results in some odd edge cases for modifier letters, letterlike symbols
and letterlike numbers. As a consequence, not every Unicode character that looks like a
lowercase character necessarily ends up with General_Category = Ll, and not every Uni-
code character that looks like an uppercase character ends up with General_Category = Lu.
>
> The second set of definitions relevant to case consist of the derived binary properties, Low-
ercase and Uppercase, specified in DerivedCoreProperties.txt in the Unicode Character
Database. Those derived properties augment the General_Category values by adding the
additional characters that ordinary users think of as being lowercase or uppercase, based
primarily on their letterforms. The additional characters are included in the derivations by
means of the contributory properties, Other_Lowercase and Other_Uppercase, defined in
PropList.txt. For example, Other_Lowercase adds the various modifier letters that are let-
terlike in shape, the circled lowercase letter symbols, and the compatibility lowercase
Roman numerals. Other_Uppercase adds the circled uppercase letter symbols, and the
compatibility uppercase Roman numerals.

# Implementation

I opened a [merge request](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9043) that adds two new functions to `Data.Char`:

- `isLowerCase`
- `isUpperCase`

Names and module may be changed.

This work is base on the package [`unicode-data`](https://hackage.haskell.org/package/unicode-data-0.3.0/docs/Unicode-Char-Case.html) and is a follow-up of #59.

# Further discussion

There is a similar issue with [`isAlpha`](https://hackage.haskell.org/package/unicode-data-0.3.0/docs/Unicode-Char-General.html#v:isAlphabetic), [`isSpace`](https://hackage.haskell.org/package/unicode-data-0.3.0/docs/Unicode-Char-General.html#v:isWhiteSpace) and `isNumber` (some CJK characters have general category `Other_Letter` but do have a numeric value).

**Comment by nomeata** [comment]
I can't help but notice that the proposal motivation would be easier to follow if https://github.com/haskell/core-libraries-committee/issues/26 was implemented ;-)

**Comment by nomeata** [comment]
Naive question: Would you also want to add a `toLowerCase`, or does that not make sense?

**Comment by wismill** [comment]
> Naive question: Would you also want to add a `toLowerCase`, or does that not make sense?

Actually `toLower` and `toUpper` give us expected results. However they are limited to a single character, which is [incorrect when applied to a string](https://hackage.haskell.org/package/text-2.0.1/docs/Data-Text.html#g:9).

**Comment by nomeata** [comment]
Thanks for the clarification!

**Comment by Bodigrim** [comment]
> I can't help but notice that the proposal motivation would be easier to follow if #26 was implemented ;-)

@wismill would you mind to update examples in your proposal with proper Unicode to make it easier to follow? E. g., 

```haskell
> import Data.Char
> toUpper 'ⓐ' == 'Ⓐ'
True
> toLower 'ⓐ' == 'ⓐ'
True
> toLower 'Ⓐ' == 'ⓐ'
True
> isUpper 'Ⓐ'
False
> isUpper 'ⓐ'
False
> isLower 'ⓐ'
False
```

**Comment by Bodigrim** [comment]
Dear CLC members, let's vote on the proposal to provide more precise upper/lower case predicates from `Data.Char`: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9043. Existing `isUpper` / `isLower` are insufficient, as they wrongly rely on `GeneralCategory` property to determine case. @tomjaguarpaw @mixphix @emilypi @chessai @cgibbard 

----

+1 from me. The proposed change is non-breaking, includes detailed explanations in Haddocks and comes with a test suite.

**Comment by cgibbard** [comment]
+1 I'm generally in favour of this. One detail is that given that "uppercase" is typically a single word, I'm not sure the camel-casing on isUpperCase is optimal, though I'm not sure I'd want to hold anything up over that. ;)

Also, I would generally be in favour of having a wider array of unicode predicates on characters exported from Data.Char, if there's motivation to push it in that direction.

**Comment by emilypi** [comment]
+1

**Comment by wismill** [comment]
> One detail is that given that "uppercase" is typically a single word, I'm not sure the camel-casing on isUpperCase is optimal, though I'm not sure I'd want to hold anything up over that.

@cgibbard Both are correct (uppercase and upper-case), but it is true that the Unicode standard uses `isLowercase` and `isUppercase`. I find `isLowerCase` more readable than `isLowercase`, but I have no strong opinion on it.

> Also, I would generally be in favour of having a wider array of unicode predicates on characters exported from Data.Char

What predicates have you in mind? Since the implementation in `Data.Char` is based on [`unicode-data`](https://hackage.haskell.org/package/unicode-data-0.3.1/docs/Unicode-Char.html) package, it should be easy to add other predicates.

However where do we stop? The 2 predicates of this proposal solve a [concrete issue](https://gitlab.haskell.org/ghc/ghc/-/issues/14589).

**Comment by Bodigrim** [comment]
FWIW I prefer `isUpperCase`, but let's not digress from the voting.

**Comment by tomjaguarpaw** [comment]
+1

----

This seems like a property that is useful to test.

(Tangential note: It seems a bit sad that `toLower` doesn't return a `Maybe`, given that many characters, even alphabetical ones, have no notion of "upper" and "lower" case. Maybe in the future we could have `toLowerMaybe` that satisfies `fmap isLower (toLowerMaybe c) /= Just False`.)

**Comment by mixphix** [comment]
+1

**Comment by chessai** [comment]
+1

**Comment by Bodigrim** [comment]
Approved unanimously, thanks all.
