### ISSUE TITLE
Add Profunctor to base

### ISSUE THREAD

**Issue by Icelandjack** [haskell/core-libraries-committee#92]
Add `Profunctor` to base with a quantified superclass

```haskell
{-# Language QuantifiedConstraints #-}

class (forall a. Functor (pro a)) => Profunctor pro where
  ..
```

This depends on adding a superclass to `Bifunctor` (#91).

There is an extensive discussion: [Move `Data.Profunctor` from `profunctors` package to `base`](https://gitlab.haskell.org/ghc/ghc/-/issues/16173)

Related issues:
* #93 Add qualitifed superclasses to `Bifoldable` and `Bitraversable`

**Comment by treeowl** [comment]
There's a big problem with that superclass on `Bifunctor`:

```haskell
second id (undefined @(a, b)) = (undefined, undefined)
fmap id (undefined @(a, b)) = undefined
```

Hideous. I think the `Bifunctor` one is wrong, but they really need to match for this.

**Comment by Icelandjack** [comment]
@treeowl You should add this comment to #91 so it's on the correct ticket

**Comment by Bodigrim** [comment]
@Icelandjack any plans to make progress with this? The current text of the proposal lacks any motivational section. There are many type classes in kmettoverse, what's the justification to move this one particular to `base`?

**Comment by Ericson2314** [comment]
Moving things to `base` constrains their evolution, as we've just seen with `Bifunctor`, so I am not keen on doing this.

**Comment by Bodigrim** [comment]
Given how ugly is Haskell story for orphan instances, I'm usually in favor of moving type classes into `base`. There is a tangible benefit for the robustness of the ecosystem in it, on contrary to moving functions / data, which is usually just a matter of convenience. On the other hand, I personally never used `Profunctor` (nor any lens), so I don't know what exactly this proposal unlocks and can use some explanation.

**Comment by Bodigrim** [comment]
Unless @Icelandjack or anyone else makes progress on this proposal within two weeks, I'll close it as abandoned.

**Comment by Bodigrim** [comment]
Closing as abandoned. Feel free to reopen once there is an active proposer.
