### ISSUE TITLE
Add Data.Array.genArray

### ISSUE THREAD

**Issue by nomeata** [haskell/core-libraries-committee#96]
I’d like to add

```diff
diff --git a/Data/Array/Base.hs b/Data/Array/Base.hs
index a999cba..f009f4b 100644
--- a/Data/Array/Base.hs
+++ b/Data/Array/Base.hs
+-- | Constructs an immutable array using a generator function.
+genArray :: (IArray a e, Ix i) => (i,i) -> (i -> e) -> a i e
+genArray (l,u) f = listArray (l,u) $ map f $ range (l,u)
```

as proposed in <https://gitlab.haskell.org/ghc/packages/array/-/merge_requests/13>. I think I noticed it's lack a few times already, last while writing [a recent blog post](https://www.joachim-breitner.de/blog/796-rec-def__Minesweeper_case_study).

**Comment by treeowl** [comment]
What about these as well?

```haskell
genArrayIO :: Ix i => (i,i) -> (i -> IO e) -> IO (Array i e)
genArrayST :: Ix i => (i,i) -> (i -> ST s e) -> ST s (Array i e)
genMArray :: (MArray a e m, Ix i) => (i,i) -> (i -> m e) -> m (a i e)
```

**Comment by nomeata** [comment]
In analogy to `newListArray`, I would call that `newGenArray`.

**Comment by treeowl** [comment]
> The third of these would subsume the other two, right?

Not really. It produces a *mutable* array which may then be frozen manually. The first two produce *immutable* arrays, internally using unsafe freezes.

**Comment by treeowl** [comment]
I'm not suggesting a refactor.

**Comment by treeowl** [comment]
I'm just suggesting three functions to add to yours (plus similar for unboxed and storable for the array type specific ones).

**Comment by Bodigrim** [comment]
@nomeata API for core packages, which are not `base` itself, is normally up to relevant maintainers. The problem with `array` is that the set in question is precisely empty. Would you like to be a maintainer of `array`? As you can see, this is generally a fairly low-traffic duty

**Comment by nomeata** [comment]
No, I don't think I'd be the right person to do that. I only have a passing interested right now… sorry

**Comment by Bodigrim** [comment]
Any volunteers to maintain `array`?

**Comment by Bodigrim** [comment]
Closing as out-of-scope. 
CC @hellwolf @July541 @CarstenKoenig as new maintainers of `array`.
