### ISSUE TITLE
Make `stimes` a method of `Semigroup`

### ISSUE THREAD

**Issue by friedbrice** [haskell/core-libraries-committee#97]
Make `stimes` a method of `Semigroup` so that it can be given a custom implementation for each semigroup, but keep the default implementation for convenience.

# Why

While many specific semigroups admit an implementation of `stimes` that converges for input `0`, we currently lack the ability to provide that implementation. For example, any semigroup that also is a monoid could use `stimes = mtimes`.

```haskell
instance Ord k => Semigroup (Map k a) where
    (<>) = ...
    stimes = mtimes

instance Ord k => Monoid (Map k a) where
    mempty = ...
```

This would make it safer to use `stimes` over `mtimes`, making it possible to relax constraints of some functions from `Monoid a` to `Semigroup a`, while still making it sensible to use such functions on a monoid type. This would obviate the need to "double-up" such generic functions by providing a version for semigroups and a version for monoids, as the version for semigroup types would "do the right thing" when applied at a monoid type.

**Comment by konsumlamm** [comment]
What do you mean, `stimes` already is a method of `Semigroup` (and it always was): https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Semigroup.html#v:stimes. The [`Semigroup (Map k a)` instance](https://hackage.haskell.org/package/containers-0.6.6/docs/src/Data.Map.Internal.html#line-480) even defines it! Also, `mtimes` isn't a thing (anymore?).

**Comment by friedbrice** [comment]
Oh, I'm a dumbass. I just saw `stimes` is not a visible method of `Semigroup` in my GHCi and got flustered. All I needed to do was import it from `Data.Semigroup`, though. Sorry for wasting your time.

**Comment by sjakobi** [comment]
> I just saw "`stimes` is not a visible method of `Semigroup`" in my GHCi and got flustered.

FWIW, improvements to this error message are discussed in https://github.com/haskell/error-messages/issues/526.
